### ISSUE TITLE
Import inflow.dat

### ISSUE THREAD

**Issue by FLO-2DKaren** [FLO-2DSoftware/qgis-flo-2d-plugin#1001]
Import inflow.dat to Boundary Condition Widget.

_Originally posted by @FLO-2DKaren in https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/issues/991#issuecomment-1745045714_

**Comment by FLO-2DKaren** [comment]
This is a task to import the inflow.dat without modifying or importing anything else.  
This is for the tailing dam tool and for the multi domain tool.

**Comment by rpachaly** [comment]
Should I also add an import for OUTFLOW.DAT file?

**Comment by FLO-2DKaren** [comment]
Let the user decide and yes to the outflow.dat.

**Comment by rpachaly** [comment]
Question: should the reservoir be imported in the BC editor or on the Initial Condition editor?

**Comment by FLO-2DKaren** [comment]
I tested this with many different configurations. It seems good.
