### ISSUE TITLE
Boundary Condition Performance

### ISSUE THREAD

**Issue by FLO-2DKaren** [FLO-2DSoftware/qgis-flo-2d-plugin#1003]
I'm looking into improving the performance of the BC polygon on the downstream boundary. Even if we change the widget interface or anything like this, the polygon BC process will be the same.

_Originally posted by @rpachaly in https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/issues/991#issuecomment-1743144081_

**Comment by FLO-2DKaren** [comment]
OK. This is one of the systems that might benefit from the moving window analysis where it does the processing in blocks of data to reduce the processing time overall.

The area average n value calculator uses that method.

**Comment by FLO-2DKaren** [comment]
I believe that what is slowing down the process is the schematize_outflows function. It is sending too much cells to be tested for BC cell. Maybe processing the cells before sending them to select_outflows_according_to_type can speed up the whole process. But I’m not totally sure, I’ll give it a shot.

**Comment by rpachaly** [comment]
More information on: [Simplify Boundary Widget#1005](https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/issues/1005)

**Comment by rpachaly** [comment]
Finally! It took me around a day to figure out where exactly where the bottleneck was and how to optimize it. It was calling two functions (is_boundary_cell and adjacent_grids) that were doing basically the same thing. I combined the two functions and the time it takes to compute the outflow cells dropped by almost the half. My testing was using the QGIS Lesson 1 Project domain with the following outflow polygon:

![Image](https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/assets/39889306/1ca6b890-af6d-4b4b-b47c-8d61b91e8294)

These are the the results:

Time taken: 420.02 seconds -> current method
Time taken: 257.69 seconds -> new method

**Comment by FLO-2DKaren** [comment]
Let's test it on a very large model.  Do you have one?  If not, I have one here:
https://flo-2d.sharefile.com/d-s69088e05783745cb858a13f1ab52c938

The way the district does this is to build a boundary around the whole project.  
This gpkg is a bit old but it should be OK for your test.

**Comment by rpachaly** [comment]
Ok, I'm testing it right now

**Comment by rpachaly** [comment]
I'm also going to add a progress bar, it will slow down the process a bit but the user will be able to see that the progress is still going on.

**Comment by FLO-2DKaren** [comment]
If the test takes more than an hour, I think that is too long.

**Comment by rpachaly** [comment]
Yes, it is still taking a lot of time. We need to combine this new version with the moving average. 

I'll be working on the import INFLOW.DAT and then I'll get back to this issue.

**Comment by FLO-2DKaren** [comment]
I wonder if this system is processing all of the outer cells instead of the ones that are within the boundary polygon?

**Comment by rpachaly** [comment]
Only the ones inside the polygon. If we want to improve this process even more, we need to use the moving window.
