### ISSUE TITLE
Boundary Outflow Overview

### ISSUE THREAD

**Issue by FLO-2DKaren** [FLO-2DSoftware/qgis-flo-2d-plugin#1004]
Karen to give an overview of the Boundary Editor

**Comment by FLO-2DKaren** [comment]
Add 
Coastal project
Multiple Domain

**Comment by rpachaly** [comment]
@FLO-2DKaren 

Hi Karen, do you have more models that have different outflow types on the OUTFLOW.DAT? 

The models that I have here all have floodplain or channel outflow (no hydrograph). I want a combination of hydrographs and time-stage for real situations. I can prepare some models, but I want some that are working and was tested before for a more complete testing.

**Comment by FLO-2DKaren** [comment]
Yes I will get you some.

**Comment by FLO-2DKaren** [comment]
Sorry forgot to reply all

Can you please try this plugin. You can install it from the zipped file to
update. Restart Qgis if needed.

https://flo-2d.sharefile.com/d-s2b9baf0506794ddba8aaef1b82b93864


Karen O'Brien
Technical Support

FLO-2D Software | Riada Engineering
P.O. Box 66 | Nutrioso, AZ | 85932
T. 928.339.1935
www.flo-2d.com | ***@***.***

**Comment by FLO-2DKaren** [comment]
Oops disregard the last two posts. Wrong email.
