### ISSUE TITLE
fplain cadpts neighbors

### ISSUE THREAD

**Issue by FLO-2DKaren** [FLO-2DSoftware/qgis-flo-2d-plugin#1006]
IMPORTANT NOTE:   If a grid size, shape, elevation or roughness is adjusted with the FLO-2D Plugin, the exported data will not overwrite FPLAIN.DAT, CADPTS.DAT, or NEIGHBORS.DAT.  Those files should be deleted prior to running the engine. 

We need to add a code to check for this.  It takes a lot of time to build those 3 files when a project gets really big so it is important not to overwrite them unless the data has been modified.

If they are not updated, the engine still uses them and ignores topo.dat and mannnings_n.dat.

Another issue with those files is that they can be corrupted if a run is stopped while they are being written.  They are not deleted and next run will use them instead of rebuilding them.

So maybe something easy is to run some statistics on them to see if they have the same data or just ask the user if the files need to be updated or deleted.

**Comment by rpachaly** [comment]
https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/assets/39889306/2142f8c9-c4b3-4c42-b40c-b58a084cb54a

It is on https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/tree/fplain-cadpts-neighbors. Let me know if you agree with this approach, Karen. Then I'll merge it.

**Comment by FLO-2DKaren** [comment]
Hi Robson,

This is a good idea.  I also wanted to let you know that the run starts much faster if you only delete fplain.dat.  This is not something you and I deal with  because we don't run huge models but once you exceed 1.5 millions cells, it takes a lot of time to write neighbors.  So if the manning or elevation changes fplain should be deleted but if the grid size or numbering changes, you should remove all three files.  I'll just let you think on that for now and see what your ideas are.  We could do a radio button instead of a checkbox.  

Also, I think a tool tip with a simple description is a good idea.

**Comment by FLO-2DKaren** [comment]
I think this is working ok.  I haven't come across any issues so far.
