### ISSUE TITLE
Levee Wall Bug

### ISSUE THREAD

**Issue by FLO-2DKaren** [FLO-2DSoftware/qgis-flo-2d-plugin#1011]
Version 115 has a bug related to the unit and cell size restrictions that were implemented with #1000.  
Do not use this build to calculate levees or walls.

**Comment by FLO-2DKaren** [comment]
When we fix this bug, can we add a color to a schema levee that has a prescribed Breach?

**Comment by rpachaly** [comment]
I already fixed the levee bug and I'm testing the color to schematized levees (breach and prescribed failures). Tomorrow I'll have it done.

**Comment by FLO-2DKaren** [comment]
OK Excellent.  I think we should do a Wall test too.  I can do it on my home computer.

**Comment by rpachaly** [comment]
**Levee Bug**

Fixed. Tested on the Brazil 2023 Workshop project and on QGIS Lesson 4. All good. 

**Levee Symbology**

I used a rule-based symbology to add this feature. It is really good to use it. You can uncheck and check to see where each prescribed/breach failure is located. We can change the colors if you didn't like. 

1. No failure:

![image](https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/assets/39889306/631485db-f15c-456e-98dd-3ac501d02df6)
![image](https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/assets/39889306/c9aa71ef-1f4d-4719-a80f-d056a6407478)

2. Prescribed Failure:

I selected a yellow color for prescribed. The symbology is FAILURE_TYPE GRID-DIRECTION.

![image](https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/assets/39889306/bd1b2fca-3ae7-4bd4-a55a-507f349ccc23)
![image](https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/assets/39889306/edf7748c-98b8-4401-bc5b-5630c16272ab)


3. Breach Failure:

I selected a blue color for prescribed. The symbology is FAILURE_TYPE GRID-DIRECTION.

![image](https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/assets/39889306/93e9d140-0857-4a9c-ac53-870a5de2fb6f)
![image](https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/assets/39889306/f53989e1-9936-46a9-915a-84b1983e51e5)

**Small bugs fixed**

1. Levee and breach editor set up
2. Wrong direction on BREACH.DAT export
3. Removed the export breach checkbox on components when it is not selected on the widget
4. Removed the fail data on LEVEE.DAT when it is not selected on the widget

**Progress Dialog**

Added progress dialog to ARF and WRF.

I'm pushing the branch!

**Comment by FLO-2DKaren** [comment]
@rpachaly 
Hi Robson,  I can't connect to my computer at home to test the Wall calculator.  Can you please run the Walls on Lesson 4 and see if it changes anything in the levee.dat file?

**Comment by rpachaly** [comment]
@FLO-2DKaren 
I've just redone the test on the walls here (Lesson 4) and all good. Both the LEVEE.DAT and the ARF.DAT match.

**Comment by rpachaly** [comment]
Ok, I'm working on MapCrafter.

**Comment by FLO-2DKaren** [comment]
BigWallTest Complete the only difference is that version 10 gave the 3 decimal places and version 115 gave 4 so I think the calculator is OK.
