### ISSUE TITLE
Loading 2 projects

### ISSUE THREAD

**Issue by FLO-2DKaren** [FLO-2DSoftware/qgis-flo-2d-plugin#1015]
If two gpkg are available, the plugin will load data from both.  It loads data from the original path and the new path.  

Let's say this is a noncritical bug and fix it when we have time.

**Comment by FLO-2DKaren** [comment]
OK I just confirmed with the new geo organization that when you load a geopackage and one still exists in the old path, two sets of layers load.



![Image](https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/assets/20424460/53c37148-f551-442f-80e8-1ab337d7df97)

**Comment by rpachaly** [comment]
@FLO-2DKaren 

I cannot reproduce this bug. I did some changes on the way that I call the projects inside the geopackage, it may have fixed it.

**Comment by FLO-2DKaren** [comment]
OK cool.  I'll test it on my system too.

**Comment by FLO-2DJJ** [comment]
I tried several loading combinations and could not reproduce the error. If the bug occurs again to anyone please indicate step by step to see if it could be replicated.

**Comment by FLO-2DKaren** [comment]
It's pretty easy to reproduce.  You need to make a copy of the gpkg in a different path and then load the gpkg using the new path. 

Because the gpkg is still in the old path, it loads twice.

It's a common problem in classes and when users copy their project into another folder so they can make changes that they don't want in the original project.

**Comment by rpachaly** [comment]
I was able to reproduce it here now. I'll fix it.

**Comment by rpachaly** [comment]
It is done. 

My testing procedure was the following:

1. Created two folders. One with the geopackage and another with the copy of it. 
2. Loaded each gpkg trough the FLO-2D Open Project button and the Recent Projects

No duplicates were found. 

I'm fixing all bugs in one branch, one commit per bug fix. I'll push this branch when I finish all "In Progress" issues.

**Comment by FLO-2DKaren** [comment]
Nice.  I'll wait for everything before I do any testing.

**Comment by FLO-2DKaren** [comment]
Hi Robson,  Since we aren't releasing this branch for a while, I can do testing on the main branch.  Once we are closer to a release, I prefer to do testing on a test branch.  If that makes sense.

**Comment by FLO-2DKaren** [comment]
I haven't had any more issues with this so I'll close this issue.
