### ISSUE TITLE
Geopackage Improvement

### ISSUE THREAD

**Issue by FLO-2DKaren** [FLO-2DSoftware/qgis-flo-2d-plugin#1016]
An email from Robson
Good morning Karen, 

I'm studying the Geopackage and I've found out that we can save the QGIS project into the Geopackage. Check the end of this video: https://www.youtube.com/watch?v=5J-J_DreFK8

Some people got confused on the Brazil Workshop regarding the .gpkg and the .qgz. Maybe we could add the .qgz into the geopackage in the future.

**Comment by FLO-2DKaren** [comment]
Update the path variable if the project moves.

**Comment by rpachaly** [comment]
OK, this is going to be a **big deal**. I was able to save the .qgz into the geopackage and open a .qgz from a geopackage (just need a little bit more of testing here to push the branch). The point is that if you add a symbology to a raster saved into the geopackage and opens that project inside the geopackage, the symbology is maintained. 

Why is that important? Rasterizor and MapCrafter. If we allow them to create the rasters into an existing FLO-2D geopackage, everything will be in the same place (one single geopackage) with all symbology maintained. So, all FLO-2D project data will be in one single file, making it a lot easier for data organization and sharing.

**Comment by FLO-2DNoemi** [comment]
Excellent, this is a good finding.

Noemi

**Comment by FLO-2DKaren** [comment]
This is excellent news.  
Robson,  
Try this easy test:

Build a project in one path and then copy it to another path and open it from the new path.   
See if it duplicates anything.

**Comment by rpachaly** [comment]
While I'm testing here and trying to solve the duplicate issue, do you agree with these two new icons?

![Image](https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/assets/39889306/0ef68141-c3e4-4a3d-b452-2461c7ab8e16)

1. The FLO wrench icon will ONLY create a new geopackage with a *.qgz inside. I've removed the open option on the settings dialog. I think we should call it create FLO-2D project/database instead of settings, it is more straightforward.
2. The FLO folder icon will open a geopackage that contains a *.qgz file inside and, if the *.qgz file is not present, it will open the geopackage and create the *.qgz project inside of it (for compatibility sake).
3. The FLO save icon will save the *.qgz inside the geopackage, no need to use the QGS save button anymore. 

Please, feel free to suggest anything or reject these changes.

**Comment by FLO-2DKaren** [comment]
I'm ok with all of the ideas so far.  But can we do a meeting because  I think we have too many branches.

**Comment by rpachaly** [comment]
Sure, just send me the link when you're ready.

**Comment by FLO-2DKaren** [comment]
Explore geopackage compression.

**Comment by rpachaly** [comment]
For tracking my testing:


![Image](https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/assets/39889306/8a3c8d09-cd4f-4682-bca3-50dd2a90cb48)

**Comment by FLO-2DKaren** [comment]
Hi Robson,

I think that your methodology will likely account for this but if someone tried to load a 10.36 or 10.66 gpkg, it is missing 10 tables and may have 2 tables that no longer exist.  

I think that your two steps labeled Open Existing Project should have a mechanism that imports old gpkg structure into the new structure if the structure is different.  Because moving forward, the gpkg will be more fluid.  

The current code isn't very good at recognizing and loading old geopackages but that's dumb because it's not a difficult process.

**Comment by FLO-2DKaren** [comment]
Hi Robson, 

I pulled this off another issue because it belongs here.  Can you build a Project or Metadata table for the geopackage that has this info.

Include meta data with a project

Project Table
Project Name
Contact Engineer Name
email address
QGIS Build
Plugin Build
FLOPRO Build
CRS EPSG Code

**Comment by rpachaly** [comment]
My initial idea was to keep the Import Geopackage button for this geopackage compatibility issue. However, we can get rid of this button and include this into the new Open Geopackage button. Send me an old geopackage for me to include this and test. 


Yes, I'll try to build a metadata for the geopackage. Can you make this another issue?

**Comment by rpachaly** [comment]
I'm going to be working on this [branch](https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/tree/geo_improve). No need to test right now.

**Comment by FLO-2DKaren** [comment]
I'm going to close this because the work is done.  We are only working on kinks now.
