### ISSUE TITLE
Layer Filter in Calculator Windows

### ISSUE THREAD

**Issue by FLO-2DKaren** [FLO-2DSoftware/qgis-flo-2d-plugin#1017]
For the next Plugin Build, I would like to explore filtering the layers so that only layers with at least one feature are presented as an option for the calculators.  It's already happening with the Walls calculator but it would be a great improvement for the other calculators.

![image](https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/assets/20424460/670a1afe-a4cd-4fee-9949-9ba9cf6ecdc4)

**Comment by FLO-2DJJ** [comment]
There are several dialogs that require filtering empty layers. This is an example:

- Without filter:

![image](https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/assets/20424575/048cf6d9-bc46-49c2-b8b3-359de217b65a)

- With filter:

![image](https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/assets/20424575/820039b1-348a-490a-8bb7-c33da3cb2445)

I'll continue with the others.

**Comment by FLO-2DJJ** [comment]
Combo boxes to filter:    **Class** (method)

- [ ] **SamplingManningDialog** (setup_src_layer_cbo)
- [ ] **SamplingToleranceDialog** (setup_src_layer_cbo)
- [ ] **SamplingOtherVariableDialog** (setup_layer_cbo)
- [ ] **SamplingXYZDialog**) (setup_layer_cbo)
- [ ] **StormDrainShapeFile**) (setup_layer_comboxes) 6 instances
- [ ] **WallsShapeFile** (setup_layers_comboxes)
- [ ] **SCSDialog** (setup_layer_combos)
- [ ] **PreProcessingWidget** (populate_dam_cbo)
- [ ] **PreProcessingWidget** (populate_channel_cbo)
- [ ] **HazusDialog** (setup_layer_comboxes)
- [ ] **HazusDialog** (setup_statatistics)
- [ ] **SamplingBuildingsElevationsDialog** (setup_layer_cbo)
- [ ] **SamplingTailingsDialog** (setup_src_layer_cbo)
- [ ] **ICEditorWidget** (save_tailings_edit)
- [ ] **SCSDialog** (setup_layer_combos)

**Comment by FLO-2DKaren** [comment]
Here is another idea for this issue.  It is related.

When I was coding MapCrafter I figured out that we can add a layer and keep it hidden on the addMapLayer function:

addToLegend (bool = True) – If true (by default), the layer will be added to the legend and to the main canvas. If you have a private layer you can set this parameter to false to hide it.

It is totally possible to modify the code to show layers that have a feature on it or when the user interacts with a specific layer (add bc, bank lines, storm drain features, etc). This way we don't need to group the unused layers, keeping the Layers' tree cleaner.
