### ISSUE TITLE
Project review

### ISSUE THREAD

**Issue by rpachaly** [FLO-2DSoftware/qgis-flo-2d-plugin#1018]
Noemi:

Be able to load additional files for project review, typically files that have grid cells,  X and Y but not necessarily go from 1 to NNOD, could be a partial list of elements with maximum depths or froude numbers and the file can have an arbitrary name. For example VELTIMEFP (header has to be skipped or we can do something about the format of this file).

**Comment by FLO-2DKaren** [comment]
c.	Use Map Crafter to make easier the project review for large ADMS projects.
d.	Adjusted the format of output files to facilitate project review in QGIS, like the VELTIMEFP.OUT, VELTIMEC.OUT and TIME.OUT
