### ISSUE TITLE
Grouping Buttons

### ISSUE THREAD

**Issue by FLO-2DKaren** [FLO-2DSoftware/qgis-flo-2d-plugin#1021]
Group any import Export button to a drop down.

Anywhere that you see the name GDS remove it and replace it with data file.

**Comment by rpachaly** [comment]
I added an icon and grouped all import/export.


![Image](https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/assets/39889306/159c5dec-43b5-403a-a086-7f5cc323075a)


I liked this icon, it has a very close color palettes. What do you think?

**Comment by FLO-2DKaren** [comment]
Yes that looks good.

**Comment by rpachaly** [comment]
Done. I created a [pull request](https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/pull/1027) for testing.
