### ISSUE TITLE
QGIS 3.34 new release

### ISSUE THREAD

**Issue by rpachaly** [FLO-2DSoftware/qgis-flo-2d-plugin#1026]
Bug on creating/opening a project

![image](https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/assets/39889306/b89a6442-4a0d-4f5b-bbc8-dd697d85f96d)

**Comment by rpachaly** [comment]
I also get this Python Warning. This also happens on the LTR version.

![image](https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/assets/39889306/1130ec13-248e-4cba-81c9-d995046536e2)

**Comment by FLO-2DKaren** [comment]
extract the qgz file and you will see the db file that comment 1 is referring too.
