### ISSUE TITLE
Storm Drain Drop Box Volume

### ISSUE THREAD

**Issue by FLO-2DKaren** [FLO-2DSoftware/qgis-flo-2d-plugin#1029]

**Comment by FLO-2DJJ** [comment]
Hi @FLO-2DKaren, @FLO-2DNoemi,
Since this issue is mentioned in issue #1155 (District Task 3 QGIS Plugin) could you expand its description or copy the District specification of it if exists?
Is it related to #1050 (Storm Drain Volume Conservation Filling Pipe)?
Thanks.

**Comment by FLO-2DKaren** [comment]
There isn't any extra instructions from the District.  We need to make the decisions ourselves.

**Comment by FLO-2DKaren** [comment]
This data can be added to the storm drain inlet nodes.  The data is saved to a file called swmmflodropbox.dat.
It is in the 2023 Data Input Manual.

2694 19.635 Line 1: SWMMDBID SWMMDROPBOX(I)
I = Number of drop box nodes.
SWMMFLODROPBOX.

But like all of our data, this should be written as

GE#   SDName   SDDBVolume

Noemi can change add the SD name to the SWMMFLODROPBOX during the file mod.

@FLO-2DJJ.  Export the data with the SD Name too ok?

![image](https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/assets/20424460/a7a55c30-9622-492b-b1ba-7dcad9024d9f)

![image](https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/assets/20424460/830c5bc6-9f08-4bce-85ea-a8510e003b4d)

**Comment by FLO-2DNoemi** [comment]
@Juan Jose Rodriguez ***@***.***>

The file swmmflodropbox.dat is described in the DATA INPUT MANUAL.PDF, you
can see the description on page 163 of the DATA INPUT MANUAL.PDF. Karen
added PNG  images to the email above showing the content of the file.

The SWMMFLODROPBOX.DAT file only needs the grid cell that contains the
inlet and the Dropbox surface area for the inlet, this is a real number. We
do not need the inlet name.

@Karen OBrien ***@***.***> :  Is there a reason that I do not see to
include the inlet name in the file?

Please note the following: the description of the file SWMMFLODROPBOX.DAT
in the DIM 2023 is not correct:    instead of  STORM DRAIN BLOCKAGE METHOD
FILE, change to something like SPATIALLY VARIABLE DROPBOX SURFACE AREA FOR
INLETS.

Noemi

**Comment by FLO-2DKaren** [comment]
Hi Noemi,

It's just a practice that I like to maintain so that I know which node I am working with and I don't have to go look at the grid element number and cross reference it to the inlet name.

**Comment by FLO-2DNoemi** [comment]
I do not have a problem with that, and I understand that when you review
the data files you need the grid and name of the inlet to cross reference
the information but once we have the HDF5 format in place, the intention is
to do project review using the graphic tools in the plugin. This means not
needing to open the ASCII files but instead loading the data in QGIS where
data is automatically cross referenced. Does that make sense?

**Comment by FLO-2DKaren** [comment]
@FLO-2DJJ 
You can start this now.

**Comment by FLO-2DJJ** [comment]
OK. I'll do it.

**Comment by FLO-2DJJ** [comment]
@FLO-2DKaren, @FLO-2DNoemi, I’m starting this new feature. However, based on the comments above, it is not clear what actions to take within the plugin or how to write the data in the SWMMFLODROPBOX.DAT file. There are a pair of conflicting comments.
Could you please clarify? Thanks.

**Comment by FLO-2DNoemi** [comment]
JJ,

The Data Input Manual has the information about the format needed for the
data file.

This should be an additional field Dropbox Surface Area to the inlet
Junctions shapefile and associated SD tables in the plugin. I think Karen
is going to provide a video.

Noemi

**Comment by FLO-2DKaren** [comment]
@FLO-2DJJ 

https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/assets/20424460/3946eb85-3ee7-40ad-b7cd-ce0cec1f57cc

**Comment by FLO-2DKaren** [comment]
Let's set it up like swmmoutf.dat.  

swmmId   gridNum   dropBoxArea




![Image](https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/assets/20424460/0085ff40-403b-4298-90d2-7bfabe427eb8)

**Comment by FLO-2DJJ** [comment]
Thank you for your feedback, with that I should have enough to continue.

**Comment by FLO-2DJJ** [comment]
Tasks:

- [ ] Add drboxarea to user_swwmm_nodes table. (DEFAULT 0.0)
- [ ] Add field  **& Dropbox Area** to Inlets/Junctions tab in **Select components from SF**. Include label **& field for SWMMFLODROPBOX.DAT** and...   
     - [ ]   Populate dialog   and  assign fields
- [ ] Add control and column to Inlet/Junctions component dialog. Include label **(4) SWMMFLODROPBOX.DAT** and...
     - [ ]   Populate dialog and save
- [ ] Export SWMMFLODROPBOX.DAT
- [ ] Add dataset SWMMFLODROPBOX to export to hdf5? @rpachaly 
- [ ] Import SWMMFLODROPBOX.DAT
- [ ] Import from hdf5? @rpachaly
- [ ] Schematize Inlets (schematize_inlets_and_outfalls)

**Comment by rpachaly** [comment]
@FLO-2DJJ 

Yes, let's add the SWMMFLODROPBOX export to hdf5. For the import, let's wait a bit.

**Comment by FLO-2DJJ** [comment]
@FLO-2DKaren, @FLO-2DNoemi 
I added a new field **drboxarea** to the User Layer **Storm Drain Nodes**, and a new field to be selected from a inlets/junctions points shapefile:

![imagen](https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/assets/20424575/a4dd68f9-a52c-40f3-96bb-439403170e6a)

Question: When exporting SWMMFLODROPBOX.DAT, if all values of the drboxarea field are 0 (zero) should I delete an existing SWMMFLODROPBOX.DAT?

**Comment by FLO-2DJJ** [comment]
> Yes delete the old file it if it is not being applied. Otherwise, we may call the old file and use what is in it. You should do that for both clogging and drop box if you haven't already.

- [ ] Delete old SWMMFLODROPBOX.DAT if all values in drboxarea field are zero.
- [ ] Delete old SDCLOGGING.DAT if all values of fields Clogging Factor and Time for Clogging are zero. See next below.
- [ ] @FLO-2DKaren, @FLO-2DNoemi: Does SDCLOGGING.DAT is ever used, read, or written? The current plugin has no code for that file.

**Comment by FLO-2DNoemi** [comment]
- Does SDCLOGGING.DAT is ever used, read, or written? The current plugin
   has no code for that file. Yes, the file is used. We should add the
   capability to read the file and create it.

**Comment by FLO-2DKaren** [comment]
We don't have import export code for clogging.dat?  Are you sure?  I thought that was put together by Lutra.

**Comment by FLO-2DJJ** [comment]
> We don't have import export code for clogging.dat? Are you sure? I thought that was put together by Lutra.

Let me check the old plugins.

**Comment by FLO-2DJJ** [comment]
Another task for this issue:

- [ ] Implement the **Import selected components files** (One Single Component) for SWMMFLODROPBOX.DAT

**Comment by FLO-2DJJ** [comment]
@FLO-2DKaren, @FLO-2DNoemi, 
I’ve submitted pull request #1268 for your review. Please take a look at this issue and merge it if it accomplishes the desired functionality.

**Comment by FLO-2DJJ** [comment]
Completed and merged into master from pull request #1268
