### ISSUE TITLE
Structure to Convert Schema to User Layers

### ISSUE THREAD

**Issue by FLO-2DKaren** [FLO-2DSoftware/qgis-flo-2d-plugin#1030]
Add Structures to  Convert Schema to User layers

![image](https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/assets/20424460/deb8533e-7d05-4631-97e9-872d31b854e7)

It's pretty easy.  Simply Copy features from Hydraulic Structures layer to Structed user layer

![image](https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/assets/20424460/ea0148d7-f6af-447f-a699-e1ac932f8191)

**Comment by FLO-2DJJ** [comment]
I'm doing it:

- [ ] Add 'Hydraulic Structures' checkbox to 'Schematic to User...' dialog.
- [ ] Code connection of above checkbox to conversion code in Schema2UserDialog class.

**Comment by FLO-2DJJ** [comment]
- [ ] To Fix: Errors occur if a schematic hyd. structure is deleted in Layers Panel: FLO-2D panel retains item in combo box of FLO-2D panel widget. Solution: make trigger in db_structure.sql  to delete item in 'user_struct' table.

**Comment by FLO-2DJJ** [comment]
> It's pretty easy. Simply Copy features from Hydraulic Structures layer to Structed user layer

Not so pretty easy and simple. Not too complicated either, but it has some nuances and requires fine-tuning.

**Comment by FLO-2DJJ** [comment]
To examine later:
- [ ] Why Center checkbox gives error?
![image](https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/assets/20424575/edfdff62-a83f-4bf6-ac3d-bcc48c59e830)

**Comment by FLO-2DJJ** [comment]
Quote from previous comment:
> To examine later:
> 
>     * [x]  Why Center checkbox gives error?
>       ![image](https://user-images.githubusercontent.com/20424575/282363353-edfdff62-a83f-4bf6-ac3d-bcc48c59e830.png)
Fixed: error produced because there were not user structure lines. Solved when schemetized structures converted to user structures. However, an aditional exception was included to catch the potential error in case the convertion was not already done by the user.

**Comment by FLO-2DKaren** [comment]
Put that error message in ChatGPT.  It will help you find a solution.  Here's the one I use.
https://thechatgpt.ai/chat

You get 7 free questions a day.  

I also have an account on this one if I run out of questions.
https://chat.openai.com/auth/login?iss=https%3A%2F%2Fauth0.openai.com%2F

**Comment by FLO-2DKaren** [comment]
JJ  Is the reason for that error because the structures are not in the user layer?

**Comment by FLO-2DJJ** [comment]
Yes Karen, the error is generated when the user Structure Lines layer is empty, AND a structure is selected in the Structures Editor widget with the 'center' checkbox clicked.
I already solved the problem but have not merged it yet into GitHub main.

**Comment by FLO-2DJJ** [comment]
Merged [#1036](https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/pull/1036) into master.

Won't close this issue until fixing this:

> * [ ]  To Fix: Errors occur if a schematic hyd. structure is deleted in Layers Panel: FLO-2D panel retains item in combo box of FLO-2D panel widget. Solution: make trigger in db_structure.sql  to delete items in 'user_struct' table.

**Comment by FLO-2DKaren** [comment]
I added a video to show you what I mean by why this is a simple issue.
https://flo-2d.sharefile.com/d-sff3607fa13294241b26c8669dd4e4f22

**Comment by FLO-2DJJ** [comment]
> I added a video to show you what I mean by why this is a simple issue. https://flo-2d.sharefile.com/d-sff3607fa13294241b26c8669dd4e4f22

Hi Karen, I still can not enter the FLO-2D Sharefile. It requires a verification with my old phone number. Could you reset it to +34 623 000 580 ? Thanks

**Comment by FLO-2DJJ** [comment]
> Karen Note: You shouldn't use the layer editor to delete a structure. You should use the Widget delete button. If it works by deleting the structure with the Widget, then you can close the issue.
