### ISSUE TITLE
Import swmm.inp writing too many conduits

### ISSUE THREAD

**Issue by FLO-2DKaren** [FLO-2DSoftware/qgis-flo-2d-plugin#1031]
Import inp is  creating too many conduits and it seems like the export inp is doubling up on conduits.  I'll get a video of this so we understand it more fully.

**Comment by FLO-2DNoemi** [comment]
I am helping a user that is dealing with this issue. Double conduits in the
inp file.

**Comment by FLO-2DJJ** [comment]
@FLO-2DKaren, do you have the user project and/or swmm.inp? Is so, please, send them to me.

**Comment by FLO-2DKaren** [comment]
You can do it with Lesson 3 data.  It's just importing the inp and then look at the conduit table to see all of the stuff that is duplicated and then export the inp to see the conduits that are duplicated.

**Comment by FLO-2DJJ** [comment]
Fixed. Already merged into master. Please test it.

**Comment by FLO-2DKaren** [comment]
Still Duplicates.  Here's a video on my method.  Maybe my method is wrong?
https://attendee.gotowebinar.com/recording/4875988158216660062

**Comment by rpachaly** [comment]
We should consider using this library for dealing with the .inp files

https://pyswmm.github.io/pyswmm/reference/api/pyswmm.links.Link.html

**Comment by FLO-2DJJ** [comment]
Yes Karen, there are still duplicates. I missed part of the code during loading of the INP file. I'm looking at it.

**Comment by FLO-2DJJ** [comment]
Fixed again and merged into master. @FLO-2DKaren and @FLO-2DNoemi  please review it to close the issue.

**Comment by FLO-2DJJ** [comment]
Pumps, orifices, and weirs do not have functionality for 'Keep existing and complete'. 
Adding new #1042 issue.
