### ISSUE TITLE
Swmm control data belongs in the geopackage

### ISSUE THREAD

**Issue by FLO-2DKaren** [FLO-2DSoftware/qgis-flo-2d-plugin#1032]
![image](https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/assets/20424460/d9af4604-562d-4aa5-96b2-ff4e2ef7b7e1)

**Comment by FLO-2DKaren** [comment]
Hi Robson,

As you are working on the geopackage improvement, can you please add a table for this data.  We can build the data io and connect it to the dialog later but if the table exists, that will be easier.

**Comment by rpachaly** [comment]
Ok, I created the table into the db. Since some data are text and other string, I set the table this way:


![Image](https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/assets/39889306/452172d7-0f22-41e3-8d43-3351d1fb9504)
