### ISSUE TITLE
Examine all "Center' checkboxes in FLO-2D Panel: error when there are no corresponding user layer features.

### ISSUE THREAD

**Issue by FLO-2DJJ** [FLO-2DSoftware/qgis-flo-2d-plugin#1035]
![image](https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/assets/20424575/c9e778ea-ed8f-4552-96d1-1e9c1ae26d71)
(Refer to issue #1030)
There are 7 'center'  checkboxes in the FLO-2D panel.
Also:
- [ ] Add a 'try...except' statement around the code to catch the error.

**Comment by rpachaly** [comment]
When fixing this bug, let's change all to the eye, it is nicer. 

![image](https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/assets/39889306/691c466f-8bf1-464d-aba2-29a111b63475)

**Comment by FLO-2DJJ** [comment]
> When fixing this bug, let's change all to the eye, it is nicer.
> 
> ![image](https://private-user-images.githubusercontent.com/39889306/318132455-691c466f-8bf1-464d-aba2-29a111b63475.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE3ODg4NjYsIm5iZiI6MTcxMTc4ODU2NiwicGF0aCI6Ii8zOTg4OTMwNi8zMTgxMzI0NTUtNjkxYzQ2NmYtOGJmMS00NjRkLWFiYTItMjlhMTExYjYzNDc1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzMwVDA4NDkyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgwM2Y3YmU3N2Y1YTg2ZmRmYzQ2ZGU2NWViNjdhYTUzZGM4YmMxODYxOTIxZjZjYmE1M2E3NWY5ZmU4YWRmY2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.20GgppYl-zbHAa5cRowc51vr2-vi1IE1Oohrinok9h0)

Yes, I agree. I'll do it.

**Comment by FLO-2DJJ** [comment]
Completed in #1310
