### ISSUE TITLE
Geo Improve Test Export .DAT files

### ISSUE THREAD

**Issue by FLO-2DKaren** [FLO-2DSoftware/qgis-flo-2d-plugin#1039]
When I imported the rainfall pattern, it caused the Export  *.DAT file button to use the Rainfall Pattern Path.  That path should stay as the project export path from the last export.

Steps

1. load project.
2. Export Dat files to set path.
3. Create Rainfall and import rainfall pattern.
4. Export Dat files again and note that the path was changed to the rainfall Distribution path.

**Comment by FLO-2DKaren** [comment]
Uploading Rainfall Path is updating Export Path.mp4…

**Comment by FLO-2DKaren** [comment]
Video example.  This link requires a login to sharefile.

https://flo-2d.sharefile.com/d-sadf7deef5ad141df8307cf3baf16a6b7

**Comment by rpachaly** [comment]
Export the .INP while exporting GDS also does not get the correct export path.

**Comment by rpachaly** [comment]
I fixed for the .INP quite easily. But for the rain issue, I didn't find where it updates the "FLO-2D/lastGdsDir". It adds a "geopackage:" before the path. I added an if statement to catch that. It is working fine, but it not a good coding practice.

**Comment by FLO-2DKaren** [comment]
Maybe the call button is a **QGS** button that has some additional embedded controls.  If so, can you replace it with a generic Open File button or code?

**Comment by rpachaly** [comment]
The "FLO-2D/lastGdsDir" from the QSettings is what has been used to set the export path everywhere in the code. But on the add_predefined_tseries function:

```
def add_predefined_tseries(self):
        self.uc.clear_bar_messages()
        s = QSettings()
        last_dir = s.value("FLO-2D/lastPredefinedSeriesDir", "")
        predefined_files, __ = QFileDialog.getOpenFileNames(
            None,
            "Select time series files to import data",
            directory=last_dir,
            filter="(*.DAT *.TXT)",
        )
        if not predefined_files:
            return
        s.setValue("FLO-2D/lastPredefinedSeriesDir", os.path.dirname(predefined_files[0]))
        try:
            QApplication.setOverrideCursor(Qt.WaitCursor)
            if not self.rain:
                return
            for file in predefined_files:
                tail = os.path.splitext(os.path.basename(file))[0]
                self.rain.add_time_series(tail, True)
                self.read_predefined_tseries_data(file)
                self.populate_tseries()
            QApplication.restoreOverrideCursor()
            self.uc.show_info("Importing predefined time series finished!")
        except Exception as e:
            QApplication.restoreOverrideCursor()
            self.uc.bar_warn("Importing predefined time series failed! Please check your input data.")

```
Only the "FLO-2D/lastPredefinedSeriesDir" is updated. I didn't find where it updates the "FLO-2D/lastGdsDir". Probably there is a QGS button or other function that updates the "FLO-2D/lastGdsDir" while this function is called.

Let me finish the other issues then I get back to this one. My solution is not the best, but it works for now.

**Comment by FLO-2DKaren** [comment]
I think this one worked because I didn't get the error again.
