### ISSUE TITLE
SD: add 'Keep existing and complete' functionality to the import of pumps, orifices, and weirs from INP file

### ISSUE THREAD

**Issue by FLO-2DJJ** [FLO-2DSoftware/qgis-flo-2d-plugin#1042]
- [x] Pumps
- [x] Orifices
- [x] Weirs

**Comment by FLO-2DKaren** [comment]
Writing too many conduits is done.  I'm happy to test this once you are ready.

**Comment by FLO-2DJJ** [comment]
Finished. There is a follow up in issue #1085

**Comment by FLO-2DKaren** [comment]
I think this one is OK.  I didn't see extra lines.
