### ISSUE TITLE
Deprecated issue

### ISSUE THREAD

**Issue by rpachaly** [FLO-2DSoftware/qgis-flo-2d-plugin#1043]
![image](https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/assets/39889306/4528bf64-d7d3-4c82-9412-f5ddd9a33a99)

**Comment by rpachaly** [comment]
While importing GDS files.

**Comment by FLO-2DJJ** [comment]
### **- This is what Bing Chat with GPT-4 says about the issue:**

> The QgsCoordinateReferenceSystem.toProj4() method is indeed deprecated. [Instead, you can use the createFromProj() method](https://api.qgis.org/api/classQgsCoordinateReferenceSystem.html)[1](https://api.qgis.org/api/classQgsCoordinateReferenceSystem.html). [This method sets the CRS by passing it a PROJ style formatted string](https://api.qgis.org/api/classQgsCoordinateReferenceSystem.html)[1](https://api.qgis.org/api/classQgsCoordinateReferenceSystem.html).
> > The DeprecationWarning: QgsCoordinateReferenceSystem.toProj4() is deprecated warning indicates that the toProj4() function from the QgsCoordinateReferenceSystem class is no longer recommended for use and may be removed in future releases of the software.

### **- And this is what ChatGPT says:**

> 
> To fix this warning, you should consider using the toWkt() or authid() methods instead, depending on your specific use case. These methods are recommended alternatives and provide similar functionality to toProj4() .
> 
> Here's an example:
> 
> # previous code
> crs = QgsCoordinateReferenceSystem(4326)
> proj4_string = crs.toProj4()
> 
> # updated code
> crs = QgsCoordinateReferenceSystem(4326)
> wkt_string = crs.toWkt()
> auth_id = crs.authid()
> 
> By making this change, you should no longer receive the deprecation warning and can ensure compatibility with future versions of the software.

**Comment by rpachaly** [comment]
Thanks JJ! I changed the toProj4() to toProj() and the warning is gone.

**Comment by FLO-2DKaren** [comment]
If Proj4 is deprecated, we should fix it here too.

calc_average_elev.py
flo-2d.py
dlg_settings.py

**Comment by FLO-2DKaren** [comment]
hmmm new deprecation warning when I import.  This import had
channels
Structure
grid
infiltration
rain
inflow outflow
reservoir

2023-11-24T16:13:22     WARNING    warning:C:\Users/Alejandro Riano/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\flo2d\flo2d.py:793: DeprecationWarning: QgsCoordinateReferenceSystem.createFromId() is deprecated
              crs.createFromId(rt)
             
             traceback: File "C:\Users/Alejandro Riano/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\flo2d\flo2d.py", line 793, in show_settings
              crs.createFromId(rt)
