### ISSUE TITLE
Show/Hide Layers

### ISSUE THREAD

**Issue by FLO-2DKaren** [FLO-2DSoftware/qgis-flo-2d-plugin#1044]
Start a project with a simple layers list and then change the show/hide status of specific layers when the user turns on a control switch.

For example, If you want to model channels, check the channel switch on in Control Variables or you check a Use Channels switch on the cross section editor widget.

Some layers can always remain hidden since they are not needed by the user.

**Comment by rpachaly** [comment]
I added this issue to the plugin organization project. The new BC editor has a code that does this for the BC layers. Let's use the new BC editor as an experiment for this show/hide layers.

**Comment by rpachaly** [comment]
I've found out a better way of hide/show layers without that lock icon on the right:

https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/assets/39889306/6171b4a8-29cc-4658-bb48-d6d4df082d66

**Comment by rpachaly** [comment]
@FLO-2DKaren What do you think?

https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/assets/39889306/18dcc4c0-57af-4456-a03b-10e6baaaa8b9

**Comment by FLO-2DKaren** [comment]
That is nice and it’s very simple too so it won’t have any problems.

**Comment by rpachaly** [comment]
I'm a little worried about what happens when opening old projects. I'll test it later

**Comment by FLO-2DKaren** [comment]
I can start testing this week during our class.

**Comment by rpachaly** [comment]
Ok, I'll try to wrap up the branch and push it today.

**Comment by rpachaly** [comment]
I want to create subsubgroups:

![image](https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/assets/39889306/717190eb-969c-4e1e-a858-b0df98ab58ea)

I couldn't make it to work today. Probably tomorrow I'll have it ready.

**Comment by rpachaly** [comment]
Added the subsubgroups:

https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/assets/39889306/2fe420e5-294d-4fa9-9926-a664f6fb8a80

It is on pull request https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/pull/1192

**Comment by FLO-2DKaren** [comment]
OK excellent.

Let's add the following to advanced layers:
streets
mult channels
gutters

You can do it for user and schema

Put EFF with infiltration

What do you think of this idea?  What if people are not using something, they can add it to the Advanced Layers?

I'm going to start testing it with my projects.

**Comment by rpachaly** [comment]
Ok, this is easy to do. I'll add and commit it to the branch. 

> What do you think of this idea? What if people are not using something, they can add it to the Advanced Layers?

This is more complicated, but doable.

**Comment by rpachaly** [comment]
Updated the pull request https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/pull/1192

I did not add the possibility of the user change a layer to advanced. I'll have to think about the best approach to do that. I mean, how to select? Maybe on the gpkg management? On an editor?

**Comment by FLO-2DKaren** [comment]
OK let's think about it for the future.  I don't think it is necessary today.
Can I merge this?  I tested it on 3 different projects.

**Comment by rpachaly** [comment]
Sure, I'm pretty sure that if it has some bugs, they will be minor.

**Comment by FLO-2DKaren** [comment]
Tested no bugs yet.
