### ISSUE TITLE
Storm Drain Type 4 Culvert Editor

### ISSUE THREAD

**Issue by FLO-2DKaren** [FLO-2DSoftware/qgis-flo-2d-plugin#1052]
2024 let's build the editor for this.  Right now only import data is allowed.

![image](https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/assets/20424460/039566e5-31aa-4cf7-bc29-0ba8cbcac6d4)

**Comment by FLO-2DNoemi** [comment]
The _**Add Inlet Type 4 Data**_ should open the **_FLO-2D Table Editor_** to entering the data (see images below). 

![image](https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/assets/20424558/6f92a0d9-db22-42b9-9899-7dc30b30594d)

![image](https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/assets/20424558/49eb12d6-1666-491b-a731-3ee4374bcc8d)

**Comment by FLO-2DJJ** [comment]
Issue #1088 included to address the 'Add Inlet Type 4 Data' for Culvert equations as well as rating table

**Comment by FLO-2DJJ** [comment]
In the SD Widget Editor the option to 'Add inlet type 4 data' should consider 2 options: rating table (currently the default) but also a Culvert Equation.
![286818350-c305d323-f02b-4045-9e4d-a5f7c05fda7a](https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/assets/20424575/962d8ce5-6ad4-4007-8e7c-6b56f4abb023)

**Comment by FLO-2DKaren** [comment]
@FLO-2DJJ 

Sorry I added my review comments to the pull request.  I don't really like that system.  Let's only do a pull request when we are ready to merge not when we are still in review.

Did you fix the issues I reported with the video?

**Comment by FLO-2DJJ** [comment]
Yes. The issues reported in the video were fixed.
