### ISSUE TITLE
Update Storm Drain Manual

### ISSUE THREAD

**Issue by FLO-2DKaren** [FLO-2DSoftware/qgis-flo-2d-plugin#1056]
District Task so use this issue to take notes.  This can be part of the Storm Drain Project.

**Comment by FLO-2DKaren** [comment]
@FLO-2DNoemi 

Noemi,

When you are ready, add the current storm drain manual here via a link.  Word version please.

**Comment by FLO-2DKaren** [comment]
Ideas for this task
1. Remove redundant data.
2. Add a Basin section if we don't already have one.
3. Use an equation identification.
4. Do we want to use Latex for this manual?
5. FCDMC What do you not like about this manual that we can fix?

**Comment by FLO-2DNoemi** [comment]
Karen,

I think we should add the following to this list:

6. Chapter 5: Keep this chapter and add a storm drain troubleshooting
lesson.
7. Chapter 6: Reviewing storm drain model results, remove this chapter and
replace it with an advanced mapping lesson.
8. Chapter 7: Porting SWMM data files to a FLO-2D Storm drain model, keep
this chapter, maybe simplify it and add a lesson to port a SWMM.INP file to
FLO-2D.


Noemi

**Comment by FLO-2DKaren** [comment]
complete
