### ISSUE TITLE
Error loading QGIS project via "Recent Projects"

### ISSUE THREAD

**Issue by FLO-2DJJ** [FLO-2DSoftware/qgis-flo-2d-plugin#1060]
The error:
![image](https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/assets/20424575/6d77a732-8676-47cf-bc14-ca5415618ed0)

Error occurs when loading a project via Menu Bar:

![image](https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/assets/20424575/ed5385c4-8675-46fc-9292-2238139a9a0d)

or via "Recent Projects" in Welcome Page:

![image](https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/assets/20424575/7e08e9cb-8143-471e-9137-66e686e4baf5)

The error **_doesn't happen_** by the new FLO-2D toolbar icon:

![image](https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/assets/20424575/a0c10e5e-90ea-42c1-96be-532af4859842)

(I'm using QGIS Version 3.34 Prizren)

**Comment by FLO-2DKaren** [comment]
I wonder if we can create a flag some sort of flag to tell people to use the flo-2d buttons?

JJ,  I'm starting Testing and Documentation updates on Monday.  I have to work on the newsletter and release this weekend.

**Comment by rpachaly** [comment]
This error arises because it is reading the project inside the geopackage now. It is better to use the FLO-2d open button.

I'll take a look and try to fix it when opening from recent projects and menu bar.

**Comment by rpachaly** [comment]
@FLO-2DJJ I'm also using the QGS 3.34-Prizren. Do you also get these warnings when loading a project?

![image](https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/assets/39889306/fdc1c318-3309-4d29-a4fc-c57f86b4aeaa)

**Comment by rpachaly** [comment]
Ok, it is fixed on [branch](https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/tree/open_recent). Opening from the FLO-2D open icon or recent projects will not show any error.

**Comment by FLO-2DJJ** [comment]
Yes Robson. Your branch fixed the issue. From my test you can now merge the
branch into master.

Juan Jose Rodriguez
FLO-2D Software
www.flo-2d.com
***@***.***

**Comment by rpachaly** [comment]
Awesome! Thanks JJ. I`ll create the pull request.

**Comment by FLO-2DKaren** [comment]
tested no db warnings or recent project issues.
