### ISSUE TITLE
QGIS Icons

### ISSUE THREAD

**Issue by rpachaly** [FLO-2DSoftware/qgis-flo-2d-plugin#1062]
I've vectorized some of the *png icons, standardized its size and added them to the toolbar as an experiment. What do you think?

![image](https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/assets/39889306/0c7beb5d-4531-4656-9d11-99292bed96b7)

**Comment by FLO-2DKaren** [comment]
I was thinking to replace the FLO logo with the icon and only apply it to the first 3.

**Comment by FLO-2DKaren** [comment]
That's getting closer but now I think we are using them too much.
@FLO-2DNoemi what do you think?

**Comment by FLO-2DJJ** [comment]
I like the "FLO" text behind the first 3 or 4 rather than the icon. What
are the subitems of the two dropdowns?:
[image: image.png]  ?




Juan Jose Rodriguez
FLO-2D Software
www.flo-2d.com
***@***.***

**Comment by rpachaly** [comment]
My suggestion:

The FLO-2D icon containing all the runs will be the first because it is the most important. Then I would combine the first three icons (settings, open, save) into the geopackage icon because they deal with the geopackage. Then, I'll create another icon for the Import/Export. 

FLO-2D -> Geopackage -> Import/export (new) -> all others

**Comment by FLO-2DNoemi** [comment]
Combining the first three icons into the geopackage makes sense because all
of them are related to opening and saving functions and to the geopackage.

We should try to order the icons following the steps that need to be
completed when you open or create a project.

**Comment by FLO-2DNoemi** [comment]
It makes more sense to maintain the intuitive order, icons like New, Open,
Save, go first then create components, export data.

The run icon seems to fit after set control parameters.

**Comment by rpachaly** [comment]
https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/assets/39889306/9503a3b9-0946-4a0f-9273-577ac833eb10

**Comment by rpachaly** [comment]
I agree with Noemi. 

I also think that we can combine the Channel Profile and Grid Info Tool into the Info Tool.

**Comment by rpachaly** [comment]
If you'll have more suggestions, please feel free to contribute. This night I'll try to come up with a combination of all suggestions.

**Comment by rpachaly** [comment]
In this new version I tried to be as close as possible to the QGIS icons. Note the new/open/save icons on bottom right. I also added the logos for importing/reading SWMM, HECRAS, HDF5, FLO-2D data. Take a look:

https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/assets/39889306/6a5aafaa-7daa-42aa-82e7-2d5cf5760264

What do you all think about the new order?

**Comment by FLO-2DJJ** [comment]
I rather keep the first 3 as:

![image](https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/assets/20424575/aad13d60-d86c-4fb1-92e6-2e12ff6eac5b)

with this submenus:
![image](https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/assets/20424575/f5e91ce6-b839-478a-84f3-62f5f31f9b92)

![image](https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/assets/20424575/a16ab740-c37a-4681-95ff-d0ead118fec7)

![image](https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/assets/20424575/b912e9d0-0840-4c23-a2df-a629f8c685d4)

Also, the 'Info Tool' and 'Select.RPT file' are related and should be somehow together 
![image](https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/assets/20424575/46dc43f4-f48d-46b3-a92b-54dc9d974165)

**Comment by rpachaly** [comment]
Following @FLO-2DJJ comments:

https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/assets/39889306/1da6bcd3-b2a1-4441-8d42-780c16ad410f

I also did the following:

- Combined the control parameters, mud & sediment, evaporation, and levee tools into one icon. Even though I believe that adding the levee tool and the evaporation editor into FLO-2D widgets is better, I kept them there. 

- Created the FLO-2D Project Review icon. My idea here is to separate the tools that don't need a run to be used (e.g. grid info tool) into the FLO-2D Info Tools and the tools that need a run to be used (HAZUS) into the FLO-2D Project Review. For instance, we can add a project summary tool that reads the SUMMARY.OUT and show important variables such as volume conservation, inundated area, computer run time, and stuff like that. Also, the storm drain review tools could be placed here. 

I'm thinking a lot about potential future escalating. Keeping everything more nested has two advantages. 

1. It is more understandable since we have an icon and a brief explanation.
2. Easy to add and remove stuff without having to change all documentation.

**Comment by FLO-2DKaren** [comment]
Run Settings stays in the Run FLO-2D Group
Change mapper button to map crafter and use map crafter icon.
Info icon might confuse regular qgis users.
Help icon might confuse regular qgis users.

**Comment by FLO-2DJJ** [comment]
Agree with Karen, put 'Run Settings' in the 'Run FLO-2D Pro' group:
![image](https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/assets/20424575/ad079ed6-c35d-4f97-be55-7af9380cc8c9)

**Comment by rpachaly** [comment]
I've implemented everything. 

- Make the first icon FLO
- Run Settings stays in the Run FLO-2D Group
- Added MapCrafter and Rasterizor on Run FLO-2D Pro. It looks for the plugins and, if they are installed, they are opened. Otherwise, a message shows up asking the user to install using QGIS Official Plugin Repository. 
- Info & help icon updated
- Changed the FLO-2D Review Project icon 
- Added Run Settings to Run FLO-2D Pro

I liked this toolbar a lot. 


https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/assets/39889306/6e0ee069-1cdc-494f-8266-6e8730fc9aa8

**Comment by FLO-2DNoemi** [comment]
I like it. Very nice.

**Comment by FLO-2DKaren** [comment]
Oh yes this is very nice.

**Comment by rpachaly** [comment]
Ok, I'm going to push this branch.

**Comment by rpachaly** [comment]
I need to fix some bugs with the buttons before pushing this branch. I'll do this after the other issues. 

- [ ] Set Control Parameters -> DeprecationWarning
- [ ] Info Tool -> Need to activate/deactivate the icon at the bar
- [ ] Grid Info Tool ->  TypeError: activate_grid_info_tool() takes 1 positional argument but 2 were given
- [ ] HAZUS -> TypeError: show_hazus_dialog() takes 1 positional argument but 2 were given
- [ ] Channel Profile
- [ ] Warnings and Errors -> TypeError: show_errors_dialog() takes 1 positional argument but 2 were given

**Comment by FLO-2DKaren** [comment]
I'm not in a hurry on this branch.  I'm happy to get these items sorted out before we move ahead with the boundary tasks.

**Comment by FLO-2DKaren** [comment]
I approve this version of the icons but I'm testing them.  I'm going to close this issue and I'll create a new issue if anything comes up in the testing.
