### ISSUE TITLE
Auto Port Geopackage

### ISSUE THREAD

**Issue by FLO-2DKaren** [FLO-2DSoftware/qgis-flo-2d-plugin#1066]
Recognize that the geopackage is old
Read CRS from old geopackage
Build new geopackage (name of old gpkg (pluginversion))

for example new geopackage
projectname_v1.0.0

**Comment by rpachaly** [comment]
@FLO-2DKaren 

I did not tested it yet and there are a lot of small bugs that I need to fix. But here is how the auto port geopackage is going to work:

https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/assets/39889306/b6e73722-1292-47ea-969f-32a5a1eacb8f

1. Identify if the geopackage is outdated based on the number of tables inside the geopackage
2. Create a new gpkg
3. Copy data to the new gpkg
4. Update the metadata 

It is a slow process, I may need to add a progress bar or whatever somewhere. Do you have any suggestions? Specially on the warning messages.

(don't worry about the old toolbar, I'm using the current master branch)

**Comment by FLO-2DKaren** [comment]
That's pretty nice.  How would you calculate the Project Bar?  I guess you could base it on now many tables were loaded?
I'm doing testing now.  Can I get this?  I have loads of old gpkgs that i can test it on.

**Comment by FLO-2DKaren** [comment]
Progress not project

**Comment by rpachaly** [comment]
Yes, probably I'll need to do that. 

I need to work a little bit more on this, Karen. The metadata table is not writing correctly and some of the paths are not working accordingly. I sent it for you to see the general idea of the auto port.

**Comment by rpachaly** [comment]
- [ ] Add progress bar
- [ ] Fix deprecated issue (DeprecationWarning: QgsCoordinateReferenceSystem.createFromId() is deprecated)

**Comment by FLO-2DKaren** [comment]
My first test didn't give the crs for the user layers

This test may be a bad example because It might have started out as a load gds files test.  

![Image](https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/assets/20424460/356266d1-7bb8-49c4-9c0c-f2b747a22344)

**Comment by FLO-2DKaren** [comment]
OK maybe that was just because the gpkg that I tested was really old.  
I suggest we leave this alone until it becomes an issue.
I need to test it with a storm drain project.

**Comment by FLO-2DKaren** [comment]
Oooh this one is harder than I thought it would be.  We'll have to do a meeting.

**Comment by FLO-2DKaren** [comment]
Important test project for our meeting.  https://flo-2d.sharefile.com/d-s76e60b3e894f4fd7b09908fb05a92b13

You may need db browser for sqlite for this project.  It's free if you don't already have it.

**Comment by FLO-2DKaren** [comment]
Let's keep the old import geopackage button on the toolbar until we've fully exhausted testing on this.  I have a feeling this system is very much more complex and will need careful testing with many projects.

**Comment by rpachaly** [comment]
> Let's keep the old import geopackage button on the toolbar until we've fully exhausted testing on this. I have a feeling this system is very much more complex and will need careful testing with many projects.

Does it work with the import gpkg button and not with new the code? I mean, the code is basically the same as the import gpkg button

**Comment by FLO-2DKaren** [comment]
Let's test it on a case I have.  I emailed it to you.

**Comment by rpachaly** [comment]
Hi Karen, 

I did not receive anything on my email. Is this one here? https://flo-2d.sharefile.com/d-s76e60b3e894f4fd7b09908fb05a92b13

**Comment by FLO-2DKaren** [comment]
Yes but I'm going to delete the last comment.  I didn't want it to be linked on here

**Comment by rpachaly** [comment]
Ok, I have downloaded the case here. As soon as I solve the loading 2 projects issue I'll be focused on this one again.

**Comment by FLO-2DKaren** [comment]
OK the key to this one is that the infil tables used to have two tables and now only have one.  Rainarf was like that too.  I think you might have fixed one and Lutra might have fixed one.  The old layers were polygon with tables and they really slowed the whole system down.

I used the db_browser to do before and after comparisons to find missing data.

**Comment by FLO-2DKaren** [comment]
Ooops didn't mean to close it.

**Comment by rpachaly** [comment]
Ok, I'll check one by one. 

Do you know which plugin version created these gpkgs? I need to test infil_cells_horton and infil_cells_chan but I don't have an old gpkg that contains data in these tables. So, I will create a test project for each case from an old plugin.

**Comment by FLO-2DKaren** [comment]
I'll upload the original.  It's got a file date of 2020 but I don't know the plugin version.  I sent you the location via email.

**Comment by rpachaly** [comment]
I did a code that checks which tables are different* from the old gpkg and the new gpkg. The test project showed that these tables are different: 

user_reservoirs
culvert_equations
infil_chan_elems
infil_cells_green
outflow_cells
infil_cells_scs
gutter_cells
infil_cells_horton
mult
reservoirs
grid

I will check one by one.  

*different means any difference in its schema, it could be anything like different number of columns or field converted from float to integer.

**Comment by rpachaly** [comment]
@FLO-2DKaren I've pushed the branch that I'm working on because I did a lot of stuff and I am afraid that we could lose everything if something happens to my computer here. Don't test or merge it yet, I still have some stuff to do.

**Comment by FLO-2DKaren** [comment]
Haha OK I'll leave it alone until you tell me it's OK to test.

**Comment by FLO-2DKaren** [comment]
Not sure if this is important but I'm seeing this in the ogr log message.

2023-12-11T21:54:39     INFO    There was an error querying the database C:/Users/Public/Documents/FLO-2D PRO Documentation/Example Projects/AFMA 2022 Workshop/QGIS Lesson 1/Lesson 1_v1.0.0.gpkg: no such table: qgis_projects

**Comment by FLO-2DKaren** [comment]
I just moved these back so you know I'm not testing them right now.  I'll move them forward when I start testing again.

**Comment by FLO-2DKaren** [comment]
I've tested this on many projects.  I don't see any issues.
