### ISSUE TITLE
Task 2.2 Read current hdf5 file

### ISSUE THREAD

**Issue by rpachaly** [FLO-2DSoftware/qgis-flo-2d-plugin#1068]
Code flopro.exe to read the current hdf5 file that is written by QGIS.

- [x] cont
- [x] rain
- [x] grid
- [x] elev
- [x] manning
- [x] toler
- [x] neighbors

**Comment by FLO-2DKaren** [comment]
Testing now. Noemi and I are testing exporting projects in simple forms with inflow and rain.

**Comment by FLO-2DKaren** [comment]
I'm going to close this issue since it is complete but I want to outline my testing process on another issue so we can track what I've tested.
