### ISSUE TITLE
Task 2.3 Add 2D datasets to hdf5

### ISSUE THREAD

**Issue by rpachaly** [FLO-2DSoftware/qgis-flo-2d-plugin#1069]
Add the 2D datasets to hdf5 with the FLO-2D Plugin.

- [x] Infiltration - Green Ampt
- [x] Infiltration - Horton
- [x] Rainarf
- [x] ARF

**Comment by FLO-2DKaren** [comment]
Split infiltration into green ampt scs and Horton

**Comment by FLO-2DKaren** [comment]
@rpachaly @FLO-2DNoemi 

Horton has that initial abstraction global now.  We need to get that into the hdf5 system.
I think we also need to make sure flopro. can read it.

**Comment by rpachaly** [comment]
This is already implemented into the export to hdf5. 

![image](https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/assets/39889306/92e4069f-95f9-41e2-9850-197533732b2b)

**Comment by FLO-2DKaren** [comment]
OK cool we need to make sure flopro_hdf5.ext  is using it.

**Comment by FLO-2DNoemi** [comment]
I will check the variables that FLOPRO is reading and using for Horton
Method and I will let you know. This is easy to implement.

@Karen OBrien ***@***.***> let me know how your testing is going for
the HDF5. If we work closely on this using the verification tests we should
be able to have a working executable by the end of the week. Upload the
projects as soon as you identify an HDF5 issue and I will fix it and resend
you a new EXE as we did yesterday.

Noemi

**Comment by FLO-2DKaren** [comment]
This is complete
