### ISSUE TITLE
Add "Select all" check box to Schematic to user layers conversion

### ISSUE THREAD

**Issue by FLO-2DJJ** [FLO-2DSoftware/qgis-flo-2d-plugin#1074]
![image](https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/assets/20424575/c77794f0-2b01-410c-a237-dce259970d14)

**Comment by rpachaly** [comment]
I can do that.

**Comment by FLO-2DJJ** [comment]
> I can do that.

Don't worry Robson. I'll do it.
