### ISSUE TITLE
Green Ampt Deprecation Warning

### ISSUE THREAD

**Issue by FLO-2DKaren** [FLO-2DSoftware/qgis-flo-2d-plugin#1077]
Got this warning when I ran Calculate Green Ampt 2018 method with the Log Avb unchecked.

2023-11-24T14:37:38     WARNING    warning:C:\Users/Alejandro Riano/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\flo2d\flo2d_tools\infiltration_tools.py:182: DeprecationWarning: QgsRectangle.setMinimal() is deprecated
              grid_elem_extent.setMinimal()
             
             traceback: File "C:\Users/Alejandro Riano/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\flo2d\gui\infil_editor_widget.py", line 500, in calculate_green_ampt
              grid_params = inf_calc.green_ampt_infiltration()
              File "C:\Users/Alejandro Riano/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\flo2d\flo2d_tools\infiltration_tools.py", line 182, in green_ampt_infiltration
              grid_elem_extent.setMinimal()

**Comment by FLO-2DKaren** [comment]
Note this error did not appear when I switched to the new method.

**Comment by FLO-2DKaren** [comment]
Hi Robson,  I'm trying to clear this issue but I keep getting this error on my new computer.  It isn't happening on any other computer.

ERROR 051218.2001: Green-Ampt infiltration failed!.
__________________________________________________

Error:
   AttributeError: 'QgsRectangle' object has no attribute 'setNull'

In file:
   C:\Users/User/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\flo2d\flo2d_tools\infiltration_tools.py

In function:
   green_ampt_infiltration

On line 183:
grid_elem_extent.setNull()

**Comment by rpachaly** [comment]
Deprecated since version QGIS: 3.34 - will be removed in QGIS 4.0. Use [setNull()](https://qgis.org/pyqgis/master/core/QgsRectangle.html#qgis.core.QgsRectangle.setNull).

**Comment by rpachaly** [comment]
I was not able to reproduce the error here. So, I did the following:

```
if Qgis.QGIS_VERSION_INT >= 33400:
      grid_elem_extent.setNull()
else:
      grid_elem_extent.setMinimal()
```
I hope it works.

**Comment by rpachaly** [comment]
Wait! I'm still working on the autoport. I'll let you know when I finish it

**Comment by FLO-2DKaren** [comment]
Green Ampt OK
