### ISSUE TITLE
SD: Conduits, pumps, and orifices dialogs: add error catching and warnings similar to the weirs dialog

### ISSUE THREAD

**Issue by FLO-2DJJ** [FLO-2DSoftware/qgis-flo-2d-plugin#1085]
This applies to all the comboboxes in the conduits, pumps, and orifices (in the dialogs from the Storm Drain Editor widget). When a row in the table within the dialog is clicked, if the value of a cell is not present in the corresponding combobox, a warning should be issued and the cell’s value should be reset to the default value.
Follow the code already written for weirs.

- [x] Conduits
- [x] Pumps
- [x] Orifices

**Comment by FLO-2DJJ** [comment]
Pumps fixed with Merged [#1087](https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/pull/1087) into master.

**Comment by FLO-2DJJ** [comment]
Done for all 3 dialogs: conduits, pumps, and orifices

**Comment by FLO-2DKaren** [comment]
@FLO-2DJJ 
Don't move them to Done.  If they are finished, move them to review so I know they need to be tested.

**Comment by FLO-2DJJ** [comment]
Ok. I'll move it to review.

**Comment by FLO-2DKaren** [comment]
Seems OK I didn't see any issues related to this and the connecting fields are good.
