### ISSUE TITLE
External Data to Geopackage

### ISSUE THREAD

**Issue by FLO-2DKaren** [FLO-2DSoftware/qgis-flo-2d-plugin#1093]
Writing external data to the geopackage is going to be  more difficult that expected.    

My concerns
MapCrafter layers will make the geopackage large.
Moving the project is still causing path issues.
Using the save button is causing the raster path errors even when using the Yes option.
When you remove a layer, the geopackage still keeps a table of that data.

Let's do a meeting Monday.

**Comment by rpachaly** [comment]
@FLO-2DKaren 

I have added something that I called "FLO-2D GeoPackage Management" under FLO-2D Project icon.

![Image](https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/assets/39889306/332891d1-8a4d-4d18-9410-3258a3c1c5ed)

It basically reads the External Layers added to the geopackage and allows the user to delete them if he wants.
