### ISSUE TITLE
FLO-2D Plugin opening for first time

### ISSUE THREAD

**Issue by rpachaly** [FLO-2DSoftware/qgis-flo-2d-plugin#1095]
Add the FLO-2D executable path.

**Comment by rpachaly** [comment]
This is solved. The best way of testing this kind of issues without using a virtual machine is: 

Settings > Advanced > Uncheck the "Use new settings tree widget" > Click on "I will be careful, I promise! > DELETE the FLO-2D Folder.

**Comment by FLO-2DKaren** [comment]
Is this solved on the branch I'm using?  external_layers_bug

**Comment by rpachaly** [comment]
I'm still committing to the external_layers_bug branch. It depends on how updated it is. 

Do you want me to commit to another branch?

**Comment by FLO-2DKaren** [comment]
No, I'll update next time I save my project.

**Comment by rpachaly** [comment]
Ok. I adding something that will be really useful.

**Comment by FLO-2DKaren** [comment]
I'm closing this because I used it on a new computer and it worked good.
