### ISSUE TITLE
SD Inlets Symbology

### ISSUE THREAD

**Issue by rpachaly** [FLO-2DSoftware/qgis-flo-2d-plugin#1103]
Create a symbology to the SD Inlets like the Storm Drain Nodes (User Layers). 

Maybe the intype field can be used to define different symbology for junctions and inlets

**Comment by FLO-2DJJ** [comment]
This is a possibility:

intype= 0 for junctions
intype= 1,2,3 curb inlets and grates
intype =4 Non Typical inlets
intype =5 Manhole inlets

And maybe in combination with 

sd_type = 'I'    --- Inlet
sd_type = 'O'   ---Outfall

**Comment by FLO-2DKaren** [comment]
Let's not do this.  We have more important tasks.
