### ISSUE TITLE
FLO-2D Info button

### ISSUE THREAD

**Issue by FLO-2DKaren** [FLO-2DSoftware/qgis-flo-2d-plugin#1104]
This button doesn't work if you don't have an rpt loaded.  That is incorrect because the info button is used by other layers.

**Comment by FLO-2DJJ** [comment]
@FLO-2DKaren
The Grid Info Tool is a toggle. It is either on or off. This operation allows you to exit from it.

**Comment by FLO-2DJJ** [comment]
I see you point @FLO-2DKaren. I'll look at the logic of it. Curiously, it also seems to be active even without a project.

**Comment by FLO-2DKaren** [comment]
This is no longer broken and I'm going to close this.  It's broken in plugin 0.115 but it is fixed in 1.0
