### ISSUE TITLE
Raster Calculator Bug

### ISSUE THREAD

**Issue by FLO-2DKaren** [FLO-2DSoftware/qgis-flo-2d-plugin#1107]
All the plugin raster calculators are probably broken once the raster layers are saved into the geopackage.

Elevation says probing done but does nothing.
RainARF says Cannot process check layer.
I didn't test scs or n value raster calculators.

**Comment by FLO-2DKaren** [comment]
Rain error shows this
              File "C:\Users/Alejandro Riano/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\flo2d\gui\rain_editor_widget.py", line 533, in raster_rain
              res = dlg.probe_rain()
              File "C:\Users/Alejandro Riano/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\flo2d\gui\dlg_sampling_rain.py", line 187, in probe_rain
              if max_val > 0:
             TypeError: '>' not supported between instances of 'NoneType' and 'int'

**Comment by FLO-2DKaren** [comment]
Hi Robson, 

I think the easy thing to do on this is to set the path of the _interp raster to the path of the geopackage and then delete it afterward.

**Comment by rpachaly** [comment]
I'm looking into this right now.

**Comment by rpachaly** [comment]
@FLO-2DKaren For the case of the elevation, where we create an interpolated raster. Do we need this interp file?

**Comment by rpachaly** [comment]
Actually, both errors are the same

**Comment by rpachaly** [comment]
These are the functions that use the gdalwarp function that cause the errors

- [x] probe_elevation
- [ ] probe_rain
- [ ] probe_roughness
- [ ] scs_infiltration_raster

**Comment by FLO-2DKaren** [comment]
Tested and complete

**Comment by FLO-2DKaren** [comment]
Test for topo.dat before and after.

**Comment by FLO-2DKaren** [comment]
I did a file compare on the two topo.dat files and no differences were detected between one with the original elevation.tif and on with the geopackage elevation.tif.
