### ISSUE TITLE
Info Tool signal connects wrongly several times with slot 'get_feature_info'

### ISSUE THREAD

**Issue by FLO-2DJJ** [FLO-2DSoftware/qgis-flo-2d-plugin#1116]
FLO-2D Info Tool connection with slot 'get_feature_info' is called more than once when a new project is created.

![image](https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/assets/20424575/b6dfa69c-570d-4e22-9b73-83dd8212e6df)

This happens just after the creation of a new project and before saving the project and running QGIS again.
The signal is emitted 3 times:

- at the creation of the project.
- after importing .DAT files.
- when converting Schematic layers to User layers.

The 3 connections imply that the Storm Drain plots are drawn 3 times.

(NOTE: Once the project is saved and loaded again in a new session the problem disappears)

**Comment by FLO-2DJJ** [comment]
The problem has been fixed by adding a variable that checks if the connection has already been done:

        if not self.infoToolCalled: 
            self.info_tool.feature_picked.connect(self.get_feature_info)
            self.infoToolCalled = True

(The fix will be included soon in a merge to the remote master)

**Comment by FLO-2DKaren** [comment]
I think this is all working now.  I tested it by using it on several diff projects.
