### ISSUE TITLE
Structure Message

### ISSUE THREAD

**Issue by FLO-2DKaren** [FLO-2DSoftware/qgis-flo-2d-plugin#1117]
When the structure schematize button is used, no message shows that the work was done.  Can we get a blue ribbon message that states the method is complete.  

No Hurry.

![image](https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/assets/20424460/ef34e63a-f4d1-4c52-8b0f-b440b54ce37d)

**Comment by FLO-2DJJ** [comment]
Ready. This issue can be reviewed. GitHub master repo is updated with this fix.

**Comment by FLO-2DKaren** [comment]
Reviewed and approved.
