### ISSUE TITLE
Import outflow.dat

### ISSUE THREAD

**Issue by rpachaly** [FLO-2DSoftware/qgis-flo-2d-plugin#1119]

**Comment by rpachaly** [comment]
Hi @FLO-2DKaren 

Quick question here: 

![Image](https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/assets/39889306/06019c0e-2145-4e08-ba5b-40a32cf22c98)

9. Channel Depth-Discharge Power Regression (Q(h) params)
and 
10. Channel Depth-Discharge (Q(h) parameters)

Are the same, rigth? I'll get rid of number 10 (which is greyed out on the current plugin version)

**Comment by FLO-2DKaren** [comment]
Let me check the data input manual.

**Comment by FLO-2DKaren** [comment]
OK I think these are different things.  
The Power Regression looks like this:
K 374                  Line 1: OUTCHAR = ‘K’ KOUT
H 10.0 2.6 0.35   Line 2: OUTCHAR = ‘H’ HOUT(J,1) HOUT(J,2) HOUT(J,3)

The Depth Discharge looks like this:
K 1007             Line 1: OUTCHAR = ‘K’ KOUT
T 0.0 0.00        Line 3: OUTCHAR = ‘T’ CHDEPTH(J) CQTABLE(J) J=1
T 3.0 50.35      Line 3: OUTCHAR = ‘T’ CHDEPTH(J) CQTABLE(J) J=2
T 5.0 157.67    Line 3: OUTCHAR = ‘T’ CHDEPTH(J) CQTABLE(J) J=3

**Comment by FLO-2DKaren** [comment]
I think these work like a diversion.

**Comment by rpachaly** [comment]
Still not sure. There are three Depth Discharge: two from the QH Parameters (9 & 10) and another from the QH Table (11). Exporting from 9, we got the 'H' line identifier and exporting from the 11 we got the 'T' line identifier. I couldn't make it to export from the 10, but the code where we export the outflow is the following:

```
k_line = "K  {0}\n"
qh_params_line = "H  {0}  {1}  {2}\n"
qh_table_line = "T  {0}  {1}\n"
n_line = "N     {0}  {1}\n"
ts_line = "S  {0}  {1}\n"
o_line = "{0}  {1}\n"
```

That's why I think that 9 and 10 are the same. At least on the export structure. Maybe when we don't have the exponent (third column) it is 10 and when we have a value is 9?

**Comment by rpachaly** [comment]
Adding Jim's email here for documentation

Ignoring the outflow elements (character 'K' for channel flow; character ID 'O' for floodplain, there are several ways to assign the outflow control:

1.  Specify a stage - discharge relationship Q = a h^b where HOUT(j,1) = max depth for the relationship, HOUT(j,2) = a, HOUT(j,3) = b and j is the channel element K.  So you can have one relationship per channel outflow node.  The depth h is the independent variable.
K = 15495
H   -line ID    HOUT(j,1)   HOUT(j,2)    HOUT(j,3)
H    10.4         20.0            2.54            0.456

2.  Assign a depth - discharge table.   
K = channel element = 15493    
T-line    Depth (CHDEPTH)     Discharge (CQTABLE)
   T                   0.                                0.0  
   T                   1.2                               3.4
   T                   2.3                               14.2
etc.

3.  Assign a time stage relationship:
K = channel element = 15495
N   NOSTA     NOSTACFP  (0 or 1 for floodplain or channel respectively)  If NOSTA is negative - it is an inflow the system not just a stage control...in other word the water will flow upstream from the outflow node to the next upstream element
N      15495              1
S    STA_TIME         STA_STAGE
S          0. (hr)               1956.0  (water surface elevation)
S          0.5                   1956.2                                      
S          1.0                   1957.3 
S          1.25                  1958.9    
etc.

If you assign a control at the outflow node at the boundary, this will force either a discharge off the grid system or a stage at the boundary depending on depth or time.  If a stage is required it will either create backwater or allow flow into the grid system (e.g. downstream main river channel at tributary confluence).

**Comment by FLO-2DKaren** [comment]
I tried this with just a simple K line and it didn't complete the process.  I think something is broken.



https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/assets/20424460/cab05eb5-ca51-4a72-afe1-1ff78fc1d536


Project for testing:
[Storm Drain Test_v1.0.0.gpkg.zip](https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/files/14230187/Storm.Drain.Test_v1.0.0.gpkg.zip)

**Comment by rpachaly** [comment]
Hi Karen, 

The grid number on the OUTFLOW.DAT is 8634 and on the Grid Info Tool is 8643. I think that the grid number that you are trying to update is the 156 (channel outflow, left bank). I tested here and the BC editor is updating correctly the grid number that is on the OUTFLOW.DAT. Can you double check?

However, I agree that the Outflow name is missing the grid number. Fixed on https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/commit/6db782882ec42c4302ba3488a63f40c5c712f260

**Comment by FLO-2DKaren** [comment]
OOOOh yeah, I was pointing to the 156 area but I actually meant to point to the 8643 area.  Sorry about that.  

So I'll assume you are getting a "Feature" in both outflow vector layers.  I wasn't getting the feature in my layers.  
That was like the 3rd attempt at explaining it on a video and I still messed it up!!!!  haha.
