### ISSUE TITLE
Outflow boundary whole grid option

### ISSUE THREAD

**Issue by rpachaly** [FLO-2DSoftware/qgis-flo-2d-plugin#1120]

**Comment by rpachaly** [comment]
@FLO-2DKaren Hi Karen, take a look on how I've set up the outflow whole boundary cells:

1. Here is the button
![Image](https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/assets/39889306/34e8f86a-fdee-4fae-a0f4-7dcec32a1c3b)

2. A warning message shows up (I didn't like the message because I'm not very creative today hahaha)

![Image](https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/assets/39889306/f9aadb46-980c-441b-95e1-78e41359d624)

3.  It creates a line in the middle of the grid cells at the boundary (Boundary Condition Lines)

![Image](https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/assets/39889306/bac24ad2-3153-4fb9-90ba-c77dde622139)

4. Update the Boundary Conditions Editor (I still need to work on the hydrograph and time series, don't worry about that)

![Image](https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/assets/39889306/45e70505-8a3e-4ce7-bbb0-b4f71bbd86e4)

5. Hit Schematize button

![Image](https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/assets/39889306/0894a3d6-c334-4a82-9f1b-97808b15f800)

The whole process is really fast, less than 3 seconds.

**Comment by FLO-2DKaren** [comment]
I’m going to help with the message.

**Comment by rpachaly** [comment]
Just ran on the Wall Large Data Test. It took around 1 minute the whole process - create the lines and schematize.

**Comment by FLO-2DKaren** [comment]
This boundary method applies a normal depth boundary to every grid element on the outer edge of the computational domain.   Please review the grid element elevation modification that happens when this method applied.

**Comment by FLO-2DKaren** [comment]
Then we’ll add that info to the user manual.

**Comment by rpachaly** [comment]
Ok, I modified the message. Thanks.

**Comment by rpachaly** [comment]
@FLO-2DKaren I'm going to push the branch that I'm working on the BC Editor because there are a lot of stuff there. But don't test it yet. I'm still working on it.

**Comment by FLO-2DKaren** [comment]
We can work on that message some more.  Feel free to simplify it.

**Comment by FLO-2DKaren** [comment]
I think we should only allow normal depth to be allowed with this approach and let other conditions overwrite local alternate conditions.  We do want to eliminate the whole boundary just replace local conditions.

**Comment by FLO-2DKaren** [comment]
I’m not testing anything today

**Comment by FLO-2DKaren** [comment]
I think this one will work fine but I believe you will need to move the line where it merges with other boundary features.  I think you could just reposition the line outside of the grid where it shares elements with other  boundaries.

**Comment by FLO-2DKaren** [comment]
Karen needs to add this to the boundary editor documentation.

![Image](https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/assets/20424460/db3865cd-32fa-429c-b427-2d00bc37e38c)
