### ISSUE TITLE
Toolbar QGIS and FLO-2D

### ISSUE THREAD

**Issue by rpachaly** [FLO-2DSoftware/qgis-flo-2d-plugin#1130]
**FLO-2D Toolbar**

- [x] FLO-2D Toolbar

**FLO-2D Project**

- [x] New FLO-2D Project
- [x] Open FLO-2D Project
- [x] FLO-2D GeoPackage Management

**FLO-2D Import/Export**

- [x] Import data (*.DAT) files
- [x] Import selected component files
- [x] Export data (*.DAT) files
- [x] Import from HDF5
- [x] Export to HDF5
- [x] Import HEC-RAS Channel

**Run FLO-2D Pro**

- [x] FLO-2D Plugin Settings
- [x] Quick Run FLO-2D Pro
- [x] Run FLO-2D
- [x] Run Tailings Dam Tool
- [x] Run Profiles
- [x] Run Hydrog
- [x] Run MaxPlot
- [x] Run MapCrafter
- [x] Run Rasterizor

**FLO-2D Parameters**

- [x] Set Control Parameters (CONT.DAT)
- [x] Mud and Sediment Transport (SED.DAT)
- [x] Convert Schematic Layers to User Layers
- [ ] Evaporation Editor
- [x] Levee Elevation Tool

**FLO-2D Info Tool**

- [x] Info Tool
- [x] Select .RPT File
- [x] Grid Info Tool

**FLO-2D Project Review**

- [x] HAZUS
- [x] Channel Profile
- [x] Debug Tool

**FLO-2D Help**

- [x] Help

**Comment by rpachaly** [comment]
@FLO-2DKaren What do you think about using this layout on the FLO-2D toolbar documentation because of the new buttons?

![Image](https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/assets/39889306/e8dda660-f049-45fc-8e11-cb9f19ac9a54)

**Comment by FLO-2DKaren** [comment]
OK this is approved.

**Comment by rpachaly** [comment]
Quick question: Is the Evaporation Editor working? If so, is there any documentation on it?

**Comment by FLO-2DKaren** [comment]
I don’t think it’s working.

**Comment by rpachaly** [comment]
That's a good idea. But since it is an editor, shouldn't it be located along with the widgets?

**Comment by FLO-2DKaren** [comment]
Since noone uses it, let's not fix it right away.  We can move it later.

**Comment by FLO-2DKaren** [comment]
I'm closing this since these tasks are complete.  I'm still reviewing but I'll add my review to new issues.
