### ISSUE TITLE
Widgets

### ISSUE THREAD

**Issue by rpachaly** [FLO-2DSoftware/qgis-flo-2d-plugin#1131]
- [X] Pre-Processing Tools  
<br>

- [x] Create Grid
- [x] Sampling grid elevation from raster layer
- [x] Sampling grid elevation from point or raster GDAL grid method
- [x] Sample elevation from point or LiDAR 
- [x] Correct grid elevation
- [x] Sampling roughness
- [x] Sampling grid roughness from raster
- [x] Calculate reduction factors (ARF and WRF)
- [x] Sampling spatial tolerance values
- [x] Sampling limiting Froude numbers
- [x] Sampling spatial shallow-n values
- [x] Sampling gutters
- [x] Sample no-exchange channel cells
- [x] Assign water elevations/flow depths to grid from points layer
- [ ] Sampling tailings
<br>

- [x] Profile Tool
<br>

- [x] Cross Sections Editor
<br>

- [x] Boundary Condition Editor
<br>

- [x] Initial Condition Editor
<br>

- [x] Rain Editor
<br>

- [x] Schematized Channel Editor
<br>

- [x] Structures Editor
<br>

- [x] Street Editor
<br>

- [x] Floodplain Cross Section Editor
<br>

- [x] Infiltration Editor
<br>

- [ ] Storm Drain Editor
<br>

- [x] Levees Breach Editor
<br>

- [x] Multiple Channels Editor
<br>

**Comment by FLO-2DKaren** [comment]
Closing this one too.  I'll add the incomplete widgets to a new issue.  Looks like it is Storm Drain Editor and Sampling Tailings.
