### ISSUE TITLE
Website 115 and 1.0

### ISSUE THREAD

**Issue by FLO-2DKaren** [FLO-2DSoftware/qgis-flo-2d-plugin#1134]
We need to fix the website redirect for 115 and 1.0

**Comment by FLO-2DKaren** [comment]
115 Repository https://flo-2dsoftware.github.io/qgis-flo-2d-plugin/

1.0 github pages build new page connect it.

**Comment by FLO-2DKaren** [comment]
@rpachaly 
Hi Robson,

We have a couple of options.  

The GitHub Pages uses the name of the repository to build the documentation webpage.  We can rename the repository of v1.0.

Or we can try to use Versioning in our Documentation.

/docs
  /v0.115
    index.html
  /v1.0
    index.html


If we don't want to use GitHub Pages, we can use a subdomain of the FLO-2D website.  That's how I set up the Tutorials.

I think anyway that we do this will be a little challenging.  Let's discuss it on Tuesday.

I'm having 2 subdomains created for FLO-2D website so they should be ready by next week.

**Comment by rpachaly** [comment]
Hi Karen,

I like both ideas. Is it okay to have multiple subdomains for the FLO-2D website? Thinking on future developments, we will have multiple versions and potentially multiple documentations pages - like the QGIS documentation.

**Comment by FLO-2DKaren** [comment]
Rebuild the documentation.flo-2d.com to fit all documentation.

**Comment by rpachaly** [comment]
@FLO-2DKaren Hi Karen, did you figure out the new documentation repo?

**Comment by FLO-2DKaren** [comment]
I'm getting closer.  I am testing it today.

**Comment by rpachaly** [comment]
@FLO-2DKaren 

Is this what you want?

![Image](https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/assets/39889306/937c843b-2db1-48f6-8483-d3c511685cf4)

**Comment by FLO-2DKaren** [comment]
That's much closer to what we want.  What happens to the sidebar when you click on another tool or Tutorials?

**Comment by rpachaly** [comment]
I pushed a branch on the repo. Take a look. 

The only one that is working almost perfectly is the Plugin 1.0.0

**Comment by FLO-2DKaren** [comment]
I'm going to close this issue since I think we have the idea well developed.  Now we need to decide when and how to publish the new branch.
