### ISSUE TITLE
Boundary Time Series Editor Bug

### ISSUE THREAD

**Issue by FLO-2DKaren** [FLO-2DSoftware/qgis-flo-2d-plugin#1137]
This bug seems to reset the Time Series Data and prevents the Time Series from being renamed.

https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/assets/20424460/2fc65166-2f00-48d4-b63b-12d00d402f47

**Comment by FLO-2DKaren** [comment]
Another bug but related to this issue.
Uploading Boundary Editor Time Series Bug 2.mp4…

**Comment by FLO-2DKaren** [comment]
The Delete button doesn't work either on the Time Series Editor.

**Comment by FLO-2DKaren** [comment]
Another related bug in this issue.


https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/assets/20424460/722e9f76-ce9a-4786-b402-b5fc917d8901

**Comment by FLO-2DKaren** [comment]
This project was not new.  Maybe that is why I had some issues.

**Comment by rpachaly** [comment]
Good bug catching Karen!

I think I know where the problems are. As soon as I finish the documentation I'll be working on these bugs.

**Comment by rpachaly** [comment]
Ok, this is fixed. The bugs in both videos.

**Comment by FLO-2DKaren** [comment]
OK I agree that this is working correctly.   All tables seem OK and are updating when you change the inflow or outflow feature.  I have even tried to create features and tables in odd sequences so I think this is OK.

I'm very excited how well this is working.
