### ISSUE TITLE
Storm Drain Control

### ISSUE THREAD

**Issue by FLO-2DKaren** [FLO-2DSoftware/qgis-flo-2d-plugin#1141]
Connect the new geopackage table for the control and report groups to the editor so they can be imported, exported and modified.

**Comment by FLO-2DKaren** [comment]
Robson added the swmm.inp control data table to the geopackage.  But we still need to connect it to the system.

- [ ] Import inp into the table
- [ ] Remember the data that the end user sets when they do the first export.
- [ ] Add a way to edit those variables without having to export the inp file.  It will just be a button that opens that window.

The idea behind this issue is to connect that so that we can import data into it and so that it remembers the data 
that the user adds to the window so it isn't reset each time.

Finally, get with Noemi to see which of those items are default or limited use so we can grey them out.

https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/assets/20424460/2b0844d4-bac1-4458-b6d1-175f1c0cf26f

**Comment by rpachaly** [comment]
> We need to figure out the best way to synchronize data and time (INP) with
> SIMUL (CON.DAT) and external BC (INP). In previous versions of the plugin,
> we grayed date and time out in the INP. The plugin calculated end date and
> time internally  as the current date and zero time (START date and time)  +
> simul time. This was exported to the SWMM.INP in the fields for start date
> and time and end date and time.
> 
> Issues with this hardwired synchronization, the BC tables for external flow
> also use date and time, and they need to be synchronized to the date and
> time from the INP to correctly impose them during runtime. I spent a lot of
> time reviewing this for previous plugins, and analyzing the potential
> different scenarios, and at that time we decided the best option was to use
> SIMUL from CON.DAT file, use current date and zero time (START date and
> time in INP), and calculate end date and time using SIMUL, the user needs
> to adjust BC to match the date and time. We can use a different approach if
> you want but just be aware of the ramifications of this issue.

Noemi's comment.

**Comment by rpachaly** [comment]
Hi @FLO-2DNoemi, which of these swmm control variables must be shown to the user?

![image](https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/assets/39889306/60972bc6-bfe0-4c48-8e9c-d198d6ed26de)

I mean, the FLOW_UNITS can be retrieved from the project and it does not need to be shown in this dialog. The FLOW_ROUTING and the INERTIAL_DAMPING also does not need to be shown here, even if the imported INP file has different values for these options. What are your thoughts on the other options? 

My idea is to reduce the amount of information here so the user does not mess up with the SWMM options. Maybe a check box to advanced options to allow more experienced users to have access to more options information.

**Comment by FLO-2DKaren** [comment]
@FLO-2DNoemi 

Hi Noemi,

I asked Robson to connect this to an openable table that can be edited at any time.  Not just when the storm drain is exported.

I know that some of these variables are not used because they are hardwired.  Can you meet with Robson and discuss this so he can set up this editor.

Robson,  I hope to add this editor to a button on the Storm Drain widget next to the Assign nodes button.

**Comment by rpachaly** [comment]
I'm working on it. 

https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/assets/39889306/7c26e379-3760-41ec-80f8-55fb7732af24

**Comment by rpachaly** [comment]
@FLO-2DNoemi @FLO-2DKaren I've finished a first version of this. Check this video:

https://flo-2d.sharefile.com/d-s1bbad02e21594e5fa6cfb5adc880f86b

I pushed the [branch ](https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/tree/sd-control) if you want to test it, but I still need to finish two things:

- [ ] Quick run
- [ ] Button tooltip

Let know your thoughts and how we can improve it even more.

**Comment by FLO-2DNoemi** [comment]
Robson,

I like the idea of hiding the advanced data fields. Some comments for
hardwired and default data:


   - *Report time* should be defaulted to the *Output Interval from CON.DAT
   *file but this field should be editable.  FLO-2D SD model allows
   different report timesteps for the surface  and for the SD.
   - FLO-2D storm drain model uses the* water surface slope and Froude
   number (BOTH) to calculate *when supercritical flow occurs in a conduit.*
   Option BOTH is hardwired*.
   - *SKIP_STEADY_STATE default* should be *NO*.


N

**Comment by FLO-2DKaren** [comment]
@FLO-2DNoemi 
Do you want Normal_Flow_Limited to be moved to the Hardwired group?

**Comment by FLO-2DKaren** [comment]
OK good.  I thought that was the case.

I also think you were giving info about Report time being synced to TOUT.  That isn't and instruction.  Just info right?

**Comment by FLO-2DNoemi** [comment]
The default value of Report Time should be TOUT, but report values for SD
and TOUT for surface results can be different so modifying Report Time
should be an option.

**Comment by FLO-2DNoemi** [comment]
Robson,

The data file for UEFCC project includes interior vertices,  download the
files and take a look:

https://flo-2d.sharefile.com/d-sccf56e06466f4868a6a5f4a37a84adb4

N

**Comment by rpachaly** [comment]
@FLO-2DKaren The SWMM.RPT results are not matching on my testing. I'll probably have this done by Thursday.

**Comment by FLO-2DKaren** [comment]
I'm going to start testing with an import export test.  It shouldn't interfere with your testing.

[Blank self help for storm drain testing.zip](https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/files/15469540/Blank.self.help.for.storm.drain.testing.zip)

**Comment by FLO-2DKaren** [comment]
tested and approved
