### ISSUE TITLE
Qh Table

### ISSUE THREAD

**Issue by rpachaly** [FLO-2DSoftware/qgis-flo-2d-plugin#1142]
The Qh table is not being called for the BC 10.

**Comment by rpachaly** [comment]
Fixed the BC being called. Error on setting the parameters on the FLO-2D Table Editor

**Comment by rpachaly** [comment]
This is fixed. 

I believe that the Q(h) parameters should be defined on the widget, not on the Table Editor. But let's discuss this in the future.

**Comment by FLO-2DKaren** [comment]
This seems to be working.
