### ISSUE TITLE
Plot/Table name linked to widget

### ISSUE THREAD

**Issue by rpachaly** [FLO-2DSoftware/qgis-flo-2d-plugin#1143]
The PLOT and TABLE do not have a link or information indicating the type of widget data they are displaying. For example, when I opened a project to use the BC Editor, I saw that the data in the table and plot are linked to the Cross Section Editor.

![Image](https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/assets/39889306/cac21f29-a8ae-4554-8a18-0e37b3b64f64)

Adding the widget name after the FLO-2D Plot and FLO-2D Table Editor could be a solution. 

![Image](https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/assets/39889306/9e6932d0-becc-4f08-a7b4-afe0dab8a233)

**Comment by FLO-2DKaren** [comment]
Oh yeah that's true.  We used to have legends on the plots too.  This is a good idea.

**Comment by jjrod200** [comment]
The legends are usually created using code similar to this example:

                self.plot.clear()
                self.plot.plot.legend = None
                self.plot.plot.addLegend()
                self.plot.add_item("Total Inflow", [timeRPT, inflowRPT], col=QColor(Qt.darkGreen), sty=Qt.SolidLine)
                self.plot.add_item("Flooding", [timeRPT, floodingRPT], col=QColor(Qt.red), sty=Qt.SolidLine)
                
In the above example timeRPT and inflowRPT are lists like [0.1, 0.3, 0.5, etc...] and [0.0, 0.004, 0.007, ...]

Hope that helps.
