### ISSUE TITLE
Boundary Editor Squished Windows

### ISSUE THREAD

**Issue by FLO-2DKaren** [FLO-2DSoftware/qgis-flo-2d-plugin#1149]
I just noticed this when I opened a project and the Widget Area was narrower than normal.

![Image](https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/assets/20424460/51fa8705-e89c-4673-bb91-78fcbc208d9b)

**Comment by rpachaly** [comment]
I fixed this bug and this is important for future implementations. In order to keep the button normal we need to set its size constrains to minimum width on Qt Creator. 

![Image](https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/assets/39889306/56f4ece1-4553-4352-bcff-d2755395663f)

**Comment by FLO-2DKaren** [comment]
OK this is acceptable.
