### ISSUE TITLE
Polygon add boundary not updating widget

### ISSUE THREAD

**Issue by FLO-2DKaren** [FLO-2DSoftware/qgis-flo-2d-plugin#1151]
I create a polygon boundary and it is not loaded into the widget after it's created.  I have to select it to finish the data and change the name.

https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/assets/20424460/61e1e9d4-142e-4875-81b2-ebe0befac0b9

**Comment by rpachaly** [comment]
To fix this bug I had to sort the inflows/outflows by fid (order that they were created) and not alphabetical, which I think is better.

**Comment by FLO-2DKaren** [comment]
OK this is working now.
