### ISSUE TITLE
Too Many Time Stage Lines

### ISSUE THREAD

**Issue by FLO-2DKaren** [FLO-2DSoftware/qgis-flo-2d-plugin#1153]
I think the schematize is writing a time stage channel line for all of the O lines.  We only want it for the K line.

!!!Ooops.  The K line and N line should be assigned to 156 not 51!!!  I think I said in the video 51. 

https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/assets/20424460/f68bf569-00d8-4fda-8a76-eade30f9e1ad

**Comment by rpachaly** [comment]
I was not able to reproduce this one on the latest version of the new-bc branch. Everything is working as expected, maybe it was solved in another bug fix.

**Comment by FLO-2DKaren** [comment]
This is working as expected.
