### ISSUE TITLE
District Task 3 QGIS Plugin

### ISSUE THREAD

**Issue by FLO-2DKaren** [FLO-2DSoftware/qgis-flo-2d-plugin#1155]
The SUB-CONSULTANT will expand the functionality of the QGIS FLO-2D Plugin as follows:
1.	Storm Drain Enhancements
a.	Add storage unit code to the FLO-2D Plugin so that storage units can be applied, imported, and exported correctly.  #1048 
b.	Add dropbox code to the FLO-2D Plugin so that dropboxes can be applied, imported, and exported correctly.  #1029 
2.	Update the user and technical documentation for the QGIS FLO-2D Plugin based on items in this scope of work.

**Comment by FLO-2DJJ** [comment]
@FLO-2DKaren 
Task 1. (Storm Drain Enhancements) is finished with issues #1048 and #1029, which have already being merged.
You can close this issue when Task 2. (Update the user and technical documentation) is completed.
