### ISSUE TITLE
Grid Info Tool Placement

### ISSUE THREAD

**Issue by FLO-2DKaren** [FLO-2DSoftware/qgis-flo-2d-plugin#1162]
Let's put the Grid Info tool back on the toolbar.  That tool is too important to be hidden in that drop down menu.  
The Toggle on/off nature of the button limits its use in that menu.

**Comment by rpachaly** [comment]
I added it back to the toolbar and fixed some minor bugs. It is on https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/pull/1163

**Comment by FLO-2DKaren** [comment]
This seems to be working good.
