### ISSUE TITLE
Plotting Channel Profile

### ISSUE THREAD

**Issue by rpachaly** [FLO-2DSoftware/qgis-flo-2d-plugin#1165]
Add more data for plotting channel profile.

**Comment by rpachaly** [comment]
Current state of development

Parsed the HYCHAN.DAT and added the maximums to the graph. 

1. No HYCHAN loaded

https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/assets/39889306/fde061f3-6611-4fd2-a96b-8027fc87a655

2. HYCHAN loaded

https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/assets/39889306/1eab2179-f357-4742-ad6a-d7db8f7de0a3

Still working on:

1. Removing those weird 'eyes' on the legend
2. Autoloading data from the export folder

Issues or potential improvements:

Velocity, Froude, and other variables have different scales. At this point, I'm auto ranging the axis and not showing the unit on the legend. I tried tot add a secondary axis but it was too complicated. Any thoughts?

**Comment by FLO-2DKaren** [comment]
Looks good.  And I do have ideas.
1. Can you treat the legend like a docked widget?  That way you would always have the units right there when you want to take a screenshot.  If that's not easy let's think about something else.
2. Can you put the auto-update scale code in a place so that it is applied across the whole plotting system.  I have to update every swmm plot myself.
3. Where does the code go?  This is going to be an important tool and I think you want to make sure that the code is well organized and documented.  I think that this is a tool that breaks between versions of python and QT.  When you build the code, use the """ """ documenting method so future people can quickly fix things.
4. The button that links to the swmm.rpt path is not ideal.  Can you eliminate that button?  The info tool button works better when its not in a drop down.

**Comment by rpachaly** [comment]
I was wondering here. Why don't we combine the channel profile tool with the info tool? The grid info tool makes sense to be separated, but the channel profile should be inside the info tool.

**Comment by rpachaly** [comment]
- Added a code to filter out data that is not currently implemented when using the Info Tool and the Results Tool
- Refactored the toolbar buttons (Grid Info, Info, and Results)
![image](https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/assets/39889306/1e9b4ced-807b-41f8-9ae2-17ba77307197)
- Removed the load .rpt file and import HYCHAN.OUT. Now it looks for the files inside the project export folder and parse the data on-the-fly (still need to check this for big projects when plotting the channel data but I think it is ok).
- Parsed the HYCHAN.OUT for each XS and added result plots for Cross-Sections (Time x Variable)
![image](https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/assets/39889306/19b45013-93ef-4b75-8a72-bd5f27b21788)
- Parsed and added result plots for HYDROSTRUCT (Time x Discharge)
![image](https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/assets/39889306/00822138-e9e4-4f4a-8b65-9293c9bf7c6b)
 
The plots are not updating the way that I want yet, I will need a couple of hours to fix the axis ranges. When I finish this I'll push the branch. 

Implementing matplotlib is doable but it will be very time-demanding. An easier solution would be to create a new dialog and add the plot there. Something like a Results Viewer. I'm still thinking about it.

**Comment by FLO-2DKaren** [comment]
Sounds like progress!!!

**Comment by rpachaly** [comment]
I still not figure out why the axis' ranges are not updating correctly when new data is added. It works pretty well for most cases, but when we check a data series and then select another plot it does not auto range correctly. See:

https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/assets/39889306/83cd10b0-04f1-40db-b837-0a5be40bd546

It is easy to fix by clicking and selecting the data series on the plot. I'm going to push the branch anyways because it is not a bug but something to be improved on the future. 

Pull Request https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/pull/1170/

**Comment by FLO-2DKaren** [comment]
Hi Robson,

I noticed that your axis didn't update until you checked the cross section.  Look for 2 things

1. Can you apply the axis update to the UI file?  Maybe its default isn't set.
2. You had to select the cross section at the end of the video.  When you clicked the plot, it wasn't selected in the checkbox so maybe your initial configuration of the check box should be **checked** when you switch to the cross section plot.

**Comment by rpachaly** [comment]
It was tricky to solve this bug, but I found a signal that allowed me to update the axis right before creating the plot. It is working now, see:

https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/assets/39889306/a6ba67eb-f1be-4e99-8193-a494e6f59d7a

I updated the pull request https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/pull/1170

**Comment by FLO-2DKaren** [comment]
This is great because it's really annoying to have to reset the axis after every new plot.  If you zoom in on anything, it locks the axis adjustment to manual.  I'm excited for this fix.

**Comment by FLO-2DKaren** [comment]
I have tested this on many different project.  I'll close it here because this particular issue is solved. We may see other related issues come up.
