### ISSUE TITLE
Make OutfallTidalCurveDialog class more general

### ISSUE THREAD

**Issue by FLO-2DJJ** [FLO-2DSoftware/qgis-flo-2d-plugin#1169]
The current **OutfallTidalCurveDialog** class is used for the Outfall functionality to define tidal curves for the outfall type 'TIDAL'. 
However the Storage Units also need to define 'Functional' or 'Tabular' curves. The tabular case requires a curve similar in structure to the tidal ones for outfalls.
So, make **OutfallTidalCurveDialog**  more general so that it can be used for both. Let's name it **CurveEditorDialog**

In the future the **CurveEditorDialog** could be used for the Pump curves (adding a Type).

Notice that SWMM uses this x,y curves for more objects: pumps, conduits of custom shape, storage units, flow dividers nodes, outfalls, and outlet links. Not all used by FLO-2D but could in the future.

**Comment by FLO-2DKaren** [comment]
@FLO-2DJJ 
Can I get a status on this?

**Comment by FLO-2DJJ** [comment]
@FLO-2DKaren,

This is already done. Closing it.
