### ISSUE TITLE
Export Type 6 Issue

### ISSUE THREAD

**Issue by FLO-2DKaren** [FLO-2DSoftware/qgis-flo-2d-plugin#1171]
There may be an issue with this type 6 export.  If it doesn't fail on your system, I'll restart and test it again.

https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/assets/20424460/d8c53aeb-a5aa-4493-a54f-d26f8efb49cf

**Comment by rpachaly** [comment]
Hi Karen, 

Here it is working

![image](https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/assets/39889306/ac2a54ad-fa3c-4f7a-8a99-5cfdb2e2e928)

Did you try to delete the schema data e rerun the schematize button?

**Comment by FLO-2DKaren** [comment]
I did lots of things so Let's close it and move on.  Thanks for testing it.
