### ISSUE TITLE
Channel Tools Brain Storming

### ISSUE THREAD

**Issue by FLO-2DKaren** [FLO-2DSoftware/qgis-flo-2d-plugin#1172]
Add interpolation code to the python.
Control update triggers better.

Error checks for channel width (need to define)
If the cross section is wider than the distance between two left and right bank elements, flag a too narrow error.
If the area on the bank elements is less than 5%, you get another too narrow flag.

![Image](https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/assets/20424460/85d8f572-abaa-4a38-99cd-f7ba4ed68289)

Error 
If a right bank is inside the two bank lines, there should be an error.

Error checks for boundary conditions (need to define)

Outflow last cross section must be lower than adjacent upstream neighbor by 0.1 ft.
Upstream inflow boundary must by positive slope in the downstream direction.  It cannot be flowing uphill.

**Comment by rpachaly** [comment]
@FLO-2DKaren 

Can you upload the project that contains the channel with errors?

**Comment by rpachaly** [comment]
Gpkg is better. I'm working on creating the checks on the plugin. So, the more errors the better.

**Comment by FLO-2DKaren** [comment]
OK it will take some time because I have a meeting but I can give it to you today.

**Comment by rpachaly** [comment]
Current state of the new Cross Sections editor

https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/assets/39889306/e47b0a3b-1e41-48bc-a413-5d5d3771f51a

**Comment by FLO-2DKaren** [comment]
Yes this is way better!!!!!  Haha the wasted years!!!!

Does the Check window lock the map?  If the map is locked, you lose your place in the dialog.  So we have to close the dialog to fix the problem instead of just moving to the next item.

When a channel is more complex than 2 segments, the confluence editor gets harder.  You don't want to always rebuild confluence.  Can you correct it so that the schematize doesn't erase the confluence data unless the confluence is no good.

**Comment by FLO-2DKaren** [comment]
If you can dock the channel check window on the bottom, it would be nice.  Like how python or profile tools docks.

**Comment by rpachaly** [comment]
> Does the Check window lock the map? If the map is locked, you lose your place in the dialog. So we have to close the dialog to fix the problem instead of just moving to the next item.

No, the check window does not lock the map. It took me some time figure out how to do this. You can fix the channel errors with the check window minimized. But if you close it, it will be cleared out. Maybe I need to change that to only clean when the button it hit again.  

> When a channel is more complex than 2 segments, the confluence editor gets harder. You don't want to always rebuild confluence. Can you correct it so that the schematize doesn't erase the confluence data unless the confluence is no good.

I thought it would break the confluences when clearing the schematized channels. I'll try to implement it.

**Comment by FLO-2DKaren** [comment]
It can be tricky with schematize channels and clearing or leaving confluence data because the confluence might need to change if the channel bank moves.  We should take care with it but overall, the tools are much better.  I believe it will be a good idea to try all three or 4 channel lessons with this new system.

- [ ] Lesson 2 HEC-RAS import
- [ ] Lesson 2 Advanced Natural, Trapezoidal, and Rectangular
- [ ] Coastal Channel
- [ ] Tailings Dam Channel 
- [ ] Lesson 2 really advanced where we add a cross section to a channel that is already finished.
- [ ] I have the bridge lesson that also has a confluence.

I will start to find these test projects so we can try them all out.

**Comment by FLO-2DKaren** [comment]
All tested and on new issues.
