### ISSUE TITLE
Test Project

### ISSUE THREAD

**Issue by FLO-2DKaren** [FLO-2DSoftware/qgis-flo-2d-plugin#1173]
Here is the test project.  This project has listings in the error.chk that need to be wider.  I usually move the left or right bank slightly apart.

Don't forget to click Schematize channel before you move any bank alignments.

[4.1. Channel and Hydraulic Structure.zip](https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/files/14301423/4.1.Channel.and.Hydraulic.Structure.zip)

**Comment by FLO-2DKaren** [comment]
Here is the elevation file for the channel.
I modified this raster with a plugin called Serval.  It's a really nice plugin.

[Channel and Hydraulic Structure Elevation.zip](https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/files/14301504/Channel.and.Hydraulic.Structure.Elevation.zip)

**Comment by FLO-2DKaren** [comment]
Complete channel no errors.


[Channel Finished and Working.zip](https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/files/14301757/Channel.Finished.and.Working.zip)

**Comment by FLO-2DJJ** [comment]
Thanks Karen, I got the attachments.

Juan Jose Rodriguez
FLO-2D Software
www.flo-2d.com
***@***.***

**Comment by FLO-2DKaren** [comment]
JJ,  This is for Robson.  He's updating the channel widget.  I owe you a different model.

**Comment by FLO-2DJJ** [comment]
Right, I replied this by mistake.

**Comment by FLO-2DKaren** [comment]
Use this project to start the test.


[4.1. Sample elev schematize and interpolate.zip](https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/files/14336065/4.1.Sample.elev.schematize.and.interpolate.zip)
