### ISSUE TITLE
Add a delete schematized channel btn

### ISSUE THREAD

**Issue by rpachaly** [FLO-2DSoftware/qgis-flo-2d-plugin#1174]
Keep the same process of deleting schema data when clicking on the schematize btn but add a separate btn for deleting schema data.

**Comment by FLO-2DKaren** [comment]
It would be nice to have a button that clears all schema data.
If you are using the table editor to enter cross section data, it can be overwritten by some triggers.  We should protect those tables better.

**Comment by rpachaly** [comment]
I already added the button. I like it, it is helping me a lot during my coding.

**Comment by FLO-2DKaren** [comment]
works good
