### ISSUE TITLE
Combine the channel buttons

### ISSUE THREAD

**Issue by rpachaly** [FLO-2DSoftware/qgis-flo-2d-plugin#1175]
Lets combine and simplify the channel buttons.

**Comment by FLO-2DKaren** [comment]
There are some buttons that aren't used.
Import right banks isn't used anymore.
Since you are changing the way we view results, the Import peaks isn't used anymore.
The n value calculator should be added to python code along with the interpolation.  I'll ask Jim for those files too.

**Comment by rpachaly** [comment]
Yes, I was going to ask you about these buttons. I removed the import right banks and the schematize right banks. I simplified the buttons to this so far:

![image](https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/assets/39889306/89e8604b-c203-46f6-9057-e4561bf99a6a)

I combined the schematize and interpolate into one button (schema). A message shows up asking if the user would like to interpolate or not the cross sections. I still not tested this thoroughly. What do you think? Is it a good idea?

**Comment by FLO-2DKaren** [comment]
New  buttons work good.  



![Image](https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/assets/20424460/04d265f0-64d8-4ea8-8ad4-618decc919c1)
