### ISSUE TITLE
IDEA: Channel bottom estimator

### ISSUE THREAD

**Issue by rpachaly** [FLO-2DSoftware/qgis-flo-2d-plugin#1178]
Add a button for estimating the channel bottom?

![Image](https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/assets/39889306/1cab37c5-4572-43b8-83db-bfa9318f6c48)

Orange line is the DEM and the dashed line is an estimation of channel bottom based on the bank slope. 

Is this a good feature?

**Comment by FLO-2DKaren** [comment]
This is a good idea but it has a flaw.  V channels cause instability so I would use a U channel.

**Comment by FLO-2DKaren** [comment]
We could add an open channel flow calculation to this and really get a good estimate.

**Comment by rpachaly** [comment]
I'm going to close this
