### ISSUE TITLE
SD Issues importing SWMM.INP

### ISSUE THREAD

**Issue by FLO-2DJJ** [FLO-2DSoftware/qgis-flo-2d-plugin#1180]
- [x] Storage Unit not finding its conduits.
- [x] SD nodes outside domain skipped.
- [x] No dates in times series must be allowed (in [TIMESERIES] group. Gives Warning 310323.0507).
- [x] Conduit has no inlet defined (referring to a storage unit).
- [x] Conduit has no outlet defined (referring to storage unit).
- [x] Warning 221220.0336: Points outside the domain.
- [x] Warning 221220.0337: Conduits outside the domain.
- [x] Check why loading SD components takes a long time (see North Mesa project).
- [x] Check why selecting items in SD components dialog also takes a long time (see North Mesa project).
- [x] Make conduits, pumps, orifices, and weirs lines with different color.
- [x] Review the final count of inlets, junctions, outfalls, etc. Maybe missing storage units.

**Comment by FLO-2DJJ** [comment]
Done. Review it in pull request #1179

**Comment by FLO-2DKaren** [comment]
I tested the import and I'm going to close this issue.  I also want to test some more complex storm drain models so we may find new issues later on.
