### ISSUE TITLE
Info Tool Mods FPXSEC

### ISSUE THREAD

**Issue by FLO-2DKaren** [FLO-2DSoftware/qgis-flo-2d-plugin#1181]
Hi Robson,  Maybe you a haven't gotten to it yet but the Info Tools don't see fpxsecs.  Probably because they are harder to identify.

The way you ID them is using the FID.  That is the order in which they are exported.  Let's get Noemi to add the name to the file when we move over to hdf5 data.

Here's some more info on my latest test.

https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/assets/20424460/9c43f3d3-cb43-4643-ab71-0bae95a0d57a

**Comment by FLO-2DKaren** [comment]
One more issue related to this new system.


https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/assets/20424460/e00d5f7a-8b73-4246-b565-8a5959d32fec

**Comment by rpachaly** [comment]
> Hi Robson, Maybe you a haven't gotten to it yet but the Info Tools don't see fpxsecs. Probably because they are harder to identify.
> 
> The way you ID them is using the FID. That is the order in which they are exported. Let's get Noemi to add the name to the file when we move over to hdf5 data.
> 

This was not previously implemented. I just coded and added to the branch. It should work without further issues.

**Comment by rpachaly** [comment]
Karen, can you upload the swmm.RPT, SWMMQIN.OUT, SWMMOUTFIN.OUT, swmm.OUT from these two models that you showed on the video? I'm trying to reproduce the error here

**Comment by rpachaly** [comment]
> One more issue related to this new system.

It was looking first for the RPT file on the settings and this could be the reason of this bug. I removed that and now it looks only for the RPT file on the export folder. I couldn't reproduce the bug, but it should be working fine. 

I also added the results for Storm Drain Conduits on the Results tool.

**Comment by FLO-2DKaren** [comment]
Nice!!!

**Comment by rpachaly** [comment]
https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/assets/39889306/7d230f97-c18a-4fe0-9d4c-aa746feef8dc

**Comment by FLO-2DKaren** [comment]
Super cool Robson.  We may need to add some features with respect to mudflow.  I know this because of recent tailings dam testing.

**Comment by FLO-2DKaren** [comment]
Hi Robson,  

Just an FYI.  If you have a non-FLO-2D layer covering a feature, you might get a python warning.  I noticed this before I turned off the external layers for conduits, and such.  They are external gpkg files for plugin 115.  May not be an issue for plugin 1.0 since we save those layers to our gpkg.

**Comment by rpachaly** [comment]
Hi Karen, 

I'll take a look into that.

**Comment by rpachaly** [comment]
Hi @FLO-2DNoemi,

Check the current state of the Results Tool on https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/issues/1181#issuecomment-1969175837. I really like that profile plot that SWMM has. I think it would be nice to add something like this.

![Image](https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/assets/39889306/422a26d8-1be3-4a54-974f-9bb628f1d445)

**Comment by rpachaly** [comment]
> Hi Robson,
> 
> Just an FYI. If you have a non-FLO-2D layer covering a feature, you might get a python warning. I noticed this before I turned off the external layers for conduits, and such. They are external gpkg files for plugin 115. May not be an issue for plugin 1.0 since we save those layers to our gpkg.

I did some tests here and this warning does not show up anymore. Now the code only shows the layers that can plot results and not all available layers.

**Comment by FLO-2DNoemi** [comment]
> One more issue related to this new system.
> 
>  swmm.rpt.or.swmminout.path.issue.mp4

These two results are coming from different output files, see the information below: 

The _total inflow_ results are retrieved from either **SWMM.RPT/SWMM.OUT**. I think  we are reading the results from SWMM.RPT, I think we should read them from SWMM.OUT instead, this is a binary file. 

The Discharge to FLO-2D are coming from SWMMQIN.OUT. This is the discharge that enters the inlet from the surface and does not include the water that is routed through the pipes from upstream.

**Comment by FLO-2DNoemi** [comment]
> Hi @FLO-2DNoemi,
> 
> Check the current state of the Results Tool on [#1181 (comment)](https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/issues/1181#issuecomment-1969175837). I really like that profile plot that SWMM has. I think it would be nice to add something like this.
> 
> ![Image](https://private-user-images.githubusercontent.com/39889306/309093935-422a26d8-1be3-4a54-974f-9bb628f1d445.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkzMDA0NjEsIm5iZiI6MTcwOTMwMDE2MSwicGF0aCI6Ii8zOTg4OTMwNi8zMDkwOTM5MzUtNDIyYTI2ZDgtMWJlMy00YTU0LTk3NGYtOWJiNjI4ZjFkNDQ1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzAxVDEzMzYwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNjYTcxYzg5OWY5MDI2ZTQ1ZjMyNjgyOGJiMGY4YWRiNTJjZjUzYWJmY2M1M2M5OTliODQ0M2MzNmY3NTViZDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.TeGXkwRPmnzATk_JIPSpRQGRN41Yzlc66wrx_9ZKPXw)

@rpachaly 

I checked the current state of the Results Tool,  it is very nice and helpful!

The SWMM profile plot works excellently and we have used it for years now. I think it would be nice to add the same capabilities to the QGIS plugin plus the option to visualize the WSE profile in the same plot. This will implies reading from MAXWSELEV.OUT the WSE in each grid containing an inlet or outfall for the selected pipeline and plot it.

**Comment by FLO-2DNoemi** [comment]
@rpachaly 

We also need to add the storm drain discharge plots to the plugin. I will send more information regarding this.

**Comment by rpachaly** [comment]
Ok! In the meanwhile, I'll add plots for weir and orifices.

**Comment by FLO-2DNoemi** [comment]
Perfect!

**Comment by FLO-2DKaren** [comment]
> Hi Karen,
> 
> I'll take a look into that.

Robson,  This is regarding the non-FLO-2D layers covering the FLO-2D layers.  The layers I'm referencing are the Geopackage layers that are in the Basin model test.

**Comment by FLO-2DKaren** [comment]
Guys i'm going to close this.  We know we want the storm drain plots but they can go on another issue.  This test is passing.  Everything works on my end.
