### ISSUE TITLE
Structure Dialog

### ISSUE THREAD

**Issue by FLO-2DKaren** [FLO-2DSoftware/qgis-flo-2d-plugin#1183]
This box is off for some reason.  The alignment if off.  

![image](https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/assets/20424460/b75772b1-9c28-4405-b407-62edd61df9f0)

**Comment by rpachaly** [comment]
Better?

![image](https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/assets/39889306/3a71d261-89cf-474b-bab4-8f460d4a084c)
