### ISSUE TITLE
Weir Dialog Error Message

### ISSUE THREAD

**Issue by FLO-2DKaren** [FLO-2DSoftware/qgis-flo-2d-plugin#1184]
JJ,  I found an error on plugin 115.  Can you check it and fix it on Plugin 1.0.0.

Open the Weir Dialog
![image](https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/assets/20424460/326e989d-994d-4a84-966a-f7e40023f2b6)

Click on a line and this message appears.
![image](https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/assets/20424460/29e6bc12-45d9-42fe-ae5c-715b646e3e3a)

Here is a test project.  Use Open GeoPackage from the FLO-2D toolbar to load it and it should port automatically.
[QGIS Lesson 1.zip](https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/files/14442811/QGIS.Lesson.1.zip)

**Comment by FLO-2DJJ** [comment]
Hi @FLO-2DKaren,
I tested the project you sent (QGIS Lesson 1.zip) and couldn't reproduce the error with the current master (plugin 1.0.0).
Am I missing something?

**Comment by FLO-2DKaren** [comment]
OK no problem.  I have been in and out of many different projects this week.  It is playing havoc on my tools.  I'll close this issue.  Thanks JJ
