### ISSUE TITLE
Error Save to 'Storm Drain weirs' User layer

### ISSUE THREAD

**Issue by rpachaly** [FLO-2DSoftware/qgis-flo-2d-plugin#1187]
![image](https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/assets/39889306/a5daf23f-a745-49e8-bbd0-78687c91b9f7)

![image](https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/assets/39889306/b35c56d9-bdb0-4703-ad91-aa44e1752a12)

**Comment by FLO-2DKaren** [comment]
There's also an error when you try to select the line.  I posted it in another post.

**Comment by rpachaly** [comment]
> There's also an error when you try to select the line. I posted it in another post.

#1184

**Comment by rpachaly** [comment]
I tested this on plugin v1.0 and it seems that it is already fixed.

**Comment by FLO-2DKaren** [comment]
Oh good!!!  I’ve loaded 6 different projects in 2 different Qgis and 2 different plugins. I know this is a bad practice. It might result in errors on my system that you don’t see. Thank you for checking them anyway.
