### ISSUE TITLE
Link storage units nodes to components in 'Auto-assign link nodes'  in Storm Drain Editor widget

### ISSUE THREAD

**Issue by FLO-2DJJ** [FLO-2DSoftware/qgis-flo-2d-plugin#1195]
When completing the links of conduits, pumps, orifices, and weirs from their inlet to outlet, the 'Auto-assign...' function fails when the inlet and/or outlet is a storage unit node.

- [ ] Auto-assign links to conduits.
- [ ] Auto-assign links to pumps.
- [ ] Auto-assign links to orifices.
- [ ] Auto-assign links to weirs.
- [x] Auto-assign all components in one go.
- [x] Remove drop-down list.
- [x] Move the messages to the FLO-2D log

**Comment by FLO-2DKaren** [comment]
@FLO-2DJJ We should link these together so you don't have to run them individually.  We should also move the messages to the FLO-2D log so we don't have to close messages for this button.

**Comment by FLO-2DJJ** [comment]
Right, there is no reason to link the components individually.

Juan Jose Rodriguez
FLO-2D Software
www.flo-2d.com
***@***.***

**Comment by FLO-2DJJ** [comment]
- [ ] Auto-assign all components in one go.
- [ ] Remove drop-down list.
