### ISSUE TITLE
Info Tool issue Storm Drain

### ISSUE THREAD

**Issue by FLO-2DKaren** [FLO-2DSoftware/qgis-flo-2d-plugin#1196]
The review tool is opening the storm drain widget.  I think that is wrong.  It doesn't load anything, just opens the widget.

I would rather open the ID panel and view the outfall variables than open the storm drain widget which is not good at loading the features.

**Comment by rpachaly** [comment]
Hi Karen, 

I was not able to replicate this one. For me it does not open anything.

**Comment by FLO-2DKaren** [comment]
OK my guess is that I was working on multiple different versions of the plugin.  I'll close this and assume that you already sorted this issue when you moved the info code to the other button.
