### ISSUE TITLE
Green Ampt OSM

### ISSUE THREAD

**Issue by FLO-2DKaren** [FLO-2DSoftware/qgis-flo-2d-plugin#1206]
@rpachaly 
Hi Robson,

The green ampt from OSM is resulting in a RTIMP greater than 1.  Can you see what's happening.  

https://flo-2d.sharefile.com/d-s0ffacf30b6684c3c8880df73fee8fdef

**Comment by FLO-2DKaren** [comment]
Robson,
I had to mod the data in that geopackage so the model would run so that data is correct.  You'll have to run the calculator again to get the data that is greater than 1.

**Comment by rpachaly** [comment]
Hi Karen, 

This is the current code for calculating RTIMP:

```
def calculate_rtimp_n(parts, globalRockOutCrop=0.2):
      # calculated natural occurring RTIMP without consideration of the effective impervious area
      rtimp_gen_n = [area * (float(rtimps)) for rtimps, area in parts]
      areaTotal = sum(area for rtimps, area in parts)
      if areaTotal < 1.0:
          rtimp_gen_n.append((1.0 - areaTotal) * globalRockOutCrop)
      rtimp_n = sum(rtimp_gen_n)
      return rtimp_n
```

The code multiplies the rtimp for the area and then sums all values. In my opinion, this is wrong and will lead to values greater than 1.

I changed the code to a more simple approach:

```
def calculate_rtimp_n(parts):
    # calculated natural occurring RTIMP without consideration of the effective impervious area
    areaTotal = sum(area for rtimps, area in parts)
    rtimp_gen_n = [(area / areaTotal) * (float(rtimps)) for rtimps, area in parts]
    rtimp_n = sum(rtimp_gen_n)
    return rtimp_n
```

I multiply the rtimp by the fraction of area that it represents (arithmetically area-weighted). I checked the Drainage Design Manual for Maricopa County and it says that "Calculate the arithmetically area-weighted value of naturally occurring rock
outcrop to obtain RTIMPN". 

The code is ready, let me know if this is correct. I've pushed the branch so you can test it.

**Comment by FLO-2DKaren** [comment]
Sweet we just need to make sure this doesn't mess up the district method.

**Comment by FLO-2DKaren** [comment]
Test approved

https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/assets/20424460/f64c519c-7fa0-437a-9350-02d39264f23f
