### ISSUE TITLE
Plot Update

### ISSUE THREAD

**Issue by FLO-2DKaren** [FLO-2DSoftware/qgis-flo-2d-plugin#1210]
Robson,
I don't think this is an issue.  I think I'm on a bad merge.  Let's get the code all on the same page and test this again.

https://www.youtube.com/watch?v=T-GyXsFokIA

3:50 min. Table not updating automatically.

**Comment by rpachaly** [comment]
The table was not automatically updating. Done on 32c5da9edf77c35eb8a3060c4de825874b60134d

I added the schematize message to the bar and added to the log messages. Done on 422abcc03f3ebb0bcf93f2f49d7c8571d5cd8071

![image](https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/assets/39889306/2ea1666d-7de0-4547-a153-b768a4cebf1f)
