### ISSUE TITLE
Zamora Test

### ISSUE THREAD

**Issue by FLO-2DKaren** [FLO-2DSoftware/qgis-flo-2d-plugin#1211]
Hi Robson,

Use this video for this item:
https://flo-2d.sharefile.com/d-s92506ea16bdd461580328828714d5dce

0.00 min.  Note that some of my plotting issues might be coming form a bad merge.

1:50 min. Note the one bad cross section.  This is a common error.

2:15 min. Note the profile in the manual.  I think we can sort this out by allowing another button to view that profile.  
I also think this is possibly already fixed in the final version.

3:28 min. Jim's interpolator reports a file called CHANNEL_XSECTION_GEOMETRY.OUT.  We might be able to do something like this that can flag bad cross sections.  For example, if the depth drops to near zero, that's a red flag.  

Here's Jim's data.
[Interpolation.zip](https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/files/14624969/Interpolation.zip)

7:04 min.  The way I checked checked this list was stupid.  I was trying to get to one side of the list and that was dumb.  I should have simply started fixing them from item 1.

We want to dock the review panel if possible.  It would dock in the Table area very well.

13:00 min. This bug happens often enough to warrant fixing.  I assume it's an easy fix.

15:06 min. I think this plot issue is simply a bad merge.  Let's get all the code on the same page. 

15:48 min. I set the inflow to the wrong side of the channel.  Ooops.  I fixed it later.

16:18 min. Can we move that message to the bar or FLO-2D log?

20:00 min. My fault skip to 22:10.

23:00 min. Error message.  Test on better merged code.   Test Project Below.

Test Project
https://flo-2d.sharefile.com/d-s5ff9df29f8bd4bfabf02bef44a19cb88

**Comment by rpachaly** [comment]
Karen, I can't download the test project. It says that contains a virus

![image](https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/assets/39889306/d2a96834-6e73-4c28-be2d-14c6d156ebf6)

**Comment by FLO-2DKaren** [comment]
It did that to me too.  I had to turn off windows defender.  I couldn't get it to leave that project alone.

**Comment by rpachaly** [comment]
Ok, I'll do the same

**Comment by rpachaly** [comment]
> 2:15 min. Note the profile in the manual. I think we can sort this out by allowing another button to view that profile.
> I also think this is possibly already fixed in the final version.

About this, the Results Tool (old profile tool) needs the HYCHAN.OUT because it reads some results (depth, velocity, flow, etc...). For plotting the model data, use the Info Tool. 

Results Tool: Model data (*.DAT files) + results (*.OUT files)
Info Tool: Model data (*.DAT files)

**Comment by rpachaly** [comment]
2:15 min. 

Info Tool: 

![image](https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/assets/39889306/076d8842-2c5c-466d-8217-c97ea8406f86)

Results Tool:

![image](https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/assets/39889306/d57f60f3-8f91-4afd-bfee-c6a3ea2dba3a)


Done on 61c942c93023f59d5ddc7ba45615eae8d8910d61

**Comment by rpachaly** [comment]
> 13:00 min. This bug happens often enough to warrant fixing. I assume it's an easy fix.

I could not replicate this one. Maybe it is a merging conflict.

**Comment by rpachaly** [comment]
> 15:06 min. I think this plot issue is simply a bad merge. Let's get all the code on the same page.

Merging conflict. Working fine on the current branch.

**Comment by rpachaly** [comment]
> 23:00 min. Error message. Test on better merged code. Test Project Below.

This was a bug related to the unit system, already fixed in a previous commit.

**Comment by FLO-2DKaren** [comment]
@robson,
Did you add a test for a user cross section with zero depth?

**Comment by FLO-2DKaren** [comment]
All good and I moved the cross section check to another issue.
