### ISSUE TITLE
Coastal Channel Test

### ISSUE THREAD

**Issue by FLO-2DKaren** [FLO-2DSoftware/qgis-flo-2d-plugin#1212]
Hi Robson,  

Here is the coastal channel video and 2 test projects.
https://flo-2d.sharefile.com/d-s432e692a41604872901ed40e97e26d23

Issues:
4:10 min. Let's remove that message.  It's annoying.
stop using this message
FLO-2D: All changes to this layer can be overwritten by changes in the User Layer.

7:00 min.  Whenever you do a save on the cross section editor, it always load the second to last cross section.  Why not the first cross section?

11:00 min.  Confirm that delete schema is also deleting cross section user data.  That's not good.
You can use the Coastal Cross Sections in Ready to Schematize project to test this.

12:00 min.  Let's consider putting the Save button from Control Variables on the outside of the window so you don't have to scroll to save.  Laptop users struggle with this and they use the roller wheel to scroll down.  They always accidentally turn off the mudflow.

14:12 min.  Oops forgot to set inflow to channel again.  Second time I did that.  I wonder if that radio button is too small?  Maybe it needs to go below the type dialog.

14:40 min. Note the channel inflow node error.   
You can use the  Coastal Inflow Cross Section Error Message project to test this.

**Comment by FLO-2DKaren** [comment]
Hi Robson,  Just some notes so you can skip most of this video.

4:10 fixed
7:00 already on another item
11:00 already on another item

**12:00 Needs feedback
14:13 Probably not worth moving.  That window is tight.
11:40  Needs feedback.  This could be something we check with the channel checker.**

**Comment by rpachaly** [comment]
11:00 min This is already done on a previous commit. However, I like the idea of clearing out the user cross section data. Maybe a button on the Sample Elevation that does that?

**Comment by rpachaly** [comment]
12:00 min. Agree! I'll do that and fix some small alignment issues.

**Comment by rpachaly** [comment]
Karen, related to the Control Parameters, a few months ago you mentioned something about a variable to remove or to set another default value. Do you remember this?

**Comment by rpachaly** [comment]
https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/assets/39889306/8b219b1e-9c06-4e10-840a-9711bd5c5578

**Comment by rpachaly** [comment]
Obs: I tested in all zoom options that my computer allows (100, 125, 150, 175%) and all looking good.

**Comment by FLO-2DKaren** [comment]
1. Please set tout, simult, and graphtim default to 0.1.  That was the default.  Thanks for reminding me.
2. That last default is needed.  I think it goes with ARF.DAT.  It's the S line on top of ARF.dat.  Not commonly used.

The rest looks good.  Thanks for fixing it.

**Comment by rpachaly** [comment]
Set Control Parameters updated on https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/pull/1241

**Comment by rpachaly** [comment]
14:12 min. I called it "Component" and added below the type. Feel free to suggest another label, it is easy to change. 

![image](https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/assets/39889306/0f1bcf71-d217-4fa4-8a68-94c629778603)

Done on 0fd916cea5660d76d1b9226e39699289534c2683

**Comment by rpachaly** [comment]
The adverse slope check is already implemented. I'm marking this issue for testing since all bugs/errors/improvements are done. 

![image](https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/assets/39889306/0c33101f-b8c6-4ca7-87e5-4a817400e1d8)

**Comment by FLO-2DKaren** [comment]
That's awesome.  Thanks Robson.

**Comment by FLO-2DKaren** [comment]
I will finish this test after Issue #1265 is finished.

**Comment by FLO-2DKaren** [comment]
Everything is working OK in this I retested everything in the video and the issues list.
