### ISSUE TITLE
Possible Wall Issue

### ISSUE THREAD

**Issue by FLO-2DKaren** [FLO-2DSoftware/qgis-flo-2d-plugin#1217]
@rpachaly 

Wall Algorithm might be having an issue.
Wall failure seems OK so this might be easy to test since one is working and the other isn't but they both work the same way.

https://flo-2d.sharefile.com/d-s95b3f009cc3d430f9df71ef1fb41edb0

Project still uploading as of 4:36pm NY time Monday March 18.

**Comment by rpachaly** [comment]
Hi Karen, 

You are right, the problem is the moving window. I spent the whole afternoon trying to figure out a way to fix the code using the moving window, but it is too complicated based on how the code was structured. I removed the moving window for this case and did a speed test:

**Moving Window**

Run time: 10.663343399999995 s

**Moving Window Removed**

Run time: 10.931088800000005 s

Not a significant difference. I'll just be sure that the algorithm is correct and then push the branch.

**Comment by FLO-2DKaren** [comment]
Oh there's a difference.  You just don't have enough data to test.  Small project make it take longer.  I'll send you a project

**Comment by FLO-2DKaren** [comment]
Big wall test
https://flo-2d.sharefile.com/d-s40854abec5fb4d9a9c8a6ef8fdde6067

**Comment by FLO-2DKaren** [comment]
Robson,
I think the key to this is that the wall fail elevation seems to be correct but the wall crest elevation seems to be doubled.  

I think the moving window should clip the wall data so it isn't duplicated.  Right now, it's just copying the features that intersect the window.  Maybe it should be clipping them.

Maybe we can use a temp levee layer that reports the wall height in an attribute table.  I bet if we see which ones are problematic we can figure out why.   I know this code is somewhat complex but we can figure out how to fix it if we understand which ones are 2x too high.  Maybe its double accounting the correction field somehow.

I wonder if we take all of the levees out but the one, would it still do that?

**Comment by rpachaly** [comment]
As far as I understood the code, if a feature (line in this case) intersects two moving window, it will add the correction twice (or more). 

The point is that it is hard to keep track of the fids that were already used because the for loop that "moves" the window is inside two functions.

**Comment by rpachaly** [comment]
I'll figure out a way to keep using the moving window

**Comment by FLO-2DKaren** [comment]
> As far as I understood the code, if a feature (line in this case) intersects two moving window, it will add the correction twice (or more).
> 
> The point is that it is hard to keep track of the fids that were already used because the for loop that "moves" the window is inside two functions.

I agree with this assessment.  That's why I recommended clipping the walls to the window but they decided to remove duplicates instead of clipping the walls.  I think it may fix our issue to simply clip the polylines to the boundary of the window.

**Comment by rpachaly** [comment]
Grid numbers: 2475 34293 53363

https://flo-2d.sharefile.com/d-s8cf8eb4727d44309af87231e60adb700

**Comment by rpachaly** [comment]
I'm going to push this branch so you test if you want but don't merge it, still work in progress.

**Comment by FLO-2DKaren** [comment]
OK

**Comment by rpachaly** [comment]
@FLO-2DKaren Did you check the video? What are your thoughts?

**Comment by FLO-2DKaren** [comment]
Hi Robson,

This makes sense.  I can't see a reason to iterate using the user_levee_line.  That seems counter intuitive. 

If you stop the moving window, does the error go away?

Why is it 12ft?  Maybe one loop is building a crest elevation and then adding the correction to the crest elevation on another loop. 

On the second loop, the elevation is filled so the correction is added.

Maybe you can isolate the loop that is filling the crest elevation.  Maybe there is an inner or outer loop that is applying the crest elevation before the correction is applied.  Because it's revisiting the same feature????

**Comment by rpachaly** [comment]
Karen, 

I've finished up the wall test using the BigWallTest project. The current version has a **lot of** doubled corrections. In the modified version, as far as I checked, there is no doubled corrected values or levees without corrections.

However, the processing time is different:

Current Version: 3:46
Modified Version: 12:43

In my opinion, it is better to take a little more time to process something and have the expected values. I'm going to push the branch and you can decide whether we implement this or not.

**Comment by rpachaly** [comment]
This branch https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/tree/wall-issue-3

**Comment by FLO-2DKaren** [comment]
Tested, merged, no change in the online documentation but I think there is a change in the technical documentation.  I'll close this and add that to a new issue.
