### ISSUE TITLE
Possible issue

### ISSUE THREAD

**Issue by FLO-2DKaren** [FLO-2DSoftware/qgis-flo-2d-plugin#1218]
@rpachaly 
Hi Robson,

Where I'm using the plotting tools.  I think it might be causing the cursor to stick in the Arrow config.  I can't see it change to expand window.

Can you check this on any project?

**Comment by FLO-2DKaren** [comment]
I thought you didn't have these?  Did I merge some old stuff?

![image](https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/assets/20424460/adb2dab0-dec5-4fe6-954b-2238620a3dcc)

**Comment by rpachaly** [comment]
> Where I'm using the plotting tools. I think it might be causing the cursor to stick in the Arrow config. I can't see it change to expand window.

What do you mean? 

> I thought you didn't have these eyes? Did I merge some old stuff?

I tried to remove these eyes, but I could not. I'll spend more time to fix this. I don't like these eyes either.

**Comment by FLO-2DKaren** [comment]
I actually think this is an issue for my laptop only.  I'll close this issue.  I've come to the conclusion small screens suck with QGIS.
