### ISSUE TITLE
Cross Section Selector

### ISSUE THREAD

**Issue by FLO-2DKaren** [FLO-2DSoftware/qgis-flo-2d-plugin#1225]
Whenever you save cross section data, the default cross section is set to the second to last cross section.
I moved this here from a closed issue because you already fixed the other stuff.

**Comment by rpachaly** [comment]
Done on f50c548946f867af5a6f07ac0b21bb1948e3ea20

This needs to be tested, the code was weird but now it pops up the same cross section that was saved.
