### ISSUE TITLE
SD "Auto-assign link nodes": catch error and maybe give solution when inlet/outlet is null

### ISSUE THREAD

**Issue by FLO-2DJJ** [FLO-2DSoftware/qgis-flo-2d-plugin#1226]
Example:
ERROR 210322.0429: Couldn't assign Conduits nodes!
(line 3824).

Check this for 

- [x] conduits
- [x] orifices
- [x] pumps 
- [x] weirs****

**Comment by FLO-2DKaren** [comment]
Tested and approved
