### ISSUE TITLE
 Add Storage Units to 'Select components from shapefile layer'

### ISSUE THREAD

**Issue by FLO-2DJJ** [FLO-2DSoftware/qgis-flo-2d-plugin#1228]

**Comment by FLO-2DJJ** [comment]
@FLO-2DKaren, @FLO-2DNoemi 
This issue has just been finished. It is now a pull request https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/pull/1292.

See it in **Select components from shapefile layer**

![imagen](https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/assets/20424575/5dc68a65-bf04-4a8f-b415-1a462ef0fc58)

Please review it, comment if necessary, and let me know if it can be merged into master branch. Currently, there are no conflicts.

**Comment by FLO-2DKaren** [comment]
Thanks JJ.  I already merged it so I can test it and do some documentation this weekend.  I have channel and storm drain documentation left over.
