### ISSUE TITLE
Opening Closed Panels

### ISSUE THREAD

**Issue by FLO-2DKaren** [FLO-2DSoftware/qgis-flo-2d-plugin#1231]
If you click the grid info tool, it should open the grid info panel.
If you click one of the plottable things like a rating table or something, it should open the table/plot panels. 

They will open in the last docked position and that's ok because it's easier to view them on another screen if you are using small screens.  Like I usually undock the grid info tool when I'm on a laptop because it squishes the layer and FLO-2D panels.

**Comment by rpachaly** [comment]
Karen, I saw that you created a project called Plotting Tools. I created a branch where I'm going to add the issues related to this project called https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/tree/plotting-tools

Do not merge it yet, let's finish some issues first.

**Comment by rpachaly** [comment]
> If you click the grid info tool, it should open the grid info panel.

Done on 0ec0d49ae0b5785e5076972f8fdd650627720bc0

**Comment by rpachaly** [comment]
Every time that the Results Tool or the Info Tool is clicked, it will reopen the table and plot. 

Done on e75e7ba468a06edd9c929b6547e48e2d7a078974

**Comment by FLO-2DKaren** [comment]
OK I'm glad you found that project.  I thought we could use it to track the new plotting stuff.  I think we put it under something else but it will make it easier for us to track here.

**Comment by FLO-2DKaren** [comment]
I won't merge anything until you are ready for me to.

**Comment by rpachaly** [comment]
What other triggers to you think that I should add to open the Table and Plot besides clicking on the toolbar buttons?
