### ISSUE TITLE
Error when setting for the FLO-2D Folder points to a directory where FLOPRO.exe does not exist

### ISSUE THREAD

**Issue by FLO-2DJJ** [FLO-2DSoftware/qgis-flo-2d-plugin#1232]
The error:

![image](https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/assets/20424575/971aeebf-4807-41a7-839b-9c538f312d97)

The error happens when creating a new project or checking **Advanced Layers** in the **Run Settings** dialog when the FLO-2D folder doesn't have the FLOPRO.exe program.

**Comment by rpachaly** [comment]
Hi JJ, 

Thanks again for catching this bug. I fixed and created a pull request https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/pull/1235.

This is shown when a gpkg is created without having the FLOPRO.exe. Also, this information is written to the gpkg metadata. 

![image](https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/assets/39889306/09ad7f25-8f91-49e4-8ec2-2f80e9a431cb)
