### ISSUE TITLE
Expand FLO-2D project group when opening an existing gpkg

### ISSUE THREAD

**Issue by rpachaly** [FLO-2DSoftware/qgis-flo-2d-plugin#1236]
When opening an existing gpkg, the FLO-2D project group does not expand on start and it is annoying. Adding this issue so I can remember to do that.

**Comment by FLO-2DKaren** [comment]
Haha that's funny because I liked that it didn't expand.  But look at the sequence.  Maybe there is a collapse command in there when you hide the advanced layers.

**Comment by rpachaly** [comment]
I didn't like this because when you create a new gpkg it is expanded, and when you open an existing gpkg it is collapsed! hahah

**Comment by FLO-2DKaren** [comment]
It should be expanded.  I'm just a minimalist when it comes to the layer list.  The less I have to look at, the happier I am.
