### ISSUE TITLE
Error when running FLO-2D Settings from QGIS Welcome page

### ISSUE THREAD

**Issue by FLO-2DJJ** [FLO-2DSoftware/qgis-flo-2d-plugin#1237]
Hi @rpachaly,

- [ ] From QGIS Welcome Page (when not FLO-2D project is selected but with the FLO-2D toolbar active) running **FLO-2D Settings** from FLO-2D tool bar produces this error:

![imagen](https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/assets/20424575/6e810de8-1f86-4fdf-88c7-b6a677d2f699)

I think it should give a message like other menu items: 

![imagen](https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/assets/20424575/10a4edb7-e0ea-402a-b23d-910b182900f4)

- [ ] Similar error with **Run FLO-2D Pro** (but not with the other menu items):

![imagen](https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/assets/20424575/bc6ea227-095f-4825-8cef-2b2d39226c32)

**Comment by FLO-2DKaren** [comment]
Good catch JJ.  We need to be able to run a model even if a project isn't loaded.  We'll have to skip those two items if a project isn't loaded.

**Comment by rpachaly** [comment]
Done on https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/pull/1242

Now if there is no project loaded, the run settings will only update the variables on the QSettings and the Run FLO-2D will read the information on the QSettings to call FLO-2D. If there are the dat files, it will run. Otherwise it will show a warning explaining that no CONT.DAT was found.

**Comment by FLO-2DJJ** [comment]
I’ve identified a couple of issues:

1. In the _Run Settings_ dialog, if a _FLO-2D Folder_ is chosen where no FLOPRO.exe exists, the selection is accepted, and a 'FLO-2D: Run Settings saved!' message is displayed. I think the user should be warned of the wrong situation.

2. (After 1) selecting **Run FLO-2D Pro** produces this error:

2024-03-26T09:02:39     WARNING    Traceback (most recent call last):
              File "C:\Users\jjrod\git\qgis-flo-2d-plugin\flo2d\flo2d.py", line 1388, in run_flopro
              self.run_program(user_program)
             UnboundLocalError: local variable 'user_program' referenced before assignment

**Comment by rpachaly** [comment]
Good idea JJ!

> 1. In the Run Settings dialog, if a FLO-2D Folder is chosen where no FLOPRO.exe exists, the selection is accepted, and a 'FLO-2D: Run Settings saved!' message is displayed. I think the user should be warned of the wrong situation.

![image](https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/assets/39889306/5cc37a68-6bb8-4a1a-b9b0-b18d5f032759)

Done on 312b0caf7ec8c1db2462a7777791a2493861def1

> (After 1) selecting Run FLO-2D Pro produces this error:

![image](https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/assets/39889306/7b8ca16a-dd5a-4f5e-a69c-f844cd69f058)

Done on 3ccf7ed4878cf47eb8808a54b7595481a370cb4b

Pull request created https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/pull/1246
