### ISSUE TITLE
Deleting table data

### ISSUE THREAD

**Issue by rpachaly** [FLO-2DSoftware/qgis-flo-2d-plugin#1240]
@FLO-2DKaren I've found a bug on the Channel Editor. I'm adding this here so you're aware of this when you're testing. 

https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/assets/39889306/d8d683ef-a9df-487f-b955-8769c2b1b671

**Comment by rpachaly** [comment]
Done on 6efa12810e4e8511d9c956f0fa25c25d0c197d45

I had to comment out a function that I think is meaningless.

**Comment by FLO-2DKaren** [comment]
I'm so glad you found this.  I knew it was in there but I didn't know how to make it happen.  I've seen it many times and now I know why.

**Comment by FLO-2DKaren** [comment]
tested
