### ISSUE TITLE
Possible grid info bug

### ISSUE THREAD

**Issue by FLO-2DKaren** [FLO-2DSoftware/qgis-flo-2d-plugin#1243]
@rpachaly 

Hi Robson,
This error goes away after I restart the project.  If you can't reproduce it, close this issue.

New project
Create grid
sample elevation

try to use grid info tool.

https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/assets/20424460/59f652ba-1e8c-4cdb-a5cb-946ebe09f585

**Comment by FLO-2DKaren** [comment]
Robson,
Open the control panel and try to expand the window.  Does your cursor not switch to the expand cursor?  
I'm getting this for loads of windows.  I can't see the expand cursor on the edge of the panels. 
I can't expand attribute tables.
I can't expand the profile tool table.

**Comment by FLO-2DJJ** [comment]
Hi,
I also get that situation sometimes, with the plugin dialogs and the QGIS
panels.
Let's see what happens.

Juan Jose Rodriguez
FLO-2D Software
www.flo-2d.com
***@***.***

**Comment by rpachaly** [comment]
> This error goes away after I restart the project. If you can't reproduce it, close this issue.

I cannot reproduce this error. But I took a look and the info_ac was being referenced before assignment. I referenced it and added a check to the variable. It should work fine, worst case the toolbar button will not stay checked but no error will be shown. Let me know if it works. Done on ae98511538cdad161bf4849b8b809910b5aeb9df

**Comment by rpachaly** [comment]
@FLO-2DKaren @FLO-2DJJ 

I think I've found this bug, and it is IMPORTANT for future coding. We need to use these two commands to change the cursor to the wait cursor. 

QApplication.setOverrideCursor(Qt.WaitCursor) -> Set the Wait Cursor (blur circle)
QApplication.restoreOverrideCursor() -> Restore to the previous cursor

In a some places in the code, save FLO-2D for instance, it is used this command:

QApplication.setOverrideCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))

This command sets the cursor to the Arrow Cursor, but when it is active, it does not switch to the expand cursor and other types of cursor, only the Arrow Cursor.

I'll remove all from the code and commit to this branch.

**Comment by rpachaly** [comment]
These functions set the Arrow Cursor. I removed/adjusted the code. It is on this branch https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/tree/fixed-cursor

- [ ] flo_save_project
- [ ] import_chan
- [ ] populate_inlets
- [ ] populate_orifices
- [ ] populate_conduits
- [ ] import_gds
- [ ] populate_storages
- [ ] import_storm_drain_INP_file
- [ ] populate_outfalls
- [ ] out_fall_type_cbo_currentIndexChanged
- [ ] populate_pumps
- [ ] highlight_outfall_cell
- [ ] xyz_elevation

@FLO-2DJJ Would you mind to test the ones related to the SD? It would be easier for you since you're more acquainted with the code and knows where to call these functions.

**Comment by rpachaly** [comment]
See: https://doc.qt.io/qt-6/qguiapplication.html#setOverrideCursor

**Comment by rpachaly** [comment]
@FLO-2DKaren Do you have a dataset that I can you to test the xyz_elevation function?

**Comment by FLO-2DKaren** [comment]
Project
https://flo-2d.sharefile.com/d-s70c2f078792a4fd49b142366c3ab5547


https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/assets/20424460/b6b01b45-f65b-497b-b986-7375beb817e0

**Comment by rpachaly** [comment]
Thanks Karen, this project was sufficient for testing the arrow bug!

**Comment by FLO-2DKaren** [comment]
I figured it would work for that simple test.  I also wanted to explain why those tools exist.  I'm glad that data works still.

**Comment by FLO-2DJJ** [comment]
> These functions set the Arrow Cursor. I removed/adjusted the code. It is on this branch https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/tree/fixed-cursor
> 
>     * [x]  flo_save_project
> 
>     * [x]  import_chan
> 
>     * [ ]  populate_inlets
> 
>     * [ ]  populate_orifices
> 
>     * [ ]  populate_conduits
> 
>     * [x]  import_gds
> 
>     * [ ]  populate_storages
> 
>     * [ ]  import_storm_drain_INP_file
> 
>     * [ ]  populate_outfalls
> 
>     * [ ]  out_fall_type_cbo_currentIndexChanged
> 
>     * [ ]  populate_pumps
> 
>     * [ ]  highlight_outfall_cell
> 
>     * [x]  xyz_elevation
> 
> 
> @FLO-2DJJ Would you mind testing the ones related to the SD? It would be easier for you since you're more acquainted with the code and knows where to call these functions.

Yes, I've already addressed some of them in PR #1244, according to the issue #1182 that I posted on Feb 28.
I'll be checking the items in the above list as they are corrected and tested.

**Comment by FLO-2DKaren** [comment]
I haven't seen any of these issues in a while.  I'll close this now and post another issue if I find any more.
