### ISSUE TITLE
Review 'set wait cursor' to follow by 'restore cursor' in Storm Drain functions

### ISSUE THREAD

**Issue by FLO-2DJJ** [FLO-2DSoftware/qgis-flo-2d-plugin#1249]
These functions set the Arrow Cursor. I removed/adjusted the code. It is on this branch https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/tree/fixed-cursor

- [x] flo_save_project
- [x] import_chan
- [x] populate_inlets
- [x] populate_orifices
- [x] populate_conduits
- [x] import_gds
- [x] populate_storages
- [x] import_storm_drain_INP_file
- [x] populate_outfalls
- [x] out_fall_type_cbo_currentIndexChanged
- [x] populate_pumps
- [x] highlight_outfall_cell
- [x] xyz_elevation

@FLO-2DJJ Would you mind testing the ones related to the SD? It would be easier for you since you're more acquainted with the code and knows where to call these functions.

_Originally posted by @rpachaly in https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/issues/1243#issuecomment-2020351931_

**Comment by FLO-2DJJ** [comment]
In branch [review_wait_cursor_#1249 ](https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/tree/review_wait_cursor_%231249) I will be doing the changes/fixes/adjustments to the functions listed above.

DO NOT pull request/merge this branch until I finish and test all items !

**Comment by FLO-2DJJ** [comment]
The tasks checklists above for inlets, outfalls, storage units, conduits, pumps, and orifices are in fact checks for their respective complete dialog classes (and a new one for weirs). Its a thorough review of the code where the mouse cursor behavior changes. The updated task list includes the following classes:

Review setting of mouse cursor in classes:

- [ ] InletNodesDialog 
- [ ] OutfallNodesDialog
- [ ] StorageUnitsDialog
- [ ] ConduitsDialog
- [ ] PumpsDialog
- [ ] OrificesDialog
- [ ] WeirsDialog

**Comment by rpachaly** [comment]
Can we close this issue?
