### ISSUE TITLE
MapCrafterGroup

### ISSUE THREAD

**Issue by FLO-2DKaren** [FLO-2DSoftware/qgis-flo-2d-plugin#1255]
When save apply same condition as google map

Do Not add to geopackage.

![Image](https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/assets/20424460/6e09c15f-5860-486e-92b0-93168a4533b5)

**Comment by rpachaly** [comment]
The easiest approach was to identify if a layer source is located in a MapCrafter folder. If it is, then it will not be added to the geopackage. It is done on https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/pull/1264 and I'll merge it because it is not a complicated code.
