### ISSUE TITLE
Tool Tips with Data Input Manual Description

### ISSUE THREAD

**Issue by FLO-2DKaren** [FLO-2DSoftware/qgis-flo-2d-plugin#1256]
Let's add tool tips to windows variables where applicable that come straight from the data Input Manual

**Comment by rpachaly** [comment]
Consider this https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/issues/851

**Comment by rpachaly** [comment]
- [x] Hydraulic Structures Editor
- [x] Bridge data
- [x] Channels Editor
- [x] Channel Geometry

Done and merged on https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/pull/1266

Obs: Added directly on the ui file.
