### ISSUE TITLE
Error when shapefile is outside the project tree in Layers panel

### ISSUE THREAD

**Issue by FLO-2DJJ** [FLO-2DSoftware/qgis-flo-2d-plugin#1259]
The error is related with **Select components from shapefile layer**.

Here the shapefile 'L3Weirs' is outside the main project tree in the Layers panel:

![imagen](https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/assets/20424575/02eaf663-e5ac-4e15-adef-926343311934)

If that layer was previously selected in the **Select components from shapefile layer**, the following error occurs when trying to open it again:

![imagen](https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/assets/20424575/9cfeeab3-ab81-49aa-9b0c-34e843b0157c)

**Comment by FLO-2DJJ** [comment]
I'm doing this with this solution (a template for now):

```
                try:
                    lyr = self.lyrs.get_layer_by_name(layer, group=self.lyrs.group).layer()
                except:
                    root = QgsProject.instance().layerTreeRoot()
                    group = root.findGroup(self.lyrs.group)                    
                    lr = QgsProject.instance().mapLayersByName(layer)[0]
                    lyr = root.findLayer(lr.id())
                    
                    # Clone the layer
                    myClone = lyr.clone()
                    
                    # Get the parent of the layer
                    parent = lyr.parent()
                    
                    # Insert the cloned layer into the group at the top (position 0)
                    group.insertChildNode(0, myClone)
                    
                    # Remove the original layer from its parent
                    parent.removeChildNode(lyr)                     
                
                    lyr = self.lyrs.get_layer_by_name(layer, group=self.lyrs.group).layer()
```

I'll convert it to a method and apply to all situations in _Select components from shapefile layer_

**Comment by FLO-2DJJ** [comment]
Yes. That's the idea. The prototype is my initial template to do it.

**Comment by FLO-2DKaren** [comment]
My point is that I think you are making it too hard.  @rpachaly Can you help JJ with this.  Storm drain layers can't be assigned if they aren't in the User Group.  I think he's trying to move them automatically instead of showing the error message.

**Comment by FLO-2DJJ** [comment]
@FLO-2DKaren 
Are you sure about this?:
> Storm drain layers can't be assigned if they aren't in the User Group. 

I'm doing it with the latest plugin and the shapefiles are recognized if they are in the Storm Drain user layer group. Even after closing and opening the project.

**Comment by FLO-2DKaren** [comment]
Hi JJ,

At this point, no I'm not sure.  I was hoping to test it all this weekend when I finish documenting the plugin.

**Comment by rpachaly** [comment]
- [ ] reduce the number of messages you have to ok when you delete a the table or culvert data

**Comment by rpachaly** [comment]
I've removed the filter by group on the code. Now the SD layer does not need to be inside the SD group or the FLO-2D group to populate on the storm drain shapefiles dialog. Also, that extra message asking to confirm the deletion of the culvert equation/rating table is removed. 

I'm not going to make a video. It is on https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/pull/1333

I feel pretty comfortable to merge it based on my testing but I'll let the pull request open today if someone wants to test it.

**Comment by rpachaly** [comment]
Let's wait a bit, I'm going to solve this issue https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/issues/1331 on the same branch.
