### ISSUE TITLE
Info Tool Error Message

### ISSUE THREAD

**Issue by FLO-2DKaren** [FLO-2DSoftware/qgis-flo-2d-plugin#1269]
![image](https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/assets/20424460/9f5f5490-1e3f-4f0c-8533-13ffd07afec2)

I get this error message when clicking on an inflow node while using the FLO-2D Info Tool.

The widget opens the Boundary Condition Editor but it does not Load the clicked inflow node into the tool or plot/table.

 --Oooh I don't think this is related but i was running a simulation on the Project Path during this test.  That would really make issues if I was trying to use the info tool on storm drain.  

Storm Drain Results are still connected to the FLO-2D Info Tool.

**Comment by rpachaly** [comment]
Done on https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/pull/1271

I didn't get the issue related to the SD. Do you mean to use the FLO-2D Info Tool while a simulation is running?

**Comment by FLO-2DKaren** [comment]
I clicked the info button and then clicked an inflow node.

It loaded the BC Widget but it didn't load the correct inflow node.

**Comment by FLO-2DKaren** [comment]
Don't worry about the SD stuff.
