### ISSUE TITLE
Missing Rect and Trap Channel Interpolator

### ISSUE THREAD

**Issue by FLO-2DKaren** [FLO-2DSoftware/qgis-flo-2d-plugin#1274]
Hi Robson,

I'm working on the Rect and Trap section of the plugin documentation.  I have a couple of channels that I want to set up.
I need to interpolate the channel but the button is missing.  Did you put it somewhere else?  

Maybe we can do something different with this.  Like If a Rect or Trap channel exists, interpolate it before we run the Natural interpolator.

![image](https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/assets/20424460/d5e48c00-251e-4cba-9603-eea8dfdb483c)

![image](https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/assets/20424460/eed1f742-a059-4c05-849e-5a8948c65d94)

**Comment by FLO-2DKaren** [comment]
OK no hurry.  I can simply move on to another part of the tutorials.

**Comment by rpachaly** [comment]
Karen, 

This portion of the code is kind of a mess, but it is working now. It works this way now:

First, it interpolates ONLY the rectangular and trapezoidal channels using a python function inside flo2d plugin called interpolate_bed. 

Second, it interpolates only Natural channels with Jim's interpolator. 

Everything is looking good on my testing here. HOWEVER, if in a segment you have a trapezoidal/rectangular xsec AND a natural xsec, it will crash the interpolator. Is is okay? Is is usual to have a channel segment containing rectangular/trapezoidal and natural xsecs altogether?

**Comment by FLO-2DKaren** [comment]
OK I think that is fine.  I don't think anyone should mix geometry like that in a single segment.

**Comment by rpachaly** [comment]
Ok, I'm going to merge it.

**Comment by FLO-2DKaren** [comment]
Tested and all ok.

https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/assets/20424460/f466b7a4-f6c4-4354-a5cf-e6b0851eec8c
