### ISSUE TITLE
floodplain cross section widget update

### ISSUE THREAD

**Issue by FLO-2DKaren** [FLO-2DSoftware/qgis-flo-2d-plugin#1275]
When you do anything to a floodplain cross section, it updates to the last cross section in the list.  Just set it to any cross section and then hit the schematize button to see the issue.

![image](https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/assets/20424460/e7c8fed9-d81c-4280-9f2f-1b89d1473e9e)

**Comment by FLO-2DKaren** [comment]
Add a help button too.  I added some nice instructions.

**Comment by rpachaly** [comment]
Ok!

**Comment by rpachaly** [comment]
Done on https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/pull/1280
