### ISSUE TITLE
Plugin Icon not connected

### ISSUE THREAD

**Issue by FLO-2DKaren** [FLO-2DSoftware/qgis-flo-2d-plugin#1283]
Reconnect the icon
![image](https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/assets/20424460/580c409b-81e4-4b1b-af5a-079f4b17d975)

**Comment by FLO-2DKaren** [comment]
Change the help button to this path.
https://flo-2dsoftware.github.io/FLO-2D-Documentation/Plugin1000/toolbar/index.html

**Comment by rpachaly** [comment]
Done on https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/pull/1285
