### ISSUE TITLE
Update metadata 

### ISSUE THREAD

**Issue by rpachaly** [FLO-2DSoftware/qgis-flo-2d-plugin#1284]
Update the metadata when publishing the release version of plugin 1.0.0.

- New toolbar
- New Boundary Condition Editor
- New Cross Section Editor
- Bug fix
- New Info Tool
- New Results Tool
- FLO-2D Geopackage Improvements
- Export to hdf5

**Comment by FLO-2DJJ** [comment]
•	Storm Drain Editor widget:
```
-Add buttons to top icons tool bar to 'Import INP', 'Export INP', 'Select components from shapefile layer', and 'Auto-assign link nodes'.
-Change the ‘export_swmm.svg’ icon to match the style of other ‘export…svg’ icons.
-Check/Uncheck ‘Simulate Storm Drain’ checkbox when loading project.
-Remove 'create discharge table and plots' button.
-Remove 'create', 'save', 'revert', and 'delete' buttons.
-Add help button and icon ‘help.svg’.
-Do not assign dropboxes values to junctions when exporting SWMMFLODROPBOX.DAT.
-Do not assign dropboxes values to user inlets when setting values from shapefile.
-Add Storage Units to ‘Select components from shapefile layer’.
-'Convert Schematic Layers to User Layers': clear all data before conversion.-
-Restore clogging data by reading SDCLOGGING.DAT after the conversion.
-Add dropbox column to table in Inlets/Junctions dialog.
-Time series improvements and fixes: Catch and correct errors when reading time series for Outfalls and Inlets in [TIMESERIES] data of .INP files.
-Add storage units table and layer. Import .INP [STORAGE] into ‘user_swmm_storage_units’ layer.
-Export SWMM.INP: add [STORAGES] group.
-Create Storage Units dialog.
-Make class CurveEditorDialog general.
-New 'swmm_other_curves' table and layer. Write/read .INP [CURVES] to/from .INP file from/to 'swmm_other_curves' table.
-Rating Tables and Culvert Equations: allow rename of Type 4 Rating Tables and Culvert equations.
-Default MULTBARRELS = 1 for Culvert equations. 
-Add Rating Tables and Culvert names without spaces. 
-Redraw plot and table when adding new RT/Culvert.
-Culverts: display integers in Table Editor for TYPEC, TYPEEN, CUBASE.
-Set DEFAULT values to fields in ‘swmmflo_culvert’ table in data base.
-Add ‘Keep Existing and Complete’ functionality to pumps, orifices, and weirs when reading .INP file.
-Remove duplicate components when importing .INP files.
-SD plots: Time series from .RPT, SWMMQIN.OUT, and SWMMOUTFIN.OUT files.
-Set default name after adding new storage unit (TRIGGER in database).
-Remove sort of combobox items in Storage Units dialog: it wrongly ordered items with ASCII upper case first.
-Add storage units to Auto-assign link nodes.
```
•	Import/export SDCLOGGING.DAT:
```
-Read SDCLOGGING.DAT to update ‘swmm_clogging_factor’ and ‘swmm_time_for_clogging’ fields of ‘User Storm Drain Nodes’ layer.
-Only export inlet/junction nodes with ‘swmm_clogging_factor’ > 0 and ‘swmm_time_for_clogging’ > 0.
-Delete SDCLOGGING.DAT if no clogging data.
-Import SDCLOGGING.DAT from 'Import data (.DAT) files'.
-Import SWMMFLODROPBOX.DAT as single component.
-Read SWMMFLODROPBOX.DAT when converting SD from Schematic and importing INP file.
-Remove SWMMFLODROPBOX.DAT when exporting if all dropbox area values in User SD Nodes are zero or null.
```
•	Add ‘Select All’ to ‘Schematic to User conversion’ dialog.
•	Fix: Writes/reads empty barrels column for weirs and orifices in [XSECTIONS].
•	Improved catching of links (conduits, pumps, orifices, and weirs) outside domain.
•	Create memory layer with all nodes and storage unit’s names and geometry.
•	Change color style of line arrows of pumps, orifices, and weirs layers.
•	Floodplain Cross Section Editor: keep current CS when changing direction.
•	Convert schematic hydraulic structures to user structure lines.
•	New icon for Tailings Dam Breach.

**Comment by FLO-2DKaren** [comment]
@FLO-2DJJ 
We don't need all of that info. Let's keep it brief.  
We will start tracking the change log after we release this version.
Maybe we can add links to the documentation so people can see how the new tools function.

**Comment by FLO-2DJJ** [comment]
Ok Karen. They are a reminder. I'll edit it whenever we are ready to publish them.

**Comment by FLO-2DKaren** [comment]
@rpachaly If this is OK go ahead and update the Metadata with it

[general]
name=FLO-2D
version=1.0.0
qgisMinimumVersion=3.22
qgisMaximumVersion=3.99
description=FLO-2D tools for QGIS
author=FLO-2D
email=contact@flo-2d.com
about=QGIS tools for FLO-2D

changelog=
 <p>1.0.0
  - Bug Fixes
	Review and help with bugs by sending messages to developers
	Check the GitHub repo for a full bug list.
	Fixed Python 3.12 deprecation warnings.
  - Boundary Condition Editor:
    	Separated the inflow and outflow BC conditions
    	Added a button to load existing INFLOW.DAT and OUTFLOW.DAT
    	Added a button to remove the schematized data
    	Added the whole grid boundary condition
    	Improved the performance of setting outflow boundary using polygons
    	Improved layout
    	Hide/show BC layers
    	Grouped BC tables into their own group
  - Channel Editor: 
	Improve channel interpolation logic
	Improve processing tools
	Group schema buttons
	Improve Confluence tools
  - Storm Drain: 
	Improve Rating/Culvert EQ editor for type 4
	Improve editor and algorithm logic
	Add profile tool
	Add Storage Unit tools
	Improve import export
	Add Storm drain control editor
  - Hydraulic Structures schematization:
	Shows message at end of schematization.
	Checks several potential errors and warns use.
  - Results and info tools
	Review results with plots and tables
	Improve FLO-2D Info tool
  - General
	Compress tools into drop down menus
	Improve import export logic
	Autoport GeoPackage
	Save all data to Geopackage
	Include metadata for GeoPackage
	Improve Run options and add Quickrun
 	Improve Progress bars, messages and log
 	Improve tooltips
 	Improve Layer Organization
 
# Tags are comma separated with spaces allowed
tags=flow, 2d, grid, preprocess, GeoPackage, FLO-2D, flood modeling, 2d modeling

homepage=https://flo-2d.com/qgis-plugin
tracker=https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/issues
repository=https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin
category=Plugins
icon=img/FLO.svg
# experimental flag
experimental=False

# deprecated flag (applies to the whole plugin, not just a single version)
deprecated=False

**Comment by rpachaly** [comment]
I adjusted the metadata and changed the repository icon for this version. What do you think?

![image](https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/assets/39889306/8b381916-014d-4382-b0a9-41c01b860678)

Here is the image in detail.

![FLOgila](https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/assets/39889306/4e7ebc0a-dc0d-4f1e-b4db-51488dab9ace)

**Comment by FLO-2DNoemi** [comment]
I like it.

Just a comment: perhaps if we make the name "Gila" a little smaller, it
will be easier to read from the icon.

Noemi

**Comment by FLO-2DKaren** [comment]
I like it too and agree it can be smaller.

**Comment by rpachaly** [comment]
Something like this?

![image](https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/assets/39889306/16f3c29c-9d45-43c3-89a9-d0d2689a21ec)

**Comment by FLO-2DNoemi** [comment]
Yeah, that looks good.

**Comment by rpachaly** [comment]
On https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/pull/1367
