### ISSUE TITLE
Drop boxes cannot be assigned to junctions.

### ISSUE THREAD

**Issue by FLO-2DJJ** [FLO-2DSoftware/qgis-flo-2d-plugin#1296]
See how to block assignment to junctions from _Select components from shape file layer_ (Inlets/Junctions tab)

**Comment by FLO-2DKaren** [comment]
I think the easy thing todo is take out the filter that connects the drop box area to storm drain type J

**Comment by FLO-2DJJ** [comment]
Fixed and merged to master with pull request #1297

**Comment by FLO-2DJJ** [comment]
Master already has this fix.
@FLO-2DKaren, @FLO-2DNoemi please review it. Issue can be reopen if there is any observation.
