### ISSUE TITLE
storm drain checkbox and help button

### ISSUE THREAD

**Issue by FLO-2DKaren** [FLO-2DSoftware/qgis-flo-2d-plugin#1298]
@FLO-2DJJ 

This isn't important.  It is a little annoying

1. Whenever you reload a project, the Simulate Storm Drain checkbox is unchecked.  I recommend that you connect this to the Simulate Storm Drain switch in the Control Variables tab.  That way, the switch will stop turning off unless someone actually turns it off.

![image](https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/assets/20424460/8678bb7d-a282-4651-b9cf-822b10c80866)

![image](https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/assets/20424460/b513b7ea-eb87-4d6b-b2c3-98036190ae4c)

2. Help button.  Please connect it to help.svg instead of help_contents.svg because we're going to put these in more places and I'd like to use the simpler help button.

3. Can you remove this button?  We're going to do this through MapCrafter.  It's already finished.  We just need to merge it.

![image](https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/assets/20424460/c67134a1-e324-4be6-acce-75930ca77659)

**Comment by FLO-2DKaren** [comment]
@FLO-2DJJ 
While you are at this, we may as well fix this too.

Remove the Greyed out buttons.  We don't use them anyway.

Move the Import Export inp buttons to this top small button area.   I attached the import export buttons in the zipped file below.

![image](https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/assets/20424460/132960a7-8697-432b-aa1c-4645b704cc9c)


[import export swmm buttons.zip](https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/files/15168034/import.export.swmm.buttons.zip)

**Comment by FLO-2DKaren** [comment]
@FLO-2DJJ 
Hi JJ,

Can you add this ui file to that branch with the pull request?  I'm adding tooltips to the variable labels but I don't have a cloned version on this computer.

[cont_toler_jj.zip](https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/files/15176994/cont_toler_jj.zip)

**Comment by FLO-2DJJ** [comment]
Hi @FLO-2DKaren,

The cont_toler_jj.ui file is already in the branch

https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/tree/storm_drain_checkbox_and_help_button_(Issue_%231298)

Isn't it what you want?

It has not been modified. It's the same found in the master branch.

**Comment by FLO-2DKaren** [comment]
I just added tool tips so it won't look different.

**Comment by FLO-2DJJ** [comment]
> I just added tool tips so it won't look different.

Great @FLO-2DKaren . I pushed your changes to _cont_toler_jj.ui_ to pull request PR #1300

**Comment by FLO-2DJJ** [comment]
Solved and merged into master with pull request #1300.
