### ISSUE TITLE
Mesh generator issue

### ISSUE THREAD

**Issue by FLO-2DKaren** [FLO-2DSoftware/qgis-flo-2d-plugin#1301]
We need to create grids that do not have dangling grid elements.  Meaning a grid element that has a connection of only a diagonal or only one compass direction.  I'll get a video.

**Comment by FLO-2DKaren** [comment]
@rpachaly Let's have a meeting about this.  It is more important than it sounds.

**Comment by rpachaly** [comment]
Hi Karen, 

Ok! Let me know when you're available and send me the meeting link.

**Comment by FLO-2DKaren** [comment]
hmmmmm  I am not sure about that.  Some things would work and some things wouldn't.

@FLO-2DNoemi 
What do you think Noemi?

**Comment by rpachaly** [comment]
Ok, in doubt, I'll reassign the fids.

**Comment by FLO-2DNoemi** [comment]
It is better to reassign the FIDS even though most of the components I am
sure will be OK and functional,  it is the connectivity between cell sides
that controls most of the cell interaction. The only potential issue that I
can foresee is the identification of internal channel elements. The
calculation method for this is quite intricate, and in the past, even minor
issues like a missing FID have caused problems.

**Comment by rpachaly** [comment]
This is done on https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/pull/1308. Check the video.

https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/assets/39889306/4fa61d09-ceca-4ac6-8557-3de555196dc7

**Comment by FLO-2DKaren** [comment]
Excellent Robson.   I think the time we lose to the extra processing is worth not having to find and fix those if we run into problems with them.
