### ISSUE TITLE
Horton Initial Abstraction

### ISSUE THREAD

**Issue by FLO-2DKaren** [FLO-2DSoftware/qgis-flo-2d-plugin#1302]
Horton needs to have initial abstraction for the v1.0.0 release.

https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/assets/20424460/a6ac06ee-be3d-40a1-9219-2afe487bb638

**Comment by rpachaly** [comment]
Ok, this seems easy to do. I'll try to have it done by tomorrow.

**Comment by rpachaly** [comment]
This is done. I recorded a nice video explaining but my internet is not helping

**Comment by rpachaly** [comment]
https://drive.google.com/file/d/1cd_ZagRxEA0uQeBre5jaQb3bP1Qav3iZ/view?usp=sharing

**Comment by FLO-2DKaren** [comment]
Hi Robson,

This is super counter intuitive but FLO-2D Horton doesn't have a metric system setup so you always use english system for Horton.

So you do not need that converter tool that you applied.   We can have a meeting if you need.

**Comment by rpachaly** [comment]
Ok! I'm going to remove it then and push the branch again.

**Comment by FLO-2DKaren** [comment]
tested
