### ISSUE TITLE
GreenAmptGenerator 

### ISSUE THREAD

**Issue by FLO-2DKaren** [FLO-2DSoftware/qgis-flo-2d-plugin#1311]
Hi Robson,  Check out this video.  I think this is a good idea.

https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/assets/20424460/7dc49c41-8cea-4104-9119-c99da1f16725

**Comment by rpachaly** [comment]
Done on https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/pull/1316

https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/assets/39889306/ee8c0119-6452-42d6-a368-3c53d1d4c029

On the video the OSM group is called Green Ampt Generator, I've changed it to OSM Generator after the video was recorded. I prefer this way.

**Comment by rpachaly** [comment]
![image](https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/assets/39889306/9b6ae16f-c604-4ed9-825d-3111840ba55e)

**Comment by FLO-2DKaren** [comment]
OK I think that seems good Robson.

**Comment by rpachaly** [comment]
I'm going to close this one since it was already merged.
