### ISSUE TITLE
Add help buttons to the widget that don't have them

### ISSUE THREAD

**Issue by FLO-2DJJ** [FLO-2DSoftware/qgis-flo-2d-plugin#1313]
- [x] Grid Tools
- [x] Pre-processing Tools
- [x] Profile Tool
- [x] Cross Section Editor
- [ ] Boundary Conditions Editor
- [x] Initial Conditions Editor
- [x] Rain Editor
- [x] Schematized Channels Editor
- [x] Structures Editor
- [ ] Street Editor
- [x] Floodplain Cross Sections Editor
- [x] Infiltration Editor
- [x] Storm Drain Editor
- [x] Levees and Breach Editor
- [x] Multiple Channels Editor

**Comment by FLO-2DKaren** [comment]
Don't bother with the street editor.

**Comment by FLO-2DJJ** [comment]
> Don't bother with the street editor.

OK
