### ISSUE TITLE
Default buffer for node assigment

### ISSUE THREAD

**Issue by FLO-2DKaren** [FLO-2DSoftware/qgis-flo-2d-plugin#1315]
JJ,

Please default this button to 3ft.  5 ft is too far.  It could accidentally connect to two nodes and we have many cases where nodes are less than 5ft apart.

3ft might even be a little high.

Remember, if you can't find the node, you should modify the point or node location with the snapping tool.

![image](https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/assets/20424460/bf68b6ba-037b-4d57-8003-07b8cb01a487)

**Comment by FLO-2DKaren** [comment]
I updated the documentation with methods on how to fix a buffer for a missing point.

**Comment by FLO-2DJJ** [comment]
> Please default this button to 3ft. 5 ft is too far. It could accidentally connect to two nodes and we have many cases where nodes are less than 5ft apart.

Noted! I’ll address this.
