### ISSUE TITLE
swmmoutf issue

### ISSUE THREAD

**Issue by FLO-2DKaren** [FLO-2DSoftware/qgis-flo-2d-plugin#1327]
Hi JJ,

SWMMOUTF  AllowQ is no longer true false.  It is now 0, 1, or 2

https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/assets/20424460/85d5f269-e266-478f-838c-2e45212b4028

**Comment by FLO-2DJJ** [comment]
@FLO-2DKaren,

Before this

> SWMMOUTF AllowQ is no longer true false. It is now 0, 1, or 2

I had already changed the plugin to remove True/False and change it to 1/0 in all the code related to Allow Discharge. That was according to a previous video you sent to me. I did it in a code that was integrated to pull request https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/pull/1329 

The fact that Allow Discharge is now 0,1,2 is new. Could you please document it, to see the logic behind this change, and adapt it to the code. 

Please, do not merge https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/pull/1329 until this is clarified.

**Comment by FLO-2DKaren** [comment]
0 is off
1 is on but fills the outfall to the rim elevation if the outfall is underground. 
2 is on but not prefilled outfall. You set it to 2 when you want to start dry instead of filled.

**Comment by FLO-2DKaren** [comment]
@FLO-2DJJ Did you see my reply in the preceding comment?

**Comment by FLO-2DJJ** [comment]
Yes @FLO-2DKaren, I saw you comments. I proceed to do the changes with the 3 _AllowQ_ values. 
I'll put the changes on top of this #1329 pull request.
Thanks.
