### ISSUE TITLE
type 4 final issue

### ISSUE THREAD

**Issue by FLO-2DKaren** [FLO-2DSoftware/qgis-flo-2d-plugin#1330]
- [x] Plot not updated when table selected

![image](https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/assets/20424460/70d5adea-5e7b-4175-a16c-eabe32505a8f)

- [x] Remove buttons

![image](https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/assets/20424460/cbe12879-f589-44ab-a87b-24328d3457c6)

- [x] Import without GE number and skip description

![image](https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/assets/20424460/1ee3a4e2-c1ba-4a64-a8af-d688683500e2)

**Comment by FLO-2DKaren** [comment]
- [ ] Trigger this grid to the schema layer.  It was filled by the table but that's not right.

![image](https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/assets/20424460/ec044648-9175-42d9-97db-d047835d7d42)

**Comment by FLO-2DKaren** [comment]
Test Project

[Self Help Kit_v1.0.0.gpkg.zip](https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/files/15322591/Self.Help.Kit_v1.0.0.gpkg.zip)

https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/assets/20424460/54d4ede7-252f-44cf-bf8d-53a02531fc20

**Comment by FLO-2DKaren** [comment]
@rpachaly I put a test project and video for this.

**Comment by rpachaly** [comment]
Thanks Karen, working on this right now.

**Comment by rpachaly** [comment]
Done on https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/pull/1332

https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/assets/39889306/e0b7460e-b61b-4c9f-8dd9-6e9a3ef17ff7

**Comment by FLO-2DKaren** [comment]
Hi Robson. That’s good. Can you reduce the number of messages you have to ok when you delete a the table or culvert data?  If you already did that ignore this. I’m on my phone this morning and the audio was super low.

**Comment by rpachaly** [comment]
> Can you reduce the number of messages you have to ok when you delete a the table or culvert data?

I already closed and merged this issue. I'll do this on the https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/issues/1259 issue
