### ISSUE TITLE
combobox issue storm drain

### ISSUE THREAD

**Issue by FLO-2DKaren** [FLO-2DSoftware/qgis-flo-2d-plugin#1331]
Add a -1 field to these so that they start at NULL and don't try to fill data when pumps or weirs or storage units aren't being used.

![image](https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/assets/20424460/e1362bdb-60f0-4786-87b7-c4d3733577ab)

**Comment by rpachaly** [comment]
This will be addressed along https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/issues/1259. I'm closing this issue.
