### ISSUE TITLE
Vertices group

### ISSUE THREAD

**Issue by FLO-2DKaren** [FLO-2DSoftware/qgis-flo-2d-plugin#1345]
Import / Export the Vertices group in the inp file.
Import data.
Export data comes from links layers.
Look if swmm.io has vertices code.

**Comment by rpachaly** [comment]
Started working on this.

**Comment by rpachaly** [comment]
The vertices code is almost ready. I found a bug that it is not importing one junction on that UEFCC project. 

@FLO-2DKaren do you have another project that have VERTICES? 

Since I got this error with the UEFCC, I want to do more testing.

**Comment by FLO-2DKaren** [comment]
@FLO-2DNoemi 

Noemi,  

Does Metro have VERTICES?

**Comment by FLO-2DNoemi** [comment]
This one has vertices but it is an old project, maybe 2014.  I am searching
for more projects with vertices.

https://www.dropbox.com/scl/fo/qe6sf5i2gro3uujqco5ue/AMRGwvGU0oG1JtlEff3HmI8?rlkey=73i3a9t5fo4xvo99osbmvcqtl&st=94fm9o9j&dl=0

**Comment by FLO-2DNoemi** [comment]
More projects with vertices, these are not our project:

https://www.dropbox.com/scl/fi/p8npr61sr7wsguj49nifb/swmm.inp?rlkey=725qyyuup28ocoiw498vpwwct&st=3v6h5kh7&dl=0

https://www.dropbox.com/scl/fi/f6amfp6iijv1hhobejuhy/swmm.inp?rlkey=p0v37csiuhsl0l4lcnsetn2od&st=eya8aq8d&dl=0

https://www.dropbox.com/scl/fi/3zxvxo50cd382suw5epsq/swmm.inp?rlkey=3zokrysq28lr57hckrxa4u424&st=0mjv7e9t&dl=0

**Comment by rpachaly** [comment]
It is done. Please, see the video:

https://flo-2d.sharefile.com/d-s36c0f6b420404713838db06c37d9aeb0

On PL https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/pull/1366/

**Comment by FLO-2DKaren** [comment]
Might not be an issue but I got this error when I loaded this plugin.

SyntaxError: expected 'except' or 'finally' block 
Traceback (most recent call last):
  File "C:\OSGeo4W/apps/qgis/./python\qgis\utils.py", line 426, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users/User/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\flo2d\__init__.py", line 19, in classFactory
    from .flo2d import Flo2D
  File "C:\OSGeo4W/apps/qgis/./python\qgis\utils.py", line 923, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users/User/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\flo2d\flo2d.py", line 99, in 
    from .gui import dlg_settings, f2d_main_widget
  File "C:\OSGeo4W/apps/qgis/./python\qgis\utils.py", line 923, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users/User/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\flo2d\gui\f2d_main_widget.py", line 25, in 
    from .storm_drain_editor_widget import StormDrainEditorWidget
  File "C:\OSGeo4W/apps/qgis/./python\qgis\utils.py", line 923, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users/User/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\flo2d\gui\storm_drain_editor_widget.py", line 77, in 
    from ..flo2d_ie.swmm_io import StormDrainProject
  File "C:\OSGeo4W/apps/qgis/./python\qgis\utils.py", line 923, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users/User/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\flo2d\flo2d_ie\swmm_io.py", line 1078
    #     self.uc.show_error("ERROR 241121.0529: Reading pump curves from SWMM input data failed!", e)
                                                                                                      ^
SyntaxError: expected 'except' or 'finally' block

**Comment by FLO-2DKaren** [comment]
@FLO-2DNoemi
Do you happen to have the grid system for those?  We can't import them without building a dataset first.
Load them through sharefile if you have them.

**Comment by FLO-2DNoemi** [comment]
For some reason, dropbox linked only the inp. Try the following links and
let me know if it works:

https://www.dropbox.com/scl/fo/trwitz7t079hxjqhhrl6n/AJSJL5n9otSqytYYNG7WRhQ?rlkey=tgy057mkfroo1up3o04czsekf&st=ywm5qngb&dl=0

https://www.dropbox.com/scl/fo/gkyojkobnz6mz2a4ix0re/AGb8vYRYsGhXLq1dXgWcevM?rlkey=40wx8i01k3h542qhcs39p4gp9&st=fcfqdtuh&dl=0

https://www.dropbox.com/scl/fi/k6zmgz866j63i8ddlwxx3/LIBW_South-Current.zip?rlkey=vfj6dc8l27dqjflwbg3v8b0yd&st=9j7wao2r&dl=0

https://www.dropbox.com/scl/fi/8ubm2sgtuugtk1g6vrx6o/150423-North-Model-Current-NGR.zip?rlkey=2pfdedudn9uv298mq3qiobtyj&st=a45y0uly&dl=0

**Comment by FLO-2DKaren** [comment]
@FLO-2DNoemi I'll share that link privately.  This repo is open to anyone.

**Comment by FLO-2DKaren** [comment]
I will take all of Noemi's projects and port them into a geopackage so we can test imports.
