### ISSUE TITLE
h5py in flo2d.py

### ISSUE THREAD

**Issue by FLO-2DKaren** [FLO-2DSoftware/qgis-flo-2d-plugin#1353]
We need to add an conditional statement to h5py import in flopro.py because users won't need that until next year and they can keep using the stand alone installer if they are using the dat export method.

**Comment by rpachaly** [comment]
I'm going to comment that out.

**Comment by rpachaly** [comment]
Now I got it. I'll do the condition statement.

**Comment by rpachaly** [comment]
The h5py is imported in the code this way:

```
try:
    import h5py
except ImportError:
    pass
```

I don't think this will be a problem.

**Comment by FLO-2DKaren** [comment]
We already know this works because we did the same thing on the rain editor.  Closing without testing since I don't have a computer left that doesn't have the network installer.
