### ISSUE TITLE
Nickname

### ISSUE THREAD

**Issue by FLO-2DKaren** [FLO-2DSoftware/qgis-flo-2d-plugin#1358]
We need a nickname for this plugin because FLO-2D Plugin v1.0.0 sounds dumb  Chat GPT liked these options.
You guys have any better ideas.  

FLO-2D Plugin NextGen
FLO-2D Plugin 1X
FLO-2D Plugin Evo
FLO-2D Plugin One
FLO-2D Plugin Prime
FLO-2D Plugin Apex
FLO-2D Plugin Zenith
FLO-2D Plugin Summit
FLO-2D Plugin Phoenix
FLO-2D Plugin Nova

**Comment by FLO-2DKaren** [comment]
I like 1x because it's simple but that's not very cool.

**Comment by FLO-2DNoemi** [comment]
FLO-2D Plugin 1X is fine.

**Comment by FLO-2DJJ** [comment]
I like _FLO-2D Plugin Apex_ or _FLO-2D Plugin Nova_, but I’m not as fond of _FLO-2D Plugin 1X_; it reminds me of the ill-chosen name of Twitter.
I think _FLO-2D Plugin Apex_ will be my choice.

**Comment by rpachaly** [comment]
I would use FLO-2D Phoenix because QGIS suggests to `avoid repeating “plugin” in the name of the plugin itself`

**Comment by FLO-2DKaren** [comment]
What if we used Rivers or bodies of water?
I like Gila.  It's my favorite river.

Cool rivers in Arizona
Gila
Salt
Black
Colorado
