### ISSUE TITLE
Import swmm.inp issue

### ISSUE THREAD

**Issue by FLO-2DKaren** [FLO-2DSoftware/qgis-flo-2d-plugin#1359]
We need to change the swmm_allow_dishcharge default to 0, 1 or 2

The Storm Drain Node table in User layer is still set to false when importing an INP.

https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/assets/20424460/e469d019-2481-4ad0-906c-b0dcf1ebe0db

**Comment by FLO-2DKaren** [comment]
Leave this alone until I meet with Robson.

**Comment by FLO-2DKaren** [comment]
Components Save Message is wrong. 

Move this message to the message bar.

![image](https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/assets/20424460/5a579485-a947-416e-8ccc-2e39119f36f5)

Inlet/Junction node message is wrong message and in the wrong place.
Outfall message not available.
Storage Unit message is OK.

The Conduits save message is in the right place but is the wrong message.
Pumps, weirs, orifices messages all wrong.

**Comment by FLO-2DKaren** [comment]
Should this be integer

![image](https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/assets/20424460/96b03485-72dd-4d24-8f47-a0a22fb43ad4)

**Comment by FLO-2DKaren** [comment]
@FLO-2DJJ 

JJ, Can you fix this?  I want to merge Robson's code into the master and then get you to fix this.  We should be really close to finishing this but Robson's working on SD Control Branch and I think it's easier to merge that with the master so you can branch it yourself.

**Comment by FLO-2DKaren** [comment]
OK JJ, you can branch off the Master to fix this.

**Comment by FLO-2DJJ** [comment]
@FLO-2DKaren,
In the end, should the _swmm_allow_discharge_ default value be 0 or 1? Currently, it is assigned to 0 in the table and wherever a value is missing.

**Comment by FLO-2DNoemi** [comment]
The default value should be zero.

**Comment by FLO-2DKaren** [comment]
JJ   I made a note on the pull request but I'll add it here too .  The messages also need to be fixed.

**Comment by FLO-2DKaren** [comment]
- [ ] Video1 7:20 The pump data is not connecting to the Pump Curves when we import an INP.
- [ ] Video1 7:30 Should we Connect the Type 4 list to the Type 4 table editor when we import an INP.
- [ ] Video 1 Noemi, Can you look at the video at 11:00 and is this OK?

https://flo-2d.sharefile.com/d-sb75c964972254b599da30077371f31dc

**Comment by FLO-2DKaren** [comment]
- [ ] Video 2 7:00 Storage Curve Description not Importing.
- [ ] Video 2 8:15 The Outfall editor seems to be connected to the schematized table.  I think it should be connected to the user table.

https://flo-2d.sharefile.com/d-s6ac638c81c8b4255ad926b964ca3962a
