### ISSUE TITLE
Import old Geopackage

### ISSUE THREAD

**Issue by FLO-2DKaren** [FLO-2DSoftware/qgis-flo-2d-plugin#1360]
We need to add the import geopackage option back into the FLO-2D Plugin Gila.  haha Does that name work???  

I got this feedback from a user today.

I am very impressed with the new  v1.0.0 plugin and think that it is a step in the right direction. However, I found that with the new plugin, there is no option to import data from a geo package; I use this feature a lot as I often set a master project and then import the master project into separate projects that are set up to change parameters used for sensitivity analysis. This saves a lot of time as I do not have to recreate the data saved in the master project and I am not overriding the date within the master project when I do sensitivity analysis. I presume that there is a way to import the geo package created using the new plugin into a new project, but I have not worked this out yet.  Unfortunately, I am not familiar with geo packages and initially thought I could create a master project using the new plugin and then simply copy past the created geo package, rename the geo package (using File Explorer), and then open the renamed geo package in a new project. However, this causes issues because the original QGIS file is saved in the geo package, even after renaming the geo package. 

This is also from the user. It should be a new issue but I want to explore it with him.

The other issue I have with the new plugin is that I cannot schematize the inflow nodes, as the schematize inflow nodes button is always greyed out. I did manage to get this to work once on my home computer, but I cannot get it to work on my work computer. This could be due to a blond moment, but eventually, I gave up and decided to go back to the 0.10.115 plugin.

**Comment by rpachaly** [comment]
Issue 1

It would be great to add a feature like he's describing on the FLO-2D Gpkg Management. The user will be able to create many copies of the geopackage, mainly for calibration or scenarios purposes, and easily open each one by selecting them on the FLO-2D Gpkg Management. This is not complicated to do and we can implement it soon. I just need to add a table to the geopackage to keep track of the geopackages paths.

Issue 2

I know what can be happening and I think it is fixed on the current version master version. Is he using that experimental version, right? But try to explore and see what's really going on.

**Comment by rpachaly** [comment]
I'm going to create something to address issue 1.

**Comment by FLO-2DKaren** [comment]
@rpachaly 
Hi Robson,  Can you take care of this one now?

**Comment by rpachaly** [comment]
Yes! I can take care of this one. I'll just prepare for the Tailings Dam Tool webinar and then I'll do this. Is it okay?

**Comment by FLO-2DKaren** [comment]
OK thanks!!

**Comment by rpachaly** [comment]
Hi Karen,

I added back the import from geopackage code. It is on https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/compare/import_old_gpkg?expand=1

I found a bug on the importing the green and ampt infiltration. This should work fine because it uses the same functions as the port geopackage. I tested in some projects and all seems to be ok.

**Comment by FLO-2DKaren** [comment]
Thanks Robson!!!  That's a very useful tool.  I'm glad to see it back in our toolbox.
