### ISSUE TITLE
Old gpkg Layers issue

### ISSUE THREAD

**Issue by FLO-2DKaren** [FLO-2DSoftware/qgis-flo-2d-plugin#1369]
Hi Robson,

- [x] I'm trying to get a Porting data video for Plugin 1 and I found an issue.  I'm not sure how to approach this but maybe flag old tables and skip them?

We deleted the tables in this video years ago but apparently I'm testing my video on a very old projejct.

https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/assets/20424460/d996b10d-a8a3-46de-89c4-e1606c140b89

Test Project
[Lesson 6 Complete.zip](https://github.com/user-attachments/files/15551630/Lesson.6.Complete.zip)

**Comment by FLO-2DKaren** [comment]
@rpachaly 

I found another one.  Sorry Robson.  You can test this on any project.  Just add a layer, remove the layer then remove the group and load the layer again.

I found this because I was resetting so I could do the video for you.

https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/assets/20424460/6a0445ef-52e5-42b3-a2b6-f39a6efdc34f

**Comment by FLO-2DKaren** [comment]
- [ ] Save issue 3.  Last one I hope.

When you hit Save and say No, you have to say no again and again.  I think we need a way to recognize that the layer is already listed in the qgz file and skip  it and just save.


https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/assets/20424460/94711745-b143-47a2-8cdb-9f9cbea360b7

**Comment by FLO-2DKaren** [comment]
If you need a meeting, let me know.

**Comment by rpachaly** [comment]
>  I'm trying to get a Porting data video for Plugin 1 and I found an issue. I'm not sure how to approach this but maybe flag old tables and skip them?

I added them into a list of 'do_not_port'. If there are more tables like this, let me know.

**Comment by rpachaly** [comment]
> I found another one. Sorry Robson. You can test this on any project. Just add a layer, remove the layer then remove the group and load the layer again.

The solution that I've found for this one is always placing layers added into the project on top of the layer tree. Even if you drag and drop it into a group, it will go to the top. I like this because it will be difficult to add layers and 'lose' them into the groups. Let me know what do you think. If you don't like this approach, I can find another solution.

**Comment by FLO-2DKaren** [comment]
> > I found another one. Sorry Robson. You can test this on any project. Just add a layer, remove the layer then remove the group and load the layer again.
> 
> The solution that I've found for this one is always placing layers added into the project on top of the layer tree. Even if you drag and drop it into a group, it will go to the top. I like this because it will be difficult to add layers and 'lose' them into the groups. Let me know what do you think. If you don't like this approach, I can find another solution.

I think this solution will work but I'll test it as comprehensively as I can.

**Comment by FLO-2DKaren** [comment]
All seems well with my testing.
