### ISSUE TITLE
Window Size Issue

### ISSUE THREAD

**Issue by FLO-2DKaren** [FLO-2DSoftware/qgis-flo-2d-plugin#1374]
I think this window is going to be too big for a laptop.   
I'm going to try and give it some expanders like the cont window.

![image](https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/assets/20424460/e8366dd1-ad96-4204-95c2-65658f92d87a)

**Comment by FLO-2DKaren** [comment]
@FLO-2DJJ 
Do you want this?  If so, please add it to the June milestone

**Comment by FLO-2DJJ** [comment]
See Pull request #1379

**Comment by FLO-2DKaren** [comment]
Change the title to Storm Drain Options please.

**Comment by FLO-2DKaren** [comment]
If you put the advanced options in an expandable window, I think we can remove the checkbox and just use the expander.
Does that make sense?

**Comment by FLO-2DJJ** [comment]
> Change the title to Storm Drain Options please.

Done. See PR #1379

**Comment by FLO-2DJJ** [comment]
> If you put the advanced options in an expandable window, I think we can remove the checkbox and just use the expander. Does that make sense?

It makes sense. Done in PR #1379.
