### ISSUE TITLE
Elevation to gpkg error message

### ISSUE THREAD

**Issue by FLO-2DKaren** [FLO-2DSoftware/qgis-flo-2d-plugin#1376]
I got this message when I added 3 elevation layers to the geopackage.  Maybe it was the Modifed one that caused the issues.  Or any of them.

Test project is to add elevation layer to geopackage.  I'll post a test project below but you should have the elevation files already.

2024-06-11T10:46:43     WARNING    Traceback (most recent call last):
              File "C:\Users/karen/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\flo2d\flo2d.py", line 1053, in flo_save_project
              dlg_gpkg_management.save_layers()
              File "C:\Users/karen/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\flo2d\gui\dlg_gpkg_management.py", line 132, in save_layers
              layer = self.project.mapLayersByName(layer_name)[0]
              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
             IndexError: list index out of range

**Comment by FLO-2DKaren** [comment]
Test Project

[Tailings Dam Project_v1.0.0.gpkg.zip](https://github.com/user-attachments/files/15789895/Tailings.Dam.Project_v1.0.0.gpkg.zip)

**Comment by rpachaly** [comment]
Karen, I tested here with the last master and all worked just fine. I exported the elevation rasters to tiff and added them back to the geopackage and no error arise. I did other small tests of deleting and adding back and also no error was shown.

**Comment by FLO-2DKaren** [comment]
Did you use my test project?  Maybe its something in the way that data is organized.  Try loading that project and then saving any elevation file to it.  Maybe that gpkg is corrupt.

**Comment by FLO-2DKaren** [comment]
I'm closing this until it happens again. I'll rebuild my project and if the issue comes back up, I'll reopen this issue.
