### ISSUE TITLE
h5py reference

### ISSUE THREAD

**Issue by FLO-2DKaren** [FLO-2DSoftware/qgis-flo-2d-plugin#1381]
@FLO-2DJJ 

Hi JJ,

Look through the code and modify any import h5py statement so that if h5py isn't installed, the plugin won't crash.

I think there is one in the storm drain editor widget that isn't referenced correctly.  I actually think we can remove it completely.  I don't think we need import h5py in that code.

Most of the import statements are already fixed.

**Comment by FLO-2DJJ** [comment]
Hi Karen,

Problem addressed in PR #1382. 

Only the **import h5py** in _storm_drain_editor_widget.py_ could cause a crash. I wraped it in a _try.. except_ block, although is doesn`t seam to be used. I left it there just in case.
