### ISSUE TITLE
Float Error

### ISSUE THREAD

**Issue by FLO-2DKaren** [FLO-2DSoftware/qgis-flo-2d-plugin#1383]
TypeError: setValue(self, val: int): argument 1 has unexpected type 'float' 
Traceback (most recent call last):
  File "C:\Users/User/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\flo2d\gui\dlg_inlets.py", line 540, in inlets_tblw_cell_clicked
    self.feature_sbox.setValue(float_or_zero(self.inlets_tblw.item(row, 12)))
TypeError: setValue(self, val: int): argument 1 has unexpected type 'float'

https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/assets/20424460/de549bfb-2075-47dd-8415-b3619d0e06dc

**Comment by FLO-2DKaren** [comment]
Test Project
[Model_12-06-2024_v1.0.0.gpkg.zip](https://github.com/user-attachments/files/15973153/Model_12-06-2024_v1.0.0.gpkg.zip)

**Comment by rpachaly** [comment]
Hi Karen, 

Do you want me to do a quick fix or should I address this on my storm drain editor modification? 

I want to have it done by Friday.

**Comment by FLO-2DKaren** [comment]
Let's go for By Friday with the understanding that we may need to add it to the current version.

**Comment by rpachaly** [comment]
Ok! The modified editor is looking AMAZING.

**Comment by FLO-2DJJ** [comment]
Hi Karen,

Are you using the latest master plugin? The test project you linked doesn't seem to fail with the current master.
Since the project is updated, did you update it when asked?
Just checking those possibilities.

**Comment by FLO-2DKaren** [comment]
I am using the latest master.
I did update the project when asked.
I opened the inlet dialog and then selected row 1.

**Comment by FLO-2DJJ** [comment]
> The error makes sense. The "Feature" parameter isn't a float, it's an integer.

Yes, it makes sense. 
It only needs to change line 540 to:

`self.feature_sbox.setValue(int_or_zero(self.inlets_tblw.item(row, 12)))`

as it is in line 599.

**Comment by rpachaly** [comment]
I fixed it on the branch that I'm working on. Let's keep the issue so we remember to test it.
