### ISSUE TITLE
ARF from old projects

### ISSUE THREAD

**Issue by rpachaly** [FLO-2DSoftware/qgis-flo-2d-plugin#1386]
During my testing on the FBSC project  - porting to the new geopackage and exporting *.DAT files - for the new storm drain editor, I've found that the ARF.DAT files have some differences.

**Comment by FLO-2DKaren** [comment]
AFT.DAT might only have 4 wrf columns in older projects but I think that one should have 8 wrf columns.

**Comment by rpachaly** [comment]
OBS: I did not spent too much time into this yet because I'm focused on wrapping up the sd editor.

**Comment by rpachaly** [comment]
> Did you see this issue with new projects like METRO or North Mesa? The
issue might be in a change of data or format.

Hi Noemi, 

Not tested yet. I'll do soon.

**Comment by FLO-2DNoemi** [comment]
Ok, thanks for the update.

**Comment by FLO-2DKaren** [comment]
@FLO-2DNoemi 

This won't be an issue with newer projects because if ARF = 1, the FLO-2D plugin will automatically make those T lines and Metro and North Mesa didn't use WRFs

**Comment by rpachaly** [comment]
> I think it's OK. It seems to be taking some cells that have an ARF = 1 and making them a T line.

> GDS should never have allowed a ARF = 1 and a WRF less than 1.

Ok, good! I'll close this issue. Thanks Karen!
