### ISSUE TITLE
ComboBox filters

### ISSUE THREAD

**Issue by FLO-2DKaren** [FLO-2DSoftware/qgis-flo-2d-plugin#1387]
Sometimes when I save a shapefile layer to the geopackage, it seems to be missed in the filter box.  I noticed it when working with storm drain, and roughness.  The combo boxes on these are filtered by geometry type and by if a layer has a feature count > 1.

In this case,  I couldn't see LanduseTD in the dropdown list.  I added geometry type multipolygon to the filter but I don't know if I fixed it or if just reloading the project multiple times fixed it.

![image](https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/assets/20424460/924dc995-b5b6-4444-8331-5b7fc49d77d5)

dlg_sampling_mann.py
line 44
old
            if l.geometryType() == QgsWkbTypes.PolygonGeometry:

new
            if l.geometryType() == QgsWkbTypes.PolygonGeometry or QgsWkbTypes.MultiPolygon:

**Comment by FLO-2DKaren** [comment]
It seems to happen after I save the layer to the geopackage.

**Comment by rpachaly** [comment]
I was looking into this issue. The layers that show up on the combobox must be visible (checked on the layer tree). Can you check if this was the issue?

`                
if lyr.layer().type() == 0 and lyr.layer().geometryType() < 3:
    if skip_views and lyr.layer().name() in views_list:
        continue
    else:
        if only_visible and not lyr.isVisible(): <<<<<<---------
            continue
        else:
            l.append(lyr.layer())
`

**Comment by rpachaly** [comment]
The layer must be visible, be a PolygonGeometry and have at least one feature to be shown in that combobox.

**Comment by FLO-2DKaren** [comment]
I don't think that was the issue. It typically happens right after I do a Save and the layers get moved to the External layers group.  They are still visible and checked but they don't show up in the dropdown.  Then when I reload the project, they do show up.

I've noticed this since I started building Storm Drain Tutorials so it's nothing new.

Try this.
1. load clean qgis
2. drag elevation, domain, and nvalue layers onto the map.
3. create geopackage
4. save project
5. create grid
6. calc elevation
7. calc n value  **This is the one that the layer is hidden**


Typically reloading the project sorts this out.

**Comment by rpachaly** [comment]
For some reason it was not understanding that the mannings (or other layers added) have features. I forced a layer.reload() and it fixed this issue. Creating the pull request and merging it. I'll let this issue open for testing purposes.

**Comment by FLO-2DKaren** [comment]
@rpachaly 
I found another one of these yesterday with the Add Walls to User Levee Lines. 
Did the fix it by forcing a reload on all external data or did you fix it where it calls the  filter.  

If it was the filter, can you search the code for those if statements and fix all of them.  I saw another one in my wall example.

**Comment by rpachaly** [comment]
The fix is where it calls the filter. I'll fix it.

**Comment by rpachaly** [comment]
I could not reproduce the bug here, but I added the same fix on the filter. It is on https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/pull/1394 and already merged.

**Comment by rpachaly** [comment]
Ok, I'll look into the code for this kind of filter and add the reload.

**Comment by rpachaly** [comment]
Added on:

- [x] HAZUS
- [x] sampling_tailings
- [x] sampling_tolerance
- [x] storm_drain_shapefile
- [x] infil_green_ampt
- [x] infil_scs
- [x] import_hydraulics

I did not test them individually, but I don't think that adding this reload will cause any type of bug.

**Comment by FLO-2DKaren** [comment]
OK this is good for now.  We'll test these when we redo the New Self Help videos.  I think our next major task is to rebuild the Self Help kit.  I'm going to close this.
