### ISSUE TITLE
Save error message

### ISSUE THREAD

**Issue by FLO-2DKaren** [FLO-2DSoftware/qgis-flo-2d-plugin#1391]
Hi Robson,

The first time you add external data to a project and save, it shows this error:

An error has occurred while executing Python code: 

IndexError: list index out of range 
Traceback (most recent call last):
  File "C:\Users/Karen/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\flo2d\flo2d.py", line 1067, in flo_save_project
    dlg_gpkg_management.save_layers()
  File "C:\Users/Karen/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\flo2d\gui\dlg_gpkg_management.py", line 132, in save_layers
    layer = self.project.mapLayersByName(layer_name)[0]
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range

I consistently see this so I think it is a valid issue.  I don't think it's only happening on my computer.
I have to restart QGIS to get the cursor to stop spinning.
I don't think the error prevents the layer from saving or updating correctly. 



https://github.com/user-attachments/assets/38e4c4cb-1998-4f82-b1e6-84408e278914

**Comment by rpachaly** [comment]
I fixed this bug along with removing the import hdf5 from the storm drain editor widget. It is on: https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/pull/1392

Already tested and merged.

**Comment by FLO-2DKaren** [comment]
Working here.
