### ISSUE TITLE
Structure Attribute not needed

### ISSUE THREAD

**Issue by FLO-2DKaren** [FLO-2DSoftware/qgis-flo-2d-plugin#1395]
This OK Attributes box isn't needed for create a structure.  Because there are no attributes to edit.
If it is easy, remove it.
If it's not easy, let's remove it next year.

![image](https://github.com/user-attachments/assets/1e38a384-0d8e-4998-861c-83aa988e12cf)

**Comment by FLO-2DKaren** [comment]
Idea:
Check the Hydraulic Structures switch when the Schematize button is clicked.

**Comment by rpachaly** [comment]
I did three things on this [pull](https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/pull/1397) request/merge.

1. Removed the Attributes box when adding a feature
2. Check the Hydraulic Structures switch when the Schematize button is clicked
3. Added a signal to recognize when a hydraulic structure is added so there is not need to click on the save button to populate data on the widget

**Comment by FLO-2DKaren** [comment]
Thanks Robson,  If you haven't already, merge it.  I'll test it starting tomorrow.
