### ISSUE TITLE
 Computational Domain and Grid at the top of their respective groups

### ISSUE THREAD

**Issue by rpachaly** [FLO-2DSoftware/qgis-flo-2d-plugin#1398]

**Comment by rpachaly** [comment]
![image](https://github.com/user-attachments/assets/eeb3a50c-d667-46c3-bdfc-9722d7fff1bb)

It is done. It will work only on new or ported geopackages. Done and merged on https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/pull/1399

**Comment by FLO-2DKaren** [comment]
ok and tested
