### ISSUE TITLE
Improve the saving efficiency of the control parameters dialog

### ISSUE THREAD

**Issue by rpachaly** [FLO-2DSoftware/qgis-flo-2d-plugin#1405]

**Comment by rpachaly** [comment]
There was two bottlenecks on the function that saves the control parameters:

1. The control layer had the startEditing() and commitChanges() functions INSIDE the loop that sets the control parameters. Moving them outside the for loop does not impact the saving process and increases the saving speed significantly. 
2. The QCoreApplication.processEvents() is not necessary and was slowing down a bit the function. 

Done and merged on https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/pull/1406

**Comment by FLO-2DKaren** [comment]
Good catch.  Thanks for fixing this.  It was a little annoying.

**Comment by FLO-2DKaren** [comment]
Tested and ok.
