### ISSUE TITLE
TIMDEP results and QGIS

### ISSUE THREAD

**Issue by rpachaly** [FLO-2DSoftware/qgis-flo-2d-plugin#1409]
Email from Noemi:

> Karen and Robson,
> 
> We should be able to read the TIMDEP.HDF5 in the QGIS plugin and by clicking in one FP cell be able to generate a timeseries depth or WSE plot, also be able to export the timeseries results for one cell to an ascii file for postprocessing will be a plus. 
> 
> I do not remember if we talk about this feature before or if you already implement it in the latest plugin, I am sorry I lost track sometimes because of all the changes.
> 
> Noemi

**Comment by FLO-2DKaren** [comment]
I think you could read that from the mesh?  Maybe see how Crayfish does it.  Crayfish is super fast because it isn't reading the text file, it's reading the mesh.

**Comment by rpachaly** [comment]
Yes, Crayfish does this way and I can do that. However, in order to do that you need to first create the mesh file. This methodology that I'm using does not require the mesh.

**Comment by FLO-2DNoemi** [comment]
Robson,

I will check the video and send you my comments.

Noemi

**Comment by FLO-2DKaren** [comment]
Once you get up around 800k cells, the mesh tool's speed becomes very helpful.  It's a super powerful tool.

**Comment by rpachaly** [comment]
The code can work like this:

1. Prints data from mesh
2. Mesh not available. Plots data from TIMDEP.HDF5
3. HDF5 not available. Plots data from TIMDEP.OUT

**Comment by rpachaly** [comment]
Just finished the code for reading from hdf5. It is REALLY fast. Karen, do you have a project with a TIMDEP.HDF5 really huge so I can do more testing?

**Comment by FLO-2DKaren** [comment]
I've got one that is 3.5 gb!!!  We'll need the geopackage.  I'll set up a link and send it.

**Comment by FLO-2DKaren** [comment]
Give it time to upload.  https://flo-2d.sharefile.com/d-s5c20904030d84ff3af63d1a0d5afdc22

The geopackage is in Subdomain 1 and the timdep is in Subdomain 1 Review.

**Comment by rpachaly** [comment]
Thanks Karen, I've got it.

**Comment by rpachaly** [comment]
It takes around 5 seconds for TIMDEP.HDF5 (5.5 gb) and 3 seconds for TIMDEP.HDF5 (3.5 gb).

https://github.com/user-attachments/assets/8c91c20d-5ba4-40c6-aff4-44c9ebf04b15

**Comment by rpachaly** [comment]
https://github.com/user-attachments/assets/95d653f2-ea71-41b6-91f0-ec29127d7b5d

**Comment by rpachaly** [comment]
On https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/pull/1408:

I'll not merge until we decide to move forward with this approach.

**Comment by FLO-2DNoemi** [comment]
This is really good. We can test it and make the decisions. We could also
add other results to HDF5 for project review.

**Comment by FLO-2DKaren** [comment]
Did I do something wrong?  I got an error on trying read timdep.out mesh import.

Uploading timdep_out mesh not loading on plog.mp4…

**Comment by rpachaly** [comment]
Karen, the video did not upload.

**Comment by FLO-2DKaren** [comment]
I think this works fine so I'm closing it here.
