### ISSUE TITLE
Inflow does not schematize

### ISSUE THREAD

**Issue by rpachaly** [FLO-2DSoftware/qgis-flo-2d-plugin#1413]
1. Blank project
2. Add inflow nodes
3. Open the Import .DAT files
4. Add Inflow nodes
5. Hit schematize

**Comment by rpachaly** [comment]
This was a very good bug catch and it could be related to https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/issues/1416.

The function self.gutils.disable_geom_triggers() blocks the geopackage triggers. This is a very handy function and should always be used with the self.gutils.enable_geom_triggers() to re-enabled the disabled triggers. When the import DAT was cancelled, it was not re-enabling the trigger. I fixed that and I'll look for other situations like this in the code. I hope it will fix that combobox on the outflow BC.

**Comment by rpachaly** [comment]
This and that bug related to the outflow boundary condition is solved. I closed https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/issues/1416 to keep the discussion in this issue since both are related. See this video for what I mean in my previous comment. 

https://github.com/user-attachments/assets/512e44d3-e8da-47a3-8c90-dd074610db57

Done and merged on: https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/pull/1426

**Comment by FLO-2DKaren** [comment]
I figured this had something to do with triggers.  But I never figured it was something so easy.  We almost need a turn on triggers button.  I'm going to see if Jonathan can watch this video.  He's pretty savy when it comes to GIS processes.  He'll enjoy this.

**Comment by FLO-2DKaren** [comment]
I'm certain there will still be times when those triggers are disabled and not reenabled.  Let's sort this out on the Boundary Widget where it should have been triggered all along.  

Enable triggers when these buttons are clicked.  

![image](https://github.com/user-attachments/assets/7b4be2d9-d443-4720-a617-51d64b7fe884)
