### ISSUE TITLE
Delete culvert

### ISSUE THREAD

**Issue by rpachaly** [FLO-2DSoftware/qgis-flo-2d-plugin#1414]
Python error when deleting a culvert on the Storm Drain editor.

**Comment by rpachaly** [comment]
The user_swmm_inlets_junctions table does not contain the rt_fid field anymore. This is done by the rt/culvert name and grid number. There were bugs related to this that were fixed and improved.

Fixed and merged on https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/pull/1419

**Comment by FLO-2DKaren** [comment]
tested ok
