### ISSUE TITLE
Storm Drain Components

### ISSUE THREAD

**Issue by rpachaly** [FLO-2DSoftware/qgis-flo-2d-plugin#1415]
Check the AllowQ when importing from external outfalls shapefiles.

**Comment by FLO-2DKaren** [comment]
I'm going to test this one from scratch.  Can you stop loading the storm drain control variables after this assign shapefiles is clicked.  My process is to click the apply nodes before I move on to that tool.

**Comment by FLO-2DKaren** [comment]
Oh I see the issue.  The AllowQ field in my data was abc and the field selector is looking for abc but it needs INT.

![image](https://github.com/user-attachments/assets/4763d761-4943-4a90-9a85-717c891ffff4)

**Comment by rpachaly** [comment]
Karen, I fixed this. However, I could not reproduce that bug that you got during the webinar. I did a code that could have fixed that bug. Can you test it? You can merge it if it passes your testing. 

It is on https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/pull/1421

**Comment by FLO-2DKaren** [comment]
Notes:  This wasn't working because I didn't select the Fixed Stage option on the outfall group.  Robson fixed that.  It had nothing to do with the AllowQ option.

**Comment by FLO-2DKaren** [comment]
Tested and everything seems OK.
