### ISSUE TITLE
Populate outflow combobox

### ISSUE THREAD

**Issue by rpachaly** [FLO-2DSoftware/qgis-flo-2d-plugin#1416]
The combobox is not populated when the whole boundary condition is applied. 

Potential solution: use signals.

**Comment by rpachaly** [comment]
Ok. I think I know how to solve this one. I'm just finishing the sd components.

**Comment by FLO-2DKaren** [comment]
Test project
https://flo-2d.sharefile.com/d-s2815e69e11b44cb5acb157d1ae4423be
