### ISSUE TITLE
Rename the external layer 

### ISSUE THREAD

**Issue by rpachaly** [FLO-2DSoftware/qgis-flo-2d-plugin#1417]
Take out from the no add to geopackage list so every time the file is import , the plugin ask for add or not to the geopackage.

**Comment by rpachaly** [comment]
@FLO-2DKaren this is related to that error that came up when you added some Elevation raster layer, you had to rename it to Elevation 2 or whatever to fix it. Do you remember what you did?

**Comment by rpachaly** [comment]
Ok, I remembered here. You added the layer and saved as user layer, removed that layer and added back to add it to the geopackage and it did not work. I'll fix it.

**Comment by rpachaly** [comment]
Done and merged on https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/pull/1428

**Comment by FLO-2DKaren** [comment]
I'll test this today.

**Comment by FLO-2DKaren** [comment]
Seems OK No issues today.
