### ISSUE TITLE
Storm Drain Profile

### ISSUE THREAD

**Issue by FLO-2DKaren** [FLO-2DSoftware/qgis-flo-2d-plugin#1423]
fix the outfall links.  The profile can't read the outfalls because they are in a new layer.

**Comment by rpachaly** [comment]
This is done on https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/pull/1424

I did not merge it. Can you do some extra testing in this one Karen?

**Comment by FLO-2DKaren** [comment]
Testing now

**Comment by FLO-2DKaren** [comment]
Test passed. Ready to merge.
