### ISSUE TITLE
RT storm drain error

### ISSUE THREAD

**Issue by FLO-2DKaren** [FLO-2DSoftware/qgis-flo-2d-plugin#1430]
https://github.com/user-attachments/assets/223b17f4-5c36-450c-a673-2bffdeafc1fe

**Comment by rpachaly** [comment]
Can you send me the rating table text file?

**Comment by FLO-2DKaren** [comment]
I have other tests too.  This one is old.  I'm finding them now.

**Comment by FLO-2DKaren** [comment]
Here's a test with more than one rating table and some culvert tables too.

[Advanced Storm Drain Shapefiles.zip](https://github.com/user-attachments/files/16392518/Advanced.Storm.Drain.Shapefiles.zip)

**Comment by rpachaly** [comment]
Awesome, I know where the error is.

**Comment by rpachaly** [comment]
Karen, it is done, tested and merged on https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/pull/1431

**Comment by FLO-2DKaren** [comment]
Works good.
