### ISSUE TITLE
Info tool left bank without elevation rastter

### ISSUE THREAD

**Issue by rpachaly** [FLO-2DSoftware/qgis-flo-2d-plugin#1435]
Add an error message showing if it there is no raster data, the tool will not run.

**Comment by rpachaly** [comment]
I saw this during one of our webinars. To replicate, use the Info Tool on the 'Left Bank Line' without an raster in the project. 

It is fixed and merged on https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/pull/1502

**Comment by FLO-2DKaren** [comment]
Working on my project.
