### ISSUE TITLE
RAINCELL.DAT

### ISSUE THREAD

**Issue by rpachaly** [FLO-2DSoftware/qgis-flo-2d-plugin#1436]
I updated the code yesterday (link to download the FLOPRO.exe below). The Raincell.dat file no longer needs to include all the zero rainfall data values for each time record. Each time record should include  the last rainfall value, despite if all rainfall values are zero for that particular time record, see below

NNOD Rainfall: which could be zero.

In other words, therainfall value for the last cells NNOD is required, even if the entire time record is zero. I made this change to avoid altering the file format and to eliminate as many zero values as possible, reducing the file size. Here’s an example:

5 10 7/23/2017 12:05:00 PM 7/25/2017 12:00:00 AM
787137 0.0000   1st time record (5 min)   - rainfall for this time record is zero for all cells but we still need this single line for NNOD Rainfall
4 0.5000             2nd time record (10 min) - note it ends with NNOD 0.000, it always need to see the last grid and rainfall value
5 0.5000
6 0.5000
7 0.5000
8 0.5000
9 0.5000
10 0.5000
787137 0.0000     This is the end of the 2nd time record NNOD 0.000 
2 0.7500             3er time record (15 min)   
4 1.0000
5 1.0000
6 1.0000
7 1.0000
8 1.0000
9 1.0000
23 2.0000
24 2.0000
25 2.0000
26 2.0000
27 2.0000
28 2.0000
787137 0.0000     This is the end of 3rd time record NNOD 0.000
787137 0.0000    4to time record (20 min) - rainfall for this time record is zero for all cells
787137 0.0000    5th to time record (25 min) - rainfall for this time record is zero for all cells

The following is a procedure to double check there are no discrepancies in the updated RAINCELL.DAT and reading the rainfall:

Step 1. Run the RAINCELL project example with the  RAINCELL.DAT   file including the zero rainfall values, let me know if you do not have this example and I will send it to you. Check the RainCell.CHK file, this shows the total rainfall for each grid cell and the average total rainfall over the grid.

Step 2. Modified the plugin and exported the new RAINCELL.DAT file so this file does not include the rainfall zero values, but includes at least one (NNOD -RAINFALL:  787137 0.0000) for those time records with no rainfall. Then run the project (nex FLOPRO.exe, see link below) with the new RAINCELL.DAT (no zeros) and compare that totals for each cell and the average are the same (RainCell.CHK) as step 1.

**Comment by rpachaly** [comment]
Also any rainfall zero value at the beginning of a time record or in the middle of two non zero rainfall values should work, see red lines below. 

5 10 7/23/2017 12:05:00 PM 7/25/2017 12:00:00 AM
1  0.0000            1st time record (5 min) - Starts  - This line  is not necessary but it will be read
787137 0.0000   1st time record (5 min) - Ends - This line is necessary for each time record   
4 0.5000             2nd time record (10 min) - note it ends with NNOD 0.000, the file always need to have the last grid and its rainfall value
5 0.5000
6 0.5000
7 0.5000
8 0.5000
9 0.5000
10 0.5000
11 0.0000       This line  is not necessary but it will be read
25 0.0000        This line  is not necessary but it will be read
787137 0.0000     This is the end of the 2nd time record NNOD 0.000 

The only condition is that for each time record we should at least have NNOD Rainfall, disregarding if all the rainfall values are zero or not.  This line identifies the end of a particular time record. All time records should be printed, see another example in green below.

SIMUL=1 hr - 60 min  NNOD=1589
First line of RAINCELL.DAT
RAININTIME= 1 min  IRINTERS= 60 time intervals     7/23/2017 12:05:00 PM 7/25/2017 12:00:00 AM
IRAINDUM(I)  RRGRID(I,K)
1589 0.0000  1st time interval 
1589 0.0000  2nd time interval 
.
.           All time intervals data need to be added, those with rainfall equal to zero needs only one line  1589 0.0000
1589 0.0000  15th time interval
1  0.0020       16th time interval - Starts 
2   0.0015
15   0.0025
45   0.0055
68   0.0028
1589 0.0000  16th time interval - Ends 
1589 0.0000  17nd time interval 
1589 0.0000  18th time interval 
.
.
.           All time intervals data need to be added, those with rainfall equal to zero only needs one line:  1589 0.0000 
.
1589 0.0000  60th time interval 
End of the file

**Comment by FLO-2DKaren** [comment]
@FLO-2DNoemi 

What if someone is trying to use an old engine?  Should we add a warning?

**Comment by FLO-2DNoemi** [comment]
It should be compatible. Updated FLOPRO.exe read and use RAINCELL.DAT with
all zeroes or with no zeroes.

The new plugin should also load both versions of the file.

Old plugins will only read the old version.

Does this make sense?

**Comment by FLO-2DKaren** [comment]
The old engines will still be able to read the new format?

It doesn't make sense because you said Updated FLOPRO.exe read.  Doesn't that prevent old engines from reading the file?

**Comment by FLO-2DNoemi** [comment]
No, not at all. Old engines will not read the new format. I see your point
now, the plugin Gila should give the warning.

**Comment by FLO-2DKaren** [comment]
OK now we are on the same page.  

Maybe Robson can write give the user the option to export the old method, new method, or hdf5 method.

**Comment by rpachaly** [comment]
Yes, a dialog suggesting which method to use can solve this issue. Something like:

If your FLOPRO.exe version is less than XX.XX.XX, you should use the old RAINCELL.DAT format. Otherwise, it is suggested to use the new RAINCELL.DAT format for a smaller file. 

New RAINCELL.DAT format/Old RAINCELL.DAT format/Cancel

Feel free to improve it

**Comment by FLO-2DKaren** [comment]
The message is good.  We can also read their plugin version from metadata and if it is old, we can help guide them.

**Comment by rpachaly** [comment]
We can only show this message if the FLOPRO.exe version is not the latest.

**Comment by rpachaly** [comment]
@FLO-2DKaren @FLO-2DNoemi 

On https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/pull/1445

https://github.com/user-attachments/assets/cf9567eb-5b36-4062-b8f9-f53751e06668

**Comment by FLO-2DNoemi** [comment]
This is good. We need to add the date:  Old Raincell.dat: use this format
if your FLOPRO.exe build id earlier than 23.10.25 Date 8-1-2024.

**Comment by FLO-2DKaren** [comment]
I always recommend building the realtime rainfall data on a skeleton model.  I'm glad you see that as a good process too.
Out of curiosity, what is the geopackage size when you finish the processing? 

The only thing I don't like about this method is that it seems counter productive.
I would hope that People are using raincell.hdf5 which is far superior method.
  
FCDMC is testing raincell.dat on old projects just to make sure there is consistency with new engines. I don't think they are going to be exporting raincell.dat in the future.  They will be exporting raincell.hdf5.

I believe a better tool would be to convert current raincell.dat files into raincell.hdf5.

I just realized this as I was watching the video.  I should have realized it during our meeting.

**Comment by rpachaly** [comment]
> This is good. We need to add the date:  Old Raincell.dat: use this format
> if your FLOPRO.exe build id earlier than 23.10.25 Date 8-1-2024.

I added this to the versioning when we create a geopackage or port it. What I mean by that is we can identify this 8-1-2024 version and only show this message if it is newer than this version. We discussed that but I forgot to add it. 

> Out of curiosity, what is the geopackage size when you finish the processing?

gpkg without RealTime Rainfall: 22.6 mb
gpkg with RealTime Rainfall: 312.6 mb

**Comment by FLO-2DNoemi** [comment]
OK, perfect. Thanks.

Karen's comment is something that we definitely need to add to the plugin:
I believe a better tool would be to convert current raincell.dat files into
raincell.hdf5.

**Comment by rpachaly** [comment]
I added your comments.

https://github.com/user-attachments/assets/692f9182-9bd8-4c1b-a74c-7b9835bde77d

**Comment by FLO-2DNoemi** [comment]
I think this is good. Thanks for sending the video. It makes the process
clear to me.

**Comment by FLO-2DKaren** [comment]
I finished my testing.
