### ISSUE TITLE
Duplicate Layer Issue

### ISSUE THREAD

**Issue by FLO-2DKaren** [FLO-2DSoftware/qgis-flo-2d-plugin#1437]
https://github.com/user-attachments/assets/c7bc58ee-f801-4b28-9924-7061c792b316

**Comment by rpachaly** [comment]
Got it. Easiest solution is to rename it to Hydraulic Structures (2) or something. And a bar message showing that FLO-2D does not allow layers with the same name.

**Comment by FLO-2DKaren** [comment]
I agree

**Comment by rpachaly** [comment]
Done on https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/pull/1439. See the video. 

https://github.com/user-attachments/assets/d42d1590-b8e2-4f78-a306-31fed8153d62

**Comment by rpachaly** [comment]
Noemi got the error while loading an old geopackage

**Comment by rpachaly** [comment]
A path error was causing the error Noemi got. It is fixed. I'm not going to merge this because it was buggy last time. Needs more testing.

Done on https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/pull/1460

**Comment by FLO-2DKaren** [comment]
I tested this with a speed run, No issues.
