### ISSUE TITLE
import hfpy

### ISSUE THREAD

**Issue by FLO-2DKaren** [FLO-2DSoftware/qgis-flo-2d-plugin#1440]
We missed an import h5py exception:

  File "C:\Users/matt.murray/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\flo2d\gui\grid_tools_widget.py", line 16, in
    import h5py

Change to 

try:
    import h5py
except ImportError:
    pass

**Comment by rpachaly** [comment]
Addressed onhttps://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/pulls

**Comment by rpachaly** [comment]
Done on https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/pull/1443
