### ISSUE TITLE
Pandas library

### ISSUE THREAD

**Issue by rpachaly** [FLO-2DSoftware/qgis-flo-2d-plugin#1441]
Check the QGIS python distribution pandas library and make a try/except to avoid bugs when importing this library.

**Comment by FLO-2DKaren** [comment]
Since Pandas is kind of slow, you should look at the LiDAR interpolator code.  I believe it uses a different method to build array data than Pandas.

**Comment by rpachaly** [comment]
Default QGIS libraries:

qt5: https://github.com/qgis/QGIS/blob/master/.docker/qgis3-qt5-build-deps.dockerfile

qt6: https://github.com/qgis/QGIS/blob/master/.docker/qgis3-qt6-build-deps.dockerfile

**Comment by rpachaly** [comment]
I converted the pandas data frame to a numpy array. And fixed another issue of adding a mesh layer with only the TIMDEP.OUT

Done and merged on https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/pull/1453

**Comment by FLO-2DKaren** [comment]
I'm closing this. I'll add my comments on the other related issue.
