### ISSUE TITLE
Boundary Bug and Structures Optimization

### ISSUE THREAD

**Issue by FLO-2DKaren** [FLO-2DSoftware/qgis-flo-2d-plugin#1444]
Hi Robson,

A client showed me this project yesterday and it has one bug and one optimization issue.

Boundary cells are being set to the wrong bc fid.

Structure schema is taking around 40 seconds.

https://flo-2d.sharefile.com/d-se4fc163153114d00b1ab2c5d0adc356c

**Comment by rpachaly** [comment]
The schematize structures optimization is done. It was performing a complex SQL query to find out the structure's inlet and outlet. I used a simpler approach and the schematize is practically instantaneous. I also did some improvements on he messages log. Done and merged on https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/pull/1447

**Comment by rpachaly** [comment]
The BC bug will be addressed in another branch.

**Comment by FLO-2DKaren** [comment]
Updated Project  https://flo-2d.sharefile.com/d-sbd33e2d42dd24391bae9d53e0c900b73

**Comment by rpachaly** [comment]
Karen, it is done on https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/pull/1450

I did not merge, if you want to merge it for your testing is ok.

**Comment by FLO-2DKaren** [comment]
works on many different projects
