### ISSUE TITLE
EPA SWMM Link

### ISSUE THREAD

**Issue by FLO-2DKaren** [FLO-2DSoftware/qgis-flo-2d-plugin#1446]
Add a Run SWMM GUI link to the Run FLO-2D group for our next release.

We'll be updating FLO-2D installer to move the epa swmm tools into the FLO-2D Pro folder. 

This should prevent the issues where people are using newer or older versions of EPA SWMM.

**Comment by rpachaly** [comment]
Done and merged on https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/pull/1449

![image](https://github.com/user-attachments/assets/f0f37965-51db-4ea8-af6c-c4bc1cbc52e2)

**Comment by FLO-2DKaren** [comment]
@rpachaly Quick Reminder
If Epaswmm5.exe isn't in the FLO-2D folder, look for it here:

C:\Program Files (x86)\EPA SWMM 5.0

Old installers will have it here.

**Comment by rpachaly** [comment]
> If Epaswmm5.exe isn't in the FLO-2D folder, look for it here:
> 
> C:\Program Files (x86)\EPA SWMM 5.0
> 
> Old installers will have it here.

Done and merged on https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/pull/1451

**Comment by FLO-2DKaren** [comment]
works on multiple computer types even when epaswmm50 is inside flopro folder
