### ISSUE TITLE
swmm.inp and swmmflo.dat order

### ISSUE THREAD

**Issue by FLO-2DKaren** [FLO-2DSoftware/qgis-flo-2d-plugin#1448]
swmmflo.dat and swmm.inp and swmmoutf.dat not in the same order.

**Comment by FLO-2DKaren** [comment]
https://flo-2d.sharefile.com/d-sabedf8adc88941f59a876b9e582b16c5

**Comment by rpachaly** [comment]
This is done on https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/pull/1452

I did not merge it. I'll let you decide to merge when you test it.

**Comment by FLO-2DKaren** [comment]
Seems OK.  It was running good on the self help kit.  I still have a couple more tests but I'll close this because it's working as expected.
