### ISSUE TITLE
Test for 8-5-2024

### ISSUE THREAD

**Issue by FLO-2DKaren** [FLO-2DSoftware/qgis-flo-2d-plugin#1454]
Boundary editor test complex boundary and multi boundary
- [x] complex boundary 
- [x] Mult domain boundary

Storm Drain Editor
- [x] Create from shapefile
- [x] import inp
- [x] import dat 
- [x] Finish review video

Structure Editor Speed
- [x] self help kit
- [x] speed
- [x] create
- [x] import

EPA swmm button
- [x] test on default install
- [x] test FLO-2D Install new install

h5py
- [x] Test on stand alone installer

Raincell
- [x] QGIS lesson 5 test 
- [x] Run raincell.dat
- [x] Run raincell.hdf5
- [x] Run raincellnew.dat
- [x] Compare depfp.out, depth.out
- [x] Review raincell.chk
- [x] Time test on large model

Duplicate layers
- [x] load a layer called hydraulic structures.shp and then save the layer.
- [x] Remove the layer
- [x] Test separate branch first (don't merge)

Pandas

- [x] Test on a stand alone installation
- [x] 2D plot time
- [x] Test hdf5 
- [x] Test with timdep.out
- [ ] Test mesh hdf5
- [x] Test mesh with timdep.out
- [ ] Test mesh with old engine

**Comment by rpachaly** [comment]
I'm still working on the duplicate layers!

**Comment by FLO-2DKaren** [comment]
Channel inflow cannot have a negative slope.  We need to add this to the channel check.

**Comment by FLO-2DKaren** [comment]
Default the Channel Profile 
Bed elevation
Left bank
right bank
water elevation

**Comment by FLO-2DKaren** [comment]
The ARF/WRF calculator on the self help kit seems to be dragging on after the progress bar closes.  This could be my fault.

**Comment by FLO-2DKaren** [comment]
Walls still need to be inside user layers or they won't work.

**Comment by FLO-2DKaren** [comment]
I did a speed run on the Self Help Kit.  it takes 41 min for me to complete it.

**Comment by FLO-2DKaren** [comment]
Quick run.  When you hit cancel, it runs anyway.

**Comment by FLO-2DKaren** [comment]
I'm getting a python error when I remove a layer but I don't have a FLO-2D GeoPackage connected.
