### ISSUE TITLE
Channel inflow cannot have a negative slope

### ISSUE THREAD

**Issue by rpachaly** [FLO-2DSoftware/qgis-flo-2d-plugin#1455]
Channel inflow cannot have a negative slope.  We need to add this to the channel check.

_Originally posted by @FLO-2DKaren in https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/issues/1454#issuecomment-2269807247_

**Comment by rpachaly** [comment]
![image](https://github.com/user-attachments/assets/3ac0dc7b-b4f0-4555-8b3a-6ca01783b3d7)

Done & merged on https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/pull/1462

**Comment by FLO-2DKaren** [comment]
OK seems good.
