### ISSUE TITLE
Default the Channel Profile

### ISSUE THREAD

**Issue by rpachaly** [FLO-2DSoftware/qgis-flo-2d-plugin#1456]
Default the Channel Profile 
Bed elevation
Left bank
right bank
water elevation

_Originally posted by @FLO-2DKaren in https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/issues/1454#issuecomment-2269817381_

**Comment by rpachaly** [comment]
Done and merged on https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/pull/1461

**Comment by FLO-2DKaren** [comment]
This seems OK to me.
