### ISSUE TITLE
Walls still need to be inside user layers

### ISSUE THREAD

**Issue by rpachaly** [FLO-2DSoftware/qgis-flo-2d-plugin#1457]
Walls still need to be inside user layers or they won't work.

_Originally posted by @FLO-2DKaren in https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/issues/1454#issuecomment-2269849987_

**Comment by rpachaly** [comment]
To solve this issue, I had to set the groups=None in the save_edits_and_proceed function. This impacts the following layers:

- Levee Lines
- Computational Domain
- Elevation Points
- Elevation Polygons
- Blocked Areas
- Roughness
- Tolerance Areas
- Froude Areas
- Shallow-n Areas
- Gutter Lines
- Gutter Areas
- No-Exchange Channel Cells
- Street lines

By impact I mean that they don't need to be inside any group to perform its processes. Which I think is OK because of the duplicate layer code. Let me know what you think. 

Done on https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/pull/1465

**Comment by FLO-2DKaren** [comment]
OK I'll do a rapid run through self help kit to see if anything comes up.

**Comment by FLO-2DKaren** [comment]
![walls error](https://github.com/user-attachments/assets/ad2a5647-b551-42fa-b9ec-46949ec957d8)

error message
ERROR 051218.1146: couldn't load point or/and line layers!
__________________________________________________

Error:
   AttributeError: 'NoneType' object has no attribute 'type'

In file:
   C:\Users/Karen/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\flo2d\gui\dlg_walls_shapefile.py

In function:
   setup_layers_comboxes

On line 87:
^^^^^^^^^^^^^^^^

**Comment by FLO-2DKaren** [comment]
Maybe we should put this back.

**Comment by rpachaly** [comment]
I cannot reproduce the bug here. Can you send me the geopackage?

I'm investigating the code and I don't think this is related to the changes that I did on https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/pull/1465. Maybe it is another issue.

**Comment by FLO-2DKaren** [comment]
It was a fluke.  Working fine now.

**Comment by rpachaly** [comment]
I'm going to close this issue
