### ISSUE TITLE
Weir End Contraction is int

### ISSUE THREAD

**Issue by FLO-2DKaren** [FLO-2DSoftware/qgis-flo-2d-plugin#1468]
The end contraction variable is supposed to be int with limited values of 0, 1, or 2.

![image](https://github.com/user-attachments/assets/85aa67dc-4040-488d-b7ed-2f87a7095fde)

**Comment by FLO-2DKaren** [comment]
It export works and the inp still runs but the import finds a bug because it's a zero or int.

Choices
Fix the export code or fix the dialog box or fix the import code.

**Comment by rpachaly** [comment]
Done and merged on https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/pull/1476

Tested on import, changing the weir end contraction, and on the export.

**Comment by FLO-2DKaren** [comment]
One more Bad Message.


https://github.com/user-attachments/assets/87d7e5a8-2b21-49cc-ac0d-d6ec8390f5b4

* To complete the Storm Drain functionality, the 'Computational Domain' and 'Storm Drains' conversion must be done using the Convert Schematic Layers to User Layers tool in the FLO-2D panel...


* To complete the Boundary Conditions functionality, the 'Boundary Conditions' conversion must be done using the Conversion from Schematic Layers to User Layers tool in the FLO-2D panel.

**Comment by rpachaly** [comment]
Karen, I'm referencing this into another issue. If you already tested this weir bug, let's close this issue.

**Comment by FLO-2DKaren** [comment]
Closing because test was OK.
