### ISSUE TITLE
Change Import Message

### ISSUE THREAD

**Issue by FLO-2DKaren** [FLO-2DSoftware/qgis-flo-2d-plugin#1469]
Change message to this:
 
 * To complete the user layer functionality, use the Convert Schematic Layers to User Layers tool in the FLO-2D panel...

Run the tool when OK is clicked.

![image](https://github.com/user-attachments/assets/68771cc4-36d8-44a3-881f-fa83f3001ca3)

**Comment by rpachaly** [comment]
I particularly don't like this message. Can I remove? I'll set always to yes.

![image](https://github.com/user-attachments/assets/8a5c6421-bf26-425f-a60f-f0ad26524e37)

**Comment by FLO-2DKaren** [comment]
You can remove it. But maybe see where we need row  cols  


I don’t typically fill those but they are required by some processes like poly2polygeos or lidar.

**Comment by rpachaly** [comment]
I'm thinking here... What if we automatize this whole process? For instance, if the user imports hydraulic structures, the schema to user process will be performed automatically behind the scenes.

**Comment by FLO-2DKaren** [comment]
Sounds good to me!!!

**Comment by FLO-2DKaren** [comment]
But do t do channels or levees

**Comment by rpachaly** [comment]
https://github.com/user-attachments/assets/89a2806e-6e87-4bbd-91b4-d4d0febe3ab7

**Comment by FLO-2DKaren** [comment]
Please be careful with this because one method wipes out the User Layers and the single method doesn't wipe out the data
The full method always imports grid and that is very time consuming.
Single method is very handy and I use it consistently when I am building models. 

Now is not the time to rebuild this system. Let's get the bugs patched so we can release on QGIS repo.

**Comment by rpachaly** [comment]
This was addressed on https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/pull/1484
