### ISSUE TITLE
Convert Hydraulic Structures

### ISSUE THREAD

**Issue by FLO-2DKaren** [FLO-2DSoftware/qgis-flo-2d-plugin#1471]
Convert hydraulic structures is deleting the structures.

Test it by importing self help and then converting structures.

**Comment by FLO-2DKaren** [comment]
This one might have happened when you fixed the slow code.  I bet the slow code happened when you added the convert structures.

**Comment by FLO-2DKaren** [comment]
https://github.com/user-attachments/assets/f7f5e489-6fa4-420d-b389-9c3c79a5012c

**Comment by FLO-2DKaren** [comment]
Status?

**Comment by rpachaly** [comment]
Working on it. Can we have a meeting?

**Comment by FLO-2DKaren** [comment]
I'm closing this issue because the bug is fixed but I'll build a new issue with another thing I found that will be an enhancement.
