### ISSUE TITLE
Inflow Line

### ISSUE THREAD

**Issue by FLO-2DKaren** [FLO-2DSoftware/qgis-flo-2d-plugin#1473]
Let's use a line to split and distribute an inflow hydrograph.

Divide the flow by the number of cells in the line.

**Comment by FLO-2DKaren** [comment]
2025 development

**Comment by rpachaly** [comment]
Same as https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/issues/1604. Closing this one.
