### ISSUE TITLE
Import from gpkg 

### ISSUE THREAD

**Issue by rpachaly** [FLO-2DSoftware/qgis-flo-2d-plugin#1479]
Error Message 1:

1. Create a “Master” FLO-2D project with a defined grid.
2. Create a “Working” FLO-2D project.
3. Create an external layer (shape file) in the “Working” FLO-2D project.
4. Save the  “Working” FLO-2D project and opt to save the external layer to the GeoPackage. The external layer is then saved to the GeoPackage as a named group called “External Layers”. See the screenshot below.
5. Import the project data from the “Master” FLO-2D project using the “Import from GeoPackage” function.
6. Immediately after Step 5, I get an error message (Error Message 1 attached).

**Comment by rpachaly** [comment]
Error Message 2:

1. Create a “Master” FLO-2D project with a defined grid.
2. Create a “Working” FLO-2D project.
3. Import the project data from the “Master” FLO-2D project using the “Import from GeoPackage” function.
4. Create an external layer (shape file) in the “Working” FLO-2D project.
5. Save the  “Working” FLO-2D project and opt to save the external layer to the GeoPackage.
6. Following step 5, the external layer is not saved to the GeoPackage, and I get an error message (Error Message 2 attached).

**Comment by FLO-2DKaren** [comment]
Error Message 1
![Error Message 1](https://github.com/user-attachments/assets/2c338f12-a5b0-48dd-975a-f0f6a3b51ba3)

Error Message 2
![Error Message 2](https://github.com/user-attachments/assets/aa1c323c-0a9e-452e-b648-b5cf79598bf3)

**Comment by rpachaly** [comment]
This was a very nice bug catch. I created a pull request on https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/pull/1481

Error 1:

Really easy to fix. One variable inside a SQL command was not inside "". The layer name was being read as separate variables and throwing the error.  That's why the SD was on the error message. 

Error 1a: 

Found an issue while fixing Error 1. The shapefile added to the geopackage was getting all elements deleted. Now it is fixed. 

Error 2: 

The metadata was being overwritten by the imported gpkg. That was causing a bunch of bugs. This was fixing by not overwriting the metadata.

**Comment by FLO-2DKaren** [comment]
When I use the import method, I get this.

![image](https://github.com/user-attachments/assets/f0a68c1f-0495-476a-8c24-49b97520f8a7)

Doesn't seem to hurt anything.

**Comment by FLO-2DKaren** [comment]
I just did an import on a clean project and I confirm that you get 2 QGIS projects in the GeoPackage list.

**Comment by FLO-2DKaren** [comment]
I deleted the record out of QGIS projects and the second listing went away.
