### ISSUE TITLE
Create Grid - Elapsed Time

### ISSUE THREAD

**Issue by rpachaly** [FLO-2DSoftware/qgis-flo-2d-plugin#1487]
See if the elapsed time printed on the dialog is correct. 

I think it is not considering the check time.

**Comment by rpachaly** [comment]
Did a small change. May not change a lot, but it is better. Done and merged on https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/pull/1500

**Comment by FLO-2DKaren** [comment]
Seems OK.  I didn't see any issues on 2 different projects.
