### ISSUE TITLE
Oufall Import Issue

### ISSUE THREAD

**Issue by FLO-2DKaren** [FLO-2DSoftware/qgis-flo-2d-plugin#1488]
Outfalls not importing correctly and possibly not schematizing.

Data here:

https://flo-2d.sharefile.com/d-s8218e6443bfd4aaa8585bb3ce334625a

**Comment by rpachaly** [comment]
Hi Karen, 

It is fixed on https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/pull/1491

It took me while because I did a bunch of small fixes on some messages, you will these changes during your testing.

**Comment by rpachaly** [comment]
Testing:

- [ ] Wrong names on SWMMOUTF
- [ ] Importing without SWMM.INP

**Comment by FLO-2DKaren** [comment]
My test was on Ian Subdomain 1 went good.  I'm closing this.  
I imported just swwmoutf.dat and then exported it.  All OK.
