### ISSUE TITLE
Schema2User default chan levee off

### ISSUE THREAD

**Issue by FLO-2DKaren** [FLO-2DSoftware/qgis-flo-2d-plugin#1489]
Default channels and levees off.  
I think we can fix these later but for now they should be off.

![image](https://github.com/user-attachments/assets/6bf5a59b-696f-4f96-af55-bb3b6eed4016)

**Comment by rpachaly** [comment]
Done and merged on https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/pull/1501

During my testing I noticed that the right channel bank is not converted to user layer. Why is that?

**Comment by FLO-2DKaren** [comment]
Tested multiple times.  I never use this converter so I think that was just an oversight from the preliminary development.
