### ISSUE TITLE
New buttons 2025

### ISSUE THREAD

**Issue by FLO-2DKaren** [FLO-2DSoftware/qgis-flo-2d-plugin#1490]
![image](https://github.com/user-attachments/assets/2fa4b070-dc26-4b23-8c22-5c8f73409536)

**Comment by rpachaly** [comment]
![image](https://github.com/user-attachments/assets/1314acc8-eeb4-4ffc-a940-68360c03e6b6)

**Comment by rpachaly** [comment]
I added the buttons on the top. The Project Folder on the bottom is not implemented yet. I'll not merge it, don't think we'll have merging problems on the future. On https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/pull/1540.

![image](https://github.com/user-attachments/assets/e2efb552-e4cd-4f3c-94ac-78a0b1c85397)

**Comment by FLO-2DKaren** [comment]
Tested on merged plugin.  I moved the project folder to a new image so I can close this one.
