### ISSUE TITLE
Wall Issue

### ISSUE THREAD

**Issue by FLO-2DKaren** [FLO-2DSoftware/qgis-flo-2d-plugin#1494]
Wall memory may cause an issue when used the first time on a clean profile.

**Comment by FLO-2DKaren** [comment]
Try this test.
1. Create a new profile and install FLO-2D Gila.
2. Load a fresh project and get far enough along to build a wall.

The issue is I saw was that the wall dialog didn't recognize any line layers until I restarted twice.  

I wonder if this is because it was looking for the memory.  
Note that the memory for this layer is being written to QGIS memory not to the Geopackage.

**Comment by FLO-2DKaren** [comment]
And I also noticed that the walls still need to be inside the User layers.  I think we should look at the branches because I might have missed a branch.

Or maybe we abandoned that method and I'm ok with that since the error message states that the layer should be inside the user layers.

**Comment by FLO-2DKaren** [comment]
Remove the check for walls.

Error:
   AttributeError: 'NoneType' object has no attribute 'layer'

In file:
   C:\Users/User/AppData/Roaming/QGIS/QGIS3\profiles\Clean/python/plugins\flo2d\gui\dlg_walls_shapefile.py

In function:
   create_user_levees_from_walls_shapefile

On line 227:

**Comment by rpachaly** [comment]
The check is removed. Done and merged on https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/pull/1498

Did some tests and all good.

**Comment by FLO-2DKaren** [comment]
OK my test passed too.
