### ISSUE TITLE
SD Drop Box and Clogging Factor Import 

### ISSUE THREAD

**Issue by FLO-2DKaren** [FLO-2DSoftware/qgis-flo-2d-plugin#1496]
I'll populate the comments in a sec.  Just uploading the projects

**Comment by FLO-2DKaren** [comment]
Project and video on Sharefile.
https://flo-2d.sharefile.com/d-s81787155bc49492c8b7225d2cc4b8419

**Comment by rpachaly** [comment]
Karen, all is finished on the branch https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/tree/outfall-import

Do your testing on the branch, all import methods should be working fine and the allow_q error should be fixed.

**Comment by FLO-2DKaren** [comment]
The swmmflodropbox file is written in a different order than the others.  The others export the data in alphabetical order.  I don't know if this is important.

**Comment by FLO-2DKaren** [comment]
Important **This fix is overwriting swmmflo.dat data.**

**Comment by FLO-2DKaren** [comment]
We didn't know this because the schema layers are still good. But when you ID a feature, it is empty.

![image](https://github.com/user-attachments/assets/7fe7b0a6-6c2b-4d27-bf76-67972173accc)

**Comment by rpachaly** [comment]
On the github testing that I'm developing, the SWMMFLORT is also not being exported correctly.

**Comment by FLO-2DKaren** [comment]
That test may be pre generalized culvert

**Comment by FLO-2DKaren** [comment]
Test step
Export a project with clogging and dropbox
import the same data files
Look at Inlet's and Junctions user data.

**Comment by rpachaly** [comment]
Karen, it is working. Since I changed the order of import INP and SWMMFLO, the SWMMFLO must be updated on the SD user layers. Done and merged on https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/pull/1508

**Comment by FLO-2DKaren** [comment]
Tested and working.
