### ISSUE TITLE
SD Outfall Schema Issue

### ISSUE THREAD

**Issue by FLO-2DKaren** [FLO-2DSoftware/qgis-flo-2d-plugin#1497]
Outfall allowQ prevents schematizing an imported inp.

**Comment by FLO-2DKaren** [comment]
Here's the project https://flo-2d.sharefile.com/d-s7b89f0cf970b47c1a7107f68841da158

**Comment by rpachaly** [comment]
Addressed on https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/issues/1496
