### ISSUE TITLE
Import Geopackage Minor Issue

### ISSUE THREAD

**Issue by FLO-2DKaren** [FLO-2DSoftware/qgis-flo-2d-plugin#1504]
Import a geopackage once and it has one project inside it.  

The table is qgis_projects

Just skip the project that isn't the new project name.

**Comment by rpachaly** [comment]
Done and merged on https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/compare/gpkg-qgis-project?expand=1

**Comment by FLO-2DKaren** [comment]
OK Tested and working.
