### ISSUE TITLE
Extra Dat files for new and improved tests

### ISSUE THREAD

**Issue by FLO-2DKaren** [FLO-2DSoftware/qgis-flo-2d-plugin#1505]
https://flo-2d.sharefile.com/d-s93f5603536f540e484ad21a5b1721489

Here is a nice test with
arf.dat  no collapse
fpfroude.dat
fpxsec.dat
mult.dat
shallown_spatial.dat
simple_mult.dat
tolspatial.dat

**Comment by FLO-2DKaren** [comment]
This is a great project to add some mudflow and sediment data to.

**Comment by rpachaly** [comment]
> Here is a nice test with
> arf.dat no collapse
> fpfroude.dat
> fpxsec.dat
> mult.dat
> shallown_spatial.dat
> simple_mult.dat
> tolspatial.dat

This one is added.

**Comment by FLO-2DKaren** [comment]
I was able to get this working on my computer with the Jupyter notebook.  I'll close this for now but open another issue related to the hdf5 testing for next weeks meeting.
