### ISSUE TITLE
Docker Info

### ISSUE THREAD

**Issue by FLO-2DKaren** [FLO-2DSoftware/qgis-flo-2d-plugin#1514]
Hi Robson,

I think you can lighten your docker package if you don't install QGIS gui.  
For unit testing, I think you only need this:

FROM ubuntu:20.04

RUN apt-get update && apt-get install -y --no-install-recommends \
    python3-qgis \
    python3-pyqt5 \
    python3-pip \
 && apt-get clean \
 && rm -rf /var/lib/apt/lists/*

Skip the qgis and qgis-plugin-grass packages if you don’t need the graphical interface or GRASS integration.

**Comment by rpachaly** [comment]
I think that the QGIS interface we need (because of the iface instance that is required in some functions). The grass I'm not totally sure. I can try.

**Comment by FLO-2DKaren** [comment]
Closing this.
