### ISSUE TITLE
Storm Drain issues

### ISSUE THREAD

**Issue by rpachaly** [FLO-2DSoftware/qgis-flo-2d-plugin#1516]
- [x] Inlet type -> adjust the minimum value on the dialog
- [x] Weir coefficient -> remove the limit and type 1 (3 en and 1.6 m) type 2 (2.3 en 1.25 m) type 3 (same as type 1) type 4 (don't need weir coefficient 0) 
- [x] importing inp -> all inlet types should be 0

**Comment by rpachaly** [comment]
I'm not going to set the weir coefficient based on the system's units.

**Comment by rpachaly** [comment]
Done and merged on https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/pull/1519

**Comment by FLO-2DKaren** [comment]
I've tested this and found no issues over the past two weeks of storm drain tutorials and webinars.
