### ISSUE TITLE
Import/Export INP code review

### ISSUE THREAD

**Issue by rpachaly** [FLO-2DSoftware/qgis-flo-2d-plugin#1517]

**Comment by rpachaly** [comment]
@FLO-2DKaren Hi Karen, I've finished the refactoring of importing SWMM INP. Here are some key points:

Pros:
- Code restructured with functions defined for each SWMM component - easy to debug
- New SWMMINP parser (faster and simpler)
- Code ready for creating automate tests (I'll be working on this)
- Code faster because it uses SQL queries instead of QgsVectorLayers editing
- Import from INP 
- Import Several Components (Storm Drain imports - swmminp, swmmflo, swmmflort, swmmoutf, swmmflodropbox, sdclogging)
- Import One Single Component - works same way as Import from INP
- Better coding for the outside nodes

Cons:
- Currently, It is not importing the descriptions (I'll be working this later)
- The messages are slightly different due to function's segmentation. But it can be improved

Honestly, I trust more this code than the old one. However, I coded this in a way that we can use the old code without any issues. The export code I did not change and I think it is okay, no need to change it. 

It is on https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/tree/import-swmminp-refactor

**Comment by rpachaly** [comment]
I don't think that we'll have any merging issues because it is brand new code and just a few adaptations. I'll be working on this code to finish the testing modules. After that, we can merge it if you agree with the new code and the testing is done.

**Comment by rpachaly** [comment]
Now it is ready for testing. I did a lot of improvements on the testing. So the SD testing on github is working.

**Comment by FLO-2DKaren** [comment]
I ran through the import inp many times with no issues.  I also did the storm drain from shapefile with no issues.  I think it will be OK.
