### ISSUE TITLE
Delete Schema Icon

### ISSUE THREAD

**Issue by rpachaly** [FLO-2DSoftware/qgis-flo-2d-plugin#1526]
Improve the delete schema data icon on the Boundary Condition Editor

**Comment by rpachaly** [comment]
The grid was in front of the X. I reorganized the order and it looks fine for me now. Done and merged on https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/pull/1531

**Comment by FLO-2DKaren** [comment]
I did a simple test on both buttons with no issues.
