### ISSUE TITLE
Reservoir/FPXS not loading in the widget

### ISSUE THREAD

**Issue by rpachaly** [FLO-2DSoftware/qgis-flo-2d-plugin#1532]
Use the signal when the editing is finished to populate the data on the combobox and not the click on the btn. 

- [x] Reservoir
- [x] Tailings Reservoir
- [x] Tailings Stack
- [x] FPXS

**Comment by rpachaly** [comment]
Done and merged on https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/pull/1533

**Comment by FLO-2DKaren** [comment]
Seems OK so far.  I'll close it for now but we may see more issues as we start to build the tailing dam training.
