### ISSUE TITLE
RAS import error message

### ISSUE THREAD

**Issue by FLO-2DKaren** [FLO-2DSoftware/qgis-flo-2d-plugin#1534]
This isn't a bug.  It's a minor improvement to the schematize channel error message system.

When the cross section shares banks, the schematize doesn't work.  Let's add a warning and maybe do something like list the cross sections that are sharing.  We can do a meeting to show the issue.

**Comment by rpachaly** [comment]
I can't open the gpkg

**Comment by FLO-2DKaren** [comment]
You are correct.  That geopackage won't open.  Let's do it on our RAS Import.  I'll add some cross sections

**Comment by rpachaly** [comment]
I imported the geopackage into another one using the 2868 CRS. It is not the correct one, but for testing purposes it will work. But  I never used this tool, what should I select when importing the ras?

**Comment by FLO-2DKaren** [comment]
Oh yes that will work because the geopackage was just a small grid.

**Comment by rpachaly** [comment]
Actually it does not have data on it. Can we have a quick meeting so I can see this bug?

**Comment by rpachaly** [comment]
Good?

![image](https://github.com/user-attachments/assets/be1adc47-ec5a-4016-95f8-8ca8c54af7ef)

**Comment by FLO-2DKaren** [comment]
I'm closing this as a quick fix but I'm adding to our channel ideas to improve this error messaging so it reports the id or name of the bad data.
