### ISSUE TITLE
SD - Typos in the table for conduits

### ISSUE THREAD

**Issue by rpachaly** [FLO-2DSoftware/qgis-flo-2d-plugin#1536]
I have the following comments for the conduits in the SD table:
- Entry losses need to be changed to Entry Loss Coeff. This should be the coefficient, not the losses, the SD calculates the energy losses using this coefficient. The entry losses coeff  depends on the type of entry to the conduit, this is used to calculate the minor loss.
- Exit losses need to be changed to Exit Loss Coeff.  This should be the coefficient, and it depends on the type of exit, this is used to calculate minor losses.
- Average Losses need to be changed to Avg. Loss Coeff.
- Flap gate losses should be change to Flap Gate (no losses)  and should not be located in the Losses table, I think it needs to be moved to the Conduit properties

![image](https://github.com/user-attachments/assets/77e22ab8-2abf-410e-a430-8ff7a919afbf)

**Comment by rpachaly** [comment]
@FLO-2DNoemi Done and merged on https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/pull/1537

![image](https://github.com/user-attachments/assets/b228fa4e-79ae-4ba6-a3f2-8dc15ca25210)

**Comment by FLO-2DKaren** [comment]
No issues on my testing.
