### ISSUE TITLE
No raster found

### ISSUE THREAD

**Issue by FLO-2DKaren** [FLO-2DSoftware/qgis-flo-2d-plugin#1549]
I keep getting this message when I add the elevation raster to the geopackage.

![image](https://github.com/user-attachments/assets/74bb66b9-b237-443b-b9e6-478560b7ad30)

Steps
1. Add elevation
2. Save Project
3. Add elevation to left side of the GeoPackage manager
4. Do almost anything else.  

1. I think it's checking for the raster too often.  Probably only needs to check for it when the Profile tool is called.
2. You might need to modify how you look for the layer.  I saw issues like this when the filter empty layers code lost layers.

**Comment by FLO-2DKaren** [comment]
I also think we should trigger another Save Project after we move move the layers to External Layers.

**Comment by rpachaly** [comment]
The issue was on the Profile widget, it was looking for a raster. It is fixed and merged on https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/pull/1563

**Comment by FLO-2DKaren** [comment]
Yeah that was annoying!!!!

**Comment by FLO-2DKaren** [comment]
I haven't seen this message in a while.  I'm going to clear this issue.
