### ISSUE TITLE
Import Issue from Data Files - Allow discharge switch SWMMOUTF.DAT

### ISSUE THREAD

**Issue by FLO-2DNoemi** [FLO-2DSoftware/qgis-flo-2d-plugin#1552]
When SD data files are imported, the allow discharge switch is set to 0 besides the data contain in the SWMMOUTF.DAT. 

@rpachaly can you double check this?. Please see image bewlo.

![image](https://github.com/user-attachments/assets/75b1ae33-de69-4dd3-9e5a-f36e15240f42)

**Comment by rpachaly** [comment]
I'll check that.

**Comment by rpachaly** [comment]
The SD Outfalls is correct but the data was not updated on the Storm Drain Outfalls. Good catch Noemi. I'll fix it.

**Comment by FLO-2DNoemi** [comment]
Great, thanks!

**Comment by rpachaly** [comment]
Done, tested, and merged on https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/pull/1555

**Comment by FLO-2DKaren** [comment]
I concur that this is OK.  Tested on NorthP.
