### ISSUE TITLE
SWMM.INP was partially written

### ISSUE THREAD

**Issue by FLO-2DNoemi** [FLO-2DSoftware/qgis-flo-2d-plugin#1553]
I got a FORTRAN error because the SWMM.INP was partially written, steps were the following:

1. FLO-2D existing surface layer.
2.  Nodes, conduits and outfalls were created editing the Storm Drain User Layers.
3. User layers were schematized.
4. SD switch was turned ON.
5. Run a Quick Run.

The INP is partially exported and generates a FORTRAN Error.  I think the SD options are missing. 

@rpachaly  @FLO-2DKaren,   Can we review this?

When the Data Files are exported, the SWMM.INP is exported without issues. This seems to be a problem only with quick run for a SD created from scratch.

**Comment by rpachaly** [comment]
I'm investigating here. Did you set the SD control variables?

![image](https://github.com/user-attachments/assets/2a66933e-4182-4873-a59c-ad3f16c513dd)

**Comment by FLO-2DNoemi** [comment]
No, I did not set it up intentionally.

I believe the default data should come from CON.DAT, as it is likely that
non-advanced users may forget to input this information. In other words, if
no data is provided by the user, the variables should default to the values
outlined below. Let me know if this makes sense.

[image: image.png]

**Comment by rpachaly** [comment]
That makes sense. If the user did not set the sd control variables, I'll set the default values from CONT.DAT.

**Comment by FLO-2DNoemi** [comment]
Ok, thanks.

**Comment by rpachaly** [comment]
Done, tested and merged on https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/pull/1556
