### ISSUE TITLE
RAIN.DAT is exported with zeroes

### ISSUE THREAD

**Issue by FLO-2DNoemi** [FLO-2DSoftware/qgis-flo-2d-plugin#1554]
RAIN.DAT is exported with zeroes when no data is entered.

![image](https://github.com/user-attachments/assets/8a4cd306-4989-4e5f-b635-ea71682194a8)

**Comment by FLO-2DKaren** [comment]
It’s always been like this. Don’t know if it’s worth fixing since it won’t use that data because the switch is off.

**Comment by rpachaly** [comment]
I'll fix it.

**Comment by rpachaly** [comment]
The rain table is created even if there is no data defined. I did not change that. I just added a check for the RTT (tot_rainfall) right before exporting and, if it is 0, it does not export the RAIN.DAT and shows the following message: 

![image](https://github.com/user-attachments/assets/d2e89106-6de9-40dc-a2f0-86664b75e95c)

All other files are exported. 

Is this a good approach?

**Comment by FLO-2DNoemi** [comment]
One thing to consider is the case when RAINCELL.DAT and RAINCELL.HDF5 are used,  RAIN.DAT must be generated with the following data:

1  0   IRAINREAL IRAINBUILDING
0   0.0  0  0

Also, there is a simplified methodology for the spatially and temporal variable rainfall data (NEXRAD) that can be used instead of the RAINCELL file. I created this for SFWMD project and it is much more simple. The plugin does not currently create the data files. The files are the following: 

FLO2DRainCell.dat
RainCellRaw.dat

I will add a separate issue for this. Eventually we need to discuss this simplified method and figure out if we want to keep it, then we can create these files in HDF5 format only.

**Comment by rpachaly** [comment]
Ok, I improved the check to evaluate the case of RAINCELL. It is done, tested and merged on https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/pull/1557

**Comment by FLO-2DKaren** [comment]
Tested and working good.
