### ISSUE TITLE
Set default Outfall type to 'FREE' 

### ISSUE THREAD

**Issue by rpachaly** [FLO-2DSoftware/qgis-flo-2d-plugin#1558]

**Comment by rpachaly** [comment]
This is fixed and tested on https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/pull/1560.

Note: This update will only take place on new geopackages.

**Comment by FLO-2DKaren** [comment]
@FLO-2DNoemi 

I tested this and it's corrected.
I also noticed that the Allow Discharge default is 0.  Noemi, do you want that to be on or off?

**Comment by rpachaly** [comment]
The Allow Discharge default is 1 now. However, this will only take place on new geopackages!

Done and merged on https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/pull/1591

**Comment by FLO-2DKaren** [comment]
Tested on QGIS 3.40.1.  I'm ok if this only works on new geopackages.
