### ISSUE TITLE
Remove unused libraries/imports

### ISSUE THREAD

**Issue by rpachaly** [FLO-2DSoftware/qgis-flo-2d-plugin#1561]

**Comment by rpachaly** [comment]
Done and merged on https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/pull/1562

I did some tests on my machine and it passed all github tests. I'm assuming that it is ok. However, let's keep an eye for potential import errors.

**Comment by FLO-2DKaren** [comment]
OK that was a lot of changes.  We aren't releasing this anytime soon but it does require good testing.

**Comment by rpachaly** [comment]
Yes, but I used the Inspect Code from Pycharm and went manually through all unused imports. I kept the ones I was in doubt.

**Comment by FLO-2DKaren** [comment]
I did a lot of additional testing on various processors.  I didn't find anything so I'll close this but I'm wondering if we'll miss a few more later.
