### ISSUE TITLE
FLO-2D Warning 060319.1710: probing grid elevation failed! please check your raster

### ISSUE THREAD

**Issue by rouzbehberton** [FLO-2DSoftware/qgis-flo-2d-plugin#1569]
Hi,
I am using Gila plugin with "QGIS Desktop 3.26.3". I am getting this error while I am trying to assign elevations into grids:

FLO-2D Warning 060319.1710: probing grid elevation failed! please check your raster

![image](https://github.com/user-attachments/assets/cd76bca4-d9d8-45e7-80e5-51ac5e9c1f44)

Thanks!

**Comment by FLO-2DKaren** [comment]
This isn't an issue.  It is a bad raster.
Some ideas to troubleshoot this.
1. Make sure the elevation raster is on the computer and not an external drive.
2. Sometime rasters have corrupted data or don't correctly identify the source CRS.  Export the raster and save it with the correct coordinate system.

There are other possible solutions in the Troubleshooting section of the User Manual.
https://documentation.flo-2d.com/Plugin1000/widgets/grid-tools/Elevation%20from%20Raster.html#troubleshooting
