### ISSUE TITLE
FLO-2D Info Tool missing a trigger

### ISSUE THREAD

**Issue by FLO-2DKaren** [FLO-2DSoftware/qgis-flo-2d-plugin#1577]
When you select an inflow node with the FLO-2D Info Tool, it loads the correct inflow name but doesn't load the correct time series.
When you change the inflow node from the inflow node selector, it sets the correct time series.

https://github.com/user-attachments/assets/de797a1c-6bd8-45f8-a3b9-7e570a1719ad

**Comment by rpachaly** [comment]
I did a simplification when setting the time series combobox. I did a lot of testing and all seems fine. Done and merged on https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/pull/1584

I kept the old code just in case.

**Comment by FLO-2DKaren** [comment]
This seems to work ok.  I've tested it on 3 different projects.
