### ISSUE TITLE
fpfroude export taking too long

### ISSUE THREAD

**Issue by FLO-2DKaren** [FLO-2DSoftware/qgis-flo-2d-plugin#1579]
It seems like fpfroude.dat is taking too long to export.  I'll package the test and add it to another comment.

https://github.com/user-attachments/assets/fe9a893d-e969-44f1-8afc-f6a0a70bbca8

**Comment by FLO-2DKaren** [comment]
Test Project https://flo-2d.sharefile.com/d-s7e23a49a948847169767c1357e202401

**Comment by rpachaly** [comment]
We should also consider adding a progress bar or a counter.

**Comment by rpachaly** [comment]
The export_fpfroude_dat function was using two queries. That why it was slow. I combined the two queries into one and it is really fast now. Done and merged on https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/pull/1582

**Comment by FLO-2DKaren** [comment]
OK this is done.
