### ISSUE TITLE
Quick raster meter to feet converter

### ISSUE THREAD

**Issue by rpachaly** [FLO-2DSoftware/qgis-flo-2d-plugin#1587]
To use on elevation data

**Comment by rpachaly** [comment]
@FLO-2DNoemi @FLO-2DKaren 

This is done on https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/compare/raster-converter?expand=1

I'll not merge it until we decide if we proceed or not. 

https://github.com/user-attachments/assets/5e63a984-6ad5-4a65-a90c-bbfefea80e48

**Comment by FLO-2DKaren** [comment]
Test Complete and Passed.

Test steps
Load project in Nevada with CRS 3422
Download USGS Elevation data which is in meters.
Convert elevation to ft.
Process elevation.
Save elevation raster to geopackage and rerun elevation interpolator.

All test passed elevation processing and raster conversion.
