### ISSUE TITLE
Create a way to quickly create a backup geopackage

### ISSUE THREAD

**Issue by rpachaly** [FLO-2DSoftware/qgis-flo-2d-plugin#1592]
Try to avoid closing and reopening QGIS.

**Comment by rpachaly** [comment]
This is driving me nuts. I can create a copy of the geopackage but to adjust the qgz project inside the geopackage is really hard. It keeps breaking the paths.

**Comment by rpachaly** [comment]
@FLO-2DKaren 

Karen, you are going to love this. See the video:


https://github.com/user-attachments/assets/df732c49-cdd6-4149-b611-c45a11848bbc


Done and merged on https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/pull/1595

**Comment by FLO-2DNoemi** [comment]
Hi Robson,

For some reason I only can watch the video up to minute 1:34

The idea of being able to create a backup by saving it helps a lot.

Noemi

**Comment by rpachaly** [comment]
Hi Noemi, 

That's weird. Here is a sharefile link directly to the video. https://flo-2d.sharefile.com/d-s1543b280bb7245cb81ad53cc1630642c

Thanks

**Comment by FLO-2DKaren** [comment]
Nice work Robson.  I think it's  a good way to load old geopackages too because sometimes you lose your external layers.  You have to go load them from the geopackage.

**Comment by FLO-2DKaren** [comment]
I think that video isn't loading because its too long.  I recommend to try to limit the videos that you upload to 3 to 4 min.  Other videos should go to sharefile.

**Comment by FLO-2DKaren** [comment]
Testing now on QGIS 3.40.1

**Comment by FLO-2DKaren** [comment]
My tests passed.  I'm closing this issue but I'll be doing a self help rapid run and doing some backups during that.  I'll reopen it if anything happens.  I'll add this to documentation.

**Comment by rpachaly** [comment]
Something that I forgot to mention, is that my testing was done on my external drive. I think this is the reason that it was a little slow.
