### ISSUE TITLE
Storm Drain schematizing fails from nodes created in Storm Drain Nodes (User Layers)

### ISSUE THREAD

**Issue by FLO-2DJJ** [FLO-2DSoftware/qgis-flo-2d-plugin#649]
Storm drain nodes created in the user layer makes the schematizing to fail. Error 060319.1832 Attribute missing.

**Comment by FLO-2DNoemi** [comment]
@FLO-2DJJ @FLO-2DKaren 

The _Add Storm Drain Points_ was removed, the button still in the plugin, we should remove it.
