### ISSUE TITLE
Storm Drains: conversion from User to Schematic  doesn't seem to work. 

### ISSUE THREAD

**Issue by FLO-2DJJ** [FLO-2DSoftware/qgis-flo-2d-plugin#681]
Storm Drains: conversion from User to Schematic  doesn't seem to work. 

![image](https://user-images.githubusercontent.com/20424575/94409403-1d8b3b80-0144-11eb-8e87-3b16a48272a6.png)

@FLO-2DNoemi , @FLO-2DKaren could you confirm this?

**Comment by FLO-2DNoemi** [comment]
@FLO-2DJJ @FLO-2DKaren

Storm Drains conversion from User to Schematic work.  Is the conversion of the rest of the components working?

**Comment by FLO-2DKaren** [comment]
Not certain.  We'll have to test it.

**Comment by FLO-2DJJ** [comment]
This issue was related with the change of cell size. It has many ramifications and complications. Better close it for now.
