### ISSUE TITLE
Outfalls Stage Time Data

### ISSUE THREAD

**Issue by FLO-2DKaren** [FLO-2DSoftware/qgis-flo-2d-plugin#693]
Stage time data: this will work but if they want the outfall BC to be controlled by a given Stage time data, the outfall will discharge out of the system. If we want to discharge this back to surface, I need to add the capability to FLOPRO.exe.

**Comment by FLO-2DNoemi** [comment]
@FLO-2DKaren this should not be difficult to complete. I will add it.

**Comment by FLO-2DKaren** [comment]
@FLO-2DNoemi Can we close this?  It can't tell if it is an issue or not.

**Comment by FLO-2DNoemi** [comment]
@FLO-2DKaren 

This is an enhancement, not an issue. 

@FLO-2DJJ do you have an update on this?

**Comment by FLO-2DJJ** [comment]
The plugin writes the following according to the Outflow type (for an outflow in cell 9503 in this example)

- 5. For Time-stage for floodplain:
N     9503  0
S  0.0  0.0
S  1.0  1.0
S  2.0  2.0
S  3.0  2.0
S  4.0  1.0

- 6. Time-stage for channel:
N     9503  1
S  0.0  0.0
S  1.0  1.0
S  2.0  2.0
S  3.0  2.0
S  4.0  1.0

- 7. Time-stage for fllodplain and free floodplain and channel:
N     9503  0
S  0.0  0.0
S  1.0  1.0
S  2.0  2.0
S  3.0  2.0
S  4.0  1.0
O  9503

- 8. Time-stage for channel and free floodplain and channel:
K  9503
N     9503  1
S  0.0  0.0
S  1.0  1.0
S  2.0  2.0
S  3.0  2.0
S  4.0  1.0

**Comment by FLO-2DNoemi** [comment]
Is this issue related to Outfalls or Outflows? We need to review both,
outfalls and outflows have  issues open in github.

N

**Comment by FLO-2DKaren** [comment]
This whole issue is wrong.  Do not use it.
