### ISSUE TITLE
Control Gate

### ISSUE THREAD

**Issue by FLO-2DKaren** [FLO-2DSoftware/qgis-flo-2d-plugin#695]
Control gate - it can be set up in epa-swmm. We need to make sure that at least the plugin reads it.  I will work with JJ on this.
 
They are internally represented in SWMM as a link connecting two nodes. An orifice can have either a circular or rectangular shape, be located either at the bottom or along the side of the upstream node, and have a flap gate to prevent backflow. Orifices can be used as storage unit outlets under all types of flow routing. If not attached to a storage unit node, they can only be used in drainage networks that are analyzed with Dynamic Wave flow routing.

**Comment by FLO-2DNoemi** [comment]
@FLO-2DKaren I will complete this with JJ. The data for a control gate is all in the INP file so we only need to make sure that we can read it and write it from the plugin. 

The *.DAT files do not have changes.

@FLO-2DJJ let's complete this along with the SD changes that we are currently working on.

**Comment by FLO-2DJJ** [comment]
@FLO-2DNoemi can be close this issue?
