### ISSUE TITLE
Multiple Barrels

### ISSUE THREAD

**Issue by FLO-2DKaren** [FLO-2DSoftware/qgis-flo-2d-plugin#717]
Add a multiple barrel switch to the Culvert data in the table form.

![image](https://user-images.githubusercontent.com/20424460/118661339-04132e80-b7bd-11eb-8fe7-9e3370dbf45e.png)

The data goes to the end of the F line in hystruct.dat.

S  ResDrainCulv  0  2  5239  5129  0  0.0  175.0  2.0
F  2  1  0.02  0.2  0.0 **3**

In this example, there is a 2 ft diameter round culvert.  It looks like the CuBase stays zero.  We need to see if this is correct with Jim.

**Comment by FLO-2DNoemi** [comment]
@FLO-2DKaren can we close this? I remember we added the multiple barrels field. Is this correct?

**Comment by FLO-2DKaren** [comment]
@FLO-2DNoemi It isn't finished but I'm giving it to Lutra.  Don't close it.

**Comment by FLO-2DNoemi** [comment]
Perfect.
