### ISSUE TITLE
Channel Confluence export via Interpolator bug

### ISSUE THREAD

**Issue by FLO-2DKaren** [FLO-2DSoftware/qgis-flo-2d-plugin#719]
When you have a confluence in the channel, the save chan.dat and xsec.dat saves the file with no confluence.

The image on the left is the channel export from the Interpolator button.

The one on the right is what it should look like.

![image](https://user-images.githubusercontent.com/20424460/119197837-6044af80-ba56-11eb-87f6-94a4c564e409.png)

**Comment by FLO-2DJJ** [comment]
The interpolator executable called from 

![image](https://user-images.githubusercontent.com/20424575/124569225-c1acbc00-de13-11eb-8dd8-68a6d133ecf6.png)

saves CHAN.DAT without no-confluence cells.

**Comment by FLO-2DKaren** [comment]
@FLO-2DJJ 
Hi JJ,  This got forgotten.  I'd like to boost it because it is important.
