### ISSUE TITLE
Type 4 Storm Drain Culvert Equation

### ISSUE THREAD

**Issue by FLO-2DKaren** [FLO-2DSoftware/qgis-flo-2d-plugin#720]
Design for the Type 4 Storm Drain Culvert EQ
![image](https://user-images.githubusercontent.com/20424460/119353336-c016a280-bc70-11eb-9684-fda8760ac338.png)

Need two new tables.  Maybe only 1 because we might be able to connect the current "Rating Tables"

@FLO-2DNoemi will post an example of the .dat file.  It goes to swmmflort.dat

**Comment by FLO-2DNoemi** [comment]
@FLO-2DJJ we need to review the Type 4 Generalized Culvert Equation.

**Comment by FLO-2DKaren** [comment]
We can add a type 4 table but not a Type 4 Culvert EQ.  You can import them but not add them manually.
We also need to test type 4 culvert EQ and the Mult Barrel options.  Conduits have mult barrels and the Culvert EQ has them.

**Comment by FLO-2DKaren** [comment]
Closing and creating newer issue.
