### ISSUE TITLE
Manage RST Data for Plugin

### ISSUE THREAD

**Issue by FLO-2DKaren** [FLO-2DSoftware/qgis-flo-2d-plugin#722]
Add new RST, Make.bat and maker.??? to User documentation on the plugin.
Set it up so that it creates an html file when deployed or installed.
Show FLO-2D staff how to maintain and keep it current.

**Comment by DamnBack** [comment]
Plugin help button opens online documentation available on: https://flo-2dsoftware.github.io/qgis-flo-2d-plugin/
