### ISSUE TITLE
Connect RST website

### ISSUE THREAD

**Issue by FLO-2DKaren** [FLO-2DSoftware/qgis-flo-2d-plugin#723]
Deploy RST to webpage.

@FLO-2DKaren can get the webpage ready.

Determine the best website program.  
Get a domain and a host.

@DamnBack 
Can you find out how you guys purchased your domain and who is hosting your sites?  I am using BlueHost.  I think it would be simple to get a domain from them but I wanted to see how you guys are doing it.
I use WordPress to develop the FLO-2D website.  It has a dashboard where I can set up the pages and shop and such.
Can you find out which platform you run your websites on.  Wix.com wordpress.com  etc.

**Comment by DamnBack** [comment]
Plugin documentation is live on: https://flo-2dsoftware.github.io/qgis-flo-2d-plugin/
