### ISSUE TITLE
Multiple Barrels

### ISSUE THREAD

**Issue by FLO-2DKaren** [FLO-2DSoftware/qgis-flo-2d-plugin#726]
Add a new parameter to QGIS for the July Release

![image](https://user-images.githubusercontent.com/20424460/122644659-5e691d00-d0e4-11eb-806a-39afc44f7aba.png)

**Comment by FLO-2DKaren** [comment]
@FLO-2DJJ 
Here is the info from the data input manual.
	Line 5:	STRUCHAR = ‘F’  TYPEC(I)  TYPEEN(I)  CULVERTN(I)  KE(I)   
		CUBASE(I)   **MULTBARRELS(I)**   
		I = number of structures, Set ICURVTABLE = 2 in Line 1.
F   1   2  0.040   0.1   0.0   **2**

MULTBARRELS(I)	i	1 - 10	Multiple barrel option for generalized culvert equation.   The engine will multiply the Q by the number of barrels (see comment 20).

We'll need the ability to import, export, digitize or ignore.  

If there are not multiple barrels, set to NULL not "0"

**Comment by FLO-2DKaren** [comment]
@FLO-2DJJ @FLO-2DNoemi When we do the multiple barrels code, let's test the import tool because it might not be importing the cubase correctly.  My cubase on subdomain 1 came in as 0 and 1 instead of a width value.

**Comment by FLO-2DKaren** [comment]
Update table
Update table editor panel
test import export with and without barrels

**Comment by FLO-2DNoemi** [comment]
@FLO-2DJJ @FLO-2DKaren is the importing tool working for Cubase?

**Comment by FLO-2DNoemi** [comment]
I need to add MULTBARRELS to FLOPRO.exe (TYPE4SD):

STRUCHAR,TYPEC(I),TYPEEN(I),CULVERTN(I),KE(I),CUBASE(I)**,MULTBARRELS(I)** 

@FLO-2DJJ we need to add this to the plugin.

**Comment by ldebek** [comment]
@FLO-2DKaren Could you please add an example project with barrels for import/export testing?

**Comment by FLO-2DKaren** [comment]
@ldebek 
Hi Lukasz,  **Rename this .7z before you extract it.**
[Module 2 Export.zip](https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/files/8017266/Module.2.Export.zip)

**Comment by vcloarec** [comment]
@FLO-2DKaren , do you want this multibarrels parameter only for type 'F' (culvert equation) or also for others type ?

**Comment by FLO-2DKaren** [comment]
Only Type F
