### ISSUE TITLE
Remove text that isn't used from GUIs

### ISSUE THREAD

**Issue by FLO-2DKaren** [FLO-2DSoftware/qgis-flo-2d-plugin#752]
Take out the overview text.
![image](https://user-images.githubusercontent.com/20424460/126384631-01876b85-1944-4b79-8da4-fe9f412430b3.png)

Take out the grey text. I don't see any use for this anymore.
![image](https://user-images.githubusercontent.com/20424460/126384471-0d82bde4-da95-403d-b4aa-2031e374bc78.png)

**Comment by FLO-2DJJ** [comment]
Fixed and pushed to remote
