### ISSUE TITLE
Gutters

### ISSUE THREAD

**Issue by FLO-2DKaren** [FLO-2DSoftware/qgis-flo-2d-plugin#753]
- [x] Make a Gutter Schema Layer.  Maybe we can use the Gutter Areas User layer.

- [x] If the gutter globals are already filled, don't show the Gutter Globals dialog.

**Comment by FLO-2DJJ** [comment]
@FLO-2DKaren @FLO-2DNoemi,
Why do we need a Gutter Schema layer? The plugin has a Gutters Cells layer (a table with no geometry) where the gutter cells numbers are intersected from the Gutter Lines and Gutter Areas from the User Layers. The GUTTER.DAT file is read and written to and from those layers.
@FLO-2DKaren, do you want to add the geometry of the cells to the table Gutter Cells and convert it in a Schematic layer?

**Comment by FLO-2DJJ** [comment]
Done. Geopackage and plugin have new gutters cell layer geometry  (as Schematic layer) and functionality.
@FLO-2DKaren, @FLO-2DNoemi please test it and close this issue if satisfied.

**Comment by FLO-2DKaren** [comment]
Seems good.
