### ISSUE TITLE
LiDAR Interpolation Non Interpolated Cells

### ISSUE THREAD

**Issue by FLO-2DKaren** [FLO-2DSoftware/qgis-flo-2d-plugin#755]
@FLO-2DJJ 

JJ,  Can you create a loop to complete the interperlation from neighbor routine in a single click. In other words loop it so the user doesn't have to click the button more than once.

**Comment by FLO-2DJJ** [comment]
Or do something similar to the "Sampling from points layer" where there is a "Max search distance" to indicate the number of neighbours to expand the interpolation:

![image](https://user-images.githubusercontent.com/20424575/126465701-342cf4a0-70bf-4e20-9090-b1b506775546.png)

zero meaning "all" or something like that.

**Comment by FLO-2DKaren** [comment]
Yes, that would be OK too.  We just need to whittle that down to 1 step.

Karen O'Brien
Technical Support

FLO-2D Software | Riada Engineering
P.O. Box 66 | Nutrioso, AZ | 85932
T. 928.339.1935
www.flo-2d.com | ***@***.***

**Comment by FLO-2DJJ** [comment]
Number of non-interpolated immediate adjacent cells are selected after the LIDAR interpolation:

![image](https://user-images.githubusercontent.com/20424575/135928028-44cc84f1-aa0c-47c7-9729-de7bdc2fe309.png)
