### ISSUE TITLE
Import GDS files: remove WSURF.DAT and WSTIME.DAT from message. They are not used.

### ISSUE THREAD

**Issue by FLO-2DJJ** [FLO-2DSoftware/qgis-flo-2d-plugin#760]
![image](https://user-images.githubusercontent.com/20424575/135928317-d708fca8-925b-4966-83e0-4571e3eef364.png)

**Comment by FLO-2DKaren** [comment]
They are used but they don't need to be in this message.

**Comment by FLO-2DJJ** [comment]
Fixed: message removed. Tested.
