### ISSUE TITLE
Levee Prescribed Breach Bug

### ISSUE THREAD

**Issue by FLO-2DKaren** [FLO-2DSoftware/qgis-flo-2d-plugin#761]
Hi JJ, 
We've already fixed this once but maybe it returned when Nate added the levee improvement code.  Can you take a look at this video?  We can likely fix this with your history.
https://transcripts.gotomeeting.com/#/s/d8171f5d16a54fe296be3d4d826224d3cfac4aafdbb553e6765eb62d37ec8b2b

**Comment by FLO-2DJJ** [comment]
Ok Karen,  I saw the video you sent. I understand the problem. I'll look at
a possible solution this afternoon. And yes, I think we've been
there before.
