### ISSUE TITLE
Storm Drain Pumps

### ISSUE THREAD

**Issue by FLO-2DKaren** [FLO-2DSoftware/qgis-flo-2d-plugin#763]
Create a data assignment for storm drain pumps.  

- [x] Create the widget tool to assign the data.
- [x] Add the new data to the storm drain layers.
- [x] Add the import export capability from the swmm.inp.
- [x] Review and correct if necessary the conduit layer.
- [x] Auto assign pumps (as in Auto assign Conduits).

### Testing Check list
- [x] Build a test scenario with a pump.
- [x] Test with and without pumps.
- [x] Calculate from shapefile.
- [x] Check number precision for all variables.
- [x] Spell check and simplify dialogs.
- [x] Test select shapefile dialog settings and initial settings.
- [x] Review error messages
- [x] Fixed Stage error

**Comment by FLO-2DKaren** [comment]
@FLO-2DJJ 

Bug Identified
![pump curve bug](https://user-images.githubusercontent.com/20424460/156774327-dd489dc2-eea7-4978-a43d-d0239b266837.gif)

When you make an edit to the pump curve description, it resets the pump data.

**Comment by FLO-2DKaren** [comment]
Curve Data not being exported.
![image](https://user-images.githubusercontent.com/20424460/156774757-7b809d1e-dc29-420b-9d68-c37d5ff2479c.png)

![image](https://user-images.githubusercontent.com/20424460/156774992-1e8b08fc-9f99-4ac0-b048-d45492771ef1.png)

Update Problem with the Pump Curve Table
![image](https://user-images.githubusercontent.com/20424460/156777417-169154bb-1fbe-4d87-82eb-755bc5388fb0.png)

Test Data: https://flo-2d.sharefile.com/d-s269fbf96ad804e3f9a58a75b35a3ebe3

**Comment by FLO-2DKaren** [comment]
The Pump Curve Data Table starts out with 5 empty rows.

**Comment by FLO-2DKaren** [comment]
Auto-assign Conduits Nodes
@FLO-2DJJ 
We need to update this tool so that it also assigns the pump conduits to the upstream and downstream nodes.

**Comment by FLO-2DKaren** [comment]
When I reload the Select Components Dialog, the Initial Status unselected.
![image](https://user-images.githubusercontent.com/20424460/156787812-dc7706aa-178a-44cc-be84-0e36b40798c2.png)

**Comment by FLO-2DJJ** [comment]
- Pump  curve des

> @FLO-2DJJ
> 
> Bug Identified ![pump curve bug](https://user-images.githubusercontent.com/20424460/156774327-dd489dc2-eea7-4978-a43d-d0239b266837.gif)
> 
> When you make an edit to the pump curve description, it resets the pump data.

Fixed: Pump description and/or type can be changed without resetting data.

**Comment by FLO-2DJJ** [comment]
> 

Fixed: new pump curve starts with a ( 0.0, 0.0) row. Others can be entered as wished.

**Comment by FLO-2DJJ** [comment]
> When I reload the Select Components Dialog, the Initial Status unselected. ![image](https://user-images.githubusercontent.com/20424460/156787812-dc7706aa-178a-44cc-be84-0e36b40798c2.png)

Fixed: Initial status field is selected and assigned when reloaded.

**Comment by FLO-2DKaren** [comment]
We need optional feature for pumps since they aren’t common and most projects will not have them.  I can’t build a storm drain without pumps right now.  That’s a big deal so it needs to be addressed by the end of next week.

Don’t forget to add a Auto-Assign method to the Pumps in out nodes.  You should be able to duplicate Lukasz’s code.  I don’t mind if you simply apply it after the Yes box appears.
 
![image](https://user-images.githubusercontent.com/20424460/157917776-a8687d9f-e42d-498a-9f5c-bb6392a16085.png)

**Comment by FLO-2DKaren** [comment]
@FLO-2DJJ 

Can you please add a default to the dialog box?  Possible Default Text:
No Pumps
Pumps not present
Pumps not used

 
![image](https://user-images.githubusercontent.com/20424460/158027921-4f38b5e3-755a-4add-ac00-faab2c055ca0.png)

**Comment by FLO-2DKaren** [comment]
Initial or Startup dialog settings should be NULL or Not Selected.

Did you change something?  
Are you seeing this too?  
If you changed something, please use NULL or no selection for the initial state of all tabs on this dialog box.  

I am currently doing all of my testing on QGIS 3.24 and 3.25 because I’m looking for future errors.  Let me know if you don't see this in QGIS 3.18.2.
![image](https://user-images.githubusercontent.com/20424460/158028008-1b112241-f306-4563-a044-e2994b72ece6.png)

**Comment by FLO-2DKaren** [comment]
Can you review what is causing the message?
It comes up when I Unselect all Pump Fields.

![image](https://user-images.githubusercontent.com/20424460/158028040-b436cebc-b4e9-4397-b064-9c24329f0671.png)

**Comment by FLO-2DJJ** [comment]
All items in  issue #763, except for 'Autoasign pump nodes', were corrected.

Juan Jose Rodriguez
FLO-2D Software
www.flo-2d.com
***@***.***

**Comment by FLO-2DKaren** [comment]
Resize Dialog icons

You can set it here.  Should be 16 not 25
I would make the change myself but all my changes get overwritten by your commits.
 
![image](https://user-images.githubusercontent.com/20424460/159137498-7430cf79-ed09-4259-8e17-2b41157883a5.png)

**Comment by FLO-2DKaren** [comment]
Storm drain Message Update.  

Change  “Outfall”  to    “outfall”
 
![image](https://user-images.githubusercontent.com/20424460/159137513-616ec7fb-ce14-44de-9b6c-191917aecf76.png)

**Comment by FLO-2DKaren** [comment]
The following message is still confusing.  The people who take the time to read this message are the exact people we don’t want to confuse.  They won’t understand the message and they will think they need to do something. 
 
![image](https://user-images.githubusercontent.com/20424460/159137525-32511af4-bb51-45d1-a3fd-1063a65b10b2.png)

Let’s try this:

Importing Nodes and Links finished!  Or Importing Storm Drain finished!

Use the Components (Nodes and Links)  buttons in the Storm Drain Editor to view / edit data.

Complete the storm drain by clicking the Schematize Storm Drain Components button.

**Comment by FLO-2DJJ** [comment]
@FLO-2DKaren 

I think all or most of the issues here are solved. Could you check them?

In the future is a good idea to have separate issues #xxx,  one for each, instead of several fixes in one issue. So each issue is closed when solved and there is no need to wait for the others to close the whole bunch.

**Comment by FLO-2DKaren** [comment]
@FLO-2DJJ The only test that remains is the test without pumps.  I will get to that today.
