### ISSUE TITLE
Simplified multiple channel

### ISSUE THREAD

**Issue by FLO-2DKaren** [FLO-2DSoftware/qgis-flo-2d-plugin#764]
Mult channel data file

- [x] One line of global parameters followed by a list of selected grid elements with multiple channels.
- [x] Adapt the current system to write the layers either way???  Ask Jim
- [x] Develop a polyline tool to select multiple channels elements.  
- [x] Revise global parameters as necessary based on a review by the District.  We'll sort this out in a meeting.
- [x] Check the number precision for all new fields.
- [x] Update data input manual data file.
- [x] Spell check and simplify dialogs.
- [x] Testing

**Comment by FLO-2DJJ** [comment]
It seems that both methods can be applied. See this near the end of white paper:

> A simplified multiple channel routine with
> automated assignment of width, depth and n-values has been implemented in the FLO-2D. The only
> data required is the list of rill and gully cells and single global n-value. Where larger channels are
> identified in the aerial images or in the field, detailed channel geometry can be assigned with the full
> multiple channel component.

**Comment by FLO-2DNoemi** [comment]
JJ, That is correct. Both methods can be used in the current FLO-2D engine.

**Comment by FLO-2DKaren** [comment]
Notes:
QGIS needs the mult channel switch.
FLOPRO doesn't need the switch right now but will still read it OK regardless of how the system is set up.


simplemult.dat - Only a single line of cells can be used.  Line 1 (global n) is n value and line 2 can only be the cell.
mult.dat - Same as before

Update data input manual.

**Comment by FLO-2DNoemi** [comment]
Mult.DAT and simplemult.dat files can be used both in a project. They are not exclusive.

**Comment by FLO-2DKaren** [comment]
@FLO-2DJJ 
Hi JJ,  

I found an issue with the autosave on mult channel system.  It isn't updating the multiple channel tables correctly.  

Can you change it to clear all and replace?  If you delete a line, it won't update and the cells will still be written.

**Comment by FLO-2DKaren** [comment]
The geometric predicate that intersects the grid layer to the polyline layers is probably set to touch or intersect.  We need to use a method where the line crosses the grid.

Here is what we are currently getting when a line touches a corner but doesn't cross a grid.
![image](https://user-images.githubusercontent.com/20424460/159184990-fe141ed1-7d7f-4b02-8b50-eab9b48b9cf9.png)

We should be writing this:
![image](https://user-images.githubusercontent.com/20424460/159185015-8139a6f4-8906-4b9d-bc71-3afecc2c72b2.png)

Here is an example of a spatial join that uses the correct geometric predicate.

![image](https://user-images.githubusercontent.com/20424460/159185053-8228be16-30f1-4943-a14f-96fc33cfb355.png)

**Comment by FLO-2DJJ** [comment]
Hi Karen,

Could you please clarify this issue. What do you mean by "autosave".
Also I see that when you delete a multiple channel line or area in the User
Layers, the intersected cells are also deleted in the Multiple Channel
Cells table (mult_cells). Is this what you mean?


Juan Jose Rodriguez
FLO-2D Software
www.flo-2d.com
***@***.***

**Comment by FLO-2DKaren** [comment]
This is a comment on the "autosave".  I think what is happening is a sql update.  When you add a polyline to the mult chan user layers, it updates the mult chan tables.  When you delete a line from the user layers, it does not remove the mult chan cells.  It applies to both mult and simple mult.

**Comment by FLO-2DJJ** [comment]
@Karen OBrien ***@***.***> I see what you mean.  The "delete
selected" doesn't work for simple multiple channel lines.
But it works for area multiple channels and line multiple channels. The
problem is only with the simple mult channels. I'll see what's happening.

Juan Jose Rodriguez
FLO-2D Software
www.flo-2d.com
***@***.***
