### ISSUE TITLE
Infiltration Calculation

### ISSUE THREAD

**Issue by FLO-2DKaren** [FLO-2DSoftware/qgis-flo-2d-plugin#765]
- [x] Enhance the infiltration calculation routine for RTIMP.
- [x] Revise code so that combined RTIMP from soils and Land Use does not exceed 1.

**Comment by FLO-2DKaren** [comment]
@vaughanster 
Nate, can you do a simple workflow and final result description here?

**Comment by vaughanster** [comment]
Workflow - 
Perform an intersection with soils, land-use and grid datasets (preferably using the moving-window analysis to limit the amount of data processed at once).
Calculate the Green and Ampt components based upon the soils and land-use data as is done currently, including use of the effective imperviousness modifier.
When performing the RTIMP portion of the Green and Ampt calculation, evaluate RTIMP from soils and RTIMP from land-use and use whichever value is more limiting (e.g. higher) and apply that. Previous methodology involved adding the soil RTIMP and the land-use RTIMP and reducing to 1 if the result was greater than 1 which, while computationally simpler, did not result in a representative RTIMP in areas where soil RTIMP and land-use RTIMP were applied.

**Comment by FLO-2DKaren** [comment]
Current method OK for these variables.  No change required.

Soil Layer:
Hydraulic conductivity
Soil depth

Land Use Layer:
IA
VC
InitSat

**Comment by FLO-2DKaren** [comment]
New Method RTIMP

EFF - Intersect to soil to grid layer.  Store result   Area weighted EFFgrid* 0.01.    

New Layer:
Intersect Soil and Land Use
Result:  Max(Rockout, RTIMPlu) = RTIMPmax

Final Calc
Intersect (RTIMPmax, Grid)*EFFgrid

**Comment by FLO-2DKaren** [comment]
Take care with the moving window code.  It works and speeds up the process significantly.
Review code session with Nate to id the code lines that are isolated for the moving window.

**Comment by saberraz** [comment]
Needs further discussions to better understand the requirements.

**Comment by FLO-2DKaren** [comment]
EFF requirement

New group for these layers.
![image](https://user-images.githubusercontent.com/20424460/162270919-f892d8f9-5878-48d7-b720-68691d423859.png)

New EFF Areas user layer goes in this group.
New EFF Calculator goes on the Infiltration Widget.

Isolate the Maricopa County Method
![image](https://user-images.githubusercontent.com/20424460/162271222-5e10f40b-a182-433a-a7af-818c2b5521e5.png)

Add standard Green Ampt Method.  Nate will help us define this but basically, it will apply a more fully functional Green-Ampt that includes dtheta and soil suction spatial averaging.  We can base it on the Department of Transportation method.

**Comment by FLO-2DKaren** [comment]
@FLO-2DKaren rebuild lesson 1 and update for Vincent.

**Comment by FLO-2DKaren** [comment]
@vcloarec 

Hi Vincent.  I just made this project for you.  

https://flo-2d.sharefile.com/d-sa6587132e03a47468135d6806b92e7f6

The current infiltration instructions are here:
https://documentation.flo-2d.com/Workshops/Lesson%201%20Part%203.html#step-7-assign-infiltration

**Comment by FLO-2DKaren** [comment]
@vcloarec 

Now that you have isolated the EFF, how is it to be applied?  I think we need an EFF button here.

![image](https://user-images.githubusercontent.com/20424460/167842566-c65deb80-ace9-4fbe-9527-288187daaf7d.png)

**Comment by FLO-2DKaren** [comment]
@vcloarec 
The final piece of the Infiltration Puzzle:  This still needs to be accomplished.

New RTIMP Method:
Intersect Soil and Land Use
Result: Max(Rockout, RTIMPlu) = RTIMPmax

RTIMPgrid = Intersect(RTIMPmax, Grid)

**Comment by vcloarec** [comment]
@FLO-2DKaren 
The EFF is applied when you launch "Calculate Green-Ampt", the value in the layer "Area Green Ampt" take account of EFF.

The new RTIMP method is implemented in https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/pull/823

**Comment by FLO-2DKaren** [comment]
@vcloarec Yes I'm just realizing this over the past 30min.  Testing is going well.  I still need to test it on a large project.  Sorry for the dumb comment.  I should just didn't see any comment about the new method.

**Comment by FLO-2DKaren** [comment]
Notes for large project testing.
4 million cells = 11 min to create grid
Infiltration calc started at 2:41.  I don't see the moving window in action.  I don't see the tracker.  Maybe these would be good additions.

**Comment by FLO-2DKaren** [comment]
Restart test at 3:20.  Ran spatial Index on landuse and soil layer first.

**Comment by FLO-2DKaren** [comment]
@vcloarec 
The Rtimp Grid calculation is still not applied correctly.  The current method is calculating the rtimp soil for a grid element and rtimp landuse for a grid element and then taking the max of those values.

It is supposed to calculate rtimp max parts between the soil and landuse layer and then intersect that to the grid to calculate a weighted average.

So it looks like this

rtimpparts = intersection(soilrockout, landrtimp)  Then keep max from those parts.
rtimpgrid = intersection(rtimpmaxparts, grid) then apply the weighted average of those to the grid element.

**Comment by FLO-2DKaren** [comment]
@vcloarec Hi Vincent,

We also need to remove the if rtimp >1 statement because it shouldn't ever be greater than 1 now.

**Comment by vcloarec** [comment]
@FLO-2DKaren , calculation should be better with https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/pull/834
