### ISSUE TITLE
Actions

### ISSUE THREAD

**Issue by FLO-2DKaren** [FLO-2DSoftware/qgis-flo-2d-plugin#767]
Verify that our testing actions are still valid.

**Comment by ldebek** [comment]
All actions seems to work just fine.

**Comment by FLO-2DJJ** [comment]
@FLO-2DKaren can this issue be closed?

**Comment by FLO-2DKaren** [comment]
@FLO-2DJJ No there are a lot that are being skipped.  I'd like to not skip any.  Can we meet to see them?

**Comment by FLO-2DKaren** [comment]
@vcloarec 
Hi Vincent, 
Can you fix these?   I think they are easier for you.  There are some new files that might need to be added.  I'll do a review and put a link in here.

**Comment by FLO-2DKaren** [comment]
Move to #786
