### ISSUE TITLE
Breach.DAT export 

### ISSUE THREAD

**Issue by FLO-2DKaren** [FLO-2DSoftware/qgis-flo-2d-plugin#775]
![Breach data export wrong](https://user-images.githubusercontent.com/20424460/142261963-31559b16-98e5-4976-b93a-a74ff841e2f3.png)

**Comment by FLO-2DKaren** [comment]
You can close the issue too if you've fixed it.

**Comment by FLO-2DKaren** [comment]
![Breach data line 2 error](https://user-images.githubusercontent.com/20424460/142264006-9181404f-7580-45a9-befe-2d45ac38e60a.png)
@FLO-2DJJ 
Hi JJ,  I've confirmed that this issue is still wrong.  The Line 2 needs to be B2 not B1.  I think the rest is OK.

**Comment by FLO-2DKaren** [comment]
@FLO-2DKaren Upload test project Module 6

**Comment by FLO-2DKaren** [comment]
Here is the test data.  The test steps are to Export the data files and look in breach.dat.  
https://flo-2d.sharefile.com/d-s46fdeeba2ee2431ab168ea77e1fc6eb7

**Comment by FLO-2DKaren** [comment]
@FLO-2DJJ 
I understand why you think this is correct.  It is because you are saving the global data as a default.  That is also wrong.

The default of this switch should be unchecked.
![image](https://user-images.githubusercontent.com/20424460/160258297-9e1b8070-e3c5-4eb4-9f8c-f8d0a1769804.png)

The individual breach data file should look like this:
![image](https://user-images.githubusercontent.com/20424460/160258316-4d68d7d7-ec43-4996-8402-e6aae66dee5d.png)

**Comment by FLO-2DKaren** [comment]
Video Example: https://transcripts.gotomeeting.com/#/s/34b54106d19bf93c73743817846f66c1d73e5b4f9205d96edcd8c17c27a6f52e

**Comment by FLO-2DJJ** [comment]
Thanks Karen for the recording.
I see your point now. I got the error now. I'll fix it.


Juan Jose Rodriguez
FLO-2D Software
www.flo-2d.com
***@***.***

**Comment by FLO-2DJJ** [comment]
@FLO-2DKaren The B2 problem is solved in the new plugin. 
It works with"Use global breach data" checked or not. The default is now unchecked, but need to create a new geopackage since the default is set there.
Please test it again.
