### ISSUE TITLE
New Realtime Rainfall Calculator

### ISSUE THREAD

**Issue by FLO-2DKaren** [FLO-2DSoftware/qgis-flo-2d-plugin#777]
Program the new real time rainfall calculator.

- [ ] Add import export functionality.
- [ ] Add calculator to the Rainfall Widget.
- [ ] Remove extra decimals (4 may be sufficient. Currently 6)
- [ ] Test 

These are related or duplicated: https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/issues/777, https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/issues/790, https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/issues/819, https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/issues/820

**Comment by FLO-2DNoemi** [comment]
@FLO-2DJJ I have an example that we can use to add this.

**Comment by FLO-2DNoemi** [comment]
Getting rid of zeroes will substantially reduce the size of the RAINCELL.DAT.

**Comment by FLO-2DKaren** [comment]
I think this should also be done from rasters not asc files.

**Comment by FLO-2DKaren** [comment]
All other jobs are done on this issue.  I might close this one and open a fresh one so we have a blank slate.
