### ISSUE TITLE
RainARF IE Issue

### ISSUE THREAD

**Issue by FLO-2DKaren** [FLO-2DSoftware/qgis-flo-2d-plugin#780]
1. When RainARF is calculated from Raster, it is stored as rainfall depth.
2. When RainARF is imported from a project, it is imported as a factor.
3. When RainARF is exported, it uses an averaging calculation to set the rainARF.  This only works for number 1.  We need a solution for number 2.  haha number 2.

**Comment by FLO-2DKaren** [comment]
@FLO-2DKaren upload an imported rainarf project for Lukasz.

**Comment by FLO-2DKaren** [comment]
https://flo-2d.sharefile.com/d-sca3041c79b4c4851adbdc3a32c14fdfe

Details on fixing this one.
1. Use two different export functions.
2. If a data was imported, the Export the data directly from that layer.
3. If the data was calculated from a raster, Export the data like normal.
4. Make the Import function only add data to the user layer.

Here is the video showing the error.
https://attendee.gotowebinar.com/recording/1090271752438990861

Probably have to register to see it.

**Comment by vcloarec** [comment]
@FLO-2DKaren , a naive question. Why not considering only the factor value in all tables and import/export in any case. 

That is, when sampling the rainfall, instead of recording the depth value, maybe it is better to calculate de factor before recording it in the "Rain ARF Cells" table ?

**Comment by FLO-2DKaren** [comment]
@vcloarec,  

Rainarf is a ratio of the value at the cell over the max of all values in the cell.  So if you wanted to do it the way you are suggesting, you would need to use zonal statistics on the raster to get that max value so you could calculate the ratio rainarf on the fly.   I was just trying to come up with the easiest solution that could be fixed fast.

**Comment by FLO-2DKaren** [comment]
Tested and approved

**Comment by FLO-2DKaren** [comment]
oops closed this too soon.

**Comment by FLO-2DKaren** [comment]
Testing Complete Fixed
