### ISSUE TITLE
Python Modules

### ISSUE THREAD

**Issue by FLO-2DKaren** [FLO-2DSoftware/qgis-flo-2d-plugin#782]
Can you see if QGIS team will add hdf5 and h5py modules to the stand alone installer.

**Comment by ldebek** [comment]
@FLO-2DKaren h5py is only available as an extra package available in OSGeo4W installer. I'm not aware of any plans to incorporate it within QGIS standalone installer.

**Comment by FLO-2DKaren** [comment]
@ldebek 

OK can you help me formulate a simple method for people who are using the Stand Alone installer?

Testing on QGIS 3.18.2  (my stand alone installation)
I used the OSGEO4W shell to install h5py.  I looked in all 3 paths to make sure h5py is located present.  Everything seems OK.

`**C:\>py3_env**
C:\>SET PYTHONHOME=C:\PROGRA~1\QGIS3~1.18\apps\Python37
C:\>SET PYTHONPATH=C:\PROGRA~1\QGIS3~1.18\apps\Python37;C:\PROGRA~1\QGIS3~1.18\apps\Python37\Scripts
C:\>PATH C:\PROGRA~1\QGIS3~1.18\apps\Python37;C:\PROGRA~1\QGIS3~1.18\apps\Python37\Scripts;C:\PROGRA~1\QGIS3~1.18\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\system32\WBem

**C:\>pip install h5py**
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: h5py in c:\users\flo-2d gpc\appdata\roaming\python\python37\site-packages (3.2.1)
Requirement already satisfied: numpy>=1.14.5; python_version == "3.7" in c:\progra~1\qgis3~1.18\apps\python37\lib\site-packages (from h5py) (1.19.1)
Requirement already satisfied: cached-property; python_version < "3.8" in c:\users\flo-2d gpc\appdata\roaming\python\python37\site-packages (from h5py) (1.5.2)
WARNING: You are using pip version 20.2.2; however, version 22.0.3 is available.
You should consider upgrading via the 'C:\PROGRA~1\QGIS3~1.18\bin\python3.exe -m pip install --upgrade pip' command.`

Check the Import from FLO-2D Plugin and get this message.
![image](https://user-images.githubusercontent.com/20424460/152569558-eac2de09-2f29-45dd-aed1-4f24664efb5c.png)

**Comment by FLO-2DKaren** [comment]
@ldebek informed me that this was not an option.  I'm closing it.
