### ISSUE TITLE
Levee Duplicate Error Message

### ISSUE THREAD

**Issue by FLO-2DKaren** [FLO-2DSoftware/qgis-flo-2d-plugin#783]
![image](https://user-images.githubusercontent.com/20424460/149364357-a2343f1a-8cca-4a18-8301-733817bf7dbc.png)

This error message shows up on only one project.  Can you see what's happening and if there is a fix?  This error message happens when the remove duplicate schema levees occurs.  

@FLO-2DKaren Upload the project

**Comment by FLO-2DKaren** [comment]
Here is the project.
https://flo-2d.sharefile.com/d-s8d409a7e3df941b38fe4e1d965f007fa

**Comment by FLO-2DKaren** [comment]
Just run this tool to get the fail message.
![image](https://user-images.githubusercontent.com/20424460/149432755-d2dc8ef9-cbd4-410f-a02b-1be983758ed3.png)

**Comment by FLO-2DJJ** [comment]
Hi @FLO-2DKaren, Could you confirm that this is an issue with new projects?
The error occurs in the geopackage of the project you linked on Jan 13, but I could not reproduce it in new projects.

In any case, the error occurs in rutine 'delete_levee_directions_duplicates_np' lastly modified by Luckasz Debek on 03-28-2021

**Comment by FLO-2DKaren** [comment]
@FLO-2DKaren 
Needs a new test project.

**Comment by FLO-2DKaren** [comment]
@vcloarec 

Hi Vincent,

Here is a new test project and it still fails.
https://flo-2d.sharefile.com/d-sc521a73e03f047a0a5eb2bbf4fdb5a3c
