### ISSUE TITLE
Failed Action Test

### ISSUE THREAD

**Issue by FLO-2DKaren** [FLO-2DSoftware/qgis-flo-2d-plugin#786]
@ldebek I'm adding a failed action test to your project.  Maybe we should wait for JJ to finish the code and then fix the action test.

1. mult.dat import test was missing 2 variables on line 1.  I added them but the test still failed.
2. I think the test is failing because of the new code JJ is adding to the import lines in the flo2dgeopackage.py.  Let's wait for him to finish his work and then fix the action test.
3. There will be another file to add to the action list.  We can look at it when JJ is finished.

@FLO-2DJJ 

1. Ignore the failed test for now and finish the multiple channel code.
2. Move the multiple channel layers into their own group like we discussed.  Since they are only used by advanced modelers, we have some freedom with their organization.

**Comment by FLO-2DKaren** [comment]
@ldebek Lukasz,  I think this is new so it isn't covered by the maintenance work order.  I think we can add it to a new work order and we can discuss it when you aren't so busy.

**Comment by ldebek** [comment]
@FLO-2DKaren Should I then  have a look at this issue or @FLO-2DJJ will handle that?

**Comment by ldebek** [comment]
@FLO-2DKaren @FLO-2DJJ  I've checked test issue and it seems that it's caused by last dir DAT files checkes like here: https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/blob/d33726bab45216da2f548149382a201798af4fee/flo2d/flo2d_ie/flo2dgeopackage.py#L719
Putting this kind of logic in `flo2dgeopackage.py` is bad idea, as it suppose to contain methods for already parsed data. Files presence checks should be moved to the `ParseDAT` class from `flo2d_parser.py` module.

**Comment by FLO-2DKaren** [comment]
@ldebek 
Thanks Lukasz.  That makes sense.  We'll fix it.

@FLO-2DJJ 
Hi JJ,  Can you fix this?  I'm sure you can take that line out and it would sort the issue.

**Comment by FLO-2DJJ** [comment]
OK. I'll put the check of presence of file and emptiness outside
flo2dgeopackage.py, and into the flo2d_parser.py module.

Juan Jose Rodriguez
FLO-2D Software
www.flo-2d.com
***@***.***

**Comment by ldebek** [comment]
Thanks @FLO-2DJJ :) It would be good to move all those checks (from other imports/expors) from flo2dgeopackage.py into the flo2d_parser.py to keep consistency of the source code.

**Comment by FLO-2DJJ** [comment]
I already deleted or moved all file checks from flo2dgeopackage.py to
flo2d_parser.py
but pushing the plugin into GitHub still fails during the tests.

I made local tests to the changes/extensions to exporting/importing
MULT.DAT and the new SIMPLE_MULT.DAT without problems.

Something else is happening. Do you see the problem Lucasz? Thanks


Juan Jose Rodriguez
FLO-2D Software
www.flo-2d.com
***@***.***

**Comment by FLO-2DKaren** [comment]
@vcloarec Hi Vincent,  We have a lot of skipped tests in our system.  I would like a little help with these.  I don't want you to fix them.  I want you to go over a few of them with us and we can fix them.

**Comment by FLO-2DKaren** [comment]
Note::  I think these failed and skipped tests might help us understand why an old gpgk won't import into a new gpkg so I think it's important to get the skipped tests working.

**Comment by vcloarec** [comment]
For the failing `test_export_mult`
> I made local tests to the changes/extensions to exporting/importing MULT.DAT and the new SIMPLE_MULT.DAT without problems. Something else is happening. Do you see the problem Lucasz? Thanks

I think the problem come from here: https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/blob/c2b7e03ed708c48f716583f33e6e0933c50a8de0/flo2d/flo2d_ie/flo2d_parser.py#L505

I issue here, two potential issues:
- first, in text environment, under Linux, the variable `last_dir` is empty, so the import can't work
- second, not sure the using `r"\MULT.DAT"` works under Linux, it is better tu use `"/MULT.DAT"`  if it works under Windows.

**Comment by vcloarec** [comment]
Following skip tests are working find on my side:

`test_flo2dgeopackage.py/test_import_chan`
`test_flo2dgeopackage.py/test_import_xsec`
`test_flo2dgeopackage.py/test_export_chan`
`test_flo2dgeopackage.py/test_export_xsec`

`test_schematics_tools.py/test_get_intervals`
`test_schematics_tools.py/test_interpolate_along_line`

**Comment by vcloarec** [comment]
`test_flo2dgeopackage.py/test_export_breach`
During test, the table levee_data is empty. To success some levee with adapted data has to be imported first, that is the file LEVEE.DAT has to be adapted. Then using `self.f2g.import_levee()` at the begining of the test make it sucessful.

**Comment by FLO-2DKaren** [comment]
@FLO-2DJJ Hi JJ,  Do you want Vincent to fix the failing tests?  I asked him to review some of them and then tell us how to fix them.  I think we should fix them and activate the skipped ones.

**Comment by FLO-2DJJ** [comment]
Let me review the current test code first. Just a quick look and then ask
Vincent if required. It won't take much time. I'll do it this afternoon.

**Comment by FLO-2DKaren** [comment]
@vcloarec   I just sent you an email with details.  I'll copy it here too so you don't have to keep that email.
[Action Test Update Files.zip](https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/files/9011445/Action.Test.Update.Files.zip)

1.	def test_import_infil(self):  Fix test
a.	data file seems ok.  Don't know why test is failing.  Maybe it's the R lines.  Maybe they can't be mixed with that data.
b.	Add another test for Horton example.

2.	def test_import_chan(self):
a.	Fix test
b.	See new data file CHAN.DAT.  E lines on the end.
c.	Set n to 0.04 (our default)

3.	def test_import_xsec(self):
a.	Fix test
b.	datafile OK

4.	def test_import_sed(self):
a.	file seems ok but logic might be more complex.  Maybe we can't mix some of these lines.

5.	def test_import_mult(self):
a.	MULT.DAT corrected file.  It was missing variables.
b.	SIMPLE_MULT.DAT new file needs to be added to the list of tests.
c.	Fix test

6.	def test_import_sed(self):
a.	Fix test
b.	Data file seems ok for a logit test.  It contains all elements of the file.  There may be some logic that doesn’t allow for mixed data types.  
c.	Let me know if you can’t get it to work.  I know just enough about this file to be dangerous.

7.	def test_export_cont(self):
a.	New possible stuff in here.  Time series switches have changed a bit.
b.	See new data on line 8.  
c.	Plugin has a bug.  It is writing too many variables on line 8.  I think its writing the default graphic time interval.  That should left off if LGPLOT = 0 and added to Line 9 if Timeseries is printed.

8.	def test_export_chan(self):
a.	No idea why its skipped

9.	def test_export_xsec(self):
a.	No idea

10.	def test_export_mult(self):
a.	New data files 

11.	def test_export_sed(self):
a.	See import skip.  Maybe need more logic on this one.

12.	def test_export_breach(self):
a.	This one was writing the data wrong.  B lines were in the wrong.  Both writing B1
b.	G lines are not needed when B2 is used.
c.	So maybe this logic needs to be revised.  I’m pretty good at these so I can answer questions.

13.	def test_export_swmmflort(self):
a.	This one got a new variable.  The Inlet name is now listed in addition to the grid element.
b.	See new file
c.	Actually, this file is about to get a bit more complicated.  I’ll send along a newer one once I understand how it works.

**Comment by vcloarec** [comment]
for 2 (test_import_chan), to test the new CHAN.DAT file provided, we need also the associated file CHANBANK.DAT and XSEC.DAT

**Comment by FLO-2DKaren** [comment]
@vcloarec 
They are the same two files.  I just added some text to the end of the chan.dat file that you already had in the test folder.

**Comment by vcloarec** [comment]
for 7. def test_export_cont(self), do you have a description of the CONT.DAT file, especially for new value?

**Comment by vcloarec** [comment]
> for 7. def test_export_cont(self), do you have a description of the CONT.DAT file, especially for new value?

More generally, is there a recent document that describes the *.DAT files content?

**Comment by FLO-2DKaren** [comment]
@vcloarec 
Here is the data input manual.  Each *.dat file is linked in the table of contents.  The variable ITIMTEP has the new line options.

The manual is not finished so it might be missing something.

https://flo-2d.sharefile.com/d-s5a94178ac27342bdbb73bcdb230318da
