### ISSUE TITLE
ARF WRF Calculator Bug 

### ISSUE THREAD

**Issue by FLO-2DKaren** [FLO-2DSoftware/qgis-flo-2d-plugin#791]
In QGIS Build 3.22, the ARF WRF calculator gives an error when using Blocked Areas.

![image](https://user-images.githubusercontent.com/20424460/156192203-0450020d-1c18-46bf-8069-72f4cbf2c481.png)

This is referencing the is_table_empty function in geopackage_utils.py around line 295.  I think it might be a sqlite query issue.

Here is a project for testing.
https://flo-2d.sharefile.com/d-s1de652a6f6e144a38dfe8502f79de096

To get the failure, Run the ARF/WRF calculator in the Grid Tools area.

**Comment by FLO-2DKaren** [comment]
@FLO-2DJJ 

Another easy fix.  
grid_tools_widget.py
line 694

Change: 
            if not self.gutils.is_table_empty("arfwrf"):

To:
            if not self.gutils.is_table_empty("user_blocked_areas"):

**Comment by FLO-2DJJ** [comment]
I tested the given project in QGIS 3.22 without error.
"arfwrf" is a SQLite view based on table/layer "blocked_cells" not "user_blocked_areas".  Line 694 asks for blocked cells that already exist because they will be overwritten. I think that's correct.

**Comment by FLO-2DKaren** [comment]
@FLO-2DJJ 

I'm using 3.24 and it's not working.  

I don't know why sqlite query is checking arfwrf.  There is no such table as arfwrf.    

It's probably applied as an alias but not correctly.  It's used in the user_blocked_areas table and the blocked_cells table in two different locations. It's also used in a several definitions.

**Comment by FLO-2DKaren** [comment]
@FLO-2DJJ , check your QGIS 3.22 python version because it is probably python 3.7 and that's why the query is still working.  QGIS 3.24 is python 3.9.

**Comment by FLO-2DKaren** [comment]
Test Complete
