### ISSUE TITLE
Correct elevation blocked areas not working

### ISSUE THREAD

**Issue by FLO-2DKaren** [FLO-2DSoftware/qgis-flo-2d-plugin#792]
The correct elevation for blocked areas tool is not working. 
![image](https://user-images.githubusercontent.com/20424460/156204393-3a7fbd90-327f-4df9-8bb2-c7e65e27b15e.png)

Here is a test project: https://flo-2d.sharefile.com/d-s1de652a6f6e144a38dfe8502f79de096

No error message.  
It doesn't correct the elevation.  
Not working in any version of QGIS.  
The external method is working but it is slightly different.

- No request filter
- No cell_size
- Uses poly2grid instead of poly2poly

see elevation_correctors.py

**Comment by FLO-2DKaren** [comment]
I think I found the problem.  The request is looking for 1 but the value is true not 1.

`    def elevation_within_arf(self, calculation_type):
        if calculation_type == "Mean":

            def calculation_method(vals):
                return sum(vals) / len(vals)

        elif calculation_type == "Max":

            def calculation_method(vals):
                return max(vals)

        elif calculation_type == "Min":

            def calculation_method(vals):
                return min(vals)

        else:
            raise ValueError
        feats = self.grid.getFeatures()
        feat = next(feats)
        cell_size = feat.geometry().area()
        qry_values = []
        qry = "UPDATE grid SET elevation = ? WHERE fid = ?;"
        request = QgsFeatureRequest().setFilterExpression('"calc_arf" = 1')
        for fid, parts in poly2poly(self.blocked_areas, self.grid, request, False, "fid", "elevation"):
            gids, elevs, subareas = [], [], []
            for gid, elev, area in parts:
                if area / cell_size < 0.9:
                    continue
                gids.append(gid)
                elevs.append(elev)
            if not elevs:
                continue
            elevation = round(calculation_method(elevs), 3)
            for g in gids:
                qry_values.append((elevation, g))
        cur = self.gutils.con.cursor()
        cur.executemany(qry, qry_values)
        self.gutils.con.commit()`

**Comment by FLO-2DKaren** [comment]
Test this one by checking the grid element elevation inside a Blocked Areas polygon.  All cell elevations inside the polygon should be the same.

**Comment by FLO-2DKaren** [comment]
@FLO-2DJJ This one is still broken.

**Comment by FLO-2DJJ** [comment]
@FLO-2DKaren

Line 374 changed (request is now None):

        # request = QgsFeatureRequest().setFilterExpression('"calc_arf" = 1')
        request = None
        for fid, parts in poly2poly(self.blocked_areas, self.grid, request, False, "fid", "elevation"):

Look Ok to me now. See it and close issue if you agree.

**Comment by FLO-2DKaren** [comment]
Tested
