### ISSUE TITLE
SD:   export_swmmflort .fetchone() or .fetchall() ?

### ISSUE THREAD

**Issue by FLO-2DJJ** [FLO-2DSoftware/qgis-flo-2d-plugin#793]
Currently is fetchone(). Should it be fetchall() and do something with repeats?                
  inlet_type = self.execute(
                    "SELECT intype FROM swmmflo WHERE swmm_jt = ?;", (gid,)
                      ).fetchone()

**Comment by FLO-2DKaren** [comment]
@FLO-2DJJ 
Do you want me to help with this?  I assume it's a comment for Noemi but I can probably help.

**Comment by FLO-2DJJ** [comment]
That's a comment for myself. I need to see what happens in both cases.

**Comment by FLO-2DNoemi** [comment]
Ok, let me know if this is related to a bug so I can help you.

**Comment by FLO-2DJJ** [comment]
.fetchone() is the correct statement

**Comment by FLO-2DJJ** [comment]
This is not clear. Thre are cases where there is more than one record with different inttypes for the same swnn_jt. Why?

**Comment by FLO-2DJJ** [comment]
@FLO-2DNoemi , @FLO-2DKaren. Code around the issue was modified to capture the situation when one grid has more than one inlet. Warning given. However, If one of the inlets is of type 4 it is included in SWMMFLORT.DAT.

**Comment by FLO-2DNoemi** [comment]
JJ,

Let's talk about this today.

Noemi
