### ISSUE TITLE
SQ Lite Operational Error

### ISSUE THREAD

**Issue by FLO-2DKaren** [FLO-2DSoftware/qgis-flo-2d-plugin#794]
@FLO-2DJJ,  

Hi JJ, I'm giving this one to you because it's another easy fix.  My comment below shows how to fix it.

QGIS 3.24 Export Data Files results in the following error.  

An error has occurred while executing Python code:

**Comment by FLO-2DKaren** [comment]
Changing these two lines will fix this error.
dlg_components.py   line 198  Replace “arfwrf” with “blocked_cells”
flo2dgeopackage.py  line 1972  Replace  “arfwrf” with “blocked_cells”

**Comment by FLO-2DKaren** [comment]
This one is still broken:
![image](https://user-images.githubusercontent.com/20424460/159708234-6dccd9c8-72af-4570-b5e9-428117fefeb2.png)

**Comment by FLO-2DKaren** [comment]
@FLO-2DJJ 
This is just another calling of arfwrf where it should be set to a table.  This one is a little odd.  Maybe it should be checking blocked_areas or user_blocked_areas.    

File: grid_tools_widget.py
Line 694

Change this line:
            if not self.gutils.is_table_empty("arfwrf"):
to this:
            if not self.gutils.is_table_empty("user_blocked_areas"):

**Comment by FLO-2DJJ** [comment]
It should be 'blocked_areas'. I'll fix it for the next commit.

**Comment by FLO-2DKaren** [comment]
Test complete.
