### ISSUE TITLE
Outfall Fixed Depth not written

### ISSUE THREAD

**Issue by FLO-2DKaren** [FLO-2DSoftware/qgis-flo-2d-plugin#795]
@FLO-2DJJ 

Hi JJ,
If I try and set a Fixed head on an outfall, it isn't being written to swmm.inp.

![image](https://user-images.githubusercontent.com/20424460/159927579-81da904a-445a-4a83-b410-a51ea8b6fbe0.png)

The value should be written right here in the red box.

![image](https://user-images.githubusercontent.com/20424460/159927728-5aa0b9fa-a14e-4eda-b052-75b344b234d3.png)

It is a Stage not a depth so you will need to change that in the plugin.

![image](https://user-images.githubusercontent.com/20424460/159928558-33dda757-b49e-4937-8326-1866f5c8e91f.png)

**Comment by FLO-2DKaren** [comment]
@FLO-2DJJ 
Don't forget.  That variable is a Stage not a Depth.  You need to change the label for it.

**Comment by FLO-2DNoemi** [comment]
JJ,

This is a mistake. It should be *Fixed stage*: water elevation for a fixed
type of boundary condition (ft)

**Comment by FLO-2DJJ** [comment]
Fixed and tested.
