### ISSUE TITLE
Mult lines and Simple Mult Lines Error

### ISSUE THREAD

**Issue by FLO-2DKaren** [FLO-2DSoftware/qgis-flo-2d-plugin#799]
If I try and copy a line from Simple mult line into mult line, the line disappears.  The table is updated but the line disappears.

JJ can look for a Clear Geometry or any trigger that might be clearing his table. 

Karen needs to build a clean dataset for testing.

**Comment by FLO-2DKaren** [comment]
@FLO-2DJJ Hi JJ,  This test is very easy.  You can do it on any project.

Start edit on Mult Chan Line.
Make new Line
Save and stop editing.
Start editing
Modify current line (Node tool or attribute)
As soon as you modify the line, it disappears from the map and from the attribute table.

Here is a video.
https://transcripts.gotomeeting.com/#/s/2b58bf1de405268b415d8dd1e3c0866844d2eb429f49fc6560fa476894fd4d54

**Comment by FLO-2DKaren** [comment]
@FLO-2DJJ 
I did confirm this test on a clean model.  It is still failing.  You can use my process above to test your own data.

**Comment by FLO-2DJJ** [comment]
@FLO-2DKaren an updated plugin merged into GitHub solves this problem. 
(Need to create a new project for changes made to triggers in db_structure.sql )

**Comment by FLO-2DKaren** [comment]
@FLO-2DJJ OK thanks JJ.  I'll get back to testing tonight.

**Comment by FLO-2DKaren** [comment]
The mult line stays in place now.  I will now continue the testing on using mult lines and simple mult lines.  I'm closing this issue and if something comes up, I'll enter it under a different issue.
