### ISSUE TITLE
Combined Mult.dat and SimpleMult.dat Redundant Issue

### ISSUE THREAD

**Issue by FLO-2DKaren** [FLO-2DSoftware/qgis-flo-2d-plugin#800]
@FLO-2DJJ 

If the simple mult line touches the same cell as the mult line, it will be listed in both data files.
**Mult.DAT is the priority**  remove the redundant grid from simple_mult.dat.

![image](https://user-images.githubusercontent.com/20424460/160217466-b09ccbdd-f7c2-4543-ba2b-f0d5922be0f4.png)

In the following image.  Mult line is Red.  Simple Mult line is Yellow.  

![image](https://user-images.githubusercontent.com/20424460/160217484-b46aad89-e93b-4ca5-99d8-54b39c942ffb.png)

**Comment by FLO-2DKaren** [comment]
Video: https://transcripts.gotomeeting.com/#/s/8ea1014c7ad9cfea08d661c309f3b7e2cbce2b63a48534a8e78726ac9e54eff2

Data:  https://flo-2d.sharefile.com/d-s68b02154387a490fa848cf56b94af903

**Comment by FLO-2DJJ** [comment]
Issue fixed. @FLO-2DKaren please test it and close it.

**Comment by FLO-2DKaren** [comment]
Tested no redundant cells.
