### ISSUE TITLE
Dask and Distributed Missing

### ISSUE THREAD

**Issue by FLO-2DKaren** [FLO-2DSoftware/qgis-flo-2d-plugin#801]
If you try and click this button, you will get a fail message.
![image](https://user-images.githubusercontent.com/20424460/160217830-90cd13fc-628e-4abd-bcae-08fa4ddb4e8b.png)

It requires DASK and DASK Distributed python modules.

Try the following:
Run as Admin  OSGEO4W Shell
commands:
o-help
pip install dask
pip install dask distributed --upgrade

**Comment by FLO-2DKaren** [comment]
If the pip command don't work, contact me.  You probably have too many pythons installed and the paths are getting mixed up.

**Comment by FLO-2DKaren** [comment]
Here's a video: https://transcripts.gotomeeting.com/#/s/9f8e9575d6a71745a742998cc74c5e2e4cdf0ad1de50d6e713f499b01cafba78

**Comment by FLO-2DKaren** [comment]
@FLO-2DJJ We can probably post these instructions in the Error Message.

**Comment by FLO-2DKaren** [comment]
Put the fix in the User's Manual.

**Comment by FLO-2DKaren** [comment]
Research how to install:
**Dask
Distributed
H5py**
in the Plugin installer.  Nate Vaughn knows how to do this.

**Comment by rpachaly** [comment]
Ok, this is a relevant issue and we discussed this today Karen. Every library that is **not native** on QGIS python should be imported within the function where it is called inside a try/except block. If the user does not have the library installed, in the exception it should be asked if he would like to install it automatically (must have admin rights) or manually (show a little tutorial). I'll fix this for the libraries that we currently use that are not native (e.g. dask, distributed, h5py, swmmio) and make a video explaining the code. 

Here is a list of the native installed python libraries with QGIS:

C:\Program Files\QGIS 3.28.11>pip list
Package            Version
------------------ -----------
affine             2.4.0
attrs              20.2.0
certifi            2020.6.20
chardet            3.0.4
click              7.1.2
click-plugins      1.1.1
cligj              0.7.0
coverage           5.3
cycler             0.10.0
decorator          4.4.2
ExifRead           2.3.2
Fiona              1.9.4.post1
fonttools          4.28.5
future             0.18.2
GDAL               3.7.2
geographiclib      1.50
geopandas          0.13.2
httplib2           0.18.1
idna               2.10
importlib-metadata 2.0.0
Jinja2             3.1.2
kiwisolver         1.2.0
lxml               4.6.2
MarkupSafe         1.1.1
matplotlib         3.5.1
mock               4.0.2
networkx           2.5
nose2              0.9.2
numpy              1.24.1
OWSLib             0.29.2
packaging          20.4
pandas             2.0.2
Pillow             9.2.0
pip                23.1.2
plotly             4.12.0
ply                3.11
psycopg2-binary    2.9.3
Pygments           2.7.2
pyodbc             4.0.30
PyOpenGL           3.1.5
pyparsing          2.4.7
PyPDF2             3.0.1
pypiwin32          223
pyproj             3.6.0
PyQt5              5.15.4
PyQt5-sip          12.8.1
pyserial           3.5
python-dateutil    2.8.1
pytz               2023.3
pywin32            304
PyYAML             5.3.1
rasterio           1.3.8
reportlab          4.0.4
requests           2.24.0
retrying           1.3.3
scipy              1.10.1
setuptools         67.6.0
shapely            2.0.1
simplejson         3.17.2
sip                6.1.1
six                1.15.0
snuggs             1.4.7
toml               0.10.1
typing_extensions  4.5.0
tzdata             2023.3
urllib3            1.25.11
wxPython           4.2.0
xlrd               1.2.0
xlwt               1.3.0
zipp               3.4.0

**Comment by rpachaly** [comment]
Check this out

https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/assets/39889306/83bcf3a7-989e-4d49-9d28-463424c99c92

I'm going to create a pull request.

**Comment by FLO-2DKaren** [comment]
Hi Robson,  

I think this is a good idea and will work well.  I agree that you cannot use that process to install h5py.  I have never successfully installed h5py without running the OSGEO installer and adding it through that system.

**Comment by FLO-2DKaren** [comment]
This is in the documentation.  I'm closing it.
