### ISSUE TITLE
Hydraulic Structures Editor: allow table editing but skip some plots

### ISSUE THREAD

**Issue by FLO-2DJJ** [FLO-2DSoftware/qgis-flo-2d-plugin#802]
Allow table editing but skip plots for rating curves, culvert eq. , and bridge routine. 
There are error messages when editing table for rating curve and culvert equation.
Rating table is ok.
For bridge routine just clear table and plot.

**Comment by FLO-2DJJ** [comment]
This is issue was fixed. @FLO-2DKaren , @FLO-2DNoemi please tested before close it.

**Comment by FLO-2DKaren** [comment]
Tested
