### ISSUE TITLE
Rating Table Warning Error 

### ISSUE THREAD

**Issue by FLO-2DKaren** [FLO-2DSoftware/qgis-flo-2d-plugin#803]
@FLO-2DJJ 

Hi JJ,  I got this error when I used the load rating table button.

![image](https://user-images.githubusercontent.com/20424460/161393416-5b2ce2c1-7ee2-40af-adf7-53ec235d71be.png)

The problem is that the code is trying to write the rating table warning text file to the Last SWMM Directory.  I deleted that directory before I clicked the button.

I think if we set the variable to last_dir, it would write the warning file to the same directory as the rating tables.  That is probably the best place for it.

        if not rating_files:
            return
        s.setValue("last_dir", os.path.dirname(rating_files[0]))
        QApplication.setOverrideCursor(Qt.WaitCursor)
        try:

**Comment by FLO-2DKaren** [comment]
@FLO-2DJJ 
Did you miss this one?  It is similar to another one.

**Comment by FLO-2DJJ** [comment]
@FLO-2DKaren 
The Warnings.CHK file is written to the same directory where the rating tables are being loaded from. 
So, the directory exists at that same moment. 
I could not reproduce the error.
Could you guide me?

**Comment by FLO-2DNoemi** [comment]
Hi JJ  and Karen,

The best place to write the CHK file is the project directory.

**Comment by FLO-2DKaren** [comment]
At this stage, the project directory may not be available.  It is a pre-run
process so there may not be a project run folder available.

**Comment by FLO-2DKaren** [comment]
@FLO-2DJJ I can give you some guidance.  

To get this to fail, follow these steps.
1. export inp to a location that is different from the rating tables file.
2. delete that folder that you just exported to (this simulates moving to another project)
3. Try and load the rating tables.

**Comment by FLO-2DJJ** [comment]
Thanks Karen, I followed your suggested steps and still don't get the
error. The 'Rating Table Warnings.CHK' is created in the folder of the
rating tables.

?

Juan Jose Rodriguez
FLO-2D Software
www.flo-2d.com
***@***.***

**Comment by FLO-2DKaren** [comment]
@FLO-2DJJ OK let's fix it when we see the error again. Maybe you sorted that variable when you made  the other change for me.
