### ISSUE TITLE
Update message storm drain

### ISSUE THREAD

**Issue by FLO-2DKaren** [FLO-2DSoftware/qgis-flo-2d-plugin#804]
@FLO-2DJJ 

Change Outfall to outfall

![image](https://user-images.githubusercontent.com/20424460/161394115-7fcab5e2-9c7a-4396-96c3-176419a119be.png)

**Comment by FLO-2DKaren** [comment]
storm_drain_editor_widget.py

Line 464

        if self.schematize_inlets_and_outfalls():
            self.uc.show_info(
                "Schematizing Storm Drains finished!\n\n"
                + "The storm drain Inlets, **outfalls,** and/or rating tables were updated.\n\n"
                + "(Note: The ‘Export Data Files’ tool will write the layer attributes into the SWMMFLO.DAT, SWMMFLORT.DAT, and SWMMOUTF.DAT files)"

**Comment by FLO-2DJJ** [comment]
Fixed. Issue may be closed.

**Comment by FLO-2DKaren** [comment]
Tested
