### ISSUE TITLE
Save swmm.inp redirect

### ISSUE THREAD

**Issue by FLO-2DKaren** [FLO-2DSoftware/qgis-flo-2d-plugin#805]
@FLO-2DJJ 

Hi JJ,  There is a problem with the Last SWMM directory.  It is being set for a wrong path when the user uses the GDS export.  I think we can fix it if we set the last_dir to FLO-2D/project_directory

storm_drain_editor_widget.py

Line 1538
            last_dir = s.value("FLO-2D/project_dir", "")

The problem I am seeing is that my end users are not resetting the directory when they try and export using the Export GDS button.  So the SWMM directory is being set to the  storm drain tables or shapefiles or some other old directory.

**Comment by FLO-2DJJ** [comment]
Fixed. Path now is redirected to latest GDS directory as in:
last_dir = s.value("FLO-2D/lastGdsDir", "")  
Issue may now be closed.

**Comment by FLO-2DKaren** [comment]
Tested
