### ISSUE TITLE
inp_groups.ui parameter

### ISSUE THREAD

**Issue by FLO-2DKaren** [FLO-2DSoftware/qgis-flo-2d-plugin#806]
@FLO-2DJJ 

Can you update this file? There was a squished label that wasn't showing correctly.  I corrected it in this file.
[inp_groups.zip](https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/files/8403250/inp_groups.zip)

**Comment by FLO-2DJJ** [comment]
Updated. Other changes and fixes to dialog via Qt Designer. Issue may be closed after testing.

**Comment by FLO-2DKaren** [comment]
tested
