### ISSUE TITLE
Skip Orifices if not present

### ISSUE THREAD

**Issue by FLO-2DKaren** [FLO-2DSoftware/qgis-flo-2d-plugin#807]
@FLO-2DJJ  
Can you add some code to skip writing the ORIFICES in the swmm.inp if the tables are empty or not present.  

I want to keep working with this plugin and not go backward but I know you aren't finished with the ORIFICE code.

![image](https://user-images.githubusercontent.com/20424460/161651479-7e22deff-2537-42f9-8aa6-f66423eb7269.png)

**Comment by FLO-2DJJ** [comment]
Close issue. Similarly, the potential problem was solved for pumps and weirs.
