### ISSUE TITLE
unable to load a project

### ISSUE THREAD

**Issue by vcloarec** [FLO-2DSoftware/qgis-flo-2d-plugin#810]
When loading a project, there are some warnings, then a python error occurs:

![image](https://user-images.githubusercontent.com/7416892/162980571-f8c5542b-b982-4e3c-98a9-1c5f97fac86d.png)

**Comment by vcloarec** [comment]
@FLO-2DKaren , I am trying to load the files from: 
https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/issues/780
and
https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/issues/770

**Comment by FLO-2DKaren** [comment]
@vcloarec 
Did you try to build a blank geopackage and then import the old gpkg file into the new one?

**Comment by vcloarec** [comment]
ok, it works with data in #780 (but not with #770)

**Comment by FLO-2DKaren** [comment]
The import into blank gpkg doesn't work with 770?
OK I was aware that some of the data wasn't importing.  Maybe we can study where it gets stuck and see a way to fix it. 

I don't know which table it's getting stuck on.  Is there a way to modify the import report so we could see more detail?

**Comment by FLO-2DKaren** [comment]
@FLO-2DJJ 
You should be importing the old gpkg not the *.dat files.  I only say this because there is a bug in that import gpkg tool and sometimes the data won't load.  If you use that as el modus operandi, you will find that when an old gpkg file won't load into a blank file, you can understand why and fix it.  I was going to bring this up with you anyway but I was waiting for us to finish a few more important things.

**Comment by FLO-2DKaren** [comment]
@FLO-2DJJ FYI, the project that Vincent is working on it just QGIS Lesson 1 data so it's super easy to fix.  I already posted a link that can load into the latest plugin.

**Comment by FLO-2DKaren** [comment]
@FLO-2DJJ @FLO-2DNoemi 
Hi JJ and Noemi,  During June, I would like to investigate this issue.  Here is a test project that will not import into a blank geopackage.

https://flo-2d.sharefile.com/share/view/s60bec0cef9434db3a78939e4a6289e92

**Comment by FLO-2DKaren** [comment]
Hi JJ,

I think the storm drain data is one problem with the gpkg import not running.  If you try to import this gpkg file into a clean gpkg, it won't load.  It simply hangs and spins and if you close it and reload it, you will only get the grid and channel data.

https://flo-2d.sharefile.com/d-s4697c565e0f04f9dae6e759d01a84993

**Comment by FLO-2DJJ** [comment]
Hi @FLO-2DKaren,

I've found that one problem with Lesson 1.gpkg is table 'infil_areas_green'. I changed the code temporality to skip it and the import completes without problem. However, I do not see any change to that table since 2 years ago, I'll continue looking at the issue with that particular table.

**Comment by FLO-2DKaren** [comment]
OK thanks JJ,   Look at the EFF field.  We replaced that with the Effective Impervious Areas layer so that field shouldn't be part of the Infiltration layers anymore.  Can you skip the import of that?

**Comment by FLO-2DJJ** [comment]
> @FLO-2DJJ @FLO-2DNoemi Hi JJ and Noemi, During June, I would like to investigate this issue. Here is a test project that will not import into a blank geopackage.
> 
> https://flo-2d.sharefile.com/share/view/s60bec0cef9434db3a78939e4a6289e92

My tests do import this geopackage without problem to a new blanks geopackage.

**Comment by FLO-2DKaren** [comment]
@FLO-2DJJ here is  a test with only 400 infiltration features

https://flo-2d.sharefile.com/d-sf65476e3a22c47f5ae406d20e9bf2f6e

It loads but takes too much time.

**Comment by FLO-2DNoemi** [comment]
Jj,

Look into the storm drain. I am also sure this is an issue importing geopackages.

Noemi

Noemi’s Iphone

**Comment by FLO-2DKaren** [comment]
@FLO-2DNoemi

Noemi the whole green ampt storage has been simplified so if you and JJ
can’t figure this out, let know because I know what was updated.
