### ISSUE TITLE
Structures Editor - Culvert of Conduit Width

### ISSUE THREAD

**Issue by FLO-2DNoemi** [FLO-2DSoftware/qgis-flo-2d-plugin#814]
In the structures editor, Culvert of Conduit Width should be changed to **_Circular diameter or box culvert height_** . This needs to be updated.

The  Culvert of Conduit width is actually the CuBase in the FLO-2D Table Editor.

**Comment by FLO-2DJJ** [comment]
Was closed because the label was changed according to the requested change
