### ISSUE TITLE
Write/Read RAINCELL.DAT with only values greater than zero

### ISSUE THREAD

**Issue by FLO-2DJJ** [FLO-2DSoftware/qgis-flo-2d-plugin#819]
1. - [ ] For each time series always write/read first and last cells AND in between only cells with values greater than zero. The idea to write the first and last cells is to determine beginning/end of each time series. And to reduce the size of the file by only having rows of cells with values greater then zero. Explore other possible solutions.
2. - [ ] Could this affect the writing of binary HDF?
3. - [ ] @FLO-2DNoemi will do the same in the model.

These are related or duplicated: https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/issues/777, https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/issues/790, https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/issues/819, https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/issues/820

**Comment by FLO-2DJJ** [comment]
Overlaps issue #790

**Comment by FLO-2DJJ** [comment]
@FLO-2DKaren let me know if we continue with this issue or close it without doing it. 
The idea of this issue is to reduce the size of RAINCELL.DAT, but..
changing the format of RAINCELL.DAT (as described in point 1 -only writing cells with values greater then zero) also requires changes in RAINCELL.HDF5 and external programs that use those files (the District? other users?).
Please tell me how to proceed with this issue.

**Comment by FLO-2DKaren** [comment]
Let's keep our replies on #777.  We should probably close this issue and just work on #777
