### ISSUE TITLE
Groups

### ISSUE THREAD

**Issue by FLO-2DKaren** [FLO-2DSoftware/qgis-flo-2d-plugin#824]
@vcloarec 

Can you make these groups?

![image](https://user-images.githubusercontent.com/20424460/166553341-a22984dd-e366-4b82-920e-96aaef95ad87.png)

**Comment by FLO-2DKaren** [comment]
If you make those, I can clean them up at my convenience.  I just didn't know how to use subgroups.

**Comment by FLO-2DKaren** [comment]
Putting a pause on this.

**Comment by FLO-2DJJ** [comment]
@FLO-2DKaren , @FLO-2DNoemi I've been trying to group some layers into subgroups of User Layers. It's been not possible to group them inside the User Layers but I managed to group them as "User Layers. Boundaries", "User Layers. Channels", etc.

![imagen](https://user-images.githubusercontent.com/20424575/203251391-7c5a267c-19e5-4c08-9e5b-98206005eb07.png)

See if you like this or prefer to mantain the previous Layers tree. 
(See the plugin in GitHub)
NOTE: you need to create a new project.

**Comment by FLO-2DKaren** [comment]
@FLO-2DJJ 
Hi JJ,

Since you are using QgsLayerTreeGroup, you might be able to use an addgroup before you build the layers.  Like if you build the groups before you build the layer tree then you can call the group.

https://qgis.org/pyqgis/3.2/core/Layer/QgsLayerTreeGroup.html#qgis.core.QgsLayerTreeGroup.addGroup

**Comment by FLO-2DKaren** [comment]
Not possible closing
