### ISSUE TITLE
Sediment Transport: add functionality for polygons for Supply Areas, Regid Bed Areas, and Mud Areas 

### ISSUE THREAD

**Issue by FLO-2DJJ** [FLO-2DSoftware/qgis-flo-2d-plugin#827]
Geometric layers already exist for building Supply Areas, Regid Bed Areas, and  Mud Areas polygons. 

- [x] Need to intersect polygons to grid.
- [x] Read, save, and edit resulting cells in Sediment Transport dialog.
- [x] Correlate resulting intersected cells with Sediment Supply Rating Curves and Mud Debris Basin Parameters wherever required. 
- [x] Review import/export SED.DAT

**Comment by FLO-2DKaren** [comment]
Closing this because it is finished.  See Sediment Transport Group Error for next code mods.
