### ISSUE TITLE
Weir Correction

### ISSUE THREAD

**Issue by FLO-2DKaren** [FLO-2DSoftware/qgis-flo-2d-plugin#837]
@FLO-2DJJ 
Hi JJ,

Is Crest Height the same as Inlet Offset?
Length is spelled wrong.

![image](https://user-images.githubusercontent.com/20424460/170398067-78df2bdf-0ef1-4120-bb49-d4f58c207309.png)

**Comment by FLO-2DJJ** [comment]
@FLO-2DNoemi could you answer @FLO-2DKaren question?

**Comment by FLO-2DKaren** [comment]
@FLO-2DKaren @FLO-2DJJ I found it online.  I'm OK.

**Comment by FLO-2DNoemi** [comment]
JJ,

Let's review this in the plugin today or tomorrow. I have some additional
comments.

I will answer Karen's question.
