### ISSUE TITLE
Import gpkg slow

### ISSUE THREAD

**Issue by FLO-2DKaren** [FLO-2DSoftware/qgis-flo-2d-plugin#840]
@vcloarec @saberraz 

The update and import of infiltration areas / infiltration tables is taking too long.  I don't know if this is a result of a new QGIS or if it is related to the gpkg table update triggers.  I am getting over 10 minutes to update a table with only 50,000 rows.  Even updating data with only 400 rows is taking way too long.

Can you please look into this?  It is a critical issue and needs to be prioritized.  We may need to add another support funding so I cc'd Saber too.

**Comment by FLO-2DKaren** [comment]
You can try to import this geopackage or you can edit any of the infiltration tables and the problem will be obvious because the little rotating circle doesn't go away.

https://flo-2d.sharefile.com/d-sdf46d364c88845338eeda6a1bbce0584

The problem is likely with all of the infiltration tables not just Green Ampt.

**Comment by vcloarec** [comment]
It comes from the triggers... When the layer "Areas Green Ampt" is modified (insert, update delete), the table "Cells Green Ampt" is sync by triggers. Theses triggers seems very costly and make every operation quite long.

I am wondering of the utility of this "Cells Green Ampt"  that is a table that links grid fid to the infiltration grid fid.
Maybe I am wrong, but, it seems the infiltration grid has always the same geometry than the main grid, no?

In that case we have always one grid feature for one infiltration feature. In that case why not simply store the grid fid in the "Areas Green Ampt" layer. So we would  not need anymore the table "Cells Green Ampt" , and so, no need anymore the costly triggers.

But maybe, I don't know enough the plugin and I miss something.

**Comment by FLO-2DJJ** [comment]
'Cells Green Amp'  is in fact table 'infil_cells_green' which is used in
several methods:

import_infil
export_infil
schematize_infiltration (called from the Infiltration Editor widget)
calculate_green_ampt

and of course when triggers are activated whenever there is an insert,
update or delete of  'Areas Green Ampt' (table 'infil_areas_green').

What Vincent is suggesting (store the grid fid in the "Areas Green Ampt"
layer) could be the solution but I wonder if there could be unexpected
implications due to the several places where the tables are used.

Juan Jose Rodriguez
FLO-2D Software
www.flo-2d.com
***@***.***

**Comment by FLO-2DKaren** [comment]
@vcloarec @FLO-2DJJ 

Hi Vincent,

If I remember correctly, the idea was to collect similar infiltration grids in blocks so that layer wasn't so bulky.  However, each cell usually different numbers because of the area weighted averaging.  The data is always 1 for 1 infiltration to grid.  I think simply having a table of values is preferable.

JJ do you agree?

**Comment by FLO-2DJJ** [comment]
@Karen OBrien ***@***.***>, @vcloarec <https://github.com/vcloarec>

Sorry, but without looking at the details of the code for this
functionality, which is distributed in several places of the plugin, I
can't  tell at this moment whether what you are suggesting works.At first
sight it doesn't look trivial.

Juan Jose Rodriguez
FLO-2D Software
www.flo-2d.com
***@***.***

**Comment by vcloarec** [comment]
Indeed, it is not trivial, but I think it is feasible to not use anymore the "Areas Green Ampt" layer but only the table "Cells Green Ampt". In this table we can put the all the parameters. 
I give a try for green ampt.

**Comment by FLO-2DJJ** [comment]
👍

Juan Jose Rodriguez
FLO-2D Software
www.flo-2d.com
***@***.***

**Comment by FLO-2DKaren** [comment]
@vcloarec 
That would be really awesome.  I appreciate your input and help.  Please let Saber know if we need additional funding and I'll work on that with him.

**Comment by FLO-2DKaren** [comment]
@vcloarec 
Hi Vincent.  I merged #844 and it is now working correctly for the RTIMP Import error fix and the speed and the RTIMP calculation.  That is excellent.

Can we return to this issue for the slow import?

Karen

**Comment by FLO-2DKaren** [comment]
This issue is solved and tested.  
@vcloarec Thanks Vincent.  All 3 infiltration types work great.  I did some additional updates to the SCS number because it should be an integer so you might way to update your local repo.
