### ISSUE TITLE
Green Ampt Error

### ISSUE THREAD

**Issue by FLO-2DKaren** [FLO-2DSoftware/qgis-flo-2d-plugin#844]
@vcloarec 

Hi Vincent,
I got this error when trying to calculate green ampt.  Can you please fix it for me.  
![image](https://user-images.githubusercontent.com/20424460/171907781-bb95e542-7a53-4fa1-bb8f-4fc862de8512.png)

Here's the project
https://flo-2d.sharefile.com/d-s63af289cc1614faf9eb63413ca54f738

**Comment by vcloarec** [comment]
I've already find this issue working on #840. I am on it.

**Comment by FLO-2DKaren** [comment]
OK I was just doing more testing and added an eff polygon and the error changed.

**Comment by FLO-2DKaren** [comment]
PS.  Thanks!!!
