### ISSUE TITLE
Create Storm Drain Discharge plots

### ISSUE THREAD

**Issue by FLO-2DJJ** [FLO-2DSoftware/qgis-flo-2d-plugin#847]
See plots created in GDS under directory StormDrainDischarge <date>.
Like this:
![image](https://user-images.githubusercontent.com/20424575/172843574-cbe9817a-1688-45ef-a0d2-3a7d161591ee.png)

**Comment by FLO-2DNoemi** [comment]
Create plots for the Storm Drain Discharges for inlet/junctions and outfalls from a SWMM.OUT/SWMM.RPT output file.

Similar to GDS:  Tools/Storm Drain/Storm Drain Discharge Display/from external .RPT

Output files are read, and plots are created for the entire storm drain system automatically. 

This tool is needed to review the storm drain system response during the storm drain development and to generate plots for final run.

**Comment by FLO-2DKaren** [comment]
Should we give this to Lutra.  We are giving them other tasks like this.

**Comment by FLO-2DJJ** [comment]
@FLO-2DNoemi , @FLO-2DKaren  Please review the plugin with this new functionality to create SD discharge plots.
Let's meet to explain it.

**Comment by FLO-2DJJ** [comment]
@FLO-2DNoemi , @FLO-2DKaren

To see each individual plot use the FLO-2D info tool:

![imagen](https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/assets/20424575/355a0a2b-df0d-42af-bd54-ebab714324b5)

and click on the desired Storm Drain node:

![imagen](https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/assets/20424575/e7edba46-323e-4016-9a56-8185396594f3)

The data and plot will be shown in the FLO-2D Table Editor and FLO-2D Plot: 

![imagen](https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/assets/20424575/0e25a236-a0e2-48a1-bf29-7dacf68314d5)

The Info Tool has now a menu item to preselect the desired .RPT file for the plots:

![imagen](https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/assets/20424575/b91f82e8-9086-4c0c-b17a-5c325fcf312f)

all subsequent plots will be based on the data from the preselected .RPT file. No need to select it again unless you want to use time series data from another .RPT file.

By the way, the "Info Tool" and "Grid Info Tool" buttons are now toggled. Clicking them will select/unselect them. I believe this was due. Previously it was not easy to return to a  "normal" state.

**Comment by FLO-2DKaren** [comment]
This is awesome!!! Can you also add the swmmin.out and swmmoutfin.out files too?

**Comment by FLO-2DKaren** [comment]
![image](https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/assets/20424460/fbcfa932-2d7b-41bf-88fc-84a6fd73f0b7)

**Comment by FLO-2DJJ** [comment]
Yes, it can be done for the .OUT files too. Could you send one or two of projects with those files?

**Comment by FLO-2DNoemi** [comment]
JJ,

I sent it two simple test cases with those OUT files.

Let's review them in our meeting tomorrow.

Noemi

**Comment by FLO-2DJJ** [comment]
@FLO-2DNoemi , @FLO-2DKaren 
The master repository in GitHub now has an updated plot fro Storm Drain discharges. The plot has a new legend, axis labels with units, and a new title.
![image](https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/assets/20424575/8b705345-8fa3-4205-ad93-5126f029e075)

Please review it and comment.

**Comment by FLO-2DNoemi** [comment]
Good Morning JJ,

Discharge should be (CFS or CMS) depending on the unit system: english or
metric.

Let's review this together. The image shows outfall results, we should see
less items in the plot.

Noemi

**Comment by FLO-2DJJ** [comment]
@FLO-2DNoemi , @FLO-2DKaren 
The pull request '**Issues 907 and 720 sd culvert equations**' (awaiting for approval in GitHub) although it refers to issues related to SD Inlets type 4, also includes other previous improvements related to this #847 issue, discharge plots. 
It has the following:
A right click on the plot lists of the name of the graphs in the legend, with a check box that hides/shows the corresponding time series:
![imagen](https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/assets/20424575/108f587d-0336-4613-b3e1-a85f0b70eb51)

For instance, if you only want to see Total Inflow:

![imagen](https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/assets/20424575/802b0f41-fae3-4cb4-a55f-12d1f2f605ba)
![imagen](https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/assets/20424575/e9d70112-472d-4b34-b5cd-c9d383030f31)

I would like to meet you to show the details of this functionality.

**Comment by FLO-2DKaren** [comment]
@FLO-2DJJ @FLO-2DNoemi 

I'd like to have a meeting when you all have time.  Maybe Monday is better, but I can meet today too.

**Comment by FLO-2DKaren** [comment]
I think the functionality of this is OK for now.  Maybe we can add conduits in the future but I'm going close the issue for now.
