### ISSUE TITLE
Add text area to all SD dialogs to include help descriptions for  each variable/parameter/field

### ISSUE THREAD

**Issue by FLO-2DJJ** [FLO-2DSoftware/qgis-flo-2d-plugin#851]
Components Dialogs;
- [ ] Inlets/Junctions
- [ ] Outfalls
- [ ] Conduits
- [ ] Pumps
- [ ] Orifices
- [ ] Weirs

From shapefile:
- [ ] Inlets/Junctions
- [ ] Outfalls
- [ ] Conduits
- [ ] Pumps
- [ ] Orifices
- [ ] Weirs

**Comment by FLO-2DKaren** [comment]
@FLO-2DJJ 

JJ, We could also add a link that opens the manual at this feature.  Since that data is already well documented in the User Manual.

**Comment by FLO-2DKaren** [comment]
@FLO-2DNoemi @FLO-2DJJ Help button to manual to a specific subsection.  

Reminder how to do the help button and link look at the elevation point tool that Gyan made.

**Comment by FLO-2DKaren** [comment]
This seems pretty old.  I'm going to close it here but we can consider expanding tooltips in future.
