### ISSUE TITLE
Simple Storm Drain Hystrruc bug

### ISSUE THREAD

**Issue by FLO-2DKaren** [FLO-2DSoftware/qgis-flo-2d-plugin#852]
@FLO-2DJJ 

Hi JJ,

The plugin saves the D line in hystruct.dat in the wrong place. It should be the last line.  
Look in flo2dgeopackage.py on line1921.

Here's a test project.
 https://flo-2d.sharefile.com/d-s05913b9b6c0149c1a93cec4fe52d7bb5

**Comment by FLO-2DJJ** [comment]
Fixed: D lines are now written at end of HYSTRUC.DAT

**Comment by FLO-2DKaren** [comment]
Tested with 2 different d lines.  Working good.
