### ISSUE TITLE
Orifice bug

### ISSUE THREAD

**Issue by FLO-2DKaren** [FLO-2DSoftware/qgis-flo-2d-plugin#855]
@FLO-2DJJ 

Hi JJ,

1. There are a lot of places in the code where the word orificies is used instead of orifices.  It's causing some problems.  Can you please change these so that the plugin calls the correct names and has the correct button spellings.  It seems to be OK to change them all to orifices.

2. This line in the auto assign is not working.  See the last "else".  That is resetting the field to conduits instead of allowing Orifices to be used.  It was also calling a table called orificies instead of orifices so it was always defaulting to assign the conduits instead of the Orifice table.  Maybe you should and error message instead of a default.

storm_drain_editor_didget.py

        try:
            QApplication.setOverrideCursor(Qt.WaitCursor)
            layer = (self.user_swmm_conduits_lyr if link_name == "Conduits"  else
            self.user_swmm_pumps_lyr if link_name == "Pumps" else  
            self.user_swmm_orifices_lyr if link_name == "Orifices" else  #FixedKJOB6-24-2022
            self.user_swmm_weirs_lyr if link_name == "Weirs" else  **self.user_swmm_conduits_lyr)**

**Comment by FLO-2DJJ** [comment]
Received. I'll take care of it.

**Comment by FLO-2DKaren** [comment]
Thanks.  I'm working on the tutorial for pumps orifices and weirs so that's why I'm doing this now.

**Comment by FLO-2DJJ** [comment]
@FLO-2DKaren: Fixed. You can test it and close it.

**Comment by FLO-2DKaren** [comment]
Tested OK
