### ISSUE TITLE
water depth to fixed stage

### ISSUE THREAD

**Issue by FLO-2DKaren** [FLO-2DSoftware/qgis-flo-2d-plugin#856]
@FLO-2DJJ 

JJ,  I found more labels and one possible field that are wrong. 

Water Depth should be  Fixed Stage or fixed_stage

![image](https://user-images.githubusercontent.com/20424460/175779594-d4804172-3a7f-48dd-8470-6605cd001932.png)

![image](https://user-images.githubusercontent.com/20424460/175779607-bbdb6fac-d096-423e-b3ef-f24f9900ebb8.png)

I added an alias to this one so I can keep working and do the documentation.  I don't know if you want to change the user field or not.  Maybe an alias can be added to the geopackage when you set the table up.
![image](https://user-images.githubusercontent.com/20424460/175779635-5ddad463-26fb-4f8a-b926-90083b737063.png)

**Comment by FLO-2DNoemi** [comment]
If we want to use a different description than Fixed stage, we could also
use Water Elevation but water depth is incorrect.

**Comment by FLO-2DKaren** [comment]
Done
