### ISSUE TITLE
Crest Height

### ISSUE THREAD

**Issue by FLO-2DKaren** [FLO-2DSoftware/qgis-flo-2d-plugin#857]
@FLO-2DJJ @FLO-2DNoemi 
Hi JJ,

I might have made a mistake and asked you to use crest height instead of inlet offset because I thought it was easier to understand.    Now that I'm building some lessons, I see that it makes more sense as Inlet Offset than crest height.  I can do this or you can do it but I think going back to Inlet Offset is best.

Noemi, let me know your opinion. 

![image](https://user-images.githubusercontent.com/20424460/175830374-2bcfcefe-9e17-4e0a-8b61-f329973886e6.png)

![image](https://user-images.githubusercontent.com/20424460/175830469-4324574e-d487-4210-a4cb-4e71684f35dd.png)

**Comment by FLO-2DNoemi** [comment]
Karen,

I agree with you that should be Inlet Offset instead of Crest Height. If if
I am not mistaken, JJ has that change in his list of changes for the SD
system. I think it is better if you let him modify it because he is doing
other updates now to the SD.

**Comment by FLO-2DKaren** [comment]
Finished
