### ISSUE TITLE
ARF/WRF GitHub Merge Problem

### ISSUE THREAD

**Issue by FLO-2DKaren** [FLO-2DSoftware/qgis-flo-2d-plugin#858]
@FLO-2DJJ @vcloarec 

It looks like JJ has set the arf/wrf calculator back in time a bit.  He pushed an absolute value correction that Vincent had already fixed but he inadvertently undid all of Vincent's new code.  

I'm surprised that we've only had this problem 3 times given how complex the code is.

Vincent, 
Can you please fix this?  I think it is easier for you to fix it because you know what you've worked on.

JJ, 

You will need to rebase your local repo once Vincent corrects this.  
Please start using branches for everything now.  That way we can do code comparisons before we accept a merge.

**Comment by vcloarec** [comment]
@FLO-2DKaren , it looks like my code was not overwritten.
Can you tell me more about the issue?

**Comment by FLO-2DKaren** [comment]
@vcloarec Oh thank goodness.  OK that's good.  So it's taking 4 min to calculate Lesson 1 ARFs.  It's usually less than 1 min.  I'm going to test a larger dataset.  I'll get back to you.

@FLO-2DJJ Sorry JJ,  I was wrong about your code.

**Comment by FLO-2DKaren** [comment]
@vcloarec 
It takes 26 min to calculate a large dataset.  I think that's about right.  I wonder why my small project increased in time?  Maybe it's the collapse correlation?  If that is tied to the Building Polygons, maybe a sql trigger is processing more data.  Any thoughts?

**Comment by vcloarec** [comment]
can you share the project and detail steps, so I could reproduce and look at?

**Comment by FLO-2DKaren** [comment]
https://flo-2d.sharefile.com/d-s493bad98246344c5b4e4e1af30601b1a

Just use the ARF/WRF calculator on Buildings or Blocked Areas.  It's taking around 4 min on my computer.  Should be like less than 1 min I think.

**Comment by vcloarec** [comment]
@FLO-2DKaren , 
I am wondering if your attributes table of "ARF_WRF" layer is open when you launch the calculator?
On my side, when this table is open it takes a very long time to proceed. 
But if the tables is closed, my computer need between 10 s and 30 s.

**Comment by FLO-2DKaren** [comment]
I didn’t have my table opened but I did notice what you are talking about.
Sometimes it seems to go fast like normal and sometimes it seems to go slow.

**Comment by vcloarec** [comment]
I have done again some try and my result are quite good (with QGIS 3.26.0): 7 seconds. I think old tries have been done with a debug built  by myself version of QGIS that is quite slower. 

With official QGIS version, it seems OK to me...

**Comment by FLO-2DKaren** [comment]
OK I'm going to ignore it for now. Ha, 7 seconds is pretty awesome.  I'll update right away.  I want to see if my large data projects get improved speed too.

I'll close this.  Thanks for looking into it.
