### ISSUE TITLE
GRAPTIM variable wrong line

### ISSUE THREAD

**Issue by FLO-2DKaren** [FLO-2DSoftware/qgis-flo-2d-plugin#860]
@FLO-2DJJ 
JJ, 

I partially fixed this.  I added lines 1282 and 1283 so the variable is only written when lgplot is not 0.
flo2dgeopackage.py

When you get a chance, see this problem.  I think the conditional code that you added to address itimtep interval is causing GRAPTIM to be written on the wrong line.  It should be the last line and it should only be written if lgplot is 2.

 24.0 0.1 2 0 0 
 1 0 0 0 0
 1 1 0 0 0 0 1
 1 0 0
 0.0 0.0 0.0 0.0 0.9 0.2
 2 3.0
 2
 21 0.25 8.0 22.0 1.1

Should BE

 24.0 0.1 2 0 0 
 1 0 0 0 0
 1 1 0 0 0 0 1
 1 0 0
 0.0 0.0 0.0 0.0 0.9 0.2
 2 3.0
 2
 21 0.25 8.0 22.0 
1.1

**Comment by FLO-2DJJ** [comment]
@FLO-2DKaren looking at the history of the code I see that I mistakenly entered an error from merge 'add_STARTIMTEP_and_ENDTIMTEP_to_CONT.DAT' 5 weeks ago on May 26. Not corrected yet, I'm looking at it.

**Comment by FLO-2DJJ** [comment]
Fixed. @FLO-2DKaren please test it and close this ticket if the fix is correct.
