### ISSUE TITLE
Storm Drain Name Issue

### ISSUE THREAD

**Issue by FLO-2DKaren** [FLO-2DSoftware/qgis-flo-2d-plugin#867]
@FLO-2DJJ 

Hi JJ,  If you already know about this one or fixed it, please close this issue.  I'm working on 0.10.66.

If the name has "i" instead of "I", it wont be written to swmmflo.dat.

Our documentation allows both cases so we can allow both for the plugin.

![image](https://user-images.githubusercontent.com/20424460/186187171-ea4811b9-26de-4478-a303-ca8c75b85c2f.png)

![image](https://user-images.githubusercontent.com/20424460/186187227-f239ec3e-feab-4011-b1ad-e9f72f1e5d2f.png)

**Comment by FLO-2DJJ** [comment]
Issue already solved from version 0.10.69
