### ISSUE TITLE
Incorrect Warning

### ISSUE THREAD

**Issue by FLO-2DKaren** [FLO-2DSoftware/qgis-flo-2d-plugin#868]
@FLO-2DJJ 

This warning is not valid.  The I1, I2 designation in the name does not reflect the storm drain type.  Only the storm drain type reflects the storm drain type. 

The example in Lesson 3 has some data that was changed after the name was made.  The name wasn't changed since it was such a pain to change node names back in the day.

@FLO-2DNoemi  can confirm this.

![image](https://user-images.githubusercontent.com/20424460/186187547-9bbe71f1-db08-45e9-9ce3-36f93f9b838c.png)

**Comment by FLO-2DJJ** [comment]
@FLO-2DNoemi I believe we already agreed to make the first 2 letters of the name reflect the inlet type.

**Comment by FLO-2DKaren** [comment]
The inlet name can be any character set so long as it starts with I or i.  Otherwise, many projects that come from other users may show this error for no reason.  Other users don't use the same name configuration as this project.
@FLO-2DNoemi

**Comment by FLO-2DJJ** [comment]
@FLO-2DJJ: when loading the inlets/junctions dialog make sure that inlets with initial lowercase 'i' and uppercase 'I' are accepted.
@FLO-2DJJ: see the 'populate_inlets' method.

**Comment by FLO-2DKaren** [comment]
Noemi says we can remove this warning.

**Comment by FLO-2DJJ** [comment]
Warning removed.
