### ISSUE TITLE
Fix controls in dialogs and widgets (.ui)

### ISSUE THREAD

**Issue by FLO-2DJJ** [FLO-2DSoftware/qgis-flo-2d-plugin#871]
- [ ] Levees and Breach Editor: Global Failure Mode radio buttons size when shrinking.
- [ ] All widgets: standardize height of QDoubleSpinBoxes and QSpinBoxes.
- [ ] Structures Editor: Rating group: height and width of texts.

**Comment by FLO-2DJJ** [comment]
Review how to make it general from environment variables

**Comment by FLO-2DKaren** [comment]
Hi JJ,

My laptop is the absolute worst computer for scaling the icons and forms correctly.  I am happy to help you research this.

![image](https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/assets/20424460/199a61d5-5f16-4fdb-8e35-52f4498ef71e)

**Comment by FLO-2DKaren** [comment]
Found this here:
https://stackoverflow.com/questions/56974012/qt-designer-how-to-fix-screen-size-disparity

QApplication::setAttribute(Qt::AA_EnableHighDpiScaling);
QApplication::setStyle(QStyleFactory::create("Fusion")); // these lines before the next
QApplication a(argc, argv);

**Comment by FLO-2DKaren** [comment]
More changes for Environmental Variables are found here:

https://doc.qt.io/qt-5/highdpi.html

I use the QT_Auto_Screen_Scale_factor = 1 when I connect to a different resolution external monitor or projector.  

It isn't very helpful for old projectors.

**Comment by FLO-2DJJ** [comment]
- [ ] Hazus Flooding Analysys dialog needs adjustments to fit labels and controls:

![image](https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/assets/20424575/2a26b287-26e9-46c5-9360-a24564bb18be)

**Comment by FLO-2DJJ** [comment]
- [ ] Global street parameters dialog needs adjustments to fit labels and controls:

![image](https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/assets/20424575/8800480e-7083-4c5f-9607-8267c1fbdc60)
