### ISSUE TITLE
Dialog missing elevation field

### ISSUE THREAD

**Issue by FLO-2DKaren** [FLO-2DSoftware/qgis-flo-2d-plugin#872]
@FLO-2DJJ  @FLO-2DNoemi 
Is there supposed to be a tailings dam elevation field in this dialog?

![image](https://user-images.githubusercontent.com/20424460/190633990-9d43e840-97eb-41c9-a7a7-61635171365a.png)

**Comment by FLO-2DJJ** [comment]
Did you created a new project?

**Comment by FLO-2DKaren** [comment]
@FLO-2DJJ 
I am doing it right now.  I'll let you know if anything goes wrong.

**Comment by FLO-2DKaren** [comment]
I don't see a new *.ui file.  Is something missing?

![image](https://user-images.githubusercontent.com/20424460/190709693-abc7bb8e-6dc4-4f13-b795-6a8625f9fe1a.png)

**Comment by FLO-2DKaren** [comment]
Found it
![image](https://user-images.githubusercontent.com/20424460/190711560-607c59ce-ef68-4c22-93b2-0d058f491d39.png)
