### ISSUE TITLE
Why is RAIN.DAT written when there is no rain?

### ISSUE THREAD

**Issue by FLO-2DJJ** [FLO-2DSoftware/qgis-flo-2d-plugin#874]

**Comment by FLO-2DJJ** [comment]
Only write if IRAIN is equal to 1 (Physical processes switches)

**Comment by rpachaly** [comment]
This was addressed on https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/commit/74904c9e6be747b3bb41f0ee83dd87c95c0d25f7
