### ISSUE TITLE
Remove, move, or improve'Model Started' message when running FLOPRO.EXE

### ISSUE THREAD

**Issue by FLO-2DJJ** [FLO-2DSoftware/qgis-flo-2d-plugin#875]

**Comment by FLO-2DKaren** [comment]
@FLO-2DJJ @FLO-2DNoemi 
Here are my thoughts.

**Regular run**
Asyncronous message is OK.  
Take out second message.
![regular run](https://user-images.githubusercontent.com/20424460/197274441-7a3a315c-90c2-41c1-a548-7d8333db68c0.gif)

**Debug Run**
![debug run](https://user-images.githubusercontent.com/20424460/197273899-fc4353e2-f797-4745-be31-8b59c6663276.gif)

The warning is confusing.  Maybe skip the message for Debug?  If someone is using Debug, they probably don't need a message.  They should be advanced enough to know how to import it too.

**Comment by FLO-2DJJ** [comment]
Fixed. @FLO-2DKaren, @FLO-2DNoemi please test it and report to close issue.

**Comment by FLO-2DKaren** [comment]
Hi JJ,

I have an idea for this that maybe a good fix.  See this note:

![image](https://user-images.githubusercontent.com/20424460/200046072-29149625-328e-4d96-a644-07d0b18c87b3.png)

I think we can use this message bar instead of messages you have to close for all of our messaging.

**Comment by FLO-2DJJ** [comment]
Yes @Karen OBrien ***@***.***> many messages could be shown in the
bar instead of dialogs that need to be closed. I'll be transferring them as
identified.

**Comment by FLO-2DKaren** [comment]
This system seems to be broken on my computer. I recommend we take the messages out and simply start the run.

**Comment by FLO-2DKaren** [comment]
Here's a Python warning I'm getting:
2023-01-11T19:15:42     WARNING    warning:C:\Users\FLO-2D GPC\AppData\Local\Programs\Python\Python39\Lib\subprocess.py:1052: ResourceWarning: subprocess 13284 is still running
              _warn("subprocess %s is still running" % self.pid,
             
             traceback: File "C:\Users\FLO-2D GPC\AppData\Local\Programs\Python\Python39\Lib\subprocess.py", line 1052, in __del__
              _warn("subprocess %s is still running" % self.pid,
