### ISSUE TITLE
New Debug File Request

### ISSUE THREAD

**Issue by FLO-2DKaren** [FLO-2DSoftware/qgis-flo-2d-plugin#877]
@FLO-2DJJ @FLO-2DNoemi 

Hi JJ,

Can you please add a few things to the extra files that are read during the Debug Checks?

ARF_ADJUSTMENT.CHK
UndergroundOUTFALLS.CHK
CHAN_INTERIOR_NODES.OUT
ManholePop.OUT

**Comment by FLO-2DKaren** [comment]
@FLO-2DJJ 

JJ, I wonder if we can add the new Debug data to a Group called Debug.  That way the data wouldn't be hidden in the user layers or schema layers.

**Comment by FLO-2DJJ** [comment]
Yes. I'll do that .

**Comment by FLO-2DJJ** [comment]
@FLO-2DKaren, what is the format of the extra files to be read during the debug checks?. These files:

ARF_ADJUSTMENT.CHK
UndergroundOUTFALLS.CHK
CHAN_INTERIOR_NODES.OUT
ManholePop.OUT

**Comment by FLO-2DNoemi** [comment]
@FLO-2DJJ see the following information:

**ARF_ADJUSTMENT.CHK** 
Grid#,3000,Grid element ARF values were adjusted to 1.0 to eliminate the potential for instability related to small surface area.

**UndergOUTFALLS.CHK** @FLO-2DJJ check the name of the file.
GRID,FPE,Outfall,Invert Elevation,Elevation Difference

**CHAN_INTERIOR_NODES.OUT**
GRID

**ManholePop.OUT**
X_coord, Ycoord, GRID, Manhole Name, PopOffTime, Pop Off Pressure Head, RIM + Surch Head, Flo2d WSE

**Comment by FLO-2DJJ** [comment]
The tasks in this issue has been adressed. @FLO-2DKaren , @FLO-2DNoemi could you please test the plugin to see if this issue can be closed?

**Comment by FLO-2DKaren** [comment]
Test
Run QGIS Lesson 3 in Debug mode.
Import debug files
All OK
