### ISSUE TITLE
Structure Editor Storm Drain Capacity

### ISSUE THREAD

**Issue by FLO-2DKaren** [FLO-2DSoftware/qgis-flo-2d-plugin#878]
@FLO-2DJJ 

Hi JJ,

This is in the Structure editor.

This box is not enabled when the checkbox is checked.  I fixed it by always enabling it but I wonder if you can fix it correctly so that it is only enabled when a storm drain is loaded or when the box is checked.

![image](https://user-images.githubusercontent.com/20424460/194777202-acc1fc27-556c-431a-b9fd-6900f202d199.png)

**Comment by FLO-2DJJ** [comment]
Storm Drain Capacity checkbox enables/disables value.
@Karen OBrien ***@***.***> please test and close issue if correct.

Juan Jose Rodriguez
FLO-2D Software
www.flo-2d.com
***@***.***

**Comment by FLO-2DKaren** [comment]
tested
