### ISSUE TITLE
Conflict slightly incorrect

### ISSUE THREAD

**Issue by FLO-2DKaren** [FLO-2DSoftware/qgis-flo-2d-plugin#880]
@FLO-2DJJ 
Hi JJ, this conflict is slightly incorrect.  It is OK  to have an inlet and a junction in one cell but it is not OK to have an inlet and an inlet in one cell.  Can you change the code so that it's only comparing inlets with the "I" or "i" in the name.

![image](https://user-images.githubusercontent.com/20424460/195314503-c6271e76-3307-43ec-a4a9-0b1a8a473566.png)

**Comment by FLO-2DJJ** [comment]
Fixed. @FLO-2DKaren, @FLO-2DNoemi please test it and report to close issue.

**Comment by FLO-2DJJ** [comment]
See issue #868 before cossing it

**Comment by FLO-2DJJ** [comment]
Warning removed.
