### ISSUE TITLE
Failed Action Test

### ISSUE THREAD

**Issue by FLO-2DKaren** [FLO-2DSoftware/qgis-flo-2d-plugin#881]
@FLO-2DJJ 

Hi JJ.  Did you see this failed import test?  I think we should see what's up with this.  I don't think anything in inflow.dat changed so far as the data structure goes.

![image](https://user-images.githubusercontent.com/20424460/195449605-6704ce5a-e398-4cbd-9fe2-ce14c35cc66e.png)

**Comment by FLO-2DNoemi** [comment]
Karen,

I think this may be related to the tailings dam R line in the INFLOW.DAt
file.

@Juan Jose Rodriguez ***@***.***>  Can you check this?. We should be
able to import a regular inflow.dat file with hydrographs, R lines and the
combination of them.

**Comment by FLO-2DKaren** [comment]
Oh right!!!  OK I can ask Lutra to modify the action test and add new action tests for the new tables.
