### ISSUE TITLE
Tidal or Timeseries tables for outfalls

### ISSUE THREAD

**Issue by FLO-2DNoemi** [FLO-2DSoftware/qgis-flo-2d-plugin#883]
@FLO-2DJJ 
Tidal or Timeseries types for outfalls can be assigned but the conditions cannot be created in the plugin. 

A table dialog box to enter the time series table (Time vs values) or the tidal table (Time vs Stage) needs to be added to the plugin.

**Comment by FLO-2DJJ** [comment]
This is the same issue #854

**Comment by FLO-2DJJ** [comment]
Fixed. @FLO-2DKaren, @FLO-2DNoemi please test it and report to close issue.

**Comment by FLO-2DKaren** [comment]
@FLO-2DJJ 
### Tidal Review

The time should be in hours not H:M.

![image](https://user-images.githubusercontent.com/20424460/226951178-b0ff552c-519d-4da4-babf-90c54c1a8d2a.png)

![image](https://user-images.githubusercontent.com/20424460/226949983-0dec0756-f75c-4be6-becd-c075791fad0d.png)

**Comment by FLO-2DKaren** [comment]
@FLO-2DJJ 
We need a Paste Button for of our tables.  
Most of our data comes from Excel or some other tab delimited data.  
You can find the code for this in the regular FLO-2D Plugin Table Editor.
![image](https://user-images.githubusercontent.com/20424460/226967570-9e344d16-2275-42e7-a3f2-3ab814a8719e.png)

**Comment by FLO-2DKaren** [comment]
@FLO-2DJJ 
### Time Table Test - Text File
When I loaded the time series file, I loaded it from here:
"C:\Users\Public\Documents\FLO-2D PRO Documentation\Example Projects\QGIS Tutorials\**QGIS Lesson 3\Basic Storm Drain Shapefiles\TmSeriesTest.txt**"

The Plugin wrote the path differently in the *.inp file.

;StageTest       
Test1            FILE       "C:/Users/Public/Documents/FLO-2D PRO Documentation/Example Projects/**QGIS Tutorials/QGIS Lesson 1/QGIS Issue Tests/Time Series Outfall Test/TmSeriesTest.txt**"
;

**Comment by FLO-2DKaren** [comment]
@FLO-2DJJ 
### Time Table Time Series

Is it possible to lock this format in so that other numbers can't accidentally be added?
![image](https://user-images.githubusercontent.com/20424460/226975644-6dd794e5-4017-4d7e-afe7-9fb32a5678b4.png)

**Comment by FLO-2DJJ** [comment]
Thanks @FLO-2DKaren. I will make the fixes you outline in this ticket:

- [ ] Time should be in hours not H:M.
- [ ] Review Paste Button for of our tables.
- [ ] Paths: review use of  '/' or '\' symbol in directory selected in Time Series when written/read in SWMM.INP file.

**Comment by FLO-2DKaren** [comment]
The time column will currently allow an integer and a decimal value.  Can you limit it to the time H:M format?

**Comment by FLO-2DKaren** [comment]
@FLO-2DJJ 
This is two separate issues.  One for Time Series and one for Tidal Table.

Tidal Table needs time in hours similar to inflow.dat.
Time Series table needs time in H:M format.

**Comment by FLO-2DJJ** [comment]
@FLO-2DKaren and @FLO-2DNoemi,
The code validates time in HH:MM format and dates in MM/DD/YYYY format for the Tidal Curves and Time Series in Inlets and Outfalls.
(NOTE: I had to make a merge to the main branch without making a pull request due to some conflicts that I encountered in the code. Hope everything is fine. Please test this issue and close it if you are satisfied).

**Comment by FLO-2DKaren** [comment]
I'm going to close this because the work is finished.  It just needs a little tweak.  This comment section is now confusing and long so I will add the new suggestion to a new issue.
