### ISSUE TITLE
Bridge Routine Missing Data File

### ISSUE THREAD

**Issue by FLO-2DKaren** [FLO-2DSoftware/qgis-flo-2d-plugin#884]
The bridge routine needs a couple of things.

1. Export BRIDGE_COEFF_DATA.DAT to export folder when bridge is used.
2. Build the BRIDGE_XSEC.DAT file.
[Extra Bridge Data.zip](https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/files/9840353/Extra.Bridge.Data.zip)

![image](https://user-images.githubusercontent.com/20424460/197231083-5c85c23d-3d7a-42c4-8fca-7c290353730a.png)

**Comment by FLO-2DJJ** [comment]
@FLO-2DKaren, @FLO-2DNoemi  could you explain this issue further? I see the BRIDGE_XSEC.DAT in the manual but not the other. Could you send me an updated Manual?

**Comment by FLO-2DNoemi** [comment]
@FLO-2DKaren, I think we should add BRIDGE_COEFF_DATA.DAT to the following directories:

C:\Program Files (x86)\FLO-2D PRO
C:\Program Files (x86)\FLO-2D PRO\Run for Project Folder

 If the user run the simulation from FLO-2D PRO folder (Program Files (x86)), data file will be in that folder. If the user runs the simulation from the project folder, then all the files from Run for Project Folder will be copied to the project folder. Does this make sense? Please let me know your comments.

**Comment by FLO-2DNoemi** [comment]
@FLO-2DKaren    Maybe we can change the extension of the BRIDGE_COEFF_DATA.DAT to something else like TBL (tabular data). This is not a DAT file that is created by the user.

**Comment by FLO-2DKaren** [comment]
Let’s tackle it after the short course. Monday or Tuesday next week we can
look at it together.

> Message ID: <FLO-2DSoftware/qgis-flo-2d-plugin/issues/884/1293828725@
> github.com>
>
-- 
Karen O'Brien
Technical Support

FLO-2D Software | Riada Engineering
P.O. Box 66 | Nutrioso, AZ | 85932
T. 928.339.1935
www.flo-2d.com | ***@***.***

**Comment by FLO-2DNoemi** [comment]
@Juan Jose Rodriguez ***@***.***> you can continue working on creating
the BRIDGE_XSEC.DAT. The format of the file that we discussed this morning
is correct.

We need to discuss the BRIDGE_COEFF_DATA.DAT next Monday with Karen.

**Comment by FLO-2DJJ** [comment]
Write the BRIDGE_COEFF_DATA.DAT file in the project directory when the hydarulic structures are exported. Take the data from a fixed table in db_structure.sql

**Comment by FLO-2DKaren** [comment]
Tested and approved
