### ISSUE TITLE
Error message close QGIS

### ISSUE THREAD

**Issue by FLO-2DKaren** [FLO-2DSoftware/qgis-flo-2d-plugin#885]
@FLO-2DJJ 
I keep seeing this message when I close QGIS.
![image](https://user-images.githubusercontent.com/20424460/197285511-be34085f-5579-4df9-b8ba-b4dc71e61c58.png)

[Ready for Hydraulic Structures.zip](https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/files/9842331/Ready.for.Hydraulic.Structures.zip)

**Comment by FLO-2DJJ** [comment]
Remove provisional 'profile'  lines used for testing speed of routines.
