### ISSUE TITLE
Maybe Future development: expandable/collapsed sections

### ISSUE THREAD

**Issue by FLO-2DJJ** [FLO-2DSoftware/qgis-flo-2d-plugin#886]
See
How to make an expandable/collapsable section widget in Qt

https://stackoverflow.com/questions/32476006/how-to-make-an-expandable-collapsable-section-widget-in-qt

**Comment by FLO-2DKaren** [comment]
@FLO-2DJJ 
That looks pretty good JJ.  I think we should do this.  @FLO-2DNoemi what do you think?

**Comment by rpachaly** [comment]
- [ ] Mud and sediment
- [ ] Levees
- [ ] Control Parameters (maybe)

**Comment by rpachaly** [comment]
https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/assets/39889306/d6e4bc30-03cc-470e-830a-ac01f8096429

**Comment by rpachaly** [comment]
https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/assets/39889306/959882d5-41e0-4408-91e2-5ae22a6eb088

**Comment by rpachaly** [comment]
Both dialogs are on the https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/tree/expandable-collapsed if someone wants to test it.

**Comment by rpachaly** [comment]
https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/assets/39889306/14181759-1498-4a4e-bbfb-e86eaeec2c8b

**Comment by FLO-2DKaren** [comment]
I'm closing this because we've done a great deal of this work.
