### ISSUE TITLE
Mult-Barrel Default

### ISSUE THREAD

**Issue by FLO-2DKaren** [FLO-2DSoftware/qgis-flo-2d-plugin#887]
@FLO-2DJJ 
Please make the mult-barrel default to 1 barrel.  If it defaults to zero, no flow moves through the structure.  This needs to be addressed in both structure editor and storm drain editor.

**Comment by FLO-2DKaren** [comment]
Data with NULL Mult Barrels is being written as 0.0.

Workflow to repeat error.
1. Create a Structure with a culvert equation.
![image](https://user-images.githubusercontent.com/20424460/212382748-cfd689f5-7b45-4910-a338-a49623bdc9ec.png)
2. Fill the culvert eq data
![image](https://user-images.githubusercontent.com/20424460/212382794-c364ec0d-0e22-4fdc-b4c8-ee70f7ef9bdb.png)
3. Schematize structures and export data.  Hystruct.dat has a zero where it should be nothing or 1.
![image](https://user-images.githubusercontent.com/20424460/212382997-2d51aac8-4530-4e37-91a5-ec32eed88cf6.png)

**Comment by FLO-2DKaren** [comment]
Rules for hystruct.dat

The variable can be empty or 1 or more.  It can't be zero.

**Comment by FLO-2DJJ** [comment]
@FLO-2DKaren, @FLO-2DNoemi,
Can the barrels parameter in SD conduits be zero? 

![imagen](https://user-images.githubusercontent.com/20424575/217177356-1f6157b3-cfd2-46aa-997a-08a0022c0531.png)

**Comment by FLO-2DKaren** [comment]
@FLO-2DJJ

I don’t think mult barrels can be zero because it’s like multiplying the Q
by zero.

**Comment by FLO-2DJJ** [comment]
@FLO-2DNoemi , @FLO-2DKaren 
Please review the latest plugin with the fixes to this issue. If you agree with them I will close it.

**Comment by FLO-2DKaren** [comment]
### Storm Drain Test

Can't test this method.  I will close this and add a new issue because I don't know how to build a Culvert Equation for storm drain.
