### ISSUE TITLE
Spelling Issue

### ISSUE THREAD

**Issue by FLO-2DKaren** [FLO-2DSoftware/qgis-flo-2d-plugin#890]
Misspelled word
![image](https://user-images.githubusercontent.com/20424460/215276002-ddbd2c18-529c-48e2-80e5-d5543cd1c8f2.png)

**Comment by FLO-2DKaren** [comment]
Sediment transport tab Gradiation coeff should be Gradation coeff.
I already changed it in my version so I can get the documentation correct.  
I don't like to mess with your code just in case you don't update your code before you do a push.

![image](https://user-images.githubusercontent.com/20424460/215276248-cf583172-ed7e-47c0-9308-c11e9faf3509.png)

**Comment by FLO-2DJJ** [comment]
Fixed
