### ISSUE TITLE
Review the 'User Layers to Schematic layers' convertion tool.

### ISSUE THREAD

**Issue by FLO-2DJJ** [FLO-2DSoftware/qgis-flo-2d-plugin#891]
Does it do anything at all? 
Do the conversion is needed for all components shown?
List the components that really require conversion.

**Comment by FLO-2DKaren** [comment]
@FLO-2DJJ 

Hi JJ,

My idea for this tool was to have a tool that could rebuild the project if you change the grid cell size.  When I think about it, that isn't really possible because so many important things change.  Maybe we can simply eliminate that tool.

Karen

**Comment by FLO-2DJJ** [comment]
Tool removed
