### ISSUE TITLE
HDF5 Structure Simple

### ISSUE THREAD

**Issue by FLO-2DKaren** [FLO-2DSoftware/qgis-flo-2d-plugin#893]
Build an hdf5 structure for:

- [x] cont.dat
- [x] toler.dat
- [x] topo.dat
- [x] mannings_n.dat
- [x] neighbors.dat

**Comment by FLO-2DKaren** [comment]
@FLO-2DNoemi @ldebek 

Hi Noemi,  Can you upload your hdf5 example here?  Please note that the neighbors is also in this group.

**Comment by FLO-2DKaren** [comment]
Hi Lukasz, 
Here is a sample hdf5 file.

[FLO-2D hdf5 Example.zip](https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/files/10972617/FLO-2D.hdf5.Example.zip)

**Comment by FLO-2DKaren** [comment]
@ldebek 

Hi Lukasz,
[FLO-2D hdf5 with neighbors example.zip](https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/files/10973568/FLO-2D.hdf5.with.neighbors.example.zip)

This example has the neighbors and that will be an important part of your hdf5 file.

**Comment by FLO-2DNoemi** [comment]
This file includes the following input:

 cont.dat
 toler.dat
 topo.dat
 mannings_n.dat
 neighbors.dat

 and the following output:

DEPTH.OUT
HYDROSTRUCT.OUT

[FLO-2D HDF5 Input-Output.zip](https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/files/10973678/FLO-2D.HDF5.Input-Output.zip)

**Comment by FLO-2DKaren** [comment]
@ldebek 
Hi Lukasz,  

I have noted some problems on Noemi's hdf5 file that I want you to avoid.   I think we should use **String** for all of our data.  
If we use String, we don't need worry about rounding errors or compound data sets.  

Simple examples:
CONT has string, int, and float in one dataset.
HYSTRUCT.DAT, int, string, and float in one dataset.

Can you foresee any issues related to h5py or QGIS import export if we limit the hdf5 datasets to String?  I foresee that we may need to reformat the data as we load it.
 
Z
Name this ELEV or GRIDELEV.  We have other elevation data and we need this one to be obvious.
  
**X**
Need to stop this rounding.  Y has it too.
 ![image](https://user-images.githubusercontent.com/20424460/226394329-02869463-536a-4e2a-b25a-89ba5a78deaa.png)
 
**Z**
More things that shouldn’t be rounded.
 ![image](https://user-images.githubusercontent.com/20424460/226394301-5b87c15c-1108-4514-9667-57b54956ffb2.png)

**Comment by ldebek** [comment]
@FLO-2DKaren I don't see point of storing float numbers as string. This will just increase HDF5 file size. Your example is probably just a result of rounding a single value to 3 places after the coma for some reason. If we will not use any rounding during import-export, then there shouldn't be any problem with it.

**Comment by ldebek** [comment]
PR: https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/pull/916
