### ISSUE TITLE
Meta Data

### ISSUE THREAD

**Issue by FLO-2DKaren** [FLO-2DSoftware/qgis-flo-2d-plugin#897]
Include meta data with a project

Project Table
Project Name
Contact Engineer Name
email address
QGIS Build
Plugin Build
FLOPRO Build
CRS EPSG Code

**Comment by FLO-2DKaren** [comment]
Just add the meta data table to the gpkg structure.  We'll sort out the io and interface when we start working on hdf5.

**Comment by rpachaly** [comment]
![Image](https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/assets/39889306/2dc8fe1d-2363-49b1-aada-aa8a8a978e02)

This is from where I retrieve the metadata information:

PROJ_NAME -> Name of geopackage
CONTACT -> Project Author (QGIS)
EMAIL -> ??
PLUGIN_V -> metadata.txt
QGIS_V -> qgis.core
FLO-2D -> ??
CRS -> Project CRS

We don't have any information on email and FLO-2D build on the plugin. My idea:

EMAIL -> Add a lineEdit on the settings dialog asking for user email (not required to fill)
FLO-2D -> Add the FLO-2D build release for the current plugin version on the settings dialog as a label and retrieve it from there.

**Comment by FLO-2DKaren** [comment]
I also think it belongs this info belongs on the Settings Form.  If it's blank, that's OK.
The FLO-2D Build might be a little more difficult.  We'll have to figure that one out.

**Comment by FLO-2DKaren** [comment]
Well the problem with listing the flopro build is that it could change depending on which version of the engine someone is using on their project. 
1. Are they running from the project folder?
2. Are they running from FLO-2D Pro folder?

It is printed to cont.dat when the engine runs and to summary.out when the engine runs.   We can discuss it and come up with something.

**Comment by FLO-2DKaren** [comment]
@FLO-2DNoemi 

Hi Noemi,  See the flopro properties.  Can we add a Build number to that when you compile it?

**Comment by rpachaly** [comment]
> Well the problem with listing the flopro build is that it could change depending on which version of the engine someone is using on their project.
> 
> 1. Are they running from the project folder?
> 2. Are they running from FLO-2D Pro folder?
> 
> It is printed to cont.dat when the engine runs and to summary.out when the engine runs. We can discuss it and come up with something.

For the metadata, it should be retrieved from the FLO-2D Pro folder. For a project review, it should be retrieved from summary.out

**Comment by rpachaly** [comment]
New Settings Dialog:

![image](https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/assets/39889306/8a09ecc2-d211-4e5e-b291-a74c9ce7317a)

Metadata Table:

![image](https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/assets/39889306/fad924f5-3605-4137-b3ac-540896dba3a5)

**Comment by FLO-2DKaren** [comment]
Ideas for Build.  Read the "Installed File Date".  Use a lookup table to set the build.  That will give it backward compatibility.

**Comment by rpachaly** [comment]
Do you have a lookup table that relates version and date?

**Comment by FLO-2DKaren** [comment]
We can easily make one and it can be written right into the plugin code.

**Comment by rpachaly** [comment]
That's a good idea

**Comment by rpachaly** [comment]
I'm working on this now. 

I'll create the lookup table using the sharefile executables information.

My code will work the following way:

Initially, the FLO-2D Pro version on metadata table will be set based on the FLO-2D.exe on the FLO-2D PRO folder.
At every run from QGIS (quick run or normal run), the FLO-2D.exe version will be read and the metadata table updated.

**Comment by FLO-2DKaren** [comment]
@FLO-2DNoemi 

Hi Noemi,  Can you check Robson's build lookup table when he is ready?  It is a simple lookup table that reads the flopro file date and then assigns a build from a table that is in the plugin code.  If it can't find the date on the table, it will leave build blank.

**Comment by rpachaly** [comment]
I created this dictionary from the executables folder on sharefile

```
FLO2D_VERSIONS = {
    "23.10.25": ["2023-11-10"],
    "22.10.24": ["2023-01-12"],
    "21.08.23": ["2021-08-04",
                 "2021-08-31",
                 "2021-09-03",
                 "2021-09-17",
                 "2021-10-06",
                 "2022-01-25"],
    "20.07.22": ["2021-07-19",
                 "2021-07-09",
                 "2021-05-14",
                 "2021-04-15",
                 "2021-03-17",
                 "2021-03-16",
                 "2020-01-24",
                 "2021-01-04",
                 "2020-12-04",
                 "2020-11-30",
                 "2020-11-13",
                 "2020-10-26",
                 "2020-09-02",
                 "2020-08-14",
                 "2020-08-06",
                 "2020-07-30",
                 "2020-07-24"],
    "19.07.21": ["2020-06-25",
                 "2020-06-10",
                 "2020-06-06",
                 "2020-06-01",
                 "2020-05-19",
                 "2020-05-14",
                 "2020-05-11",
                 "2020-04-15",
                 "2020-03-31",
                 "2020-03-18",
                 "2020-03-11",
                 "2020-03-05",
                 "2020-02-25",
                 "2020-02-20",
                 "2020-02-18",
                 "2020-02-17",
                 "2020-02-10",
                 "2020-01-27",
                 "2019-01-21",
                 "2019-11-05",
                 "2019-11-04",
                 "2019-10-14",
                 "2019-09-30",
                 "2019-09-26",
                 "2019-09-23",
                 "2019-09-04",
                 "2019-08-21",
                 "2019-08-01",
                 "2019-07-31",
                 "2019-07-23",
                 ],
    "18.09.19": ["2018-12-06",
                 "2018-11-28",
                 "2018-09-17"],
    "18.12.20": ["2019-07-23",
                 "2019-07-12",
                 "2019-06-18",
                 "2019-06-10",
                 "2019-06-07",
                 "2019-05-17",
                 "2019-05-16",
                 "2019-05-13",
                 "2019-04-08",
                 "2019-02-13",
                 "2019-02-07",
                 "2019-01-23",
                 "2019-01-11",
                 "2019-01-07",
                 ],
}
```

**Comment by FLO-2DKaren** [comment]
OH yeah that looks pretty easy.  Nice!!!!  What does read file date return currently?

**Comment by rpachaly** [comment]
What do you mean read file date?

**Comment by rpachaly** [comment]
I'm finishing up my testing here and it will work. However, I have two concerns/comments.

1. The date on the .zip folders in the redistributable folder on sharefile is not always the same date on the FLO2D.exe. Since we have many versions, probably some will return "Version not found". I believe that we can keep this method for a while, but the best way to proceed is to add a Product Version to the executable. Another solution is to add a the date range that a version was considered the latest release (e.g, from 2023-01-01 until 2023-06-31 is version 23.10.25), but I don't like this approach. 

2. Old geopackages do not have the newly implemented metadata table. Since we're getting and saving some important information on this table, I'm going to add a small code to verify if the geopackage has the metadata and, if not, add it.

**Comment by FLO-2DKaren** [comment]
1. I agree.  When you extract a file, sometimes the date is modified too.  This system will only work with installed engines.
2. There has always been an issue with porting old GeoPackages.  Maybe we can come up with an idea to help automate porting an old geopackage into the new structure.

**Comment by rpachaly** [comment]
Checking and porting geopackages should be done every time a FLO-2D project/geopackage is opened.

**Comment by FLO-2DNoemi** [comment]
This looks good.

I think the best option is to read the version from the properties of the
file. I  added the version to the FLOPRO.exe, you can download it from the
link below. Robson, let me know if you can grab the version from the
properties of the file. I am cleaning  the information that is currently
in the properties, this exe is just the first attempt.

https://flo-2d.sharefile.com/d-s7c04ad79e3054e79b4a6967c0563829a

**Comment by rpachaly** [comment]
Thanks @FLO-2DNoemi! I'll adapt my code to read first the version on the properties and, if not present (for the case of older versions), it will do the creation date approach.

**Comment by FLO-2DKaren** [comment]
OK this is working on my computer.  



![Image](https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/assets/20424460/aceee7dc-76f2-4854-b923-d247e5bbaa2f)
