### ISSUE TITLE
Quick Load

### ISSUE THREAD

**Issue by FLO-2DKaren** [FLO-2DSoftware/qgis-flo-2d-plugin#898]
Create a Quick Load method for QGIS via the FLO-2D Plugin

- [ ] Quick Load Button
- [ ] Point to project folder
- [ ] Specify projection or Unknown projection
- [ ] Auto-Create FolderName.gpkg
- [ ] Import data into project
- [ ] Import *.dat or *.hdf5

**Comment by FLO-2DKaren** [comment]
This won't be an easy task but it will give you a good understanding of how the geopackage and the import code works so it's worth studying.

**Comment by FLO-2DKaren** [comment]
@FLO-2DNoemi 
Hi Noemi,  Here's the second issue in Robson's project list.  This is a nice task because we can do a quick load in QGIS and that brings us one step closer to closing out GDS.

**Comment by rpachaly** [comment]
Is this necessary on v1.0.0?

**Comment by FLO-2DKaren** [comment]
It hasn't ever been necessary.  For me, it was a way to quickly open a project without using GDS.  But I found a work around that I'm happy with.
