### ISSUE TITLE
Green Ampt Modification

### ISSUE THREAD

**Issue by FLO-2DKaren** [FLO-2DSoftware/qgis-flo-2d-plugin#899]
Adapt the FCDMC Green Ampt method.

Allow old or new method.

Add dtheta and psif to parts so that they can also use weighted average method of calculation.

one of them still needs to be multiplied by the logxksat.  It's obvious which one from the current code.

**Comment by FLO-2DKaren** [comment]
@FLO-2DKaren 
Build a project with Lesson 1 data.
Build a large project.
What happens to the Wet Dry Normal?

FCDMC Method still need Saturation Column.

**Comment by saberraz** [comment]
Hi @FLO-2DKaren could you pass some data and the formula for this ticket?

**Comment by FLO-2DKaren** [comment]
@saberraz 
I cut this from the SOW.  
![image](https://user-images.githubusercontent.com/20424460/220741684-31f427cb-565e-4ef8-8dcc-bd18b03e23e0.png)

### Current PSIF

    def calculate_psif(avg_xksat):
        if 0.01 <= avg_xksat:
            psif = exp(
                0.9813 - 0.439 * log(avg_xksat) + 0.0051 * (log(avg_xksat)) ** 2 + 0.0060 * (log(avg_xksat)) ** 3
            )
            return psif
        else:
            raise ValueError(avg_xksat)

**I believe that instead of this calculation, they want a log area weighted average of the PSIFparts.**

### Current DTHETA

The current method uses a lookup values.  

    def calculate_dtheta(avg_xksat, saturation):
        if saturation == "dry":
            if 0.01 <= avg_xksat <= 0.15:
                dtheta = exp(-0.2394 + 0.3616 * log(avg_xksat))
            elif 0.15 < avg_xksat <= 0.25:
                dtheta = exp(-1.4122 - 0.2614 * log(avg_xksat))
            elif 0.25 < avg_xksat:
                dtheta = 0.35
            else:
                raise ValueError(avg_xksat)
        elif saturation == "normal":
            if 0.01 <= avg_xksat <= 0.02:
                dtheta = exp(1.6094 + log(avg_xksat))
            elif 0.02 < avg_xksat <= 0.04:
                dtheta = exp(-0.0142 + 0.585 * log(avg_xksat))
            elif 0.04 < avg_xksat <= 0.1:
                dtheta = 0.15
            elif 0.1 < avg_xksat <= 0.15:
                dtheta = exp(1.0038 + 1.2599 * log(avg_xksat))
            elif 0.15 < avg_xksat <= 0.4:
                dtheta = 0.25
            elif 0.4 < avg_xksat:
                dtheta = exp(-1.2342 + 0.1660 * log(avg_xksat))
            else:
                raise ValueError(avg_xksat)
        elif saturation == "wet" or saturation == "saturated":
            dtheta = 0.0
        else:
            raise ValueError(saturation)
        return dtheta

**I believe that instead of this calculation, they want a log area weighted average of the DTHETAparts.**
DTHETA wet should be zero so if the sum of the parts = zero, Set that cell to zero for DTHETA.  

### Form Edits
Now as far as the form goes...
1. Add DTHETA and PSIF to the Soil Group.
2. Remove Saturation from the Landuse Group.

![image](https://user-images.githubusercontent.com/20424460/220744464-4b9c8da7-714a-4498-a0cf-099da42d3e1e.png)

**Comment by FLO-2DKaren** [comment]
@saberraz Test project and Test Shapefiles.

[GrnAmptProject.zip](https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/files/10864821/GrnAmptProject.zip)
[GrnAmptShapefiles.zip](https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/files/10864827/GrnAmptShapefiles.zip)

**Comment by FLO-2DKaren** [comment]
@ldebek 

Log Area Average for xksat 
![image](https://user-images.githubusercontent.com/20424460/226402513-d9f8d108-24ff-40a1-880a-1e4350774be7.png)

As far as "a" goes, let's use -0.54 for now.
![image](https://user-images.githubusercontent.com/20424460/226403047-817bfcfc-88ee-4b0d-bb0d-0fb05eb1cf24.png)

**Comment by FLO-2DKaren** [comment]
@ldebek 

This is from the Green-Ampt method in the Plugin.  We'll be applying the same method but with some considerations for when DTHETA = 0 where there is ponded water and saturation already full.

    def calculate_xksat(self, parts, globalXKSAT=0.06):
        # parts are reported in % of grid area
        try:
            xksat_gen = [area * log10(xksat) for xksat, area in parts if xksat > 0]
            areaTotal = sum(area for xksat, area in parts)
            if (
                areaTotal < 1.0
            ):  # check if intersected parts area is less than grid area, assumes same units. Values would differ if soils did not completely cover cell.
                if (
                    globalXKSAT > 0
                ):  # if it's zero, we don't need to do anything and can't evaluate log10. If it's less than zero, it's not valid input.
                    xksat_gen.append((1.0 - areaTotal) * log10(globalXKSAT))
            avg_xksat = round(10 ** (sum(xksat_gen)), 4)
            return avg_xksat

        except Exception as e:
            QApplication.restoreOverrideCursor()
            self.uc.show_error(
                "ERROR 140119.1715: Green-Ampt infiltration failed!."
                + "\nError while calculating xksat."
                + "\n__________________________________________________",
                e,
            )

**Comment by FLO-2DKaren** [comment]
@ldebek 
Additional clarification. I'm getting some feedback from Nate Vaughn.  I'll some of that here.

DTHETA Landuse

- Ignore all but the wet polygons.  No need to modify maps.  
- Intersect Landuse to Soil to get DTHETA = 0 polygons.  
- Then intersect that to the grid and perform the log area avg.  
- We can probably use or adapt the RTIMP intersection to add the DTHETA.  
PSIF = 0  

- Modified calculation like DTHETA or error message?
- I think error message.

DTHETA = 0  

- Exclude DTHETA zero part from the numerator.
- Keep total area in the Denominator.  
- Total area should always = Grid element area.  If it doesn't, I think the calc will fail.
- Would it be faster to set use the grid element area?
- I think there will always be a potential for DTHETA = 0. 
- We'll have a control for that.  If SUM of the parts = zero, DTHETA = 0 for that cell.

Email from Nate:
if DTHETA = 0 (saturated soil), the infiltration rate becomes mathematically equal to XKSAT. While PSIF isn't 0 in that case, it might as well be. Calculating the infiltration depth become impossible in this case as well (which Jim and Noemi are well aware). 

What you describe between the soil and land-use layers is the intended use - the potential DTHETA values are defined by the soil, but the operational antecedent moisture condition is defined by the land-use. 

In general, the XKSAT log-averaging method should be okay for PSIF and DTHETA as well - handling of 0 values, which you've already touched on, is the key difference. The easy way to handle the 0 values for DTHETA is to exclude them from the log-average numerator, but not the area from the denominator

That's really what the "if xksat > 0" part at the end of this line is doing:
xksat_gen = [area * log10(xksat) for xksat, area in parts if xksat > 0]

Because sub-part area is calculated in %, the reduction is handled automatically by omitting any sub-parts with an xksat (or DTHETA, PSIF, etc.) with a value of 0. It's pretty elegant, really. Care should be taken to handle the case where xksat_gen has no non-zero sub-parts (e.g. the whole thing has a 0 value) because the statement above isn't evaluatable in that case - I think xksat_gen would resolve to None (null) in that case and would need to be set to 0.

**Comment by ldebek** [comment]
@FLO-2DKaren Thanks for additional information. That clarify most of the things for me, but I still have some questions. Main one is:
How should I handle cases when there are parts of grid which are not intersecting with soil layer. For the xksat there is default `globalXKSAT` parameter definded for such cases, but what about PISF and DTHETA?

**Comment by FLO-2DKaren** [comment]
@ldebek 

I always get an 'Check Layers Error' when the polygons don't completely cover the grid.  I prefer that error to defaults.

The PSIF and DTHETA Global Defaults are in the Global Form when you open the project or in the infiltration widget code.  Not the UI code but the py one.

Did you see the note about the DTHETA Landuse?  It complicates things so feel free to reach out for discussion on that one.

Contingency plan for intersection not working.  Because it's not going to work on most projects.  I like the Schematize Infiltration Areas method.  It is works great and we can use it for non-district people.  When you get to the LANDUSE-SOIL layer intersection, let's discuss that method.

**Comment by ldebek** [comment]
@FLO-2DKaren Do I understand correctly that polygons DTHETA = 0 should be obtained from intersection of soil and landuse polygons with `InitSat` parameter set to "wet" or  "saturated"? In that case we algorithm would override DTHETA from soils and set it to 0, correct?

**Comment by FLO-2DKaren** [comment]
@ldebek 
You understand correctly.  You may need to edit a few features to have a "wet" Initial Saturation.
Things like ponds, irrigated fields, golf course water features are not included in the soil data.  That surface features come from land use.

**Comment by ldebek** [comment]
@FLO-2DKaren Then requirement to remove saturation from the Landuse Group form is not valid anymore, as it will be still needed, right?

**Comment by FLO-2DKaren** [comment]
@ldebek That is correct.

**Comment by FLO-2DKaren** [comment]
Testing

**Comment by FLO-2DKaren** [comment]
Simple Test Calculator was successful.  Results for GE 4170

F 4170     0.0670  **7.3590**  0.2510  0.0820  0.5890  0.3330 

![image](https://user-images.githubusercontent.com/20424460/233688069-b3d94e7d-bf53-4273-ad20-4f18f6946101.png)

Intersection test
![image](https://user-images.githubusercontent.com/20424460/233688270-0eadfbe2-778a-48e7-a0af-975ede599f4d.png)

PSIFarea  (400.0319*log(9.500)+500.1436*log(6.000))/(400.0319+500.1436) = 0.8670
PSIFavg = 10^(0.8670) = 7.3622

Grid area Test
![image](https://user-images.githubusercontent.com/20424460/233691183-33ebb2ce-3af1-4de9-b4a7-788493d04a8d.png)
