### ISSUE TITLE
Graphics Mode for Reservoir

### ISSUE THREAD

**Issue by FLO-2DKaren** [FLO-2DSoftware/qgis-flo-2d-plugin#902]
@FLO-2DJJ 

QGIS needs to be able to apply graphics mode when no inflow or rainfall is present. 

If there is an R line in inflow.dat, lgplot can = 2 and graphtim = >0.

Steps.
1. Set Display mode.

![image](https://user-images.githubusercontent.com/20424460/222229560-24b1fbbb-7572-447b-822c-30b5c534ae7e.png)

2. Export project.
CONT.DAT
lgplot = 0
graphtime = 0.02

![image](https://user-images.githubusercontent.com/20424460/222230509-5f910baf-8fdb-4057-b689-e891226c5fcc.png)

It should be lgpot = 2.

I think it is resetting lgplot because there is no inflow node.

**Comment by FLO-2DJJ** [comment]
@FLO-2DKaren, @FLO-2DNoemi, this issue is fixed. Please test it and close it is correct.

**Comment by FLO-2DKaren** [comment]
Testing now

**Comment by FLO-2DKaren** [comment]
Testing Complete.  looks ok.
