### ISSUE TITLE
Storm Drain Culvert

### ISSUE THREAD

**Issue by FLO-2DKaren** [FLO-2DSoftware/qgis-flo-2d-plugin#907]
@FLO-2DJJ 

JJ, I need help to build a storm drain with a culvert equation.  Do you have some text files I can import?  I don't know how they are set up.  It isn't documented anywhere.

Things to do:

- [ ] Get Example Culvert  Data from JJ
- [ ] Update Storm Drain Guidelines
- [ ] Update User Manual
- [ ] Update Tech Ref Manual if necessary

**Comment by FLO-2DNoemi** [comment]
Karen,

I will help with this. I have a simple test case and the data and
information for manuals.

Noemi

**Comment by FLO-2DNoemi** [comment]
@FLO-2DKaren 

Karen, were you able to test the culvert for Type 4 inlets? I think this is complete.

I have an example that I think I sent you before, let me know so we can close this issue.

Noemi

**Comment by FLO-2DJJ** [comment]
A pull request **' Issues 907 and 720 sd culvert equations #976'** that tackles this issue is awaiting for approval.

**Comment by FLO-2DJJ** [comment]
@FLO-2DKaren and @FLO-2DNoemi,
I closed this issue but then I realized that there are 2 sub tasks related to updating the Manuals (User and Tech ref) . Have the Manuals been updated?
I reopened it until then.

**Comment by FLO-2DKaren** [comment]
@FLO-2DJJ 
Hi JJ,  I didn't finish the documentation but I think I can get to it now that we are doing the class document.  I should be able to work on it this week.

**Comment by FLO-2DKaren** [comment]
Closing and building new issue.
