### ISSUE TITLE
Outfalls Tidal Curve clarification: HH:MM format or just float number?

### ISSUE THREAD

**Issue by FLO-2DJJ** [FLO-2DSoftware/qgis-flo-2d-plugin#912]
I think I misunderstood this correction: the format for 'Hour of Day" is HH:MM or a float number? 

### Tidal Review

The time should be in hours not H:M.
The default is H:M but i can enter decimal numbers.  That's why my image looks OK for the first 48 hours but when I add a new row, the new data is set to H:M

![image](https://user-images.githubusercontent.com/20424460/226951178-b0ff552c-519d-4da4-babf-90c54c1a8d2a.png)

This is from the EPA SWMM GUI for an example.
![image](https://user-images.githubusercontent.com/20424460/226949983-0dec0756-f75c-4be6-becd-c075791fad0d.png)

_Originally posted by @FLO-2DKaren in https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/issues/883#issuecomment-1479765173_

**Comment by FLO-2DKaren** [comment]
@FLO-2DJJ 
For Tidal
Time of day is decimal value like time in hours just like inflow.dat.

You can open up EPA SWMM GUI and see them in the Tidal Curve section.

**Comment by FLO-2DKaren** [comment]
I approve this test but I now need a new issue to allow file import and a paste option.

**Comment by FLO-2DJJ** [comment]
I'm currently working on the save, load, and paste options.
