### ISSUE TITLE
Outfalls Tidals: include an option to load/save external files. Suggest extension .txt

### ISSUE THREAD

**Issue by FLO-2DJJ** [FLO-2DSoftware/qgis-flo-2d-plugin#913]
In the Outfall Tidal Curve dialog 

![imagen](https://user-images.githubusercontent.com/20424575/229574506-97cd9d02-7fbb-4aa9-8381-176a9732bee9.png)

- [x] include a button to Load.. 

- [x] and Save... file as in the EPA SWMM dialog:

![imagen](https://user-images.githubusercontent.com/20424575/229574792-7a863c88-a6c6-473e-aae7-4d506ccb1aed.png)

**Comment by FLO-2DKaren** [comment]
@FLO-2DJJ JJ this is a good idea.  Can we also have a Paste Button like the regular table editor has?

**Comment by FLO-2DJJ** [comment]
@FLO-2DKaren, @FLO-2DNoemi 
Could you please test this issue? Is already in the plugin since April 11. 
Issues to test:

1. Load File
2. Save File
3. Copy
4. Paste

**Comment by FLO-2DKaren** [comment]
I think I tested this in Mexico but I'm going to test it again just to be sure.

**Comment by FLO-2DKaren** [comment]
Tested OK

https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/assets/20424460/762f0cd6-2b0b-4e8b-a9fe-a74f0d51fe31
