### ISSUE TITLE
Control window has unnecessary ** 

### ISSUE THREAD

**Issue by FLO-2DKaren** [FLO-2DSoftware/qgis-flo-2d-plugin#917]
@FLO-2DJJ 
Hi JJ,  I just notice that many of these grey items have **.  Did something change?  Those should be normal grey boxes.  They are empty.

![image](https://user-images.githubusercontent.com/20424460/230726568-9b3c5411-5035-4821-b8f7-d07c91599b19.png)

**Comment by FLO-2DJJ** [comment]
Fixed.
Asterisks only added to the beginning and end of the component name when the component exists and is not selected in the Control Parameters dialog
