### ISSUE TITLE
Code Style and Formatting Conventions

### ISSUE THREAD

**Issue by FLO-2DJJ** [FLO-2DSoftware/qgis-flo-2d-plugin#923]
Whenever a pull request or merge is made to the master remote repository many differences could be shown in the code used by various programmers using different IDE platforms. The differences are usually not conflicts but the IDE may go crazy.. In particular I use Eclipse with PyDev. Others use PyCharm or Visual Studio or another. 
I've been suggested to use Black as a way around but I may not need it since Eclipse PyDev has configuration options that could be set if we convene the style and formatting.
In the following comment I will show the current settings for PyDev.
Please @FLO-2DKaren, @ldebek , @vcloarec, @PeterPetrik review them and tell me what settings should I use to to be in synchrony with your code.
Any suggestions are appreciated.

**Comment by FLO-2DJJ** [comment]
These are the settings in my Eclipse Pydev:
![imagen](https://user-images.githubusercontent.com/20424575/232959019-c644ad14-e457-4366-9ba8-d3a0e30b3536.png)

![imagen](https://user-images.githubusercontent.com/20424575/232959338-4560362c-db44-49b2-96f4-5d7ecdad905e.png)

![imagen](https://user-images.githubusercontent.com/20424575/232959505-1055e91b-94c6-49e1-ac14-8c4cf479afd9.png)

**Comment by ldebek** [comment]
@FLO-2DJJ Personally I'm usually using `black` code auto-formatting tool from the command line with following syntax and flags (example catalog is **flo2d**):
`black -l 120 flo2d`. As you can see  there is only one customized option  - which is a single line length set to 120. This flag value follows default settings in the most Python IDEs and imho looks most readable.

**Comment by FLO-2DKaren** [comment]
It looks like Pdev can use Black as of version 7.0.3.
https://www.pydev.org/history_pydev.html

Release 7.0.3 (2018-11-08)
    Mypy

            PyDev can now use Mypy when doing code analysis.
    Black Formatter

            PyDev can now use black as the code formatting engine.
    Virtual environments

            It's now possible to use pipenv for managing virtual environments.

            It's possible to manage virtual environments from the editor.

                    Ctrl+2, pip <command>
                    Ctrl+2, pipenv <command>
                    Ctrl+2, conda <command>

    Debugger

            Should be much faster for those on Python 3.6 onwards with cython extensions (using frame evaluation).

    The Python 3.7 grammar is now available as an option (even though it's the same as 3.6).

    Removed support for using the Python 2.4 grammar.

    The 2to3 integration shows a better dialog.

    It's possible to autogenerate docstring parameters using the Google Code format (patch by ghbcode).

**Comment by FLO-2DJJ** [comment]
These are the settings in my Eclipse Pydev:
![imagen](https://user-images.githubusercontent.com/20424575/232959019-c644ad14-e457-4366-9ba8-d3a0e30b3536.png)

![imagen](https://user-images.githubusercontent.com/20424575/232959338-4560362c-db44-49b2-96f4-5d7ecdad905e.png)

![imagen](https://user-images.githubusercontent.com/20424575/232959505-1055e91b-94c6-49e1-ac14-8c4cf479afd9.png)
