### ISSUE TITLE
Storm Drain Import

### ISSUE THREAD

**Issue by FLO-2DKaren** [FLO-2DSoftware/qgis-flo-2d-plugin#925]
@FLO-2DJJ 
Storm Drain Import system is not completely correct.  I'm having problems rebuilding a storm drain and I would like some help.  I'll be posting a video to this issue to show you the problem.

**Comment by FLO-2DKaren** [comment]
@FLO-2DJJ 
Project link and video covering Issue.
https://flo-2d.sharefile.com/d-sa923b560f450425e9b2b56527074ff01

**Comment by FLO-2DKaren** [comment]
@FLO-2DJJ 
JJ, 
This video outlines the method I used to fill the missing data.
https://flo-2d.sharefile.com/d-sae844b75623242b8a79c03ff59538d7b

**Comment by FLO-2DJJ** [comment]
@FLO-2DKaren, @FLO-2DNoemi 
I'm looking at this issue. I'll contact you soon, may need a meeting to clarify it.

**Comment by FLO-2DJJ** [comment]
Recap: This issue has been fixed as follows:

1. When importing SWMM.INP, data for all inlets and junctions are read when using the "Keep existing and complete" option. Previously the junctions where not updated.
2. Conduits are now rightly connected.

@FLO-2DKaren, @FLO-2DNoemi please test it for approval to close this issue.

**Comment by FLO-2DKaren** [comment]
I am testing this today or tomorrow.

**Comment by FLO-2DKaren** [comment]
Hi JJ,

I wasn't sure where I left this so I tested it again.  I only see one issue here.  The junctions are all sent to the bottom of the list.  I don't think that is a problem.  See the second video starting at about 2.52 min of comparisons.

The first video shows the import export process and the second video shows the file compare process.



https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/assets/20424460/52845668-a4cb-4334-b088-a053dd10802b



https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/assets/20424460/4421ea9b-a8ef-41ca-8be0-33e37547c397

**Comment by FLO-2DNoemi** [comment]
Hi all,

That is not a problem if the connectivity between nodes and pipes is
correct, table [CONDUITS].

Karen, run the model with the junctions at the end of the table and with
the other configuration,  create the plots for the storm drain discharges.
They should be identical.

Noemi
