### ISSUE TITLE
Storm Drain Flapgate

### ISSUE THREAD

**Issue by FLO-2DKaren** [FLO-2DSoftware/qgis-flo-2d-plugin#926]
@FLO-2DJJ 
I just noticed that the flapgate field is in the wrong table.  It should be in the swmmoutf table.

See here there are no flapgate in the Inlet/Junction table.
![image](https://user-images.githubusercontent.com/20424460/233806100-18a9bdac-3109-444d-b003-41f210676b87.png)

The flapgate is in the Outfall table.
![image](https://user-images.githubusercontent.com/20424460/233806121-a3fad7e5-0cdb-416a-8ff3-5ba85e1ad6a7.png)

But in the geopackage, it is in the wrong place.  I think we should move it or copy it because this is only a problem when you have to import a project with flapgates.
![image](https://user-images.githubusercontent.com/20424460/233806141-59076d34-b27c-4fa4-a7d6-2052a4e05016.png)

**Comment by FLO-2DKaren** [comment]
@FLO-2DJJ
Good news JJ,  The flapgate field in the swmmflo table is probably not hurting anything.  I don't think it is being used.  I believe the flapgate field in the user_swmm_nodes table is imported and exported via the swmm.inp. 

Hope this video helps explain it.
https://flo-2d.sharefile.com/d-s5b0ca232c6e14d59b8e6947d60d3a161

**Comment by FLO-2DJJ** [comment]
Hi @FLO-2DNoemi. what's your take on this? We've been working on this area several times in the past. We arrived to the current structure and functionality after several ajustments. Do you think it needs a change?

**Comment by FLO-2DNoemi** [comment]
The FLAPGATE option from SWMMFLO.DAT file should be fully functional.

SWMMFLO.DAT file has a variable  "Feature" (correctly identify this
variable as FEATURE(I) in the  Data input manual, storm drain manual
identifies this variable as FLAPGATE, we need to update this).

Feature has the following options 0,1 or 2:

0 = default, no flap gate, no vertical inlet opening for Inlets type 4.
This is the default option for inlets type 1, 2, 3 and 5.
1 = vertical inlet opening, only for Inlets type 4.
2 = flapgate, controls outlet node discharge for a fake outfall, this can
be used for Inlet types 1, 2, 3 and 5. For these inlets FEATURE(I) can be 0
or 2.

@Juan Jose Rodriguez ***@***.***>  @Karen OBrien ***@***.***>

**Comment by FLO-2DJJ** [comment]
- [ ] In the inlets dialog allow only 0, 1, or 2 for feature:
![imagen](https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/assets/20424575/4a1ae9fd-df30-4b61-b620-83762e1033b7)

**Comment by FLO-2DJJ** [comment]
Things to consider:
- The value of  attribute 'swmm_feature' in the 'swmmflo' layer is used to write the FEATURE value in SWMMFLO.DAT (9th item of the 'D' lines), when Exporting GDS Files.
- The field Feature in 'Select components from shapefile layer' is stored in attribute  'swmm_feature' of layer 'user_swmm_nodes':
![imagen](https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/assets/20424575/42045487-c6dd-49e5-b64b-41e746d127ee)

- The value of the attribute 'swmm_feature' in layer 'user_swmm_nodes' is passed to attribute 'swmm_feature' in layer 'swmmflo' when schematizing storm drain components:
![imagen](https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/assets/20424575/90b569a0-7c0b-48cd-bdcc-e8bf03a419f4)

- The attribute 'flapgate' in layer 'swmmflo' is of no use.
- When importing SWMM.INP, the option 'Keep existing and complete'  leaves the atribute 'swmm_feature' in user_swmm_nodes as it is. The option 'Create new storm drains' assigns zero to 'swmm_feature'.

Actions:

- [ ] Remove or ignore field 'flapgate'  of layer 'swmmflo'.
- [ ] Store the FEATURE value (9th value of 'D' lines of SWMMFLO.DAT) in attribute 'swmm_feature' of 'swmmflo' layer when importing GDS files.

**Comment by FLO-2DNoemi** [comment]
@FLO-2DJJ

If the field 'flapgate' of layer 'swmmflo' is not used, then you can remove it. Review the implications of removing it but it should not produce issues.

When DAT files are imported, the FEATURE value (9th value of 'D' lines of SWMMFLO.DAT) should be stored in attribute 'swmm_feature'.

There is one additional variable to review, now that we are reviewing gates. The additional variable is the TIDE GATE from SWMM.INP for outfalls, this has to be read from INP and write to INP,  in the plugin.  This DOES NOT go to SWMMOUTF.DAT. See Example:

[OUTFALLS]
;;               Invert     Outfall    Stage/Table      Tide
;;Name           Elev.      Type       Time Series      Gate
;;-------------- ---------- ---------- ---------------- ----
END              1234.13    FREE                        YES

**Comment by FLO-2DJJ** [comment]
@FLO-2DNoemi 
Your points 1 and 2 above have been fixed. Look at them in the current plugin in GitHub.
I made point 3 as  a new issue #939.
