### ISSUE TITLE
Boundary Conditions Groups

### ISSUE THREAD

**Issue by FLO-2DKaren** [FLO-2DSoftware/qgis-flo-2d-plugin#931]
Modify the Inflow and outflow tables and group everything under boundary conditions.
Add profiles options

**Comment by rpachaly** [comment]
I grouped all bc tables under Boundary Conditions Tables. However, it will only work for new or ported geopackages.

![Image](https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/assets/39889306/2f02d78e-2de9-411a-997a-df7ef8f35247)

**Comment by FLO-2DKaren** [comment]
Very Cool.  I think we'll need to test the auto-porting for it.   And hide it too.  I think we can hide some of those tables.

**Comment by FLO-2DKaren** [comment]
I think this works good but I want to test it on a project that you import from the *.DAT files.  I already have that in another issue so I'm going to close this issue.

**Comment by rpachaly** [comment]
Maybe we can reopen that and add more groups on the Layer Tree, specially on the User Layers. I saw that almost all lessons required to create groups to simplify the layer tree (Channels, BC, Storm Drain).

**Comment by FLO-2DKaren** [comment]
Hi Robson,
I was wondering how you do this for years now.  It would be really nice to have a simplified user layer list and hide tables that aren't commonly used.
