### ISSUE TITLE
SED.DAT file: in what order should the P lines be written within each Z group? (Same question for N lines in S groups )

### ISSUE THREAD

**Issue by FLO-2DJJ** [FLO-2DSoftware/qgis-flo-2d-plugin#935]
@FLO-2DNoemi, @FLO-2DKaren 
- [x] Order of P lines: ascending according to SEDPERCENT?
- [x] Order of N lines; ascending according to SSEDPERCENT?

**Comment by FLO-2DNoemi** [comment]
@FLO-2DJJ check FILE: SED.DAT in the Data Input Manual, Chapter 4 page 121. Let me know if you have questions.

**Comment by FLO-2DKaren** [comment]
@FLO-2DJJ 
Both lines need to be in ascending order by sediment diameter.  So from low diameter to high diameter.

**Comment by FLO-2DJJ** [comment]
Fixed. Ordered in ascending order by diameter.
