### ISSUE TITLE
SED.DAT file: should each Z group have the same number of P line pairs ?

### ISSUE THREAD

**Issue by FLO-2DJJ** [FLO-2DSoftware/qgis-flo-2d-plugin#936]
@FLO-2DNoemi, @FLO-2DKaren 
The Data Input Manual for the SED.DAT file says:
Line 4: Repeat this line for each size fraction. Each group must have the same number of size fractions.

- [ ] Should the S groups also have same number of N lines for each group?

**Comment by FLO-2DKaren** [comment]
@FLO-2DJJ 
It is not necessary for the S groups to have the same number of N lines.

**Comment by FLO-2DJJ** [comment]
Not at issue
