### ISSUE TITLE
Mud Sediment Transport dialog: Chan/FP should be 0 or 1 only

### ISSUE THREAD

**Issue by FLO-2DJJ** [FLO-2DSoftware/qgis-flo-2d-plugin#937]
![imagen](https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/assets/20424575/b9fa0e83-f06d-47e7-afd2-4a1bbb54455c)

This is the ISEDCFP variable in S line of SED.DAT:
ISEDCFP = 0 for a floodplain sediment supply rating curve.
ISEDCFP = 1 for a channel sediment supply rating curve.

Use a dropdown list similar to the equation in the Size Fraction table.

**Comment by FLO-2DJJ** [comment]
@FLO-2DKaren @FLO-2DNoemi
Chan/FP field checked for 0 or 1 values.
Also all fields with an element cell number is checked to see if the cell is in the domain. Corresponding warnings or errors are shown.
Branch already merged into repository master.

**Comment by FLO-2DKaren** [comment]
This seems to be working ok.  I'll approve this one and move onto the other ones.
