### ISSUE TITLE
Read/Write TIDE GATE column of [OUTFALLS] group of SWMM.INP 

### ISSUE THREAD

**Issue by FLO-2DJJ** [FLO-2DSoftware/qgis-flo-2d-plugin#939]
TIDE GATE from SWMM.INP for outfalls has to be read from INP and write to INP, in the plugin. This DOES NOT go to SWMMOUTF.DAT. See Example:

[OUTFALLS]
;; Invert Outfall Stage/Table Tide
;;Name Elev. Type Time Series Gate
;;-------------- ---------- ---------- ---------------- ----
END 1234.13 FREE YES

**Comment by FLO-2DNoemi** [comment]
Test it. I am closing this issue.

**Comment by FLO-2DNoemi** [comment]
@Juan Jose Rodriguez ***@***.***>   Does this still need verification of
the plugin from our side? I think we checked this together in one of our
meetings.

In other words, verify that the plugin writes and reads TIDE GATE from
SWMM.INP.
