### ISSUE TITLE
Mult Channel message 

### ISSUE THREAD

**Issue by FLO-2DKaren** [FLO-2DSoftware/qgis-flo-2d-plugin#942]
@FLO-2DJJ 
I keep getting this message when I export a project.  
![image](https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/assets/20424460/1b9437d4-88e3-4a06-8996-47c763c9b322)

Is anyone else getting this?  @FLO-2DJJ  can  you see if this is an error.

**Comment by FLO-2DJJ** [comment]
The logic of the writing of multiple channels (MULT.DAT and SIMPLE_MULT.DAT) is a little convoluted (at least to me).
This is what happens:
When exporting the DAT files, the IMULTC switch is turned off if there isn't any 'mult_cells' or 'simple_mult_cells' (if both layers are empty). The warning message is given. 
![image](https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/assets/20424575/8bb42030-f38c-4b59-8905-60a860f4a66f)

The reason for the above warning is that If either  'mult_cells' or 'simple_mult_cells' is not empty, the "Multiple Channels' checkbox is checked in the Components to Export dialog (independently of whether the component was selected in the Control Variables dialog (for the CONT.DAT file).
![image](https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/assets/20424575/52e40277-aedc-416e-8d89-ceb79278d1a9)
In turn, after the proper export one of these 2 messages could appear:
![image](https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/assets/20424575/b1ba2776-b1f9-4303-af8c-532ae12609dc) 
![image](https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/assets/20424575/cf073d61-5f64-48d1-b2e4-e7999f650ae4)

1. If 'simple_mult_cells' layer is empty and there is a previous SIMPLE_MULT.DAT in the project directory, the model FLOPRO.EXE will use it (it seems that independently of the IMULTC switch, please @FLO-2DNoemi verify this). That is why at the end of the Export the plugin asks if we want to delete SIMPLE_MULT.DAT.
2. The same happens with the layer 'mult_cells': If 'mult_cells' layer is empty and there is a MULT.DAT in the project directory, the model will use it (it seems that independently of the IMULTC switch, again @FLO-2DNoemi verify this please). That is why at the end of the Export the plugin asks if we want to delete  MULT.DAT .

Sorry about this long and maybe confusing comment. As I said before, the logic behind the plugin for this component is sort of convoluted. 
Please, let's meet when you have time to clarify this.

**Comment by FLO-2DKaren** [comment]
@FLO-2DJJ @FLO-2DNoemi 

I am getting the error even when I am not using mult channels.  So my switch is never checked and I'm still getting the error.

**Comment by FLO-2DJJ** [comment]
Yes. I understand. I already removed the warning in some circumstances (in
a working branch, not yet in the GitHub repo). But there are some details
that Noemi is consulting with Jim.

**Comment by rpachaly** [comment]
Is this solved? Can I close the issue?

**Comment by FLO-2DKaren** [comment]
This is done should have been closed a long time ago.
