### ISSUE TITLE
Mapping Processing Tools

### ISSUE THREAD

**Issue by FLO-2DKaren** [FLO-2DSoftware/qgis-flo-2d-plugin#947]
Build processing tools into the Processing Toolbox specifically for FLO-2D Output.

**Comment by FLO-2DKaren** [comment]
Let's look for an online tutorial related to the processing tools.  I think I have one on my computer now.

**Comment by FLO-2DKaren** [comment]
A simple tutorial for building plugins for the processing toolbox
https://www.qgistutorials.com/en/docs/3/processing_python_plugin.html

**Comment by rpachaly** [comment]
This looks obsolete with MapCrafter. Can we close this issue?

**Comment by FLO-2DKaren** [comment]
Aaaah dang it.  We should have done the mapcrafter stuff in the Processing toolbox.  It would have been awesome.  This is no longer relevant.
