### ISSUE TITLE
raincell.hdf5 bug

### ISSUE THREAD

**Issue by FLO-2DKaren** [FLO-2DSoftware/qgis-flo-2d-plugin#951]
When exporting raincell.hdf5, a bug comes up to Check Layers. 

I think this is related to the new hdf_group and create_group modules that Lukasz made when he wrote the hdf import export code for the other FLO-2D export data.

**Comment by FLO-2DKaren** [comment]
@rpachaly Hi Robson,  I just had an idea.  We can look at an old plugin and see what changed. 
This plugin is from before Lutra's hdf5 update.  Check out the differences related to the hdf5 code.

https://flo-2d.sharefile.com/d-s2ca674fff4444dfdad4bbc8c4063edde

**Comment by FLO-2DKaren** [comment]
@rpachaly 
Hi Robson,
[RAINCELL.zip](https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/files/11697034/RAINCELL.zip)

I tested it on my laptop and it worked with 7 rainfall datasets.
![image](https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/assets/20424460/1e297f34-4767-49e7-9c40-4fabebc5bb15)

**Comment by FLO-2DKaren** [comment]
Maybe we are running out of space or something?  Can you look at the raincell table in the database browswer and see if it's the correct size and shape?

**Comment by FLO-2DKaren** [comment]
@rpachaly The raincell.hdf5 is working on my laptop.
[RAINCELL_hdf5.zip](https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/files/11697159/RAINCELL_hdf5.zip)

Also very interesting that the hdf5 file compresses down to 1.7 Mb.  I don't think we are applying the compression correctly.

This might be a QGIS bug not a plugin bug.

**Comment by rpachaly** [comment]
Hi @FLO-2DKaren!

The bug was caused by a deprecated numpy alias. It was being used np.int() in the code but it was deprecated on version 1.20 of numpy. I just changed the code to int() and it is working fine on my machine. I tested on versions 3.30 and 3.28 of QGIS. I also looked for others np.int() in the code and I didn't find any. So, I think this bug is solved. 

I pushed the branch. Let me know if everything is working fine. I'll be waiting for further instructions!

**Comment by FLO-2DKaren** [comment]
@rpachaly 
Excellent find.  I'm going to test this right now.  I actually need to test more than one thing.  The QGIS export and running it with FLOPRO.EXE because it looks like the hdf5 file is new and I might need a different version for FLOPRO.EXE.  I'll get a video and share my ideas with you.

**Comment by rpachaly** [comment]
I have the same version here. I'll take a look on this error.

**Comment by rpachaly** [comment]
I don't get this error here. It looks like it is an error related to IRAINDUM array's dimensions. Which raincell data did you try to export?

**Comment by rpachaly** [comment]
numpy.version.version
'1.24.1'

**Comment by rpachaly** [comment]
I tried to export to another folder and I've got the error here. I'll check it.

**Comment by FLO-2DKaren** [comment]
I think this issue was resolved.
