### ISSUE TITLE
Infiltration Editor Bug

### ISSUE THREAD

**Issue by FLO-2DKaren** [FLO-2DSoftware/qgis-flo-2d-plugin#957]
A few buttons are not working correctly since we removed some of the infiltration tables.  I'd like to reconnect them to their tables.

I'll add notes to this to show the errors.

**Comment by FLO-2DKaren** [comment]
The curve number has been disconnected from the editor widget.  We should be able to update this variable from the dialog.  The green-ampt one is working so it should show how to fix the connection.



![Image](https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/assets/20424460/c0be7166-0e0c-40dc-9ac4-fb0311856820)

**Comment by FLO-2DKaren** [comment]
The Green-Ampt variables are disconnected too.
Aaaand Horton is also disconnected.

**Comment by FLO-2DKaren** [comment]
@rpachaly 
We are probably on hold waiting for Nate to send us his method so if you want to work on this issue so that we can keep up the momentum, that is cool.

**Comment by rpachaly** [comment]
Cool! I'll start working on that.

**Comment by rpachaly** [comment]
> The Green-Ampt variables are disconnected too.
Aaaand Horton is also disconnected.

I was checking here and for me only the SCS is disconnected. G&A and Horton are fine.

**Comment by rpachaly** [comment]
I found another bug. When exporting the SCS infiltration method, it does not save correctly the global infiltration parameter.

**Comment by FLO-2DKaren** [comment]
OK good.  I'm glad you found that.  I hadn't done any exports yet.

**Comment by rpachaly** [comment]
@FLO-2DKaren 
Everything is connected again. I also fixed that bug of not exporting correctly the SCS global parameters. All the bugs here were due to the fact that the if statements were based on the QDoubleSpinBox object, but the SCS Curve Number is a QSpinBox.

**Comment by rpachaly** [comment]
I pushed the branch!

**Comment by FLO-2DKaren** [comment]
OK I'll test it right now.

**Comment by FLO-2DKaren** [comment]
Tested and approved.
