### ISSUE TITLE
Boundary Conditions 

### ISSUE THREAD

**Issue by FLO-2DJJ** [FLO-2DSoftware/qgis-flo-2d-plugin#960]
Discuss con Noemi and Karen current state of boundary conditions

**Comment by FLO-2DKaren** [comment]
@FLO-2DJJ @FLO-2DNoemi 
Hi JJ,
JE Fuller is going to work with us on the Boundary Conditions to modify them so that we can have more than one flow or rainfall profile in a single geopackage.  If you need to discuss something specific, let's have a meeting.

**Comment by FLO-2DNoemi** [comment]
@Karen OBrien ***@***.***>

We need to review the stage time BCs and the process to create them in the
plugin. I think this is not related to the task that JEFuller is working on.

**Comment by FLO-2DNoemi** [comment]
@FLO-2DJJ Let's talk about this in our next meeting.

They will change the geopackage to allow more than one flow or rainfall datasets. In other words, allow the geopackage to have multiple rainfall or flow events. This is a new capability , nothing that we can help with for now.

**Comment by FLO-2DKaren** [comment]
Closing this issue because we are going to do this ourselves.
