### ISSUE TITLE
SQL elevation and levee error message

### ISSUE THREAD

**Issue by FLO-2DKaren** [FLO-2DSoftware/qgis-flo-2d-plugin#977]
This error comes up when you do anything related to levee elevation or grid element elevation correction.  It doesn't seem to inhibit the tools but it does send out a red flag error message in the message bar.  

Layer Elevation Polygons: OGR[3] error 1: In ExecuteSQL(): sqlite3_step(SELECT * FROM user_elevation_polygons WHERE membership = 'all' OR membership = 'grid'): unable to open database file

**Comment by FLO-2DKaren** [comment]
I tested this yesterday and got a similar error message when the point layer was empty.  

When I added levee elevation points to the point layer and the error went away. Then when I deleted those points, the error still was gone.

This is a weird one.  it seems like it's trying to read from an empty layer instead of skipping the empty layer.

Maybe the fix for this one is to skip empty layers?

I'm not convinced that we need to fix it right away.

**Comment by rpachaly** [comment]
This error comes along the SQL error


![Image](https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/assets/39889306/771bba96-15a4-4824-a61e-9ddb7f4737be)

**Comment by rpachaly** [comment]
The problem is in this function (79 to 81 on elevation_correctors)

>     def set_filter(self):
>         self.user_points.setSubsetString(self.filter_expression.format("user_elevation_points"))
>         self.user_polygons.setSubsetString(self.filter_expression.format("user_elevation_polygons"))

**Comment by FLO-2DKaren** [comment]
Create new project from project domain
Create grid
Create levee polyline
Create levee polygon with elevation

Run Build Levees and you should see an error about the points but it's probably using the same code as the one you already fixed.

This project might work to show the bug.  Otherwise, just do Project domain from lesson 1
[HydroOK.zip](https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/files/13380341/HydroOK.zip)

**Comment by rpachaly** [comment]
Ok, I'll do. 

Currently, the error message disappeared and all is working good for three out of the four elevation correction options.

**Comment by rpachaly** [comment]
I've pushed the [branch](https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/tree/new_gpkg_bugs). 

The issue was the way it was setting a filter on the user_polygons & user_points shapes. I also removed the creation of the struc_data_tables from the db because it was not being read on the code and it was causing some warnings. 

Obs: I was not able to use the correct elevation using the TIN (based on elevation polygon boundaries) method. For the current version and the one with the bug fix.

**Comment by FLO-2DKaren** [comment]
Responding to your Obs:

Is this a bug?  It worked as of build 0.10.74.  I created a test control for the whole elevation correction tool.  I will run through all tests before we release the next version.

**Comment by rpachaly** [comment]
I don't know if it is a bug or not. I didn't change anything on the function that uses that correction option. Maybe I am setting the polygons wrong or the function was already broken.

**Comment by FLO-2DKaren** [comment]
> I don't know if it is a bug or not. I didn't change anything on the function that uses that correction option. Maybe I am setting the polygons wrong or the function was already broken.

The only thing I think you could be doing wrong is not assigning Grid to the polygon.

**Comment by FLO-2DKaren** [comment]
I'm not seeing this error as often as I used to so I'll just close it.
