### ISSUE TITLE
Control Window size

### ISSUE THREAD

**Issue by FLO-2DKaren** [FLO-2DSoftware/qgis-flo-2d-plugin#979]
The initial size of the control window is not good for laptops.  This is a problem during classes where most people are on laptops.  Let's correct the initial size in the UI file so that it fits the window and the data.

**Comment by FLO-2DKaren** [comment]
OK I found the issue.  The tabs have a fixed size control.  I reset it to expanding and fixed the size at something smaller.  Here's the UI file.  

@rpachaly 
Robson,  Can you update the plugin code with this ui file?


[cont_toler_jj.zip](https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/files/12431280/cont_toler_jj.zip)

**Comment by rpachaly** [comment]
Sure. Just give some minutes and I'll do the pull request.

**Comment by rpachaly** [comment]
I pushed the branch. I'm closing this issue.
