### ISSUE TITLE
SCS single field 

### ISSUE THREAD

**Issue by rpachaly** [FLO-2DSoftware/qgis-flo-2d-plugin#982]
When reading the CN values from a polygon layer is returning wrong values. I've tested with two polygons layers and it is not assigning the correct values. 

Polygon layer
![image](https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/assets/39889306/7651c7ff-c4f2-4b62-82eb-385c6afd6f8d)

Cells SCS
![image](https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/assets/39889306/294e5840-0f52-439b-a392-c3caebbbfd9f)

**Comment by FLO-2DKaren** [comment]
@rpachaly 
Hi Robson,  I also saw this when using polygon layers that were not created by the Curve Number Generator.  I noticed it on most of my SCS polygon shapefiles.  It's one reason I asked for the raster method.

**Comment by rpachaly** [comment]
> @rpachaly Hi Robson, I also saw this when using polygon layers that were not created by the Curve Number Generator. I noticed it on most of my SCS polygon shapefiles. It's one reason I asked for the raster method.

I think I found the error. It is not calculating correctly the subareas when we have 1 grid element with two or more polygons. I'll try to fix it.

**Comment by FLO-2DKaren** [comment]
That would be good.  It's been problematic for a long time.  I'm not sure why it seems to work well with the files created by the curve number generator.

**Comment by rpachaly** [comment]
The error was that it was trying to calculate the contributing area inside the grid wrongly. I changed the code to a simpler solution: it is sampling the CN value based solely on the grid centroid point. The problem with that solution is that if the grid centroid point is not inside the infiltration polygon layer, it will throw an exception. In the future, we could add an option to choose between "Area average" and "Centroid point sample". Same as the sampling roughness tool.

I tested with the polygons that I've here and it worked. I'm pushing the branch.

**Comment by FLO-2DKaren** [comment]
I wonder why it use the Avg N value process?  Good idea for future use.  The Pima County method is also broken.

**Comment by rpachaly** [comment]
Let's not close this issue and revisit it in the future. I like the idea of having both options.

**Comment by FLO-2DKaren** [comment]
I'm going to go ahead and close this because I think our time would be wasted on modifying the Pima County Method.  They have their own calculators and all we need is the CN field from their data.
