### ISSUE TITLE
Rubberband issue

### ISSUE THREAD

**Issue by FLO-2DKaren** [FLO-2DSoftware/qgis-flo-2d-plugin#990]
I saw an error related to the rubberband reset.  It has a variable called int that isn't acceptable.  We should investigate this but I don't see it on my system.

**Comment by FLO-2DKaren** [comment]
If you see an error related to RubberBand variable, it is fixed by installing a newer version of QGIS.

**Comment by FLO-2DKaren** [comment]
Some users don't understand what a rubberband is and why their selection stays red.  Maybe we can add a button next to the Expand/Collapse Widget buttons that clears the rubberband.

**Comment by FLO-2DKaren** [comment]
Ignore Comment 1 and focus on Comment 3

**Comment by rpachaly** [comment]
The qgisMinimumVersion and qgisMaximumVersion on metadata are working. I've installed QGIS 3.16 to fix this bug and I've got this message:

![Image](https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/assets/39889306/84f8276f-71ef-4e83-b834-513ca49cab1c)

I'll try to fix this bug anyway, it could arise in a newer version.

**Comment by rpachaly** [comment]
I couldn't reproduce the bug on QGIS 3.16.

**Comment by FLO-2DKaren** [comment]
Don't try to fix the bug.  It's a Python 3.7 vs. 3.9 issue and we are not looking backwards on this.

Please see if you can add a button to the plugin that clears the current rubberband.  For example.  The Tailing Dam class sets an outflow condition in the 3rd module.  But we don't do anyhthing else with the boundary for the next several lessons so the boundary stays red until QGIS is restarted.  This confuses people and they don't know what a rubberband is.

Can you add a ClearRubberband button?  

If you have a better idea, take it away.

![image](https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/assets/20424460/ce4e4c55-83d3-458d-b6d0-86060925ba6a)

**Comment by FLO-2DKaren** [comment]
This seems to work

```
canvas = iface.mapCanvas()  # Get the current map canvas

# Find the rubberband item in the canvas scene
items = canvas.scene().items()
rubberband_item = None
for item in items:
    if isinstance(item, QgsRubberBand):
        rubberband_item = item
        break

if rubberband_item is not None:
    # Remove the rubberband item from the scene
    canvas.scene().removeItem(rubberband_item)
    canvas.refresh()
else:
    print("Rubberband not found in the canvas scene.")
```

**Comment by rpachaly** [comment]
I'm working on this. Probably by tomorrow I'm going to push a big branch with all "In Progress" issues.

**Comment by rpachaly** [comment]
New button to clear the rubberband

![Image](https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/assets/39889306/0033f0d0-fa25-47e9-a74c-15bbe3fc9e25)

**Comment by FLO-2DKaren** [comment]
Haha It's a broom.  Nice

**Comment by rpachaly** [comment]
I think we need to refactor this bc editor asap. Having the inflow and outflow all together makes the code really hard to understand. If I change a signal or connection on the inflow, it breaks the outflow.

**Comment by FLO-2DKaren** [comment]
OK I agree.  Let's also plan it out so that the tables are simplified.  I think we can limit some of the tables associated with the BC editor.  We can do this next.
