### ISSUE TITLE
Boundary Schema

### ISSUE THREAD

**Issue by FLO-2DKaren** [FLO-2DSoftware/qgis-flo-2d-plugin#991]
If you have a complex polygon on the downstream boundary, it is recalculating the boundary every time you use the schematize button. This is unnecessary and it can take a long time to process.  We should allow the user to uncheck that boundary if that is easy.

We should also look at the speed of that process.  it still seems to take too long.

**Comment by FLO-2DKaren** [comment]
Boundary Condition Notes for our meeting:
Maybe it's going through a reset loop but it's leaving the loop before it finishes the enable statement.

I agree that widget doesn't need to be so complicated.  
In addition to simplifying the widget, we need to sort out the algorithm speed of the outflow polygon.  That process takes way to long.  I bet it's doing more work than it needs to.  

Outflow nodes can do lots of stuff so if you want an overview of the widget, we could do a meeting.  
Noemi also wants to simplify the time series table so a tide table is assigned to a group of nodes instead of every node.

Noemi also has a sink source system that we might want to review.  It's for ground water.

**Comment by rpachaly** [comment]
I'm looking into improving the performance of the BC polygon on the downstream boundary. Even if we change the widget interface or anything like this, the polygon BC process will be the same.

**Comment by rpachaly** [comment]
Another idea here. Do we need to have a button to schematize the BCs? I mean, we can schematize directly on the code when the layer is saved. It will reduce the number of clicks by the user.

**Comment by FLO-2DNoemi** [comment]
I like the idea of reducing the number of clicks and removing the
additional schematize buttons.

**Comment by rpachaly** [comment]
This is more for me to track my steps and to remember the code, but feel free to contribute in any way.

As far as I understood the code, it does the following:
1. schematize_bc: It is the main function to schematize the data. It calls two functions in order.
2. schematize_outflows (or schematize_inflows): This function insert data on the outflow_cells table from the all_user_bc and grid_layers. 
3. select_outflows_according_to_type: This function processes the outflow cells and, in the case of a polygon bc, removes the diagonal cells and the others that are not in the boundary. 

I believe that what is slowing down the process is the schematize_outflows function. It is sending too much cells to be tested for BC cell. Maybe processing the cells before sending them to select_outflows_according_to_type can speed up the whole process. But I’m not totally sure, I’ll give it a shot.

**Comment by FLO-2DKaren** [comment]
OK.  This is one of the systems that might benefit from the moving window analysis where it does the processing in blocks of data to reduce the processing time overall.

The area average n value calculator uses that method.

**Comment by FLO-2DKaren** [comment]
Let's move the messages from the code to the FLO-2D Message log.
