### ISSUE TITLE
Baseflow in channel

### ISSUE THREAD

**Issue by FLO-2DKaren** [FLO-2DSoftware/qgis-flo-2d-plugin#997]
We need to accommodate and test this for tailings dam modeling and floodwave arrival time when a channel baseflow is used.

2.  TIME_TO_ABOVE_BASEFLOW.OUT

Both files have cell #, x-coord., y-coord., Vxd (ft^2/s) or Time (hrs)

To create the second output file, you need to assign the channel baseflow in the CHAN.DAT file. 
This can be assigned at the bottom of the file and requires only a line ID and the baseflow Q in the following format: 

B         12.3

This doesn't have to be the last line but you should put it after all the lines with the channel geometry (line ID = R, T, or N).  See the attached CHAN.DAT file.

**Comment by JJ-HYD** [comment]
Starting working on this. Assigning it to myself now. 👍

**Comment by FLO-2DKaren** [comment]
JJ  Here is the data input manual.  It looks like you get a B line after every segment.  So you'll need to connect the data to a segment.

https://flo-2d.sharefile.com/d-s104b2813323e45c88d73b18461f6de9a

**Comment by FLO-2DKaren** [comment]
It's in Chan.DAT

See Variable Name, Line Comments, and Variable Description.

**Comment by FLO-2DJJ** [comment]
Thank Karen

**Comment by FLO-2DJJ** [comment]
@FLO-2DKaren,

The **Data Input Manual PRO 2024** has an error for the _IBASEFLOW_ Variable Description: the type (under FMT column) should be r (for real) not i (for integer).

**Comment by FLO-2DKaren** [comment]
Thanks JJ  I'll fix it

**Comment by FLO-2DJJ** [comment]
Hi @FLO-2DNoemi, (and @FLO-2DKaren)

Is the model ready to read CHAN.DAT with lines B (IBASEFLOW)?
I've finished the writing/reading of CHAN.DAT with them (in the plugin branch **add_channel_baseflow_to_CHAN_DAT**).

There is new field _ibaseflow_ in TABLE _chan_:

```
CREATE TABLE "chan" (
    "fid" INTEGER NOT NULL PRIMARY KEY,
    "name" TEXT, -- name of segment (optional)
    "depinitial" REAL DEFAULT 0, -- DEPINITIAL, initial channel flow depth
    "froudc" REAL DEFAULT 0, -- FROUDC, max Froude channel number
    "roughadj" REAL DEFAULT 0, -- ROUGHADJ, coefficient for depth adjustment
    "isedn" INTEGER DEFAULT 0, -- ISEDN, sediment transport equation or data
    "ibaseflow" REAL DEFAULT 0, -- IBASEFLOW, chanel baseflow discharge
    "notes" TEXT,
    "user_lbank_fid" INTEGER, -- FID of parent left bank line,
    "rank" INTEGER
);
```
and a _Channel Baseflow_ control in the _Schematized Channels Editor_ widget:

![image](https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/assets/20424575/121bcb18-fc62-4696-a746-bc69fb4cf3a6)

and in the  _Schematic Channel Segments_ dialog:

![image](https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/assets/20424575/f14db875-3754-4143-9789-9b97bddd6765)

I'm still doing some tests. I just want to let you know about the coming changes.

I`m following the description of the _CHAN.DAT File_ in the **Data Input Manual PRO 2024**.

**Comment by FLO-2DNoemi** [comment]
Yes, the FLOPRO.exe is ready to read lines B  for the baseflow.

**Comment by FLO-2DKaren** [comment]
When you first load a project one of the channels is Selected and turns yellow.  Is there a better way to address that?  Maybe don't populate that list until the dialog is opened.
Maybe have the first option in the list be empty.

**Comment by FLO-2DKaren** [comment]
Ooooh I might be wrong about the location of the B lines location in chan.dat.  They might need to go to the end of the channel.  Testing now.

**Comment by FLO-2DNoemi** [comment]
They go at the end of the channel with the confluences and the no-exchange
grids.

**Comment by FLO-2DNoemi** [comment]
Check the Data Input Manual, they seem to be correctly located in the
manual.

**Comment by FLO-2DKaren** [comment]
I think it's wrong too.  We need to check with Jim.

**Comment by FLO-2DNoemi** [comment]
I just checked the code and it should be reading them at the end of the
data file. Send me the data files, I will check first and we can send it to
Jim if I can not figure it out.

Best Regards,
Noemi Gonzalez, Ph.D., P.E.
FLO-2D Software | Riada Engineering
Ph: (786) 223-0410
www.flo-2d.com | ***@***.***

**Comment by FLO-2DKaren** [comment]
I moved mine to the end of the file and it ran.  I assume we use the same segment order.  Noemi,  Can you confirm that?
Here is a test project but Its running when they all are moved to the end.

[Quick Run.zip](https://github.com/user-attachments/files/15805887/Quick.Run.zip)

**Comment by JJ-RM** [comment]
> When you first load a project one of the channels is Selected and turns yellow. Is there a better way to address that? Maybe don't populate that list until the dialog is opened. Maybe have the first option in the list be empty.

OK. I'll disable the highlight on loading the project and enable it afterwards.

**Comment by JJ-RM** [comment]
Currently, the pull request #1375 I summitted, follows the description in the Data Input Manual PRO 2024, quote:

_Line 6: If a baseflow is used to report a time TIME_TO_ABOVE_BASEFLOW.OUT. **Place Line 6
after each segment.**_

and 

_IBASEFLOW(K) i 0.0 -
Baseflow of a channel to establish a flow condition for floodwave
arrival time. **Place this line after each segment if more than one
segment is used**._

Do we need to change that?

**Comment by FLO-2DNoemi** [comment]
JJ,

  Let me confirm the information, but the comment in Line 6 appears to be
incorrect. The FLOPRO.exe file shows that B Lines are located at the end of
the CHAN.DAT file, along with C and E lines.

Karen, can you send me your project datafiles for this?

Noemi

**Comment by FLO-2DNoemi** [comment]
B lines are at the end of the chan.dat files, they are read after all
channel segments, in other words, the data is read at the end of the
CHAN.DAT file with C and E lines.

We need to fix the Line 6 comment in DIM. B lines are not at the end of
each channel segment

Karen, if you believe the FLOPRO.exe is not reading correctly B lines, then
send me the test simulation and I will check it.

**Comment by FLO-2DKaren** [comment]
@FLO-2DNoemi 
See a test project further up in the comments. It's just data.  I move b lines to the bottom and it works.  I will fix the DIM.

**Comment by FLO-2DNoemi** [comment]
Good, thanks.  I do not need the data set if you already confirmed the B
lines are working at the end of the CHAN.DAT file.

**Comment by JJ-RM** [comment]
OK. I'll move the B lines to the end of CHAN.DAT (lines 6) , after the C (lines 4) and E lines (lines 5):

```
C 501 498 Line 4: CHANCHAR = ‘C’ ICONFLO1(J) ICONFLO2(J)
E 5112 Line 5: CHANCHAR = 'E' ICHANGRID(N)
B 12.3 Line 6: CHANCHAR = 'B' IBASEFLOW(K)
J = number of channel confluences
K = number of channel segments
N = number of nofloc and noexchange data sets
```

**Comment by FLO-2DJJ** [comment]
This is already done and merged to master with PR #1378

**Comment by FLO-2DJJ** [comment]
Hi @rpachaly, 

I noticed that there are two calls to the local method ‘_import_chan_’ in module  **xs_editor_widget.py**. That method doesn’t take into account the new  channel baseflow lines ‘B’ of CHAN.DAT.  
The two calls are made from _interpolate_channel_elevation_ and _interpolate_channel_n_.

The currently modified method ‘_import_chan_’ in class **Flo2dGeoPackage** does read the ‘B’ lines and takes the appropriate actions.  Don’t you think that is convenient to use this method in the above **xs_editor_widget.py** module, by creating an instance of **Flo2dGeoPackage**? In doing so we’ll have the same routine to do the import of CHAN.DAT, now and in case we need to modify it in the future. This will ensure consistency in the import of CHAN.DAT.
That approach is already made when exporting CHAN.DAT in **xs_editor_widget.py**:
```
        self.f2g = Flo2dGeoPackage(self.con, self.iface)
.
.
.
            self.f2g.export_chan(outdir)
```

(By the way, there is another call to ‘_import_chan_’ in ‘_save_channel_DAT_and_SEC_files_’, but this is not used anywhere)

What do you think?

**Comment by FLO-2DJJ** [comment]
Hi @rpachaly,

Could you also please look at the **export_chan_hdf5** method? It should export the **B** lines from the _ibaseflow_ field of the _chan_ table.

**Comment by rpachaly** [comment]
Hi @FLO-2DJJ,

> The currently modified method ‘import_chan’ in class Flo2dGeoPackage does read the ‘B’ lines and takes the appropriate actions. Don’t you think that is convenient to use this method in the above xs_editor_widget.py module, by creating an instance of Flo2dGeoPackage? In doing so we’ll have the same routine to do the import of CHAN.DAT, now and in case we need to modify it in the future. This will ensure consistency in the import of CHAN.DAT.
That approach is already made when exporting CHAN.DAT in xs_editor_widget.py:

I think it is a good idea. 

> Could you also please look at the export_chan_hdf5 method? It should export the B lines from the ibaseflow field of the chan table.

I will add this to the hdf5 issue.
